# Generated by Django 4.2.4 on 2025-05-26 17:27

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import utils.common.utils
import validators.mediaValidators.image_validators
import validators.security_validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('brand_title', models.CharField(max_length=100, verbose_name='Brand')),
                ('image_name', models.ImageField(upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file], verbose_name='Product group picture')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('feature', models.CharField(max_length=50, verbose_name='Feature')),
            ],
        ),
        migrations.CreateModel(
            name='FeatureValue',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value_title', models.CharField(max_length=50, verbose_name='Value Title')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values_of_features', to='products.feature', verbose_name='Feature')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=150, verbose_name='Product Name')),
                ('summary_description', models.TextField(blank=True, null=True, verbose_name='Summary Description')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Product Description')),
                ('image_name', models.ImageField(upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file], verbose_name='Product Picture')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='Register Date')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Published Date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('selling_type', models.CharField(choices=[('free', 'Free'), ('for_sale', 'For Sale')], default='for_sale', max_length=20, verbose_name='Selling Type')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Product Price')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='Is Active')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='products.brand', verbose_name='Product Brand')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('group_title', models.CharField(max_length=100, verbose_name='Product Group Title')),
                ('image_name', models.ImageField(upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file], verbose_name='Product Group Picture')),
                ('description', models.TextField(blank=True, verbose_name='Product Group Description')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='Register Date')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Published Date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('group_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='products.productgroup', verbose_name='Parent Product Group')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.feature', verbose_name='Feature')),
                ('feature_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_of_value', to='products.featurevalue', verbose_name='Feature Value')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_features', to='products.product', verbose_name='Product Feature')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='feature',
            field=models.ManyToManyField(through='products.ProductFeature', to='products.feature'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_groups',
            field=models.ManyToManyField(related_name='products', to='products.productgroup', verbose_name='Product Group'),
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image_name', models.ImageField(upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file], verbose_name='Product Picture')),
                ('product_gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_gallery', to='products.product', verbose_name='Product Gallery')),
            ],
        ),
        migrations.AddField(
            model_name='feature',
            name='product_groups',
            field=models.ManyToManyField(related_name='features', to='products.productgroup', verbose_name='Product Group Feature'),
        ),
    ]
