# Generated by Django 4.2.4 on 2025-05-26 17:27

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import utils.common.utils
import validators.mediaValidators.pdf_validators
import validators.security_validators
import validators.user_validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('education_document_type', models.CharField(choices=[('Transcript', 'Transcript'), ('Diploma', 'Diploma'), ('Certificate', 'Certificate'), ('Course Completion Certificate', 'Course Completion Certificate'), ('Degree Certificate', 'Degree Certificate'), ('Licensure', 'Licensure'), ('Ordination Certificate', 'Ordination Certificate')], max_length=50, verbose_name='Education Document Type')),
                ('education_degree', models.CharField(choices=[('Bachelor of Theology (BTh)', 'Bachelor of Theology (BTh)'), ('Master of Divinity (MDiv)', 'Master of Divinity (MDiv)'), ('Doctor of Theology (ThD)', 'Doctor of Theology (ThD)'), ('Bachelor of Arts (BA)', 'Bachelor of Arts (BA)'), ('Master of Science (MSc)', 'Master of Science (MSc)'), ('Doctor of Philosophy (PhD)', 'Doctor of Philosophy (PhD)'), ('Diploma in Pastoral Ministry', 'Diploma in Pastoral Ministry'), ('Associate Degree in Biblical Studies', 'Associate Degree in Biblical Studies'), ('Advanced Diploma in Christian Counseling', 'Advanced Diploma in Christian Counseling'), ('Postgraduate Certificate in Religious Studies', 'Postgraduate Certificate in Religious Studies')], max_length=100, verbose_name='Education Degree')),
                ('school', models.CharField(max_length=100, verbose_name='School')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('graduation_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Graduation Year')),
                ('document', models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.pdf_validators.validate_pdf_file, validators.security_validators.validate_no_executable_file], verbose_name='Document')),
                ('is_teology_related', models.BooleanField(default=False, verbose_name='Teology Related')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Is Approved')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Academic Record',
                'verbose_name_plural': 'Academic Records',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('register_date', models.DateField(default=django.utils.timezone.now, verbose_name='Register Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': '4. Client',
                'verbose_name_plural': '4. Clients',
            },
        ),
        migrations.CreateModel(
            name='ClientRequest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('request', models.CharField(max_length=50, verbose_name='Request')),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
                ('document_1', models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.pdf_validators.validate_pdf_file, validators.security_validators.validate_no_executable_file], verbose_name='Document 1')),
                ('document_2', models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.pdf_validators.validate_pdf_file, validators.security_validators.validate_no_executable_file], verbose_name='Document 2')),
                ('register_date', models.DateField(default=django.utils.timezone.now, verbose_name='Register Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Client Request',
                'verbose_name_plural': 'Client Requests',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('customer_phone_number', models.CharField(max_length=20, validators=[validators.user_validators.validate_phone_number], verbose_name='Phone Number')),
                ('register_date', models.DateField(default=django.utils.timezone.now, verbose_name='Register Date')),
                ('deactivation_reason', models.CharField(blank=True, choices=[('user_request', 'User Request'), ('payment_issue', 'Payment Issue'), ('account_suspension', 'Account Suspension'), ('inactivity', 'Inactivity'), ('security_concerns', 'Security Concerns'), ('violation_of_terms', 'Violation of Terms'), ('other', 'Other')], max_length=50, null=True, verbose_name='Deactivation Reason')),
                ('deactivation_note', models.TextField(blank=True, null=True, verbose_name='Deactivation Note')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': '5. Customer',
                'verbose_name_plural': '5. Customers',
            },
        ),
        migrations.CreateModel(
            name='Fellowship',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fellowship_type', models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Son', 'Son'), ('Daughter', 'Daughter'), ('Husband', 'Husband'), ('Wife', 'Wife'), ('Confidant', 'Confidant'), ('Pastor', 'Pastor'), ('Mentor', 'Mentor')], max_length=20, verbose_name='Fellowship Type')),
                ('reciprocal_fellowship_type', models.CharField(blank=True, choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Son', 'Son'), ('Daughter', 'Daughter'), ('Husband', 'Husband'), ('Wife', 'Wife'), ('Confidant', 'Confidant'), ('Pastor', 'Pastor'), ('Mentor', 'Mentor'), ('Disciple', 'Disciple'), ('Mentee', 'Mentee'), ('Entrusted', 'Entrusted')], max_length=50, null=True, verbose_name='Reciprocal Fellowship Type')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Declined', 'Declined'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fellowship',
                'verbose_name_plural': 'Fellowships',
            },
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled', 'Cancelled'), ('deleted', 'Deleted')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Friendship',
                'verbose_name_plural': 'Friendships',
            },
        ),
        migrations.CreateModel(
            name='GuestUser',
            fields=[
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('register_date', models.DateField(default=django.utils.timezone.now, verbose_name='Register Date')),
                ('is_migrated', models.BooleanField(default=False, verbose_name='Is Migrated')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': '1. Guest User',
                'verbose_name_plural': '1. Guest Users',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('biography', models.CharField(blank=True, max_length=300, null=True, verbose_name='Biography')),
                ('vision', models.CharField(blank=True, max_length=500, null=True, verbose_name='Vision')),
                ('spiritual_rebirth_day', models.DateField(blank=True, null=True, verbose_name='Spiritual Rebirth Days')),
                ('denominations_type', models.CharField(blank=True, choices=[('lutheranism', 'Lutheranism'), ('calvinism_or_reformed', 'Calvinism or Reformed'), ('anglicanism', 'Anglicanism'), ('methodism', 'Methodism'), ('baptism', 'Baptism'), ('presbyterianism', 'Presbyterianism'), ('pentecostalism', 'Pentecostalism'), ('adventism', 'Adventism'), ('anabaptism', 'Anabaptism'), ('congregationalism', 'Congregationalism'), ('roman_catholicism', 'Roman Catholicism'), ('eastern_catholic_churches', 'Eastern Catholic Churches'), ('eastern_orthodoxy', 'Eastern Orthodoxy'), ('oriental_Orthodoxy', 'Oriental Orthodoxy'), ('church_of_the_East', 'Church of the East')], max_length=40, null=True, verbose_name='Denominations Type')),
                ('show_gifts_in_profile', models.BooleanField(default=True, help_text='Allow gifts to be visible on the profile page.', verbose_name='Show Gifts in Profile')),
                ('show_fellowship_in_profile', models.BooleanField(default=True, verbose_name='Show Fellowship in Profile')),
                ('register_date', models.DateField(default=django.utils.timezone.now, verbose_name='Register Date')),
                ('identity_document', models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.pdf_validators.validate_pdf_file, validators.security_validators.validate_no_executable_file], verbose_name='Identity Document')),
                ('identity_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Identity Verified At')),
                ('identity_verification_status', models.CharField(choices=[('not_submitted', 'Not Submitted'), ('pending_review', 'Pending Review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='not_submitted', max_length=20, verbose_name='Identity Verification Status')),
                ('is_verified_identity', models.BooleanField(default=False, verbose_name='Verified Identity')),
                ('is_sanctuary_participant', models.BooleanField(default=False, verbose_name='Sanctuary Participant')),
                ('is_hidden_by_confidants', models.BooleanField(default=False, verbose_name='Hidden by Confidants')),
                ('is_privacy', models.BooleanField(default=False, verbose_name='Is Privacy')),
                ('is_migrated', models.BooleanField(default=False, verbose_name='Is Migrated')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('academic_record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_academic_record', to='profiles.academicrecord')),
            ],
            options={
                'verbose_name': '2. Member',
                'verbose_name_plural': '2. Members',
            },
        ),
        migrations.CreateModel(
            name='SpiritualGift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('wisdom', 'Wisdom'), ('knowledge', 'Knowledge'), ('administration', 'Administration'), ('apostleship', 'Apostleship'), ('shepherding', 'Shepherding'), ('faith', 'Faith'), ('miracles', 'Miracles'), ('prophecy', 'Prophecy'), ('leadership', 'Leadership'), ('giving', 'Giving'), ('compassion', 'Compassion'), ('healing', 'Healing'), ('discernment', 'Discernment'), ('teaching', 'Teaching'), ('helping', 'Helping'), ('evangelism', 'Evangelism'), ('servanthood', 'Servanthood'), ('exhortation', 'Exhortation'), ('tongues', 'Tongues'), ('interpretation_of_tongues', 'Interpretation of Tongues')], max_length=100, verbose_name='Spiritual Gift Name')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Spiritual Gift',
                'verbose_name_plural': 'Spiritual Gifts',
            },
        ),
        migrations.CreateModel(
            name='SpiritualGiftSurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=500, verbose_name='Question Text')),
                ('question_number', models.IntegerField(verbose_name='Question Number')),
                ('language', models.CharField(choices=[('en', 'English'), ('fa', 'Persian'), ('tr', 'Turkish'), ('es', 'Spanish'), ('zh', 'Chinese'), ('ar', 'Arabic'), ('ko', 'Korean'), ('fr', 'French'), ('de', 'German'), ('it', 'Italian'), ('pt', 'Portuguese'), ('ru', 'Russian'), ('ja', 'Japanese'), ('hi', 'Hindi'), ('bn', 'Bengali'), ('ur', 'Urdu'), ('id', 'Indonesian'), ('ta', 'Tamil'), ('ms', 'Malay'), ('vi', 'Vietnamese'), ('th', 'Thai')], max_length=10, verbose_name='Language')),
                ('options', models.JSONField(verbose_name='Options')),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.spiritualgift', verbose_name='Spiritual Gift')),
            ],
            options={
                'verbose_name': 'Spiritual Gift Survey Question',
                'verbose_name_plural': 'Spiritual Gift Survey Questions',
            },
        ),
        migrations.CreateModel(
            name='SpiritualService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('administration', 'Administration'), ('charitable_work', 'Charitable Work'), ('chaplaincy', 'Chaplaincy'), ('childrens_ministry', 'Children’s Ministry'), ('church_planting', 'Church Planting'), ('counseling', 'Counseling'), ('discipleship', 'Discipleship'), ('evangelism', 'Evangelism'), ('healing_ministry', 'Healing Ministry'), ('hospital_visitation', 'Hospital Visitation'), ('hospitality', 'Hospitality'), ('intercessory_prayer', 'Intercessory Prayer'), ('leadership', 'Leadership'), ('media_ministry', 'Media Ministry'), ('missionary_work', 'Missionary Work'), ('music_ministry', 'Music Ministry'), ('outreach_ministry', 'Outreach Ministry'), ('pastoring', 'Pastoring'), ('prayer_ministry', 'Prayer Ministry'), ('small_group_leadership', 'Small Group Leadership'), ('spiritual_direction', 'Spiritual Direction'), ('support_group_leadership', 'Support Group Leadership'), ('teaching', 'Teaching'), ('worship_leadership', 'Worship Leadership'), ('youth_ministry', 'Youth Ministry')], max_length=40, unique=True, verbose_name='Name of Service')),
                ('color', colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=18, null=True, samples=None, verbose_name='Color Code')),
                ('description', models.CharField(blank=True, max_length=300, null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Spiritual Service',
                'verbose_name_plural': 'Spiritual Services',
            },
        ),
        migrations.CreateModel(
            name='SpiritualGiftSurveyResponse',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('question_number', models.IntegerField(verbose_name='Question Number')),
                ('answer', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], verbose_name='Answer')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.member', verbose_name='Member')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.spiritualgiftsurveyquestion', verbose_name='Question')),
            ],
            options={
                'verbose_name': 'Spiritual Gift Survey Response',
                'verbose_name_plural': 'Spiritual Gift Survey Responses',
            },
        ),
        migrations.CreateModel(
            name='MigrationHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('migration_type', models.CharField(choices=[('guest_to_member', 'GuestUser to Member'), ('member_to_guest', 'Member to GuestUser')], max_length=20)),
                ('migration_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='migration_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Migration History',
                'verbose_name_plural': 'Migration Histories',
            },
        ),
        migrations.CreateModel(
            name='MemberSurveyProgress',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('current_question', models.IntegerField(default=1, verbose_name='Current Question')),
                ('answered_questions', models.JSONField(default=list, verbose_name='Answered Questions')),
                ('incomplete_survey', models.BooleanField(default=False, verbose_name='Incomplete Survey')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.member', verbose_name='Member')),
            ],
            options={
                'verbose_name': 'Member Survey Progress',
                'verbose_name_plural': 'Member Survey Progresses',
            },
        ),
        migrations.CreateModel(
            name='MemberSpiritualGifts',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('survey_results', models.JSONField(verbose_name='Survey Results')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('gifts', models.ManyToManyField(to='profiles.spiritualgift', verbose_name='Spiritual Gifts')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.member', verbose_name='Member')),
            ],
            options={
                'verbose_name': 'User Spiritual Gifts',
                'verbose_name_plural': 'User Spiritual Gifts',
            },
        ),
        migrations.CreateModel(
            name='MemberServiceType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('history', models.CharField(blank=True, max_length=500, null=True, verbose_name='History')),
                ('document', models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.pdf_validators.validate_pdf_file, validators.security_validators.validate_no_executable_file], verbose_name='Documents')),
                ('register_date', models.DateField(default=django.utils.timezone.now, verbose_name='Register Date')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Is Approved')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_instances', to='profiles.spiritualservice', verbose_name='Service Name')),
            ],
            options={
                'verbose_name': 'MemberServiceType',
                'verbose_name_plural': 'MemberServiceTypes',
            },
        ),
    ]
