# Generated by Django 4.2.4 on 2025-04-20 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profilesOrg', '0001_initial'),
        ('accounts', '0001_initial'),
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='organization_memberships',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='memberships', to='profilesOrg.organization', verbose_name='Organization Memberships'),
        ),
        migrations.AddField(
            model_name='member',
            name='service_types',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='member_service_types', to='profiles.memberservicetype', verbose_name='Service Types'),
        ),
        migrations.AddField(
            model_name='member',
            name='testimony',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_testimonies', to='posts.testimony', verbose_name='Member Testimony'),
        ),
        migrations.AddField(
            model_name='friendship',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_initiated', to=settings.AUTH_USER_MODEL, verbose_name='Initiator'),
        ),
        migrations.AddField(
            model_name='friendship',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_received', to=settings.AUTH_USER_MODEL, verbose_name='Friend'),
        ),
        migrations.AddField(
            model_name='fellowship',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fellowship_sent', to=settings.AUTH_USER_MODEL, verbose_name='From User'),
        ),
        migrations.AddField(
            model_name='fellowship',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fellowship_received', to=settings.AUTH_USER_MODEL, verbose_name='To User'),
        ),
        migrations.AddField(
            model_name='customer',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_billing_addresses', to='accounts.address', verbose_name='Billing Address'),
        ),
        migrations.AddField(
            model_name='customer',
            name='shipping_addresses',
            field=models.ManyToManyField(related_name='customer_shipping_addresses', to='accounts.address', verbose_name='Shipping Addresses'),
        ),
        migrations.AddField(
            model_name='client',
            name='organization_clients',
            field=models.ManyToManyField(blank=True, related_name='organization_clients', to='profilesOrg.organization', verbose_name='Organization Clients'),
        ),
        migrations.AddField(
            model_name='client',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.clientrequest', verbose_name='Request'),
        ),
        migrations.AddConstraint(
            model_name='friendship',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('from_user', 'to_user'), name='unique_active_friendship'),
        ),
        migrations.AddConstraint(
            model_name='fellowship',
            constraint=models.UniqueConstraint(fields=('from_user', 'to_user', 'fellowship_type', 'reciprocal_fellowship_type'), name='unique_fellowship_per_type'),
        ),
    ]
