# Generated by Django 4.2.4 on 2025-07-29 02:19

from django.db import migrations, models
import utils.common.utils
import validators.mediaValidators.pdf_validators
import validators.security_validators


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_academicrecord_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='hide_confidants',
            field=models.BooleanField(default=False, verbose_name='Hide Confidants in setting'),
        ),
        migrations.AlterField(
            model_name='academicrecord',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.pdf_validators.validate_pdf_file, validators.security_validators.validate_no_executable_file], verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='clientrequest',
            name='document_1',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.pdf_validators.validate_pdf_file, validators.security_validators.validate_no_executable_file], verbose_name='Document 1'),
        ),
        migrations.AlterField(
            model_name='clientrequest',
            name='document_2',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.pdf_validators.validate_pdf_file, validators.security_validators.validate_no_executable_file], verbose_name='Document 2'),
        ),
        migrations.AlterField(
            model_name='fellowship',
            name='fellowship_type',
            field=models.CharField(choices=[('Husband', 'He is my Husband'), ('Wife', 'She is my Wife'), ('Father', 'He is my Father'), ('Mother', 'She is my Mother'), ('Son', 'He is my Son'), ('Daughter', 'She is my Daughter'), ('Confidant', 'My Trusted Confidant'), ('Pastor', 'My Spiritual Pastor'), ('Mentor', 'My Mentor and Guide')], max_length=20, verbose_name='Fellowship Type'),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('s', 'Cancelled'), ('deleted', 'Deleted')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='member',
            name='identity_document',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.pdf_validators.validate_pdf_file, validators.security_validators.validate_no_executable_file], verbose_name='Identity Document'),
        ),
        migrations.AlterField(
            model_name='memberservicetype',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.pdf_validators.validate_pdf_file, validators.security_validators.validate_no_executable_file], verbose_name='Documents'),
        ),
    ]
