# Generated by Django 4.2.4 on 2025-10-07 02:27

from django.db import migrations, models
import utils.common.utils
import validators.mediaValidators.pdf_validators
import validators.security_validators


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_alter_academicrecord_document_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicrecord',
            options={'ordering': ['-started_at', '-graduated_at', '-expected_graduation_at', '-id'], 'verbose_name': 'Academic Record', 'verbose_name_plural': 'Academic Records'},
        ),
        migrations.RemoveField(
            model_name='academicrecord',
            name='graduation_year',
        ),
        migrations.RemoveField(
            model_name='academicrecord',
            name='is_teology_related',
        ),
        migrations.AddField(
            model_name='academicrecord',
            name='expected_graduation_at',
            field=models.DateField(blank=True, null=True, verbose_name='Expected Graduation (YYYY-MM-01)'),
        ),
        migrations.AddField(
            model_name='academicrecord',
            name='graduated_at',
            field=models.DateField(blank=True, null=True, verbose_name='Graduated At (YYYY-MM-01)'),
        ),
        migrations.AddField(
            model_name='academicrecord',
            name='is_theology_related',
            field=models.BooleanField(default=False, verbose_name='Theology Related'),
        ),
        migrations.AddField(
            model_name='academicrecord',
            name='started_at',
            field=models.DateField(blank=True, null=True, verbose_name='Started At (YYYY-MM-01)'),
        ),
        migrations.AddField(
            model_name='academicrecord',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('dropped', 'Dropped')], default='in_progress', max_length=20, verbose_name='Study Status'),
        ),
        migrations.AlterField(
            model_name='academicrecord',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.pdf_validators.validate_pdf_file, validators.security_validators.validate_no_executable_file], verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='clientrequest',
            name='document_1',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.pdf_validators.validate_pdf_file, validators.security_validators.validate_no_executable_file], verbose_name='Document 1'),
        ),
        migrations.AlterField(
            model_name='clientrequest',
            name='document_2',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.pdf_validators.validate_pdf_file, validators.security_validators.validate_no_executable_file], verbose_name='Document 2'),
        ),
        migrations.AlterField(
            model_name='member',
            name='identity_document',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.pdf_validators.validate_pdf_file, validators.security_validators.validate_no_executable_file], verbose_name='Identity Document'),
        ),
        migrations.AlterField(
            model_name='memberservicetype',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.pdf_validators.validate_pdf_file, validators.security_validators.validate_no_executable_file]),
        ),
    ]
