# Generated by Django 4.2.4 on 2025-10-27 23:45

from django.db import migrations, models
import utils.common.utils
import validators.mediaValidators.pdf_validators
import validators.security_validators


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0022_remove_member_denominations_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicrecord',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.pdf_validators.validate_pdf_file, validators.security_validators.validate_no_executable_file], verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='clientrequest',
            name='document_1',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.pdf_validators.validate_pdf_file, validators.security_validators.validate_no_executable_file], verbose_name='Document 1'),
        ),
        migrations.AlterField(
            model_name='clientrequest',
            name='document_2',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.pdf_validators.validate_pdf_file, validators.security_validators.validate_no_executable_file], verbose_name='Document 2'),
        ),
        migrations.AlterField(
            model_name='member',
            name='biography',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Biography'),
        ),
        migrations.AlterField(
            model_name='member',
            name='denomination_family',
            field=models.CharField(blank=True, choices=[('anglicanism', 'Anglican'), ('lutheranism', 'Lutheran'), ('calvinism_or_reformed', 'Reformed/Calvinist'), ('presbyterianism', 'Presbyterian'), ('congregationalism', 'Congregational'), ('methodism', 'Methodist/Wesleyan'), ('wesleyan_holiness', 'Wesleyan Holiness'), ('baptist', 'Baptist'), ('anabaptism', 'Anabaptist (Mennonite/Amish/Hutterite)'), ('pietist_moravian', 'Pietist/Moravian'), ('quaker_friends', 'Friends (Quaker)'), ('restorationist_stone_campbell', 'Restorationist (Stone-Campbell)'), ('adventism', 'Adventist'), ('brethren_plymouth', 'Brethren (Plymouth Brethren)'), ('pentecostalism', 'Pentecostal'), ('charismatic_nondenominational', 'Charismatic (Non-denominational)'), ('evangelical_nondenominational', 'Evangelical (Non-denominational)'), ('latin_rite', 'Catholic – Latin (Roman) Rite'), ('byzantine_catholic', 'Catholic – Byzantine (Eastern Catholic)'), ('alexandrian_coptic_catholic', 'Catholic – Alexandrian/Coptic Catholic'), ('antiochian_west_syriac_catholic', 'Catholic – Antiochian/West Syriac (Syriac/Maronite)'), ('east_syriac_chaldean_catholic', 'Catholic – East Syriac (Chaldean/Syro-Malabar)'), ('armenian_catholic', 'Catholic – Armenian Catholic'), ('eastern_catholic_churches', 'Catholic – Eastern Catholic (General)'), ('eo_greek', 'Eastern Orthodox – Greek'), ('eo_russian', 'Eastern Orthodox – Russian'), ('eo_serbian', 'Eastern Orthodox – Serbian'), ('eo_romanian', 'Eastern Orthodox – Romanian'), ('eo_bulgarian', 'Eastern Orthodox – Bulgarian'), ('eo_georgian', 'Eastern Orthodox – Georgian'), ('eo_antiochian', 'Eastern Orthodox – Antiochian'), ('eo_oca', 'Eastern Orthodox – Orthodox Church in America'), ('eo_other_autocephalous', 'Eastern Orthodox – Other Autocephalous'), ('oo_coptic', 'Oriental Orthodox – Coptic'), ('oo_armenian_apostolic', 'Oriental Orthodox – Armenian Apostolic'), ('oo_syriac', 'Oriental Orthodox – Syriac'), ('oo_ethiopian', 'Oriental Orthodox – Ethiopian'), ('oo_eritrean', 'Oriental Orthodox – Eritrean'), ('oo_malankara_indian', 'Oriental Orthodox – Malankara (Indian)'), ('coe_assyrian', 'Church of the East – Assyrian'), ('coe_ancient', 'Church of the East – Ancient Church of the East'), ('oc_union_of_utrecht', 'Old Catholic – Union of Utrecht'), ('oc_union_of_scranton', 'Old Catholic – Union of Scranton'), ('oc_other_old_catholic', 'Old Catholic – Other Old Catholic')], max_length=60, null=True, verbose_name='Denomination Family (Optional)'),
        ),
        migrations.AlterField(
            model_name='member',
            name='identity_document',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.pdf_validators.validate_pdf_file, validators.security_validators.validate_no_executable_file], verbose_name='Identity Document'),
        ),
        migrations.AlterField(
            model_name='member',
            name='vision',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Vision'),
        ),
        migrations.AlterField(
            model_name='memberservicetype',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.pdf_validators.validate_pdf_file, validators.security_validators.validate_no_executable_file]),
        ),
    ]
