# Generated by Django 4.2.4 on 2025-10-30 23:35

from django.db import migrations, models
import utils.common.utils
import validators.mediaValidators.pdf_validators
import validators.security_validators


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0023_alter_academicrecord_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicrecord',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.pdf_validators.validate_pdf_file, validators.security_validators.validate_no_executable_file], verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='clientrequest',
            name='document_1',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.pdf_validators.validate_pdf_file, validators.security_validators.validate_no_executable_file], verbose_name='Document 1'),
        ),
        migrations.AlterField(
            model_name='clientrequest',
            name='document_2',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.pdf_validators.validate_pdf_file, validators.security_validators.validate_no_executable_file], verbose_name='Document 2'),
        ),
        migrations.AlterField(
            model_name='member',
            name='identity_document',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.pdf_validators.validate_pdf_file, validators.security_validators.validate_no_executable_file], verbose_name='Identity Document'),
        ),
        migrations.AlterField(
            model_name='memberservicetype',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.pdf_validators.validate_pdf_file, validators.security_validators.validate_no_executable_file]),
        ),
        migrations.AlterField(
            model_name='spiritualservice',
            name='name',
            field=models.CharField(choices=[('administration', 'Administration'), ('hospitality', 'Hospitality'), ('greeter', 'Greeter'), ('welcome', 'Welcome'), ('newcomer', 'Newcomer'), ('outreach', 'Outreach'), ('evangelism', 'Evangelism'), ('missions', 'Missions'), ('prayer', 'Prayer'), ('intercession', 'Intercession'), ('worship', 'Worship'), ('music', 'Music'), ('choir', 'Choir'), ('band', 'Band'), ('audio', 'Audio'), ('video', 'Video'), ('sound', 'Sound'), ('lighting', 'Lighting'), ('livestream', 'Livestream'), ('production', 'Production'), ('media', 'Media'), ('photography', 'Photography'), ('design', 'Design'), ('it', 'IT'), ('communications', 'Communications'), ('events', 'Events'), ('logistics', 'Logistics'), ('setup', 'Setup'), ('facilities', 'Facilities'), ('maintenance', 'Maintenance'), ('transport', 'Transport'), ('translation', 'Translation'), ('stewardship', 'Stewardship'), ('training', 'Training'), ('benevolence', 'Benevolence')], max_length=40, unique=True, verbose_name='Name of Service'),
        ),
    ]
