# Generated by Django 4.2.4 on 2025-11-17 21:28

from django.db import migrations, models
import utils.common.utils
import validators.mediaValidators.pdf_validators
import validators.security_validators


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0028_alter_guestuser_options_alter_member_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicrecord',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.pdf_validators.validate_pdf_file, validators.security_validators.validate_no_executable_file], verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='clientrequest',
            name='document_1',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.pdf_validators.validate_pdf_file, validators.security_validators.validate_no_executable_file], verbose_name='Document 1'),
        ),
        migrations.AlterField(
            model_name='clientrequest',
            name='document_2',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.pdf_validators.validate_pdf_file, validators.security_validators.validate_no_executable_file], verbose_name='Document 2'),
        ),
        migrations.AlterField(
            model_name='member',
            name='identity_document',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.pdf_validators.validate_pdf_file, validators.security_validators.validate_no_executable_file], verbose_name='Identity Document'),
        ),
        migrations.AlterField(
            model_name='memberservicetype',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.pdf_validators.validate_pdf_file, validators.security_validators.validate_no_executable_file]),
        ),
    ]
