# Generated by Django 4.2.4 on 2025-12-20 08:16

from django.db import migrations, models
import utils.common.utils
import validators.mediaValidators.pdf_validators
import validators.security_validators


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0035_alter_academicrecord_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='identity_document',
        ),
        migrations.RemoveField(
            model_name='member',
            name='identity_verification_status',
        ),
        migrations.RemoveField(
            model_name='member',
            name='identity_verified_at',
        ),
        migrations.RemoveField(
            model_name='member',
            name='is_verified_identity',
        ),
        migrations.AddField(
            model_name='member',
            name='is_townlit_verified',
            field=models.BooleanField(db_index=True, default=False, verbose_name='TownLIT Verified'),
        ),
        migrations.AddField(
            model_name='member',
            name='townlit_verified_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='TownLIT Verified At'),
        ),
        migrations.AddField(
            model_name='member',
            name='townlit_verified_reason',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='TownLIT Verification Reason'),
        ),
        migrations.AlterField(
            model_name='academicrecord',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.pdf_validators.validate_pdf_file, validators.security_validators.validate_no_executable_file], verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='clientrequest',
            name='document_1',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.pdf_validators.validate_pdf_file, validators.security_validators.validate_no_executable_file], verbose_name='Document 1'),
        ),
        migrations.AlterField(
            model_name='clientrequest',
            name='document_2',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.pdf_validators.validate_pdf_file, validators.security_validators.validate_no_executable_file], verbose_name='Document 2'),
        ),
        migrations.AlterField(
            model_name='memberservicetype',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.pdf_validators.validate_pdf_file, validators.security_validators.validate_no_executable_file]),
        ),
    ]
