# Generated by Django 4.2.4 on 2025-05-22 22:21

import common.validators
from django.db import migrations, models
import utils.common.utils


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0053_alter_academicrecord_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='member_active_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='member_active_code_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academicrecord',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[common.validators.validate_pdf_file, common.validators.validate_no_executable_file], verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='clientrequest',
            name='document_1',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[common.validators.validate_pdf_file, common.validators.validate_no_executable_file], verbose_name='Document 1'),
        ),
        migrations.AlterField(
            model_name='clientrequest',
            name='document_2',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[common.validators.validate_pdf_file, common.validators.validate_no_executable_file], verbose_name='Document 2'),
        ),
        migrations.AlterField(
            model_name='member',
            name='identity_document',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[common.validators.validate_pdf_file, common.validators.validate_no_executable_file], verbose_name='Identity Document'),
        ),
        migrations.AlterField(
            model_name='memberservicetype',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[common.validators.validate_pdf_file, common.validators.validate_no_executable_file], verbose_name='Documents'),
        ),
    ]
