# Generated by Django 4.2.4 on 2026-03-17 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0077_alter_academicrecord_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestuser',
            name='biography',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Biography'),
        ),
        migrations.AddField(
            model_name='guestuser',
            name='is_privacy',
            field=models.BooleanField(default=False, verbose_name='Is Privacy'),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled', 'Cancelled'), ('deleted', 'Deleted')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='guestuser',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Is Active'),
        ),
    ]
