# Generated by Django 4.2.4 on 2026-03-23 04:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0078_guestuser_biography_guestuser_is_privacy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestuser',
            name='register_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Register Date'),
        ),
        migrations.AlterField(
            model_name='member',
            name='register_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Register Date'),
        ),
    ]
