# Generated by Django 4.2.4 on 2026-04-11 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookstore_inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookorder',
            name='fulfilled_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='bookorder',
            name='fulfilled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookstore_orders_fulfilled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inboundshipment',
            name='stock_posted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='inboundshipment',
            name='stock_posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookstore_inbound_shipments_stock_posted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
