# Generated by Django 4.2.4 on 2026-04-12 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_inventory', '0003_remove_bookorder_customer_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookorder',
            old_name='organization_email',
            new_name='customer_email',
        ),
        migrations.RenameField(
            model_name='bookorder',
            old_name='address_line_1',
            new_name='customer_name',
        ),
        migrations.RenameField(
            model_name='bookorder',
            old_name='organization_phone',
            new_name='customer_phone',
        ),
        migrations.RemoveField(
            model_name='bookorder',
            name='address_line_2',
        ),
        migrations.RemoveField(
            model_name='bookorder',
            name='city',
        ),
        migrations.RemoveField(
            model_name='bookorder',
            name='country',
        ),
        migrations.RemoveField(
            model_name='bookorder',
            name='delivery_method',
        ),
        migrations.RemoveField(
            model_name='bookorder',
            name='organization_contact_person',
        ),
        migrations.RemoveField(
            model_name='bookorder',
            name='organization_name',
        ),
        migrations.RemoveField(
            model_name='bookorder',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='bookorder',
            name='province_state',
        ),
        migrations.RemoveField(
            model_name='bookorder',
            name='purpose',
        ),
        migrations.RemoveField(
            model_name='bookorder',
            name='recipient_email',
        ),
        migrations.RemoveField(
            model_name='bookorder',
            name='recipient_first_name',
        ),
        migrations.RemoveField(
            model_name='bookorder',
            name='recipient_last_name',
        ),
        migrations.RemoveField(
            model_name='bookorder',
            name='recipient_phone',
        ),
        migrations.RemoveField(
            model_name='bookorder',
            name='recipient_type',
        ),
    ]
