# Generated by Django 4.2.4 on 2026-04-12 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_inventory', '0004_rename_organization_email_bookorder_customer_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookorder',
            old_name='customer_name',
            new_name='address_line_1',
        ),
        migrations.RenameField(
            model_name='bookorder',
            old_name='customer_email',
            new_name='organization_email',
        ),
        migrations.RenameField(
            model_name='bookorder',
            old_name='customer_phone',
            new_name='organization_phone',
        ),
        migrations.AddField(
            model_name='bookorder',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='bookorder',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='bookorder',
            name='country',
            field=models.CharField(blank=True, default='Canada', max_length=120),
        ),
        migrations.AddField(
            model_name='bookorder',
            name='delivery_method',
            field=models.CharField(choices=[('pickup', 'Pickup'), ('shipping', 'Shipping'), ('hand_delivery', 'Hand delivery'), ('internal_transfer', 'Internal transfer')], db_index=True, default='pickup', max_length=24),
        ),
        migrations.AddField(
            model_name='bookorder',
            name='organization_contact_person',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='bookorder',
            name='organization_name',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='bookorder',
            name='postal_code',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='bookorder',
            name='province_state',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='bookorder',
            name='purpose',
            field=models.CharField(choices=[('personal_sale', 'Personal sale'), ('organization_sale', 'Organization sale'), ('donation', 'Donation'), ('church_support', 'Church support'), ('event_distribution', 'Event distribution'), ('internal_use', 'Internal use'), ('promotional', 'Promotional'), ('other', 'Other')], db_index=True, default='personal_sale', max_length=32),
        ),
        migrations.AddField(
            model_name='bookorder',
            name='recipient_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='bookorder',
            name='recipient_first_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='bookorder',
            name='recipient_last_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='bookorder',
            name='recipient_phone',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='bookorder',
            name='recipient_type',
            field=models.CharField(choices=[('person', 'Person'), ('organization', 'Organization')], db_index=True, default='person', max_length=24),
        ),
    ]
