"""
Django settings for townlit_b project.

Generated by 'django-admin startproject' using Django 4.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from cryptography.fernet import Fernet
from corsheaders.defaults import default_headers


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

ENV_FILE = os.getenv('ENV_FILE', '.env')
load_dotenv(BASE_DIR / ENV_FILE, override=True)



# ---------------------------------------------------------------------------------------
CORS_ALLOW_ALL_ORIGINS = os.getenv('CORS_ALLOW_ALL_ORIGINS', 'False').lower() in ('true', '1', 't')

if not CORS_ALLOW_ALL_ORIGINS:
    allowed_origins = os.getenv("CORS_ALLOWED_ORIGINS", "")
    CORS_ALLOWED_ORIGINS = [origin.strip() for origin in allowed_origins.split(",") if origin.strip()]
else:
    CORS_ALLOWED_ORIGINS = []


FRONTEND_BASE_URL = CORS_ALLOWED_ORIGINS[0] if CORS_ALLOWED_ORIGINS else "http://localhost:3000"
CORS_ALLOW_CREDENTIALS = os.getenv('CORS_ALLOW_CREDENTIALS', 'True').lower() in ('true', '1', 't')

# ---------------------------------------------------------------------------------------
ADMIN_E2E_DEBUG_PASSWORD = "testpassword"

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() in ('true', '1', 't')

# ----------------------------------------------------------------------------------------------------------------------------
ALLOWED_HOSTS = os.getenv("DJANGO_ALLOWED_HOSTS", "").split(",")
CSRF_TRUSTED_ORIGINS = os.getenv("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",")

REDIS_URL = os.getenv('REDIS_URL', 'redis://127.0.0.1:6379/0')
SITE_URL = os.getenv("SITE_URL", "https://www.townlit.com")
EMAIL_LOGO_URL = os.getenv("EMAIL_LOGO_URL", "https://www.townlit.com")


# ---- Cookies (read directly from env) ----------------------------------------
# Valid values: "Lax" | "Strict" | "None"
SESSION_COOKIE_SAMESITE = os.getenv("SESSION_COOKIE_SAMESITE", "Lax")

# Parse booleans from env: "1|true|yes|on" => True, otherwise False
CSRF_COOKIE_SECURE = os.getenv("CSRF_COOKIE_SECURE", "false").strip().lower() in ("1", "true", "yes", "on")
SESSION_COOKIE_SECURE = os.getenv("SESSION_COOKIE_SECURE", "false").strip().lower() in ("1", "true", "yes", "on")
SESSION_COOKIE_HTTPONLY = os.getenv("SESSION_COOKIE_HTTPONLY", "true").strip().lower() in ("1", "true", "yes", "on")

# Safety: SameSite=None requires Secure (browser rule)
if SESSION_COOKIE_SAMESITE == "None" and not SESSION_COOKIE_SECURE:
    import warnings
    warnings.warn("SESSION_COOKIE_SAMESITE='None' requires SESSION_COOKIE_SECURE=True; cookie may be dropped by browsers.")
    

# -----------------------------------------------------------------------------
RESET_LINK_EXPIRATION_MINUTES = int(os.getenv('RESET_LINK_EXPIRATION_MINUTES', 30))
EMAIL_CODE_EXPIRATION_MINUTES = int(os.getenv('EMAIL_CODE_EXPIRATION_MINUTES', 10))
PHONE_CODE_EXPIRATION_MINUTES = int(os.getenv("PHONE_CODE_EXPIRATION_MINUTES", 10))
LITSHIELD_ACCESS_EXPIRATION_SECONDS = int(os.getenv("LITSHIELD_ACCESS_EXPIRATION_SECONDS", 300))

# Set to False to disable invite code requirement -----------------------------
USE_INVITE_CODE = os.getenv("USE_INVITE_CODE", "False").lower() in ("true", "1", "yes")


# Ip Info ---------------------------------------------------------------------
IPINFO_API_KEY = os.getenv("IPINFO_API_KEY", "")


# ------------------------------------------------------------------------------
DEFAULT_USER_AVATAR_URL = os.getenv("DEFAULT_USER_AVATAR_URL", "/static/defaults/default-avatar.png")
DEFAULT_GROUP_AVATAR_URL = os.getenv("DEFAULT_GROUP_AVATAR_URL", "/static/defaults/default-group-avatar.png")



# ✅ Media files
# DEFAULT_PROFILE_IMAGE = "defaults/default-avatar.png"



DJANGO_CRYPTO_KEY = os.getenv("DJANGO_CRYPTO_KEY") 

# Application definition

INSTALLED_APPS = [
    'channels',             # Real-Time Notification
    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_cryptography',
    
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    
    'colorfield',
    'django_admin_listfilter_dropdown',
    'ckeditor',
    'ckeditor_uploader',
    'django_celery_beat',   # Celery
    'django_cleanup.apps.CleanupConfig', # Cleanup older files
    "django_extensions",
    
    # 2FA
    'django_otp',
    'django_otp.plugins.otp_totp',
    'django_otp.plugins.otp_static',

    'apps.main.apps.MainConfig',
    'apps.accounts.apps.AccountsConfig',
    'apps.profiles.apps.ProfilesConfig',
    'apps.profilesOrg.apps.ProfilesorgConfig',
    'apps.posts.apps.PostsConfig',
    'apps.sanctuary.apps.SanctuaryConfig',
    'apps.notifications.apps.NotificationsConfig',
    'apps.conversation.apps.ConversationConfig',
    'apps.communication.apps.CommunicationConfig',
    'apps.moderation.apps.ModerationConfig',
    'apps.store.apps.StoreConfig',
    'apps.products.apps.ProductsConfig',
    'apps.orders.apps.OrdersConfig',
    'apps.payment.apps.PaymentConfig',
    'apps.warehouse.apps.WarehouseConfig',
    
    # pip install django-cors-headers
    'corsheaders',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_otp.middleware.OTPMiddleware',  # 2FA
    'whitenoise.middleware.WhiteNoiseMiddleware',

    'townlit_b.middleware.media_headers.AddMediaCORSHeadersMiddleware',

    'common.middleware.security_headers.SecurityHeadersMiddleware',
]

# To active WebSocket
ASGI_APPLICATION = 'townlit_b.asgi.application'

CORS_ALLOW_HEADERS = list(default_headers) + [
    'Range',
    'x-device-id',
    "x-install-id",
]
CORS_EXPOSE_HEADERS = ['Content-Range', 'Accept-Ranges']



ROOT_URLCONF = 'townlit_b.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates/')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'townlit_b.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.getenv('DATABASE_ENGINE', 'django.db.backends.mysql'),
        'NAME': os.getenv('DATABASE_NAME'),
        'USER': os.getenv('DATABASE_USER'),
        'PASSWORD': os.getenv('DATABASE_PASSWORD'),
        'HOST': os.getenv('DATABASE_HOST', 'mysql'),
        'PORT': os.getenv('DATABASE_PORT', '3306'),
        'OPTIONS': {
            'charset': 'utf8mb4',
            'init_command': "SET NAMES 'utf8mb4' COLLATE 'utf8mb4_unicode_ci'"
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

# LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True





# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'accounts.CustomUser'

# -------------------------------------------------------------------------------------------------------------------
POP_TTL_MINUTES = int(os.getenv("POP_TTL_MINUTES", "10"))
MAX_ACTIVE_DEVICE_KEYS = int(os.getenv("MAX_ACTIVE_DEVICE_KEYS", "10"))


# Throttle rates from env (fallback to sensible defaults) -----------------------------------------------------------
CRYPTO_THROTTLE_RATE = os.getenv("CRYPTO_THROTTLE_RATE", "30/min")
CRYPTO_HEAVY_THROTTLE_RATE = os.getenv("CRYPTO_HEAVY_THROTTLE_RATE", "10/min")


# Enforce sender verification only for DMs (True by default) --------------------------------------------------------
REQUIRE_SENDER_VERIFIED_DMS_ONLY = os.getenv("REQUIRE_SENDER_VERIFIED_DMS_ONLY", "1").lower() in ("1","true","yes")

# Optional grace for new devices to send before completing PoP (0 = disabled).
SENDER_VERIFIED_GRACE_MINUTES = int(os.getenv("SENDER_VERIFIED_GRACE_MINUTES", "0"))


# -------------------------------------------------------------------------------------------------------------------
REST_FRAMEWORK = {
    # --- Auth ---
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],

    # --- Permissions ---
    # Global gate: blocks authenticated users if is_suspended/is_deleted unless view sets allow_* flags.
    'DEFAULT_PERMISSION_CLASSES': [
        'apps.core.permissions.DenyIfDeletedOrSuspended',
    ],

    # --- Renderers / Parsers ---
    "DEFAULT_RENDERER_CLASSES": (
        "rest_framework.renderers.JSONRenderer",
    ),
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],

    # --- Exceptions ---
    # Unified error payload (code/message/status) incl. 423 Locked for suspended accounts.
    "EXCEPTION_HANDLER": "apps.core.exceptions.custom_exception_handler",

    # --- Throttling ---
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.ScopedRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        # Read from env; strings like "30/min" or "200/hour"
        "crypto": CRYPTO_THROTTLE_RATE,
        "crypto_heavy": CRYPTO_HEAVY_THROTTLE_RATE,
    },
}

from datetime import timedelta
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=24),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=14),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    "UPDATE_LAST_LOGIN": False,

    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": "",
    "AUDIENCE": None,
    "ISSUER": None,
    "JSON_ENCODER": None,
    "JWK_URL": None,
    "LEEWAY": 0,

    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "USER_AUTHENTICATION_RULE": "rest_framework_simplejwt.authentication.default_user_authentication_rule",

    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "TOKEN_USER_CLASS": "rest_framework_simplejwt.models.TokenUser",

    "JTI_CLAIM": "jti",

    "SLIDING_TOKEN_REFRESH_EXP_CLAIM": "refresh_exp",
    "SLIDING_TOKEN_LIFETIME": timedelta(minutes=5),
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(days=1),

    "TOKEN_OBTAIN_SERIALIZER": "rest_framework_simplejwt.serializers.TokenObtainPairSerializer",
    "TOKEN_REFRESH_SERIALIZER": "rest_framework_simplejwt.serializers.TokenRefreshSerializer",
    "TOKEN_VERIFY_SERIALIZER": "rest_framework.simplejwt.serializers.TokenVerifySerializer",
    "TOKEN_BLACKLIST_SERIALIZER": "rest_framework_simplejwt.serializers.TokenBlacklistSerializer",
    "SLIDING_TOKEN_OBTAIN_SERIALIZER": "rest_framework.simplejwt.serializers.TokenObtainSlidingSerializer",
    "SLIDING_TOKEN_REFRESH_SERIALIZER": "rest_framework.simplejwt.serializers.TokenRefreshSlidingSerializer",
}

# 2FA -------------------------------------------------------------------------------
SESSION_ENGINE = 'django.contrib.sessions.backends.cached_db'   # Session configuration to support OTP
OTP_TOTP_ISSUER = 'TownLIT'  # Your app name that will be shown in authenticator app



# Generate and store the Fernet key as an environment variable ----------------------
FERNET_KEY = os.getenv('FERNET_KEY')
if not FERNET_KEY:
    raise ValueError("FERNET_KEY is not set in the environment")

# Google API Key ---------------------------------------------------------------------
GOOGLE_API_KEY = os.getenv('GOOGLE_API_KEY')

# Email Backend
# AWS SES Configuration ---------------------------------------------------------------
AWS_SES_ACCESS_KEY_ID = os.getenv('AWS_SES_ACCESS_KEY_ID')
AWS_SES_SECRET_ACCESS_KEY = os.getenv('AWS_SES_SECRET_ACCESS_KEY')
AWS_SES_REGION_NAME = os.getenv('AWS_SES_REGION_NAME', 'us-east-1')
AWS_SES_REGION_ENDPOINT = os.getenv('AWS_SES_REGION_ENDPOINT', 'email.us-east-1.amazonaws.com')
AWS_SES_EMAIL_FROM = os.getenv('AWS_SES_EMAIL_FROM', 'no-reply@townlit.com')
AWS_SES_RETURN_PATH = 'no-reply@mail.townlit.com'


# Optional settings 
AWS_SES_AUTO_THROTTLE = 0.5  # Throttle for bulk emails

# AWS SNS Settings ----------------------------------------------------------------------
AWS_SNS_ACCESS_KEY_ID = os.getenv('AWS_SNS_ACCESS_KEY_ID')
AWS_SNS_SECRET_ACCESS_KEY = os.getenv('AWS_SNS_SECRET_ACCESS_KEY')
AWS_SNS_REGION = os.getenv('AWS_SNS_REGION')


# CKEditor ------------------------------------------------------------------------------
CKEDITOR_BASEPATH = "/static/ckeditor/ckeditor/"
CKEDITOR_UPLOAD_PATH = "photo/images/ckeditor/upload_files/"                
CKEDITOR_STORAGE_BACKEND = 'django.core.files.storage.FileSystemStorage' 

CKEDITOR_CONFIGS = {
    'default': {
        'skin': 'moono',
        'toolbar_Basic': [
            ['Source', '-', 'Bold', 'Italic']
        ],
        'toolbar_YourCustomToolbarConfig': [
            {'name': 'document', 'items': ['Source', '-', 'Save', 'NewPage', 'Preview', 'Print', '-', 'Templates']},
            {'name': 'clipboard', 'items': ['Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo']},
            {'name': 'editing', 'items': ['Find', 'Replace', '-', 'SelectAll']},
            {'name': 'forms',
             'items': ['Form', 'Checkbox', 'Radio', 'TextField', 'Textarea', 'Select', 'Button', 'ImageButton',
                       'HiddenField']},
            '/',
            {'name': 'basicstyles',
             'items': ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat']},
            {'name': 'paragraph',
             'items': ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote', 'CreateDiv', '-',
                       'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-', 'BidiLtr', 'BidiRtl',
                       'Language']},
            {'name': 'links', 'items': ['Link', 'Unlink', 'Anchor']},
            {'name': 'insert',
             'items': ['Image', 'Flash', 'Table', 'HorizontalRule', 'Smiley', 'SpecialChar', 'PageBreak', 'Iframe']},
            '/',
            {'name': 'styles', 'items': ['Styles', 'Format', 'Font', 'FontSize']},
            {'name': 'colors', 'items': ['TextColor', 'BGColor']},
            {'name': 'tools', 'items': ['Maximize', 'ShowBlocks']},
            {'name': 'about', 'items': ['About']},
            '/',  # put this to force next toolbar on new line
            {'name': 'yourcustomtools', 'items': [
                # put the name of your editor.ui.addButton here
                'Preview',
                'Maximize',
            ]},
        ],
        'toolbar': 'YourCustomToolbarConfig',  # put selected toolbar config here
        'tabSpaces': 4,
        'extraPlugins': ','.join([
            'uploadimage', # the upload image feature
            # your extra plugins here
            'div',
            'autolink',
            'autoembed',
            'embedsemantic',
            'autogrow',
            # 'devtools',
            'widget',
            'lineutils',
            'clipboard',
            'dialog',
            'dialogui',
            'elementspath'
        ]),
    }
}

# Redis Celery ------------------------------------------------------------------------
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

# Celery Task Tracking
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60 
CELERY_TASK_ALWAYS_EAGER = False
CELERY_ACKS_LATE = True
CELERY_TASK_DEFAULT_QUEUE = 'default'


broker_connection_retry_on_startup = True

# FCM KEY for push Notifications ------------------------------------------------------
FCM_PRIVATE_KEY_ID = os.getenv('FCM_PRIVATE_KEY_ID')
FCM_API_KEY = os.getenv('FCM_API_KEY')

# Real-Time Notification --------------------------------------------------------------
ASGI_APPLICATION = 'townlit_b.asgi.application'



# channels_redis for Real-Time Notification -------------------------------------------
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [REDIS_URL],
            "capacity": 2000,  # ← افزایش ظرفیت (پیش‌فرض 100)
            "expiry": 60 * 10,  # مدت‌زمان ذخیره‌سازی پیام‌ها
        },
    },
}


# Veriff -------------------------------------------------------------------------------
VERIFF_API_KEY = os.getenv('VERIFF_API_KEY')
VERIFF_BASE_URL = 'https://api.veriff.com/v1/'



# Fetch the master key from environment variables -------------------------------------
MASTER_KEY = os.environ.get('MASTER_KEY')

# Ensure the key is valid (Optional but recommended)
if not MASTER_KEY:
    raise ValueError("MASTER_KEY is not set in the environment")


# Configuration for PayPal ------------------------------------------------------------
PAYPAL_MODE = os.getenv('PAYPAL_MODE', 'sandbox')
PAYPAL_CLIENT_ID = os.getenv('PAYPAL_CLIENT_ID')
PAYPAL_SECRET_KEY = os.getenv('PAYPAL_SECRET_KEY')
PAYPAL_API_BASE_URL = 'https://api.paypal.com' 
TOWNLIT_PAYMENT_CONFIRM_TOKEN_EXPIRATION_MINUTES = 10
TOWNLIT_PAYMENT_CANCEL_TOKEN_EXPIRATION_MINUTES = 15

# Configuration for Stripe ------------------------------------------------------------
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY')
STRIPE_PUBLISHABLE_KEY = os.getenv('STRIPE_PUBLISHABLE_KEY')
STRIPE_WEBHOOK_SECRET = os.getenv('STRIPE_WEBHOOK_SECRET')
STRIPE_CURRENCY = os.getenv('STRIPE_CURRENCY', 'CAD')



# For Translate Languages --------------------------------------------------------------
from apps.profiles.gift_constants import GIFT_LANGUAGE_CHOICES
LANGUAGES = GIFT_LANGUAGE_CHOICES 
LANGUAGE_CODE = 'en'
USE_I18N = True
# USE_L10N = True 



# ✅ Static files
STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'



# ---------------- File Serving Policy ------------------
SERVE_FILES_PUBLICLY = os.getenv('SERVE_FILES_PUBLICLY', 'False').lower() in ('true', '1', 't')

# ---------------- Amazon S3 Media Storage ------------------
USE_S3 = os.getenv('USE_S3', 'False').lower() in ('true', '1', 't')

if USE_S3:
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

    AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME')
    AWS_S3_REGION_NAME = os.getenv('AWS_S3_REGION_NAME', 'us-east-1')

    AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com'

    AWS_DEFAULT_ACL = None  
    AWS_QUERYSTRING_AUTH = True  
    AWS_S3_FILE_OVERWRITE = False  

    AWS_S3_OBJECT_PARAMETERS = {
        'CacheControl': 'max-age=86400',
        'ACL': 'private',
    }

    MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/'

else:
    DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'
    MEDIA_URL = '/media/'
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {"console": {"class": "logging.StreamHandler"}},
    "root": {"handlers": ["console"], "level": "INFO"},
    "loggers": {
        "botocore": {"level": "WARNING"},
        "boto3": {"level": "WARNING"},
        "urllib3": {"level": "WARNING"},
        "django": {"level": "INFO"},
    },
}






# # Custom IP Whitelisting Configuration --------------------------------------------
# <RequireAll>
#     # My IP
#     Require ip 172.218.33.146
    
#     # Daivid IP
#     Require ip 88.242.139.164
    
# </RequireAll>

# public_html/api-v1-private.townlit.com

# https://github.com/settings/keys
# 


