# apps/accounting/config/chart_of_accounts.py

"""
Default Chart of Accounts configuration for TownLIT.
Used by the accounting seeder.
"""


CHART_OF_ACCOUNTS = [
    # -------------------------
    # Assets
    # -------------------------
    {
        "code": "1000",
        "name": "Cash",
        "account_type": "asset",
        "category": "Assets",
        "normal_balance": "debit",
        "allows_posting": True,
        "is_system": True,
        "parent_code": "",
        "sort_order": 1000,
        "description": "Cash on hand",
    },
    {
        "code": "1010",
        "name": "Bank Account",
        "account_type": "asset",
        "category": "Assets",
        "normal_balance": "debit",
        "allows_posting": True,
        "is_system": True,
        "parent_code": "",
        "sort_order": 1010,
        "description": "Primary operating bank account",
    },
    {
        "code": "1020",
        "name": "Payment Processor Balance",
        "account_type": "asset",
        "category": "Assets",
        "normal_balance": "debit",
        "allows_posting": True,
        "is_system": True,
        "parent_code": "",
        "sort_order": 1020,
        "description": "Balance held by payment processors",
    },
    {
        "code": "1030",
        "name": "Stripe Balance",
        "account_type": "asset",
        "category": "Assets",
        "normal_balance": "debit",
        "allows_posting": True,
        "is_system": True,
        "parent_code": "",
        "sort_order": 1030,
        "description": "Balance held in Stripe",
    },
    {
        "code": "1100",
        "name": "Accounts Receivable",
        "account_type": "asset",
        "category": "Assets",
        "normal_balance": "debit",
        "allows_posting": False,
        "is_system": True,
        "parent_code": "",
        "sort_order": 1100,
        "description": "Parent receivable account",
    },
    {
        "code": "1110",
        "name": "Subscription Receivable",
        "account_type": "asset",
        "category": "Assets",
        "normal_balance": "debit",
        "allows_posting": True,
        "is_system": True,
        "parent_code": "1100",
        "sort_order": 1110,
        "description": "Amounts due from subscriptions",
    },
    {
        "code": "1120",
        "name": "Advertisement Receivable",
        "account_type": "asset",
        "category": "Assets",
        "normal_balance": "debit",
        "allows_posting": True,
        "is_system": True,
        "parent_code": "1100",
        "sort_order": 1120,
        "description": "Amounts due from advertising",
    },
    {
        "code": "1130",
        "name": "Marketplace Receivable",
        "account_type": "asset",
        "category": "Assets",
        "normal_balance": "debit",
        "allows_posting": True,
        "is_system": True,
        "parent_code": "1100",
        "sort_order": 1130,
        "description": "Amounts due from marketplace activity",
    },
    {
        "code": "1200",
        "name": "Grants Receivable",
        "account_type": "asset",
        "category": "Assets",
        "normal_balance": "debit",
        "allows_posting": True,
        "is_system": True,
        "parent_code": "",
        "sort_order": 1200,
        "description": "Approved grants not yet received",
    },
    {
        "code": "1210",
        "name": "Pledged Donations",
        "account_type": "asset",
        "category": "Assets",
        "normal_balance": "debit",
        "allows_posting": True,
        "is_system": True,
        "parent_code": "",
        "sort_order": 1210,
        "description": "Donations pledged but not yet received",
    },
    {
        "code": "1300",
        "name": "Prepaid Expenses",
        "account_type": "asset",
        "category": "Assets",
        "normal_balance": "debit",
        "allows_posting": False,
        "is_system": True,
        "parent_code": "",
        "sort_order": 1300,
        "description": "Parent prepaid expense account",
    },
    {
        "code": "1310",
        "name": "Prepaid Hosting",
        "account_type": "asset",
        "category": "Assets",
        "normal_balance": "debit",
        "allows_posting": True,
        "is_system": True,
        "parent_code": "1300",
        "sort_order": 1310,
        "description": "Hosting paid in advance",
    },
    {
        "code": "1320",
        "name": "Prepaid Services",
        "account_type": "asset",
        "category": "Assets",
        "normal_balance": "debit",
        "allows_posting": True,
        "is_system": True,
        "parent_code": "1300",
        "sort_order": 1320,
        "description": "Services paid in advance",
    },
    {
        "code": "1500",
        "name": "Equipment",
        "account_type": "asset",
        "category": "Assets",
        "normal_balance": "debit",
        "allows_posting": False,
        "is_system": True,
        "parent_code": "",
        "sort_order": 1500,
        "description": "Parent equipment account",
    },
    {
        "code": "1510",
        "name": "Office Equipment",
        "account_type": "asset",
        "category": "Assets",
        "normal_balance": "debit",
        "allows_posting": True,
        "is_system": True,
        "parent_code": "1500",
        "sort_order": 1510,
        "description": "Office equipment assets",
    },
    {
        "code": "1520",
        "name": "Computer Equipment",
        "account_type": "asset",
        "category": "Assets",
        "normal_balance": "debit",
        "allows_posting": True,
        "is_system": True,
        "parent_code": "1500",
        "sort_order": 1520,
        "description": "Computer hardware assets",
    },

    # -------------------------
    # Liabilities
    # -------------------------
    {
        "code": "2000",
        "name": "Accounts Payable",
        "account_type": "liability",
        "category": "Liabilities",
        "normal_balance": "credit",
        "allows_posting": False,
        "is_system": True,
        "parent_code": "",
        "sort_order": 2000,
        "description": "Parent payable account",
    },
    {
        "code": "2010",
        "name": "Vendor Payable",
        "account_type": "liability",
        "category": "Liabilities",
        "normal_balance": "credit",
        "allows_posting": True,
        "is_system": True,
        "parent_code": "2000",
        "sort_order": 2010,
        "description": "Amounts owed to vendors",
    },
    {
        "code": "2100",
        "name": "Trade Payable",
        "account_type": "liability",
        "category": "Liabilities",
        "normal_balance": "credit",
        "allows_posting": False,
        "is_system": True,
        "parent_code": "",
        "sort_order": 2100,
        "description": "Amounts owed to vendors and suppliers for unpaid invoices and operating expenses.",
    },
    {
        "code": "2110",
        "name": "Loan from Hossein",
        "account_type": "liability",
        "category": "Liabilities",
        "normal_balance": "credit",
        "allows_posting": True,
        "is_system": True,
        "parent_code": "2100",
        "sort_order": 2110,
        "description": "Amounts owed to Hossein",
    },
    {
        "code": "2180",
        "name": "Founder Interest Payable",
        "account_type": "liability",
        "category": "Liabilities",
        "normal_balance": "credit",
        "allows_posting": True,
        "is_system": True,
        "parent_code": "",
        "sort_order": 2180,
        "description": "Accrued but unpaid interest owed by TownLIT to the founder on approved financing obligations.",
    },
    {
        "code": "2190",
        "name": "Accrued Expenses Payable",
        "account_type": "liability",
        "category": "Liabilities",
        "normal_balance": "credit",
        "allows_posting": True,
        "is_system": True,
        "parent_code": "",
        "sort_order": 2190,
        "description": "Accrued operating expenses recognized before payment, including month-end accruals.",
    },
    {
        "code": "2200",
        "name": "Deferred Revenue and Statutory Payables",
        "account_type": "liability",
        "category": "Liabilities",
        "normal_balance": "credit",
        "allows_posting": False,
        "is_system": True,
        "parent_code": "",
        "sort_order": 2200,
        "description": "Parent deferred revenue account",
    },
    {
        "code": "2210",
        "name": "Subscription Deferred Revenue",
        "account_type": "liability",
        "category": "Liabilities",
        "normal_balance": "credit",
        "allows_posting": True,
        "is_system": True,
        "parent_code": "2200",
        "sort_order": 2210,
        "description": "Subscription cash received before recognition",
    },
    {
        "code": "2300",
        "name": "Deferred Revenue",
        "account_type": "liability",
        "category": "Liabilities",
        "normal_balance": "credit",
        "allows_posting": False,
        "is_system": True,
        "parent_code": "",
        "sort_order": 2300,
        "description": "Cash received before the related service or subscription period is earned.",
    },
    {
        "code": "2310",
        "name": "Sales Tax Payable",
        "account_type": "liability",
        "category": "Liabilities",
        "normal_balance": "credit",
        "allows_posting": True,
        "is_system": True,
        "parent_code": "2300",
        "sort_order": 2310,
        "description": "Sales tax collected and payable",
    },
    {
        "code": "2320",
        "name": "Payroll Tax Payable",
        "account_type": "liability",
        "category": "Liabilities",
        "normal_balance": "credit",
        "allows_posting": True,
        "is_system": True,
        "parent_code": "2300",
        "sort_order": 2320,
        "description": "Payroll taxes payable",
    },

    # -------------------------
    # Equity
    # -------------------------
    {
        "code": "3000",
        "name": "Founder Capital",
        "account_type": "equity",
        "category": "Equity",
        "normal_balance": "credit",
        "allows_posting": True,
        "is_system": True,
        "parent_code": "",
        "sort_order": 3000,
        "description": "Founder capital contributions",
    },
    {
        "code": "3100",
        "name": "Retained Earnings",
        "account_type": "equity",
        "category": "Equity",
        "normal_balance": "credit",
        "allows_posting": True,
        "is_system": True,
        "parent_code": "",
        "sort_order": 3100,
        "description": "Accumulated earnings",
    },
    {
        "code": "3200",
        "name": "Current Year Earnings",
        "account_type": "equity",
        "category": "Equity",
        "normal_balance": "credit",
        "allows_posting": True,
        "is_system": True,
        "parent_code": "",
        "sort_order": 3200,
        "description": "Current year net income",
    },
    {
        "code": "3300",
        "name": "Founder Withdrawals",
        "account_type": "equity",
        "category": "Equity",
        "normal_balance": "debit",
        "allows_posting": True,
        "is_system": True,
        "parent_code": "",
        "sort_order": 3300,
        "description": "Personal amounts withdrawn by founder",
    },
    {
        "code": "3900",
        "name": "Opening Balance Equity",
        "account_type": "equity",
        "category": "Equity",
        "normal_balance": "credit",
        "allows_posting": True,
        "is_system": True,
        "parent_code": "",
        "sort_order": 3900,
        "description": "Used for system setup and opening balances",
    },

    # -------------------------
    # Revenue
    # -------------------------
    {
        "code": "4000",
        "name": "Donations",
        "account_type": "revenue",
        "category": "Revenue",
        "normal_balance": "credit",
        "allows_posting": False,
        "is_system": True,
        "parent_code": "",
        "sort_order": 4000,
        "description": "Parent donation revenue account",
    },
    {
        "code": "4010",
        "name": "Individual Donations",
        "account_type": "revenue",
        "category": "Revenue",
        "normal_balance": "credit",
        "allows_posting": True,
        "is_system": True,
        "parent_code": "4000",
        "sort_order": 4010,
        "description": "Donations from individuals",
    },
    {
        "code": "4020",
        "name": "Church Donations",
        "account_type": "revenue",
        "category": "Revenue",
        "normal_balance": "credit",
        "allows_posting": True,
        "is_system": True,
        "parent_code": "4000",
        "sort_order": 4020,
        "description": "Donations from churches",
    },
    {
        "code": "4030",
        "name": "Major Gifts",
        "account_type": "revenue",
        "category": "Revenue",
        "normal_balance": "credit",
        "allows_posting": True,
        "is_system": True,
        "parent_code": "4000",
        "sort_order": 4030,
        "description": "Large donor gifts",
    },
    {
        "code": "4100",
        "name": "Grants",
        "account_type": "revenue",
        "category": "Revenue",
        "normal_balance": "credit",
        "allows_posting": False,
        "is_system": True,
        "parent_code": "",
        "sort_order": 4100,
        "description": "Parent grant revenue account",
    },
    {
        "code": "4110",
        "name": "Government Grants",
        "account_type": "revenue",
        "category": "Revenue",
        "normal_balance": "credit",
        "allows_posting": True,
        "is_system": True,
        "parent_code": "4100",
        "sort_order": 4110,
        "description": "Government grant revenue",
    },
    {
        "code": "4120",
        "name": "Foundation Grants",
        "account_type": "revenue",
        "category": "Revenue",
        "normal_balance": "credit",
        "allows_posting": True,
        "is_system": True,
        "parent_code": "4100",
        "sort_order": 4120,
        "description": "Foundation grant revenue",
    },
    {
        "code": "4130",
        "name": "Church Grants",
        "account_type": "revenue",
        "category": "Revenue",
        "normal_balance": "credit",
        "allows_posting": True,
        "is_system": True,
        "parent_code": "4100",
        "sort_order": 4130,
        "description": "Church grant revenue",
    },
    {
        "code": "4200",
        "name": "Subscription Revenue",
        "account_type": "revenue",
        "category": "Revenue",
        "normal_balance": "credit",
        "allows_posting": False,
        "is_system": True,
        "parent_code": "",
        "sort_order": 4200,
        "description": "Revenue earned from monthly or recurring TownLIT subscriptions.",
    },
    {
        "code": "4210",
        "name": "Monthly Subscription",
        "account_type": "revenue",
        "category": "Revenue",
        "normal_balance": "credit",
        "allows_posting": True,
        "is_system": True,
        "parent_code": "4200",
        "sort_order": 4210,
        "description": "Monthly recurring subscriptions",
    },
    {
        "code": "4220",
        "name": "Premium Features",
        "account_type": "revenue",
        "category": "Revenue",
        "normal_balance": "credit",
        "allows_posting": True,
        "is_system": True,
        "parent_code": "4200",
        "sort_order": 4220,
        "description": "Premium feature revenue",
    },
    {
        "code": "4300",
        "name": "Advertising Revenue",
        "account_type": "revenue",
        "category": "Revenue",
        "normal_balance": "credit",
        "allows_posting": False,
        "is_system": True,
        "parent_code": "",
        "sort_order": 4300,
        "description": "Revenue earned from approved advertising placements within the TownLIT platform.",
    },
    {
        "code": "4310",
        "name": "Sponsored Posts",
        "account_type": "revenue",
        "category": "Revenue",
        "normal_balance": "credit",
        "allows_posting": True,
        "is_system": True,
        "parent_code": "4300",
        "sort_order": 4310,
        "description": "Revenue from sponsored posts",
    },
    {
        "code": "4320",
        "name": "Display Ads",
        "account_type": "revenue",
        "category": "Revenue",
        "normal_balance": "credit",
        "allows_posting": True,
        "is_system": True,
        "parent_code": "4300",
        "sort_order": 4320,
        "description": "Revenue from display ads",
    },
    {
        "code": "4400",
        "name": "Marketplace Revenue (LITMarket)",
        "account_type": "revenue",
        "category": "Revenue",
        "normal_balance": "credit",
        "allows_posting": False,
        "is_system": True,
        "parent_code": "",
        "sort_order": 4400,
        "description": "Revenue earned from marketplace (LITMarket) activities, commissions, or direct platform sales.",
    },
    {
        "code": "4410",
        "name": "Product Sales",
        "account_type": "revenue",
        "category": "Revenue",
        "normal_balance": "credit",
        "allows_posting": True,
        "is_system": True,
        "parent_code": "4400",
        "sort_order": 4410,
        "description": "Direct product sales",
    },
    {
        "code": "4420",
        "name": "Marketplace Commission",
        "account_type": "revenue",
        "category": "Revenue",
        "normal_balance": "credit",
        "allows_posting": True,
        "is_system": True,
        "parent_code": "4400",
        "sort_order": 4420,
        "description": "Commission earned from marketplace activity",
    },

    # -------------------------
    # Expenses
    # -------------------------
    {
        "code": "5000",
        "name": "Program Expenses",
        "account_type": "expense",
        "category": "Expenses",
        "normal_balance": "debit",
        "allows_posting": False,
        "is_system": True,
        "parent_code": "",
        "sort_order": 5000,
        "description": "Parent program expense account",
    },
    {
        "code": "5010",
        "name": "Content Development",
        "account_type": "expense",
        "category": "Expenses",
        "normal_balance": "debit",
        "allows_posting": True,
        "is_system": True,
        "parent_code": "5000",
        "sort_order": 5010,
        "description": "Content production and development",
    },
    {
        "code": "5020",
        "name": "Translation Services",
        "account_type": "expense",
        "category": "Expenses",
        "normal_balance": "debit",
        "allows_posting": True,
        "is_system": True,
        "parent_code": "5000",
        "sort_order": 5020,
        "description": "Translation expenses",
    },
    {
        "code": "5030",
        "name": "Ministry Programs",
        "account_type": "expense",
        "category": "Expenses",
        "normal_balance": "debit",
        "allows_posting": True,
        "is_system": True,
        "parent_code": "5000",
        "sort_order": 5030,
        "description": "Ministry program expenses",
    },
    {
        "code": "5040",
        "name": "Community Programs",
        "account_type": "expense",
        "category": "Expenses",
        "normal_balance": "debit",
        "allows_posting": True,
        "is_system": True,
        "parent_code": "5000",
        "sort_order": 5040,
        "description": "Community outreach expenses",
    },
    {
        "code": "5100",
        "name": "Infrastructure",
        "account_type": "expense",
        "category": "Expenses",
        "normal_balance": "debit",
        "allows_posting": False,
        "is_system": True,
        "parent_code": "",
        "sort_order": 5100,
        "description": "Parent infrastructure expense account",
    },
    {
        "code": "5110",
        "name": "Hosting",
        "account_type": "expense",
        "category": "Expenses",
        "normal_balance": "debit",
        "allows_posting": True,
        "is_system": True,
        "parent_code": "5100",
        "sort_order": 5110,
        "description": "Hosting expenses",
    },
    {
        "code": "5120",
        "name": "CDN",
        "account_type": "expense",
        "category": "Expenses",
        "normal_balance": "debit",
        "allows_posting": True,
        "is_system": True,
        "parent_code": "5100",
        "sort_order": 5120,
        "description": "CDN expenses",
    },
    {
        "code": "5130",
        "name": "Storage",
        "account_type": "expense",
        "category": "Expenses",
        "normal_balance": "debit",
        "allows_posting": True,
        "is_system": True,
        "parent_code": "5100",
        "sort_order": 5130,
        "description": "Cloud storage expenses",
    },
    {
        "code": "5140",
        "name": "Third Party APIs",
        "account_type": "expense",
        "category": "Expenses",
        "normal_balance": "debit",
        "allows_posting": True,
        "is_system": True,
        "parent_code": "5100",
        "sort_order": 5140,
        "description": "Third-party API expenses",
    },
    {
        "code": "5200",
        "name": "Software Development",
        "account_type": "expense",
        "category": "Expenses",
        "normal_balance": "debit",
        "allows_posting": False,
        "is_system": True,
        "parent_code": "",
        "sort_order": 5200,
        "description": "Parent software development expense account",
    },
    {
        "code": "5210",
        "name": "Developer Payments",
        "account_type": "expense",
        "category": "Expenses",
        "normal_balance": "debit",
        "allows_posting": True,
        "is_system": True,
        "parent_code": "5200",
        "sort_order": 5210,
        "description": "Developer compensation",
    },
    {
        "code": "5220",
        "name": "Contractors",
        "account_type": "expense",
        "category": "Expenses",
        "normal_balance": "debit",
        "allows_posting": True,
        "is_system": True,
        "parent_code": "5200",
        "sort_order": 5220,
        "description": "Contractor expenses",
    },
    {
        "code": "5230",
        "name": "Development Tools",
        "account_type": "expense",
        "category": "Expenses",
        "normal_balance": "debit",
        "allows_posting": True,
        "is_system": True,
        "parent_code": "5200",
        "sort_order": 5230,
        "description": "Development tool subscriptions and licenses",
    },
    {
        "code": "5300",
        "name": "Administrative Expenses",
        "account_type": "expense",
        "category": "Expenses",
        "normal_balance": "debit",
        "allows_posting": False,
        "is_system": True,
        "parent_code": "",
        "sort_order": 5300,
        "description": "Parent administrative expense account",
    },
    {
        "code": "5310",
        "name": "Office Expenses",
        "account_type": "expense",
        "category": "Expenses",
        "normal_balance": "debit",
        "allows_posting": True,
        "is_system": True,
        "parent_code": "5300",
        "sort_order": 5310,
        "description": "General office expenses",
    },
    {
        "code": "5320",
        "name": "Legal",
        "account_type": "expense",
        "category": "Expenses",
        "normal_balance": "debit",
        "allows_posting": True,
        "is_system": True,
        "parent_code": "5300",
        "sort_order": 5320,
        "description": "Legal expenses",
    },
    {
        "code": "5330",
        "name": "Accounting",
        "account_type": "expense",
        "category": "Expenses",
        "normal_balance": "debit",
        "allows_posting": True,
        "is_system": True,
        "parent_code": "5300",
        "sort_order": 5330,
        "description": "Accounting expenses",
    },
    {
        "code": "5340",
        "name": "Insurance",
        "account_type": "expense",
        "category": "Expenses",
        "normal_balance": "debit",
        "allows_posting": True,
        "is_system": True,
        "parent_code": "5300",
        "sort_order": 5340,
        "description": "Insurance expenses",
    },
    {
        "code": "5350",
        "name": "Home Office Expense",
        "account_type": "expense",
        "category": "Expenses",
        "normal_balance": "debit",
        "allows_posting": True,
        "is_system": True,
        "parent_code": "5300",
        "sort_order": 5350,
        "description": "Business share of home office expenses",
    },
    {
        "code": "5370",
        "name": "Bank Charges and Fees",
        "account_type": "expense",
        "category": "Expenses",
        "normal_balance": "debit",
        "allows_posting": True,
        "is_system": True,
        "parent_code": "",
        "sort_order": 5370,
        "description": "Bank service charges, transfer fees, account fees, and related banking costs.",
    },
    {
        "code": "5375",
        "name": "Payment Processor Fees",
        "account_type": "expense",
        "category": "Expenses",
        "normal_balance": "debit",
        "allows_posting": True,
        "is_system": True,
        "parent_code": "",
        "sort_order": 5375,
        "description": "Fees charged by payment processors such as Stripe, PayPal, or marketplace settlement providers.",
    },
    {
    "code": "5380",
    "name": "Founder Financing Interest Expense",
    "account_type": "expense",
    "category": "Expenses",
    "normal_balance": "debit",
    "allows_posting": True,
    "is_system": True,
    "parent_code": "",
    "sort_order": 5380,
    "description": "Interest expense payable by TownLIT on founder financing or line of credit used personally for TownLIT obligations.",
    },
    {
        "code": "5400",
        "name": "Marketing",
        "account_type": "expense",
        "category": "Expenses",
        "normal_balance": "debit",
        "allows_posting": False,
        "is_system": True,
        "parent_code": "",
        "sort_order": 5400,
        "description": "Parent marketing expense account",
    },
    {
        "code": "5410",
        "name": "Advertising",
        "account_type": "expense",
        "category": "Expenses",
        "normal_balance": "debit",
        "allows_posting": True,
        "is_system": True,
        "parent_code": "5400",
        "sort_order": 5410,
        "description": "Advertising costs",
    },
    {
        "code": "5420",
        "name": "Promotion",
        "account_type": "expense",
        "category": "Expenses",
        "normal_balance": "debit",
        "allows_posting": True,
        "is_system": True,
        "parent_code": "5400",
        "sort_order": 5420,
        "description": "Promotional expenses",
    },
    {
        "code": "5430",
        "name": "Events",
        "account_type": "expense",
        "category": "Expenses",
        "normal_balance": "debit",
        "allows_posting": True,
        "is_system": True,
        "parent_code": "5400",
        "sort_order": 5430,
        "description": "Event-related expenses",
    },
    {
        "code": "5500",
        "name": "Fundraising Expenses",
        "account_type": "expense",
        "category": "Expenses",
        "normal_balance": "debit",
        "allows_posting": False,
        "is_system": True,
        "parent_code": "",
        "sort_order": 5500,
        "description": "Parent fundraising expense account",
    },
    {
        "code": "5510",
        "name": "Fundraising Campaigns",
        "account_type": "expense",
        "category": "Expenses",
        "normal_balance": "debit",
        "allows_posting": True,
        "is_system": True,
        "parent_code": "5500",
        "sort_order": 5510,
        "description": "Fundraising campaign costs",
    },
    {
        "code": "5520",
        "name": "Donor Management",
        "account_type": "expense",
        "category": "Expenses",
        "normal_balance": "debit",
        "allows_posting": True,
        "is_system": True,
        "parent_code": "5500",
        "sort_order": 5520,
        "description": "Donor management costs",
    },
]