# Generated by Django 4.2.4 on 2025-06-12 21:35

from django.db import migrations, models
import django.utils.timezone
import utils.common.utils
import validators.mediaValidators.image_validators
import validators.security_validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='registration_started_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Registration Start Date'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image_name',
            field=models.ImageField(blank=True, default='media/sample/user.png', null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file], verbose_name='Image'),
        ),
    ]
