# Generated by Django 4.2.4 on 2025-04-27 14:11

import common.validators
from django.db import migrations, models
import utils.common.utils


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customlabel',
            name='name',
            field=models.CharField(choices=[('believer', 'I follow Jesus (Believer)'), ('seeker', 'I’m exploring faith (Seeker)'), ('prefer_not_to_say', 'I’d prefer not to say')], max_length=20, unique=True, verbose_name='Label Name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image_name',
            field=models.ImageField(blank=True, default='media/sample/user.png', null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[common.validators.validate_image_or_video_file, common.validators.validate_no_executable_file], verbose_name='Image'),
        ),
    ]
