# Generated by Django 4.2.4 on 2025-05-02 22:41

import common.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.common.utils


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_address_id_alter_customuser_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image_name',
            field=models.ImageField(blank=True, default='media/sample/user.png', null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[common.validators.validate_image_or_video_file, common.validators.validate_no_executable_file], verbose_name='Image'),
        ),
        migrations.CreateModel(
            name='InviteCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, help_text='Optional: restrict to specific email', max_length=254, null=True)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_invite_code', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
