# Generated by Django 4.2.4 on 2025-08-08 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.common.utils
import validators.mediaValidators.image_validators
import validators.security_validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customuser_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image_name',
            field=models.ImageField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file], verbose_name='Image'),
        ),
        migrations.CreateModel(
            name='UserDeviceKeyBackup',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('device_id', models.CharField(db_index=True, max_length=100)),
                ('blob', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_key_backups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'device_id')},
            },
        ),
    ]
