# Generated by Django 4.2.4 on 2025-05-03 14:59

import common.validators
from django.db import migrations, models
import utils.common.utils


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customuser_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitecode',
            name='invite_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invitecode',
            name='invite_email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image_name',
            field=models.ImageField(blank=True, default='media/sample/user.png', null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[common.validators.validate_image_or_video_file, common.validators.validate_no_executable_file], verbose_name='Image'),
        ),
    ]
