# Generated by Django 4.2.4 on 2025-05-03 20:18

import common.validators
from django.db import migrations, models
import utils.common.utils


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_invitecode_invite_email_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitecode',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='invitecode',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image_name',
            field=models.ImageField(blank=True, default='media/sample/user.png', null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[common.validators.validate_image_or_video_file, common.validators.validate_no_executable_file], verbose_name='Image'),
        ),
    ]
