# Generated by Django 4.2.4 on 2025-08-11 19:08

from django.db import migrations, models
import utils.common.utils
import validators.mediaValidators.image_validators
import validators.security_validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_customuser_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdevicekey',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdevicekey',
            name='pop_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdevicekey',
            name='pop_challenge_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdevicekey',
            name='pop_challenge_hash',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdevicekey',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image_name',
            field=models.ImageField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file], verbose_name='Image'),
        ),
    ]
