# Generated by Django 4.2.4 on 2025-11-18 23:27

from django.db import migrations, models
import utils.common.utils
import validators.mediaValidators.image_validators
import validators.security_validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_alter_customuser_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdevicekey',
            name='fcm_token',
            field=models.CharField(blank=True, help_text='FCM registration token for this device/browser', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='userdevicekey',
            name='platform',
            field=models.CharField(blank=True, help_text='web / android / ios (for future multi-platform support)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image_name',
            field=models.ImageField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file], verbose_name='Image'),
        ),
    ]
