# Generated by Django 4.2.4 on 2025-12-20 03:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.common.utils
import validators.mediaValidators.image_validators
import validators.security_validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_alter_customuser_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image_name',
            field=models.ImageField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file], verbose_name='Image'),
        ),
        migrations.CreateModel(
            name='IdentityVerification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('veriff', 'Veriff'), ('church', 'Church Endorsement'), ('manual', 'Manual Review'), ('waived', 'Waived (Protected)')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('revoked', 'Revoked')], db_index=True, default='pending', max_length=20)),
                ('level', models.CharField(choices=[('basic', 'Basic'), ('strong', 'Strong'), ('protected', 'Protected')], db_index=True, max_length=20)),
                ('provider_reference', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('provider_payload', models.JSONField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('risk_flag', models.BooleanField(db_index=True, default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='identity_verification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Identity Verification',
                'verbose_name_plural': 'Identity Verifications',
            },
        ),
    ]
