# Generated by Django 4.2.4 on 2025-12-20 04:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.common.utils
import validators.mediaValidators.image_validators
import validators.security_validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_alter_customuser_image_name_identityverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image_name',
            field=models.ImageField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file], verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='identityverification',
            name='method',
            field=models.CharField(choices=[('veriff', 'Veriff'), ('organization', 'Organization Endorsement'), ('manual', 'Manual Review'), ('waived', 'Waived (Protected)')], db_index=True, max_length=20),
        ),
        migrations.CreateModel(
            name='OrganizationEndorsement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('organization_name', models.CharField(max_length=255)),
                ('organization_country', models.CharField(max_length=2)),
                ('organization_website', models.URLField(blank=True, max_length=500, null=True)),
                ('referrer_name', models.CharField(max_length=255)),
                ('referrer_role', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=254)),
                ('endorsement_document', models.FileField(blank=True, null=True, upload_to='identity/endorsements/', validators=[validators.security_validators.validate_no_executable_file], verbose_name='Endorsement Document')),
                ('verified_by_admin', models.BooleanField(default=False)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('identity_verification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organization_endorsement', to='accounts.identityverification')),
            ],
            options={
                'verbose_name': 'Organization Endorsement',
                'verbose_name_plural': 'Organization Endorsements',
            },
        ),
        migrations.CreateModel(
            name='IdentityAuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('create', 'Create'), ('submit', 'Submit'), ('verify', 'Verify'), ('reject', 'Reject'), ('revoke', 'Revoke'), ('update', 'Update')], db_index=True, max_length=20)),
                ('source', models.CharField(choices=[('veriff', 'Veriff'), ('organization', 'Organization'), ('admin', 'Admin'), ('system', 'System')], db_index=True, max_length=20)),
                ('reason', models.CharField(blank=True, max_length=1000, null=True)),
                ('previous_status', models.CharField(blank=True, max_length=20, null=True)),
                ('new_status', models.CharField(blank=True, max_length=20, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_identity_audits', to=settings.AUTH_USER_MODEL)),
                ('identity_verification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='accounts.identityverification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Identity Audit Log',
                'verbose_name_plural': 'Identity Audit Logs',
                'ordering': ('-created_at',),
            },
        ),
    ]
