# Generated by Django 4.2.4 on 2025-12-20 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.common.utils
import validators.mediaValidators.image_validators
import validators.security_validators


class Migration(migrations.Migration):

    dependencies = [
        ('profilesOrg', '0032_alter_organization_license_document_and_more'),
        ('profiles', '0037_alter_academicrecord_document_and_more'),
        ('accounts', '0042_alter_customuser_image_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LITShieldGrant',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('direct', 'Direct TownLIT Decision'), ('org_endorsement', 'Organization Endorsement')], db_index=True, max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'LITShield Grant',
                'verbose_name_plural': 'LITShield Grants',
            },
        ),
        migrations.CreateModel(
            name='OrganizationLITShieldEndorsement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('approved', models.BooleanField(null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='litshield_grants', to='profilesOrg.organization')),
                ('referrer_member', models.ForeignKey(help_text='Member submitting endorsement', on_delete=django.db.models.deletion.PROTECT, to='profiles.member')),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image_name',
            field=models.ImageField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file], verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='identityverification',
            name='method',
            field=models.CharField(choices=[('provider', 'Provider'), ('admin', 'TownLIT Admin (Manual)')], db_index=True, max_length=20),
        ),
        migrations.DeleteModel(
            name='OrganizationEndorsement',
        ),
        migrations.AddField(
            model_name='organizationlitshieldendorsement',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='litshield_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationlitshieldendorsement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='litshield_endorsement_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='litshieldgrant',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='TownLIT admin who approved', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='litshield_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='litshieldgrant',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='litshield_endorsements', to='profilesOrg.organization'),
        ),
        migrations.AddField(
            model_name='litshieldgrant',
            name='requested_by',
            field=models.ForeignKey(blank=True, help_text='Admin or organization owner who initiated this', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='litshield_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='litshieldgrant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='litshield_grant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='organizationlitshieldendorsement',
            unique_together={('user', 'organization')},
        ),
    ]
