# Generated by Django 4.2.4 on 2025-12-21 05:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.common.utils
import validators.mediaValidators.image_validators
import validators.security_validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_litshieldgrant_organizationlitshieldendorsement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityGrant',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('admin', 'TownLIT Admin'), ('system', 'System')], max_length=20)),
                ('level', models.CharField(choices=[('basic', 'Basic'), ('strong', 'Strong'), ('protected', 'Protected')], max_length=20)),
                ('reason', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Identity Grant',
                'verbose_name_plural': 'Identity Grants',
            },
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image_name',
            field=models.ImageField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file], verbose_name='Image'),
        ),
        migrations.AddConstraint(
            model_name='litshieldgrant',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user',), name='unique_active_litshield_per_user'),
        ),
        migrations.AddField(
            model_name='identitygrant',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_identity_grants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='identitygrant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_grants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='identitygrant',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user',), name='unique_active_identity_grant_per_user'),
        ),
    ]
