# Generated by Django 4.2.4 on 2026-03-13 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.common.utils
import validators.mediaValidators.image_validators
import validators.security_validators


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0076_alter_academicrecord_document_and_more'),
        ('accounts', '0083_alter_customuser_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image_name',
            field=models.ImageField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file], verbose_name='Image'),
        ),
        migrations.CreateModel(
            name='TownlitVerificationGrant',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('admin', 'TownLIT Admin'), ('system', 'System')], max_length=20)),
                ('reason', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_townlit_verification_grants', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='townlit_verification_grants', to='profiles.member')),
            ],
            options={
                'verbose_name': 'TownLIT Verification Grant',
                'verbose_name_plural': 'TownLIT Verification Grants',
            },
        ),
        migrations.CreateModel(
            name='TownlitVerificationAuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(db_index=True, max_length=30)),
                ('source', models.CharField(db_index=True, max_length=20)),
                ('reason', models.CharField(blank=True, max_length=1000, null=True)),
                ('previous_status', models.CharField(blank=True, max_length=30, null=True)),
                ('new_status', models.CharField(blank=True, max_length=30, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_townlit_verification_audits', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='townlit_verification_audit_logs', to='profiles.member')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='townlit_verification_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TownLIT Verification Audit Log',
                'verbose_name_plural': 'TownLIT Verification Audit Logs',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='townlitverificationgrant',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('member',), name='unique_active_townlit_verification_grant_per_member'),
        ),
    ]
