# Generated by Django 4.2.4 on 2026-06-01 23:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import utils.common.utils
import validators.mediaValidators.image_validators
import validators.security_validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0090_alter_customlabel_name_alter_customuser_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image_name',
            field=models.ImageField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file], verbose_name='Image'),
        ),
        migrations.CreateModel(
            name='UsernameReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40, unique=True)),
                ('reserved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='username_reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Username Reservation',
                'verbose_name_plural': 'Username Reservations',
                'indexes': [models.Index(fields=['username'], name='accounts_us_usernam_1614fa_idx'), models.Index(fields=['expires_at'], name='accounts_us_expires_8aa658_idx')],
            },
        ),
    ]
