# Generated by Django 4.2.4 on 2026-07-14 06:28

from django.db import migrations, models
import utils.common.utils
import validators.mediaValidators.image_validators
import validators.security_validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0093_alter_customuser_image_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usernamereservation',
            options={'verbose_name': 'Username Alias', 'verbose_name_plural': 'Username Aliases'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image_name',
            field=models.ImageField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file], verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='usernamereservation',
            name='username',
            field=models.CharField(db_index=True, max_length=40, unique=True),
        ),
        migrations.AddIndex(
            model_name='usernamereservation',
            index=models.Index(fields=['user', 'username'], name='accounts_us_user_id_3cd8ce_idx'),
        ),
    ]
