# Generated by Django 4.2.4 on 2026-07-15 18:36

from django.db import migrations, models
import utils.common.utils
import validators.mediaValidators.image_validators
import validators.security_validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0094_alter_usernamereservation_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userdevicekey',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='userdevicekeybackup',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image_name',
            field=models.ImageField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file], verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='userdevicekey',
            name='platform',
            field=models.CharField(blank=True, help_text='web / android / ios', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userdevicekey',
            name='push_token',
            field=models.CharField(blank=True, db_index=True, help_text='Platform-specific push registration token.', max_length=512, null=True),
        ),
        migrations.AddIndex(
            model_name='userdevicekey',
            index=models.Index(fields=['user', 'is_active'], name='acct_dev_user_active_idx'),
        ),
        migrations.AddIndex(
            model_name='userdevicekey',
            index=models.Index(fields=['platform', 'is_active'], name='acct_dev_plat_active_idx'),
        ),
        migrations.AddIndex(
            model_name='userdevicekey',
            index=models.Index(fields=['push_token', 'is_active'], name='acct_dev_push_active_idx'),
        ),
        migrations.AddIndex(
            model_name='userdevicekey',
            index=models.Index(fields=['install_id', 'is_active'], name='acct_dev_inst_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='userdevicekey',
            constraint=models.UniqueConstraint(fields=('user', 'device_id'), name='accounts_unique_user_device_id'),
        ),
        migrations.AddConstraint(
            model_name='userdevicekeybackup',
            constraint=models.UniqueConstraint(fields=('user', 'device_id'), name='accounts_unique_user_device_backup'),
        ),
    ]
