# Generated by Django 4.2.4 on 2026-07-24 07:24

from django.db import migrations, models
import utils.common.utils
import validators.mediaValidators.image_validators
import validators.security_validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0095_alter_userdevicekey_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customlabel',
            name='name',
            field=models.CharField(choices=[('believer', 'I follow Jesus (Believer)'), ('seeker', 'I’m exploring faith (Seeker)'), ('prefer_not_to_say', 'I’d prefer not to say'), ('young_path', 'Protected Children’s Path — Coming Soon')], max_length=20, unique=True, verbose_name='Label Name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image_name',
            field=models.ImageField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file], verbose_name='Image'),
        ),
    ]
