#
#  apps/accounts/migrations/0098_remove_customuser_accounts_user_distinct_profile_languages_and_more.py
#  TownLIT
#
#  Generated by Django 4.2.4 on 2026-07-30.
#  Corrected by Hossein Sakkaki on 2026-07-31.
#

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0097_customuser_language_onboarding_completed_and_more",
        ),
    ]

    operations = []
