# Generated by Django 4.2.4 on 2026-07-30 22:43

from django.db import migrations, models
import utils.common.utils
import validators.mediaValidators.image_validators
import validators.security_validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0098_remove_customuser_accounts_user_distinct_profile_languages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='language_onboarding_completed',
            field=models.BooleanField(default=False, verbose_name='Language Onboarding Completed'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image_name',
            field=models.ImageField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file], verbose_name='Image'),
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.CheckConstraint(check=models.Q(('primary_language__isnull', True), ('secondary_language__isnull', True), models.Q(('primary_language', models.F('secondary_language')), _negated=True), _connector='OR'), name='accounts_user_distinct_profile_languages'),
        ),
    ]
