# Generated by Django 4.2.4 on 2026-08-04 20:56

from django.db import migrations, models
import utils.common.utils
import validators.mediaValidators.image_validators
import validators.security_validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0099_customuser_language_onboarding_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='deletion_canceled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deletion Canceled At'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='deletion_completed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Deletion Completed At'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='deletion_scheduled_for',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Deletion Scheduled For'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='deletion_requested_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Deletion Requested At'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image_name',
            field=models.ImageField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file], verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted'),
        ),
    ]
