# Generated by Django 4.2.4 on 2026-09-14 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0010_stabilize_worship_evidence_upload_path'),
        ('accounts', '0103_alter_customuser_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='litshieldgrant',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='litshield_endorsements', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='organizationlitshieldendorsement',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='litshield_grants', to='organizations.organization'),
        ),
        migrations.AlterUniqueTogether(
            name='organizationlitshieldendorsement',
            unique_together={
                ('user', 'organization'),
            },
        ),
    ]
