services:
  video_worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: video_worker
    entrypoint: /entrypoint_worker.sh
    command: celery -A townlit_b worker -Q video -n video_worker@%h -l info
    env_file:
      - .env.production
    volumes:
      - media_volume:/app/media
    restart: always
    mem_limit: 7g
    cpus: 1.9

    networks:
      - townlit-network

volumes:
  media_volume:

networks:
  townlit-network:
    external: true

