# Generated by Django 4.2.4 on 2025-04-20 16:15

import common.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import utils.common.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('products', '0001_initial'),
        ('profilesOrg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(choices=[('artwork', 'Artwork'), ('books', 'Books'), ('children_baby_products', 'Children and Baby Products'), ('christian_apparel', 'Christian Apparel'), ('christian_media', 'Christian Media'), ('christian_relics', 'Christian Relics and Religious Items'), ('digital_goods', 'Digital Goods'), ('educational_materials', 'Educational Materials'), ('electronics', 'Electronics'), ('food_beverages', 'Food and Beverages'), ('games', 'Games'), ('gifts', 'Gifts'), ('health_wellness', 'Health and Wellness'), ('home_decor', 'Home Décor'), ('jewelry_accessories', 'Jewelry and Accessories'), ('kitchenware', 'Kitchenware'), ('luggage', 'Luggage'), ('mobile_accessories', 'Mobile Accessories'), ('music_audio', 'Music and Audio'), ('office_supplies', 'Office Supplies'), ('outdoor_gear', 'Outdoor Gear'), ('personal_care', 'Personal Care'), ('pet_supplies', 'Pet Supplies'), ('religious_books', 'Religious Books'), ('sports_equipment', 'Sports Equipment'), ('stationery', 'Stationery'), ('toys', 'Toys'), ('video', 'Video'), ('watches', 'Watches'), ('other', 'Other')], max_length=50, unique=True, verbose_name='Service Category')),
                ('description', models.CharField(blank=True, max_length=300, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug')),
                ('custom_service_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Custom Service Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Store Description')),
                ('store_logo', models.ImageField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[common.validators.validate_image_or_video_file, common.validators.validate_no_executable_file], verbose_name='Store Logo')),
                ('store_phone_number', models.CharField(blank=True, max_length=20, null=True, validators=[common.validators.validate_phone_number], verbose_name='Store Contact Number')),
                ('currency_preference', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('CAD', 'Canadian Dollar'), ('GBP', 'British Pound'), ('AUD', 'Australian Dollar'), ('JPY', 'Japanese Yen'), ('CNY', 'Chinese Yuan'), ('INR', 'Indian Rupee'), ('CHF', 'Swiss Franc'), ('BRL', 'Brazilian Real'), ('MXN', 'Mexican Peso'), ('RUB', 'Russian Ruble')], default='USD', max_length=3, verbose_name='Currency Preference')),
                ('license_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='License Number')),
                ('license_expiry_date', models.DateField(blank=True, null=True, verbose_name='License Expiry Date')),
                ('tax_id', models.CharField(blank=True, max_length=40, null=True, verbose_name='Tax Id')),
                ('store_license', models.FileField(upload_to=utils.common.utils.FileUpload.dir_upload, validators=[common.validators.validate_pdf_file, common.validators.validate_no_executable_file], verbose_name='Store License')),
                ('sales_report', models.TextField(blank=True, null=True, verbose_name='Sales Report')),
                ('revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Revenue')),
                ('register_date', models.DateField(default=django.utils.timezone.now, verbose_name='Register Date')),
                ('active_date', models.DateField(blank=True, null=True, verbose_name='Active Date')),
                ('is_restricted', models.BooleanField(default=False, verbose_name='Restricted to Members')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Is Verified')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='Is Hidden')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store_details', to='profilesOrg.organization', verbose_name='Store Detail')),
                ('products', models.ManyToManyField(blank=True, related_name='stores', to='products.product', verbose_name='Products')),
                ('service_categories', models.ManyToManyField(blank=True, related_name='stores', to='store.servicecategory', verbose_name='Service Categories')),
                ('store_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_address', to='accounts.address', verbose_name='Store Address')),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Stores',
            },
        ),
    ]
