# Generated by Django 4.2.4 on 2025-11-07 22:25

from django.db import migrations, models
import utils.common.utils
import validators.mediaValidators.image_validators
import validators.mediaValidators.pdf_validators
import validators.security_validators


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_alter_store_store_license_alter_store_store_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_license',
            field=models.FileField(upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.pdf_validators.validate_pdf_file, validators.security_validators.validate_no_executable_file], verbose_name='Store License'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_logo',
            field=models.ImageField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file], verbose_name='Store Logo'),
        ),
    ]
