# Generated by Django 4.2.4 on 2026-09-14 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0010_stabilize_worship_evidence_upload_path'),
        ('store', '0080_stabilize_store_upload_paths'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store_details', to='organizations.organization', verbose_name='Store Detail'),
        ),
    ]
