# Generated by Django 4.2.4 on 2026-05-25 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBoundary',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('boundary_type', models.CharField(choices=[('stillness', 'Stillness'), ('boundary', 'Boundary')], db_index=True, default='stillness', max_length=24)),
                ('source', models.CharField(choices=[('profile', 'Profile'), ('messenger', 'Messenger'), ('comment', 'Comment'), ('reaction', 'Reaction'), ('settings', 'Settings'), ('sanctuary', 'Sanctuary'), ('system', 'System')], db_index=True, default='profile', max_length=32)),
                ('reason', models.CharField(blank=True, default='', help_text='Short optional reason selected by the user.', max_length=120)),
                ('note', models.TextField(blank=True, default='', help_text='Private optional note visible only to the owner/admin tools.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boundaries_created', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boundaries_received', to=settings.AUTH_USER_MODEL, verbose_name='Target')),
            ],
            options={
                'verbose_name': 'User Boundary',
                'verbose_name_plural': 'User Boundaries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', 'target', 'boundary_type', 'is_active'], name='boundaries__owner_i_44cd36_idx'), models.Index(fields=['target', 'owner', 'boundary_type', 'is_active'], name='boundaries__target__817c79_idx'), models.Index(fields=['owner', 'is_active', 'boundary_type'], name='boundaries__owner_i_e97f77_idx'), models.Index(fields=['target', 'is_active', 'boundary_type'], name='boundaries__target__b88f1f_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='userboundary',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('owner', 'target', 'boundary_type'), name='unique_active_boundary_per_type'),
        ),
        migrations.AddConstraint(
            model_name='userboundary',
            constraint=models.CheckConstraint(check=models.Q(('owner', models.F('target')), _negated=True), name='prevent_self_boundary'),
        ),
    ]
