BIBLE_WORDS = [
    "GRACE", "FAITH", "LORD", "LOVE", "PEACE", "HOPE", "LIGHT", "TRUTH", "JOY", "SHEPHERD",
    "MERCY", "HEAVEN", "REDEEM", "GLORY", "BLESS", "PRAYER", "CROSS", "SAVIOR", "SPIRIT",
    "KING", "GOSPEL", "TRUST", "HOLY", "BIBLE", "WORSHIP", "JESUS", "UNITY", "TRINITY", "DISCIPLE", "VICTORY", "ETERNAL"
]
