# apps/help_support/constants.py

SUPPORT_CATEGORY_TECHNICAL = "technical"
SUPPORT_CATEGORY_ACCOUNT = "account_access"
SUPPORT_CATEGORY_FEEDBACK = "feedback"
# SUPPORT_CATEGORY_STORE_ORDER = "store_order"
SUPPORT_CATEGORY_PAYMENT = "payment"
# SUPPORT_CATEGORY_ORGANIZATION = "organization"
SUPPORT_CATEGORY_OTHER = "other"

SUPPORT_CATEGORY_CHOICES = [
    (SUPPORT_CATEGORY_TECHNICAL, "Technical Issue"),
    (SUPPORT_CATEGORY_ACCOUNT, "Account or Access"),
    (SUPPORT_CATEGORY_FEEDBACK, "Feedback or Suggestion"),
    # (SUPPORT_CATEGORY_STORE_ORDER, "Store or Order"),
    (SUPPORT_CATEGORY_PAYMENT, "Payment"),
    # (SUPPORT_CATEGORY_ORGANIZATION, "Organization"),
    (SUPPORT_CATEGORY_OTHER, "Other"),
]


SUPPORT_AREA_GENERAL = "general"
SUPPORT_AREA_ACCOUNTS = "accounts"
SUPPORT_AREA_PROFILES = "profiles"
SUPPORT_AREA_CONTENT = "content"
SUPPORT_AREA_MESSENGER = "messenger"
SUPPORT_AREA_JOURNEY = "journey"
# SUPPORT_AREA_STORE = "store"
# SUPPORT_AREA_ORDERS = "orders"
SUPPORT_AREA_PAYMENT = "payment"
# SUPPORT_AREA_ORGANIZATIONS = "organizations"
SUPPORT_AREA_OTHER = "other"

SUPPORT_AREA_CHOICES = [
    (SUPPORT_AREA_GENERAL, "General"),
    (SUPPORT_AREA_ACCOUNTS, "Account"),
    (SUPPORT_AREA_PROFILES, "Profile"),
    (SUPPORT_AREA_CONTENT, "Content"),
    (SUPPORT_AREA_MESSENGER, "Messenger"),
    (SUPPORT_AREA_JOURNEY, "Journey"),
    # (SUPPORT_AREA_STORE, "Store"),
    # (SUPPORT_AREA_ORDERS, "Orders"),
    (SUPPORT_AREA_PAYMENT, "Payment"),
    # (SUPPORT_AREA_ORGANIZATIONS, "Organizations"),
    (SUPPORT_AREA_OTHER, "Other"),
]


SUPPORT_SOURCE_SETTINGS = "settings"
SUPPORT_SOURCE_PROFILE = "profile"
SUPPORT_SOURCE_CONTENT = "content"
SUPPORT_SOURCE_MESSENGER = "messenger"
SUPPORT_SOURCE_JOURNEY = "journey"
SUPPORT_SOURCE_STORE = "store"
SUPPORT_SOURCE_ORDER = "order"
SUPPORT_SOURCE_PAYMENT = "payment"
SUPPORT_SOURCE_ORGANIZATION = "organization"
SUPPORT_SOURCE_SYSTEM = "system"

SUPPORT_SOURCE_CHOICES = [
    (SUPPORT_SOURCE_SETTINGS, "Settings"),
    (SUPPORT_SOURCE_PROFILE, "Profile"),
    (SUPPORT_SOURCE_CONTENT, "Content"),
    (SUPPORT_SOURCE_MESSENGER, "Messenger"),
    (SUPPORT_SOURCE_JOURNEY, "Journey"),
    (SUPPORT_SOURCE_STORE, "Store"),
    (SUPPORT_SOURCE_ORDER, "Order"),
    (SUPPORT_SOURCE_PAYMENT, "Payment"),
    (SUPPORT_SOURCE_ORGANIZATION, "Organization"),
    (SUPPORT_SOURCE_SYSTEM, "System"),
]


SUPPORT_STATUS_OPEN = "open"
SUPPORT_STATUS_IN_REVIEW = "in_review"
SUPPORT_STATUS_WAITING_USER = "waiting_user"
SUPPORT_STATUS_RESOLVED = "resolved"
SUPPORT_STATUS_CLOSED = "closed"

SUPPORT_STATUS_CHOICES = [
    (SUPPORT_STATUS_OPEN, "Open"),
    (SUPPORT_STATUS_IN_REVIEW, "In Review"),
    (SUPPORT_STATUS_WAITING_USER, "Waiting for User"),
    (SUPPORT_STATUS_RESOLVED, "Resolved"),
    (SUPPORT_STATUS_CLOSED, "Closed"),
]


SUPPORT_PRIORITY_NORMAL = "normal"
SUPPORT_PRIORITY_HIGH = "high"
SUPPORT_PRIORITY_URGENT = "urgent"

SUPPORT_PRIORITY_CHOICES = [
    (SUPPORT_PRIORITY_NORMAL, "Normal"),
    (SUPPORT_PRIORITY_HIGH, "High"),
    (SUPPORT_PRIORITY_URGENT, "Urgent"),
]


SUPPORT_SENDER_USER = "user"
SUPPORT_SENDER_STAFF = "staff"
SUPPORT_SENDER_AI = "ai"
SUPPORT_SENDER_SYSTEM = "system"

SUPPORT_SENDER_CHOICES = [
    (SUPPORT_SENDER_USER, "User"),
    (SUPPORT_SENDER_STAFF, "TownLIT Support"),
    (SUPPORT_SENDER_AI, "AI Assistant"),
    (SUPPORT_SENDER_SYSTEM, "System"),
]


SUPPORT_AI_NOT_USED = "not_used"
SUPPORT_AI_ELIGIBLE = "eligible"
SUPPORT_AI_PROCESSING = "processing"
SUPPORT_AI_DRAFTED = "drafted"
SUPPORT_AI_ASSISTED = "assisted"

SUPPORT_AI_STATUS_CHOICES = [
    (SUPPORT_AI_NOT_USED, "Not Used"),
    (SUPPORT_AI_ELIGIBLE, "Eligible"),
    (SUPPORT_AI_PROCESSING, "Processing"),
    (SUPPORT_AI_DRAFTED, "Drafted"),
    (SUPPORT_AI_ASSISTED, "AI Assisted"),
]