# apps/creative_editor/constants.py

from __future__ import annotations


CREATIVE_RENDER_QUEUE = "creative_render"

CREATIVE_RENDER_MAX_RETRIES = 2
CREATIVE_RENDER_RETRY_COUNTDOWN_SECONDS = 10

CREATIVE_RENDER_OUTPUT_QUALITY = 92
CREATIVE_RENDER_THUMBNAIL_QUALITY = 86

CREATIVE_RENDER_THUMBNAIL_MAX_WIDTH = 540
CREATIVE_RENDER_THUMBNAIL_MAX_HEIGHT = 960

CREATIVE_RENDER_MAX_CANVAS_PIXELS = (
    8192 * 8192
)

CREATIVE_RENDER_DEFAULT_BACKGROUND = (
    "#00000000"
)

CREATIVE_RENDER_DEFAULT_FONT_KEY = (
    "townlit-sans-regular"
)

CREATIVE_RENDER_DEFAULT_FONT_SIZE = 48

CREATIVE_RENDER_ALLOWED_IMAGE_MODES = {
    "RGB",
    "RGBA",
    "L",
    "LA",
    "P",
}