# Generated by Django 4.2.4 on 2025-05-15 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField()),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_logs', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('cover_letter', models.TextField(blank=True)),
                ('position', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('interview', 'Interview Scheduled'), ('hired', 'Hired'), ('rejected', 'Rejected')], default='new', max_length=20)),
                ('admin_comment', models.TextField(blank=True)),
                ('admin_note', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('last_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_application_last_reviewed', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CollaborationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('collaboration_type', models.CharField(choices=[('content', 'Content Creation'), ('translation', 'Translation'), ('video', 'Video Editing / Production'), ('design', 'Design & UI'), ('development', 'Development / Programming'), ('outreach', 'Community Outreach'), ('prayer', 'Prayer Ministry'), ('admin', 'Administrative Help'), ('other', 'Other')], max_length=50)),
                ('collaboration_mode', models.CharField(choices=[('online', 'Online'), ('onsite', 'On-site'), ('hybrid', 'Hybrid')], default='online', max_length=20)),
                ('availability', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField(blank=True)),
                ('allow_contact', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('contacted', 'Contacted'), ('closed', 'Closed')], default='new', max_length=20)),
                ('admin_comment', models.TextField(blank=True)),
                ('admin_note', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('last_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collaboration_last_reviewed', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
