# Generated by Django 4.2.4 on 2025-05-26 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Country')),
                ('how_found_us', models.CharField(blank=True, choices=[('friend', 'Friend or Family'), ('church', 'Church or Fellowship'), ('social', 'Social Media (Facebook, Instagram, etc.)'), ('search', 'Search Engine (Google, Bing, etc.)'), ('youtube', 'YouTube'), ('podcast', 'Podcast or Radio Program'), ('event', 'Event or Conference'), ('newsletter', 'Email Newsletter'), ('blog', 'Blog or Article'), ('whatsapp', 'WhatsApp Group / Contact'), ('telegram', 'Telegram Channel / Group'), ('influencer', 'Influencer or Public Figure'), ('other', 'Other')], max_length=30, verbose_name='How did you hear about us?')),
                ('message', models.TextField(blank=True, verbose_name='Message (optional)')),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('invited', 'Invite Sent'), ('rejected', 'Rejected')], default='new', max_length=20, verbose_name='Request Status')),
                ('invite_code_sent', models.BooleanField(default=False, verbose_name='Invite Code Sent?')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Submitted At')),
            ],
            options={
                'verbose_name': 'Access Request',
                'verbose_name_plural': 'Access Requests',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('object_id', models.PositiveIntegerField()),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_logs', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('cover_letter', models.TextField(blank=True)),
                ('position', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('interview', 'Interview Scheduled'), ('hired', 'Hired'), ('rejected', 'Rejected')], default='new', max_length=20)),
                ('admin_comment', models.TextField(blank=True)),
                ('admin_note', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_application_last_reviewed', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CollaborationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('collaboration_type', models.CharField(choices=[('content', 'Content Creation'), ('writing', 'Writing / Editing / Blogging'), ('translation', 'Translation'), ('video', 'Video Editing / Production'), ('design', 'Design & UI'), ('development', 'Development / Programming'), ('outreach', 'Community Outreach'), ('prayer', 'Prayer Ministry'), ('mentoring', 'Mentoring / Discipleship Support'), ('teaching', 'Teaching / Bible Study Facilitation'), ('admin', 'Administrative Help'), ('financial', 'Financial Contribution / Support'), ('other', 'Other')], max_length=50)),
                ('collaboration_mode', models.CharField(choices=[('online', 'Online'), ('onsite', 'On-site'), ('hybrid', 'Hybrid')], default='online', max_length=20)),
                ('availability', models.CharField(blank=True, choices=[('5', '5 hours/week'), ('8', '8 hours/week'), ('10', '10 hours/week'), ('15', '15 hours/week'), ('20', '20 hours/week'), ('30', '30 hours/week'), ('40', '40 hours/week')], default='5', max_length=10, null=True)),
                ('message', models.TextField(blank=True)),
                ('allow_contact', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('contacted', 'Contacted'), ('closed', 'Closed')], default='new', max_length=20)),
                ('admin_comment', models.TextField(blank=True, null=True)),
                ('admin_note', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collaboration_last_reviewed', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
