# Generated by Django 4.2.4 on 2025-08-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborationrequest',
            name='collaboration_type',
            field=models.CharField(choices=[('content', 'Content Creation'), ('writing', 'Writing / Editing / Blogging'), ('translation', 'Translation'), ('video', 'Video Editing / Production'), ('design', 'Design & UI'), ('development', 'Development / Programming'), ('outreach', 'Community Outreach'), ('prayer', 'Prayer Ministry'), ('mentoring', 'Mentoring / Discipleship Support'), ('teaching', 'Teaching / Bible Study Facilitation'), ('admin', 'Administrative Help'), ('financial', 'Financial Contribution / Support'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='collaborationrequest',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
