# Generated by Django 4.2.4 on 2025-05-16 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborationrequest',
            name='admin_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collaborationrequest',
            name='admin_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collaborationrequest',
            name='availability',
            field=models.CharField(blank=True, choices=[('5', '5 hours/week'), ('8', '8 hours/week'), ('10', '10 hours/week'), ('15', '15 hours/week'), ('20', '20 hours/week'), ('30', '30 hours/week'), ('40', '40 hours/week')], default='5', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='collaborationrequest',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='collaborationrequest',
            name='collaboration_type',
            field=models.CharField(choices=[('content', 'Content Creation'), ('writing', 'Writing / Editing / Blogging'), ('translation', 'Translation'), ('video', 'Video Editing / Production'), ('design', 'Design & UI'), ('development', 'Development / Programming'), ('outreach', 'Community Outreach'), ('prayer', 'Prayer Ministry'), ('mentoring', 'Mentoring / Discipleship Support'), ('teaching', 'Teaching / Bible Study Facilitation'), ('admin', 'Administrative Help'), ('financial', 'Financial Contribution / Support'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='collaborationrequest',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='collaborationrequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='collaborationrequest',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='collaborationrequest',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
