# Generated by Django 4.2.4 on 2025-05-16 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0002_alter_collaborationrequest_admin_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewlog',
            name='action',
            field=models.CharField(max_length=255),
        ),
    ]
