# Generated by Django 4.2.4 on 2025-05-22 03:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0003_alter_reviewlog_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Country')),
                ('how_found_us', models.CharField(blank=True, choices=[('friend', 'Friend or Family'), ('church', 'Church or Fellowship'), ('social', 'Social Media'), ('search', 'Search Engine'), ('other', 'Other')], max_length=30, verbose_name='How did you hear about us?')),
                ('message', models.TextField(blank=True, verbose_name='Message (optional)')),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('invited', 'Invite Sent'), ('rejected', 'Rejected')], default='new', max_length=20, verbose_name='Request Status')),
                ('invite_code_sent', models.BooleanField(default=False, verbose_name='Invite Code Sent?')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Submitted At')),
            ],
            options={
                'verbose_name': 'Access Request',
                'verbose_name_plural': 'Access Requests',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AlterField(
            model_name='collaborationrequest',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reviewlog',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
