# Generated by Django 4.2.4 on 2025-05-22 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0004_accessrequest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessrequest',
            name='how_found_us',
            field=models.CharField(blank=True, choices=[('friend', 'Friend or Family'), ('church', 'Church or Fellowship'), ('social', 'Social Media (Facebook, Instagram, etc.)'), ('search', 'Search Engine (Google, Bing, etc.)'), ('youtube', 'YouTube'), ('podcast', 'Podcast or Radio Program'), ('event', 'Event or Conference'), ('newsletter', 'Email Newsletter'), ('blog', 'Blog or Article'), ('whatsapp', 'WhatsApp Group / Contact'), ('telegram', 'Telegram Channel / Group'), ('influencer', 'Influencer or Public Figure'), ('other', 'Other')], max_length=30, verbose_name='How did you hear about us?'),
        ),
    ]
