# Generated by Django 4.2.4 on 2026-03-07 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(db_index=True, help_text='Unique account code', max_length=20, unique=True)),
                ('account_type', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('revenue', 'Revenue'), ('expense', 'Expense')], db_index=True, max_length=20)),
                ('normal_balance', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], help_text='Normal balance side for reporting logic', max_length=10)),
                ('allows_posting', models.BooleanField(default=True, help_text='Whether journal lines can be posted directly to this account')),
                ('is_system', models.BooleanField(default=False, help_text='System account protected from accidental changes')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='AccountCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code_prefix', models.CharField(help_text='Prefix used for account numbering', max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Account Category',
                'verbose_name_plural': 'Account Categories',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='AccountingApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('posted', 'Posted')], db_index=True, default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='AccountingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('invoice', 'Invoice'), ('receipt', 'Receipt'), ('contract', 'Contract'), ('grant_letter', 'Grant Letter'), ('payment_proof', 'Payment Proof'), ('bank_support', 'Bank Support'), ('other', 'Other')], db_index=True, default='other', max_length=30)),
                ('file', models.FileField(upload_to='accounting/documents/%Y/%m/')),
                ('description', models.TextField(blank=True)),
                ('reference', models.CharField(blank=True, db_index=True, default='', help_text='Invoice number, receipt number, or external reference', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Unique bank account code', max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('account_type', models.CharField(choices=[('operating', 'Operating'), ('savings', 'Savings'), ('grant', 'Grant'), ('reserve', 'Reserve'), ('payment_settlement', 'Payment Settlement'), ('other', 'Other')], db_index=True, default='operating', max_length=30)),
                ('institution_name_snapshot', models.CharField(blank=True, default='', help_text='Snapshot of institution name for exports/history', max_length=255)),
                ('account_holder_name', models.CharField(blank=True, default='', max_length=255)),
                ('account_number_masked', models.CharField(blank=True, help_text='Masked account number only', max_length=50)),
                ('transit_number', models.CharField(blank=True, default='', max_length=20)),
                ('routing_number', models.CharField(blank=True, default='', max_length=50)),
                ('iban', models.CharField(blank=True, default='', max_length=100)),
                ('currency', models.CharField(default='CAD', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('closed', 'Closed')], db_index=True, default='active', max_length=20)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('opened_on', models.DateField(blank=True, null=True)),
                ('closed_on', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='BankInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Unique institution code', max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('institution_type', models.CharField(choices=[('bank', 'Bank'), ('credit_union', 'Credit Union'), ('payment_processor', 'Payment Processor'), ('fintech', 'Fintech'), ('other', 'Other')], db_index=True, default='bank', max_length=30)),
                ('country', models.CharField(default='CA', help_text='ISO country code', max_length=2)),
                ('swift_code', models.CharField(blank=True, default='', max_length=50)),
                ('website', models.URLField(blank=True)),
                ('support_phone', models.CharField(blank=True, default='', max_length=50)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('note', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bank Institution',
                'verbose_name_plural': 'Bank Institutions',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='BankReconciliationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(db_index=True)),
                ('period_end', models.DateField(db_index=True)),
                ('statement_ending_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('ledger_ending_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('unreconciled_difference', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('open', 'Open'), ('completed', 'Completed'), ('locked', 'Locked')], db_index=True, default='open', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-period_end', '-id'),
            },
        ),
        migrations.CreateModel(
            name='BankStatementImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_file', models.FileField(blank=True, null=True, upload_to='accounting/bank_imports/%Y/%m/')),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('statement_date', models.DateField(blank=True, null=True)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('opening_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('closing_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(default='CAD', max_length=10)),
                ('status', models.CharField(choices=[('imported', 'Imported'), ('processed', 'Processed'), ('archived', 'Archived')], db_index=True, default='imported', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='BankStatementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(db_index=True)),
                ('posted_date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(max_length=500)),
                ('reference', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Signed amount. Positive inflow, negative outflow.', max_digits=14)),
                ('balance_after', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('external_id', models.CharField(blank=True, db_index=True, default='', help_text='Bank-provided transaction id if available', max_length=255)),
                ('match_status', models.CharField(choices=[('unmatched', 'Unmatched'), ('suggested', 'Suggested'), ('matched', 'Matched'), ('ignored', 'Ignored')], db_index=True, default='unmatched', max_length=20)),
                ('matched_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('transaction_date', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Unique budget code', max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed')], db_index=True, default='draft', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('currency', models.CharField(default='CAD', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='BudgetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Unique code inside the budget scope', max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('approved_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('sort_order', 'code'),
            },
        ),
        migrations.CreateModel(
            name='FounderLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lender_display_name', models.CharField(max_length=255)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='CAD', max_length=10)),
                ('loan_date', models.DateField(db_index=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('partial', 'Partially Repaid'), ('repaid', 'Repaid'), ('cancelled', 'Cancelled')], db_index=True, default='open', max_length=20)),
                ('repaid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('internal_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-loan_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Unique fund code', max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('fund_type', models.CharField(choices=[('general', 'General'), ('restricted', 'Restricted'), ('grant', 'Grant'), ('support', 'Support')], db_index=True, default='general', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('on_hold', 'On Hold')], db_index=True, default='active', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_restricted', models.BooleanField(default=False)),
                ('source_app', models.CharField(blank=True, default='', max_length=100)),
                ('source_model', models.CharField(blank=True, default='', max_length=100)),
                ('source_ref', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('total_awarded', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(default='CAD', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_number', models.CharField(db_index=True, help_text='Human-friendly unique entry number', max_length=50, unique=True)),
                ('entry_date', models.DateField(db_index=True)),
                ('description', models.TextField()),
                ('reference', models.CharField(blank=True, db_index=True, default='', help_text='External business reference such as invoice id', max_length=255)),
                ('source_app', models.CharField(blank=True, default='', max_length=100)),
                ('source_model', models.CharField(blank=True, default='', max_length=100)),
                ('source_ref', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('void', 'Void')], db_index=True, default='draft', max_length=20)),
                ('currency', models.CharField(db_index=True, default='CAD', max_length=10)),
                ('internal_note', models.TextField(blank=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_journal_entries', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_journal_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-entry_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField(default=1, help_text='Line order inside the journal entry')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('memo', models.TextField(blank=True)),
                ('fund_code', models.CharField(blank=True, default='', max_length=50)),
                ('budget_code', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='accounting.account')),
                ('budget_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='accounting.budgetline')),
                ('fund', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='accounting.fund')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounting.journalentry')),
            ],
            options={
                'ordering': ('line_number', 'id'),
            },
        ),
        migrations.CreateModel(
            name='RecurringJournalTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('template_type', models.CharField(choices=[('standard', 'Standard'), ('home_office', 'Home Office'), ('founder_loan', 'Founder Loan')], db_index=True, default='standard', max_length=30)),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], db_index=True, default='monthly', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('closed', 'Closed')], db_index=True, default='active', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Template configuration for recurring posting')),
                ('next_run_date', models.DateField(blank=True, db_index=True, null=True)),
                ('last_run_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_recurring_journal_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='FundPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('open', 'Open'), ('restricted', 'Restricted')], db_index=True, default='open', help_text='Open allows all posting accounts. Restricted requires explicit allow rules.', max_length=20)),
                ('enforce_rules', models.BooleanField(default=True, help_text='If disabled, reporting still works but hard validation is skipped.')),
                ('enforce_date_window', models.BooleanField(default=True, help_text='Require journal entry date to be inside fund start/end date.')),
                ('prevent_budget_overrun', models.BooleanField(default=True, help_text='Prevent spending beyond approved budget line amount.')),
                ('require_budget_line_for_expenses', models.BooleanField(default=False, help_text='If true, expense lines tagged to this fund must also include a budget line.')),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fund', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='policy', to='accounting.fund')),
            ],
            options={
                'ordering': ('fund__code',),
            },
        ),
        migrations.CreateModel(
            name='FundAllowedBudgetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('budget_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_permissions', to='accounting.budgetline')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_budget_lines', to='accounting.fund')),
            ],
            options={
                'ordering': ('fund__code', 'budget_line__budget__code', 'budget_line__code'),
            },
        ),
        migrations.CreateModel(
            name='FundAllowedAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_revenue', models.BooleanField(default=True)),
                ('allow_expense', models.BooleanField(default=True)),
                ('allow_asset', models.BooleanField(default=False)),
                ('allow_liability', models.BooleanField(default=False)),
                ('allow_equity', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_permissions', to='accounting.account')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_accounts', to='accounting.fund')),
            ],
            options={
                'ordering': ('fund__code', 'account__code'),
            },
        ),
        migrations.AddIndex(
            model_name='fund',
            index=models.Index(fields=['fund_type', 'status'], name='accounting__fund_ty_927a5a_idx'),
        ),
        migrations.AddIndex(
            model_name='fund',
            index=models.Index(fields=['source_app', 'source_model', 'source_ref'], name='accounting__source__009a18_idx'),
        ),
        migrations.AddField(
            model_name='founderloan',
            name='journal_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='founder_loan_record', to='accounting.journalentry'),
        ),
        migrations.AddField(
            model_name='founderloan',
            name='lender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='founder_loans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budgetline',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.budget'),
        ),
        migrations.AddField(
            model_name='budget',
            name='fund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='accounting.fund'),
        ),
        migrations.AddField(
            model_name='bankstatementline',
            name='bank_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statement_lines', to='accounting.bankaccount'),
        ),
        migrations.AddField(
            model_name='bankstatementline',
            name='matched_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_bank_statement_lines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bankstatementline',
            name='matched_journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_bank_lines', to='accounting.journalentry'),
        ),
        migrations.AddField(
            model_name='bankstatementline',
            name='statement_import',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.bankstatementimport'),
        ),
        migrations.AddField(
            model_name='bankstatementimport',
            name='bank_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statement_imports', to='accounting.bankaccount'),
        ),
        migrations.AddField(
            model_name='bankstatementimport',
            name='imported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_bank_statements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bankreconciliationsession',
            name='bank_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_sessions', to='accounting.bankaccount'),
        ),
        migrations.AddField(
            model_name='bankreconciliationsession',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_reconciliation_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_accounts', to='accounting.bankinstitution'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='ledger_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_accounts', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='accountingdocument',
            name='founder_loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='accounting.founderloan'),
        ),
        migrations.AddField(
            model_name='accountingdocument',
            name='fund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='accounting.fund'),
        ),
        migrations.AddField(
            model_name='accountingdocument',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='accounting.journalentry'),
        ),
        migrations.AddField(
            model_name='accountingdocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_accounting_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accountingapproval',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_accounting_workflows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accountingapproval',
            name='journal_entry',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval_flow', to='accounting.journalentry'),
        ),
        migrations.AddField(
            model_name='accountingapproval',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_accounting_workflows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accountingapproval',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_accounting_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='account',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='accounting.accountcategory'),
        ),
        migrations.AddField(
            model_name='account',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='accounting.account'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['account', 'journal_entry'], name='accounting__account_464492_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['fund'], name='accounting__fund_id_c9e78f_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['budget_line'], name='accounting__budget__fc934d_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['fund_code'], name='accounting__fund_co_3ce126_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['budget_code'], name='accounting__budget__446658_idx'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(fields=('journal_entry', 'line_number'), name='uniq_journal_entry_line_number'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('debit__gt', 0), ('credit', 0)), models.Q(('credit__gt', 0), ('debit', 0)), _connector='OR'), name='transaction_exactly_one_side_positive'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(check=models.Q(('debit__gte', 0), ('credit__gte', 0)), name='transaction_non_negative_amounts'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['entry_date', 'status'], name='accounting__entry_d_68b453_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['source_app', 'source_model', 'source_ref'], name='accounting__source__e5a99f_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['reference', 'status'], name='accounting__referen_373ac8_idx'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.UniqueConstraint(condition=models.Q(('source_app__gt', ''), ('source_model__gt', ''), ('source_ref__gt', ''), ('status', 'posted')), fields=('source_app', 'source_model', 'source_ref', 'status'), name='uniq_posted_source_reference'),
        ),
        migrations.AddConstraint(
            model_name='fundallowedbudgetline',
            constraint=models.UniqueConstraint(fields=('fund', 'budget_line'), name='uniq_fund_allowed_budget_line'),
        ),
        migrations.AddConstraint(
            model_name='fundallowedaccount',
            constraint=models.UniqueConstraint(fields=('fund', 'account'), name='uniq_fund_allowed_account'),
        ),
        migrations.AddIndex(
            model_name='founderloan',
            index=models.Index(fields=['status', 'loan_date'], name='accounting__status_4d3e30_idx'),
        ),
        migrations.AddConstraint(
            model_name='budgetline',
            constraint=models.UniqueConstraint(fields=('budget', 'code'), name='uniq_budget_line_code_per_budget'),
        ),
        migrations.AddIndex(
            model_name='bankstatementline',
            index=models.Index(fields=['bank_account', 'transaction_date'], name='accounting__bank_ac_4a23a0_idx'),
        ),
        migrations.AddIndex(
            model_name='bankstatementline',
            index=models.Index(fields=['match_status', 'transaction_date'], name='accounting__match_s_8bde05_idx'),
        ),
        migrations.AddConstraint(
            model_name='bankstatementline',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__gt', '')), fields=('statement_import', 'external_id'), name='uniq_statement_import_external_id'),
        ),
        migrations.AddConstraint(
            model_name='bankreconciliationsession',
            constraint=models.UniqueConstraint(fields=('bank_account', 'period_start', 'period_end'), name='uniq_bank_reconciliation_period'),
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['institution', 'status'], name='accounting__institu_d31d0f_idx'),
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['ledger_account', 'status'], name='accounting__ledger__851521_idx'),
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['account_type', 'status'], name='accounting__account_50a7d6_idx'),
        ),
        migrations.AddIndex(
            model_name='accountingdocument',
            index=models.Index(fields=['document_type', 'reference'], name='accounting__documen_d65ab1_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['account_type', 'is_active'], name='accounting__account_e6bebd_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['category', 'is_active'], name='accounting__categor_1764a1_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['parent'], name='accounting__parent__da6035_idx'),
        ),
    ]
