# Generated by Django 4.2.4 on 2026-06-04 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_payperiod_payrollcompensationplan_payrollemployee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paystub',
            name='salary_paid_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paystub',
            name='salary_payment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='paystub',
            name='salary_payment_journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_payment_pay_stubs', to='accounting.journalentry'),
        ),
        migrations.AddField(
            model_name='paystub',
            name='salary_payment_reference',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
