# Generated by Django 4.2.4 on 2026-06-04 17:02

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0004_paystub_salary_paid_on_paystub_salary_payment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollcompensationplan',
            name='daily_double_time_after_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('12.00'), max_digits=6),
        ),
        migrations.AddField(
            model_name='payrollcompensationplan',
            name='daily_overtime_after_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('8.00'), max_digits=6),
        ),
        migrations.AddField(
            model_name='payrollcompensationplan',
            name='default_regular_hours_per_period',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Fallback regular hours for hourly employees when no work summary exists.', max_digits=8),
        ),
        migrations.AddField(
            model_name='payrollcompensationplan',
            name='double_time_rate_multiplier',
            field=models.DecimalField(decimal_places=3, default=Decimal('2.000'), max_digits=6),
        ),
        migrations.AddField(
            model_name='payrollcompensationplan',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='payrollcompensationplan',
            name='overtime_rate_multiplier',
            field=models.DecimalField(decimal_places=3, default=Decimal('1.500'), max_digits=6),
        ),
        migrations.AddField(
            model_name='payrollcompensationplan',
            name='pay_type',
            field=models.CharField(choices=[('monthly_salary', 'Monthly salary'), ('hourly', 'Hourly')], db_index=True, default='monthly_salary', max_length=30),
        ),
        migrations.AddField(
            model_name='payrollcompensationplan',
            name='weekly_overtime_after_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('40.00'), max_digits=6),
        ),
        migrations.AddField(
            model_name='paystub',
            name='daily_overtime_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='paystub',
            name='daily_overtime_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='paystub',
            name='double_time_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='paystub',
            name='double_time_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='paystub',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='paystub',
            name='pay_type',
            field=models.CharField(blank=True, db_index=True, default='monthly_salary', max_length=30),
        ),
        migrations.AddField(
            model_name='paystub',
            name='regular_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='paystub',
            name='regular_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='paystub',
            name='weekly_overtime_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='paystub',
            name='weekly_overtime_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.CreateModel(
            name='PayrollWorkSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regular_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('daily_overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('weekly_overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('double_time_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('unpaid_break_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('source_app', models.CharField(blank=True, default='', help_text='Example: attendance, time_clock, device_clock.', max_length=100)),
                ('source_model', models.CharField(blank=True, default='', max_length=100)),
                ('source_ref', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('locked', 'Locked')], db_index=True, default='draft', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payroll_work_summaries', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_summaries', to='accounting.payrollemployee')),
                ('pay_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_summaries', to='accounting.payperiod')),
            ],
            options={
                'ordering': ('-pay_period__start_date', 'employee__display_name'),
            },
        ),
        migrations.AddField(
            model_name='paystub',
            name='work_summary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pay_stubs', to='accounting.payrollworksummary'),
        ),
        migrations.AddConstraint(
            model_name='payrollworksummary',
            constraint=models.UniqueConstraint(fields=('employee', 'pay_period'), name='uniq_payroll_work_summary_employee_period'),
        ),
    ]
