# Generated by Django 4.2.4 on 2026-06-04 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_payrollcompensationplan_daily_double_time_after_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paystub',
            name='pay_stub_emailed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paystub',
            name='payment_confirmation_emailed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paystub',
            name='salary_payment_method',
            field=models.CharField(blank=True, choices=[('e_transfer', 'E-Transfer'), ('direct_deposit', 'Direct Deposit'), ('cheque', 'Cheque'), ('cash', 'Cash'), ('other', 'Other')], default='', max_length=30),
        ),
    ]
