# Generated by Django 4.2.4 on 2026-06-04 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_paystub_pay_stub_emailed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollemployee',
            name='cpp_exempt',
            field=models.BooleanField(default=False, help_text='If checked, CPP will NOT be calculated for this employee. Leave unchecked when CPP should be deducted and remitted.', verbose_name='CPP exempt'),
        ),
        migrations.AlterField(
            model_name='payrollemployee',
            name='ei_exempt',
            field=models.BooleanField(default=False, help_text='If checked, EI will NOT be calculated for this employee. Use this when the employee is EI-exempt, such as certain related/employer-controlled situations.', verbose_name='EI exempt'),
        ),
        migrations.AlterField(
            model_name='payrollemployee',
            name='income_tax_exempt',
            field=models.BooleanField(default=False, help_text='If checked, income tax will NOT be deducted from payroll. Leave unchecked for regular payroll income tax deductions.', verbose_name='Income tax exempt'),
        ),
    ]
