# Generated by Django 4.2.4 on 2026-06-04 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0007_alter_payrollemployee_cpp_exempt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollSalaryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_on', models.DateField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payment_method', models.CharField(choices=[('e_transfer', 'E-Transfer'), ('direct_deposit', 'Direct Deposit'), ('cheque', 'Cheque'), ('bank_transfer', 'Bank Transfer'), ('other', 'Other')], db_index=True, default='e_transfer', max_length=30)),
                ('payment_reference', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payroll_salary_payments', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_salary_payment_record', to='accounting.journalentry')),
                ('pay_stub', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_payments', to='accounting.paystub')),
            ],
            options={
                'ordering': ('-paid_on', '-id'),
                'indexes': [models.Index(fields=['paid_on', 'payment_method'], name='accounting__paid_on_9f4c26_idx'), models.Index(fields=['payment_reference'], name='accounting__payment_a311f6_idx')],
            },
        ),
    ]
