# Generated by Django 4.2.4 on 2026-09-01 01:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0008_payrollsalarypayment'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bankstatementline',
            name='uniq_statement_import_external_id',
        ),
        migrations.AddField(
            model_name='bankreconciliationsession',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankreconciliationsession',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_reconciliation_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bankstatementimport',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bankstatementimport',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='bankstatementimport',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankstatementline',
            name='fingerprint',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='reversal_of',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal_entry', to='accounting.journalentry'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='reversal_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='reversed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='reversed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_journal_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='institution_name_snapshot',
            field=models.CharField(blank=True, default='', help_text='Snapshot for exports and history', max_length=255),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Legacy field only. Accounting opening balances must be posted through the general ledger.', max_digits=14),
        ),
        migrations.AlterField(
            model_name='bankstatementimport',
            name='status',
            field=models.CharField(choices=[('imported', 'Imported'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed'), ('archived', 'Archived')], db_index=True, default='imported', max_length=20),
        ),
        migrations.AlterField(
            model_name='bankstatementline',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Positive inflow, negative outflow.', max_digits=14),
        ),
        migrations.AlterField(
            model_name='bankstatementline',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Bank-provided transaction id', max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='journal_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='accounting.journalentry'),
        ),
        migrations.AddIndex(
            model_name='bankstatementimport',
            index=models.Index(fields=['bank_account', 'status'], name='accounting__bank_ac_5c3a04_idx'),
        ),
        migrations.AddIndex(
            model_name='bankstatementline',
            index=models.Index(fields=['bank_account', 'fingerprint'], name='accounting__bank_ac_ea940b_idx'),
        ),
        migrations.AddConstraint(
            model_name='bankreconciliationsession',
            constraint=models.CheckConstraint(check=models.Q(('period_end__gte', models.F('period_start'))), name='bank_reconciliation_end_gte_start'),
        ),
        migrations.AddConstraint(
            model_name='bankstatementimport',
            constraint=models.UniqueConstraint(condition=models.Q(('file_hash__gt', '')), fields=('bank_account', 'file_hash'), name='uniq_bank_statement_file_hash'),
        ),
        migrations.AddConstraint(
            model_name='bankstatementline',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__gt', '')), fields=('bank_account', 'external_id'), name='uniq_bank_account_external_id'),
        ),
        migrations.AddConstraint(
            model_name='founderloan',
            constraint=models.CheckConstraint(check=models.Q(('principal_amount__gt', 0)), name='founder_loan_principal_positive'),
        ),
        migrations.AddConstraint(
            model_name='founderloan',
            constraint=models.CheckConstraint(check=models.Q(('repaid_amount__gte', 0)), name='founder_loan_repaid_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='founderloan',
            constraint=models.CheckConstraint(check=models.Q(('repaid_amount__lte', models.F('principal_amount'))), name='founder_loan_repaid_lte_principal'),
        ),
    ]
