# Generated by Django 4.2.4 on 2026-09-01 04:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0009_remove_bankstatementline_uniq_statement_import_external_id_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bankstatementimport',
            name='uniq_bank_statement_file_hash',
        ),
        migrations.RemoveConstraint(
            model_name='bankstatementline',
            name='uniq_bank_account_external_id',
        ),
        migrations.RemoveConstraint(
            model_name='journalentry',
            name='uniq_posted_source_reference',
        ),
        migrations.AddField(
            model_name='bankstatementimport',
            name='file_dedupe_key',
            field=models.CharField(blank=True, editable=False, help_text='Internal MySQL-safe file idempotency key', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='bankstatementline',
            name='external_dedupe_key',
            field=models.CharField(blank=True, editable=False, help_text='Internal MySQL-safe bank transaction key', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='source_dedupe_key',
            field=models.CharField(blank=True, editable=False, help_text='Internal MySQL-safe source idempotency key', max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='bankreconciliationsession',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_bank_reconciliation_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bankstatementimport',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, default='', editable=False, max_length=64),
        ),
        migrations.AlterField(
            model_name='bankstatementline',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Signed amount. Positive inflow, negative outflow.', max_digits=14),
        ),
        migrations.AlterField(
            model_name='bankstatementline',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Bank-provided transaction id if available', max_length=255),
        ),
        migrations.AlterField(
            model_name='bankstatementline',
            name='fingerprint',
            field=models.CharField(blank=True, db_index=True, default='', editable=False, max_length=64),
        ),
    ]
