# Generated by Django 4.2.4 on 2026-09-01 22:07

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0010_remove_bankstatementimport_uniq_bank_statement_file_hash_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('asset_number', models.CharField(db_index=True, editable=False, max_length=40, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('purchase_date', models.DateField(db_index=True)),
                ('placed_in_service_date', models.DateField(db_index=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=14)),
                ('salvage_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('useful_life_months', models.PositiveIntegerField()),
                ('depreciation_method', models.CharField(choices=[('straight_line', 'Straight Line')], default='straight_line', max_length=30)),
                ('vendor_name', models.CharField(blank=True, default='', max_length=255)),
                ('reference', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('serial_number', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('fully_depreciated', 'Fully Depreciated'), ('disposed', 'Disposed')], db_index=True, default='active', max_length=30)),
                ('disposed_on', models.DateField(blank=True, null=True)),
                ('disposal_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accumulated_depreciation_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fixed_assets_accumulated_depreciation', to='accounting.account')),
                ('acquisition_bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fixed_asset_purchases', to='accounting.bankaccount')),
                ('acquisition_journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fixed_asset_acquisition', to='accounting.journalentry')),
                ('asset_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fixed_assets', to='accounting.account')),
                ('budget_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fixed_assets', to='accounting.budgetline')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fixed_assets', to=settings.AUTH_USER_MODEL)),
                ('depreciation_expense_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fixed_assets_depreciation_expense', to='accounting.account')),
                ('fund', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fixed_assets', to='accounting.fund')),
            ],
            options={
                'ordering': ('-purchase_date', 'asset_number'),
            },
        ),
        migrations.CreateModel(
            name='FixedAssetDepreciation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depreciation_entries', to='accounting.fixedasset')),
                ('journal_entry', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='fixed_asset_depreciation', to='accounting.journalentry')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_fixed_asset_depreciation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-period_end', 'asset__asset_number'),
                'indexes': [models.Index(fields=['period_end'], name='accounting__period__5c9379_idx'), models.Index(fields=['asset', 'period_end'], name='accounting__asset_i_e90f07_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='fixedassetdepreciation',
            constraint=models.UniqueConstraint(fields=('asset', 'period_start', 'period_end'), name='uniq_fixed_asset_depreciation_period'),
        ),
        migrations.AddIndex(
            model_name='fixedasset',
            index=models.Index(fields=['status', 'placed_in_service_date'], name='accounting__status_5cc410_idx'),
        ),
        migrations.AddIndex(
            model_name='fixedasset',
            index=models.Index(fields=['asset_account', 'status'], name='accounting__asset_a_5ba55e_idx'),
        ),
        migrations.AddIndex(
            model_name='fixedasset',
            index=models.Index(fields=['fund', 'status'], name='accounting__fund_id_150c8c_idx'),
        ),
    ]
