# Generated by Django 4.2.4 on 2026-09-01 23:51

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0011_fixedasset_fixedassetdepreciation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('legal_name', models.CharField(max_length=255)),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('website', models.URLField(blank=True, default='')),
                ('address_line1', models.CharField(blank=True, default='', max_length=255)),
                ('address_line2', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=120)),
                ('province', models.CharField(blank=True, default='', max_length=120)),
                ('postal_code', models.CharField(blank=True, default='', max_length=30)),
                ('country', models.CharField(default='CA', max_length=2)),
                ('default_terms_days', models.PositiveSmallIntegerField(default=30)),
                ('default_payment_method', models.CharField(choices=[('e_transfer', 'E-Transfer'), ('eft', 'EFT / Direct Deposit'), ('cheque', 'Cheque'), ('card', 'Card'), ('wire', 'Wire Transfer'), ('other', 'Other')], default='eft', max_length=30)),
                ('tax_registration_number', models.CharField(blank=True, default='', max_length=100)),
                ('account_number_with_vendor', models.CharField(blank=True, default='', max_length=100)),
                ('internal_note', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('display_name', 'legal_name', 'code'),
            },
        ),
        migrations.CreateModel(
            name='VendorBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('bill_number', models.CharField(db_index=True, max_length=120)),
                ('bill_date', models.DateField(db_index=True)),
                ('due_date', models.DateField(db_index=True)),
                ('currency', models.CharField(default='CAD', max_length=10)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('internal_note', models.TextField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('tax_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('partial', 'Partially Paid'), ('paid', 'Paid'), ('void', 'Void')], db_index=True, default='draft', max_length=20)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vendor_bills', to=settings.AUTH_USER_MODEL)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_vendor_bills', to=settings.AUTH_USER_MODEL)),
                ('posting_journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendor_bill', to='accounting.journalentry')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='accounting.vendor')),
            ],
            options={
                'ordering': ('-bill_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='VendorPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('payment_number', models.CharField(db_index=True, editable=False, max_length=50, unique=True)),
                ('payment_date', models.DateField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='CAD', max_length=10)),
                ('payment_method', models.CharField(choices=[('e_transfer', 'E-Transfer'), ('eft', 'EFT / Direct Deposit'), ('cheque', 'Cheque'), ('card', 'Card'), ('wire', 'Wire Transfer'), ('other', 'Other')], default='eft', max_length=30)),
                ('reference', models.CharField(db_index=True, max_length=255)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_payments', to='accounting.bankaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vendor_payments', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_payment', to='accounting.journalentry')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='accounting.vendor')),
            ],
            options={
                'ordering': ('-payment_date', '-id'),
            },
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='acquisition_bank_account',
            field=models.ForeignKey(blank=True, help_text='Bank account used for direct purchases. Blank when acquired through Accounts Payable.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fixed_asset_purchases', to='accounting.bankaccount'),
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='acquisition_journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fixed_asset_acquisitions', to='accounting.journalentry'),
        ),
        migrations.CreateModel(
            name='VendorPaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_allocations', to='accounting.vendorbill')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='accounting.vendorpayment')),
            ],
            options={
                'ordering': ('bill__due_date', 'bill_id'),
            },
        ),
        migrations.CreateModel(
            name='VendorBillLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveSmallIntegerField()),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount before separately recoverable tax.', max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('capitalize_as_fixed_asset', models.BooleanField(default=False)),
                ('asset_name', models.CharField(blank=True, default='', max_length=255)),
                ('placed_in_service_date', models.DateField(blank=True, null=True)),
                ('useful_life_months', models.PositiveIntegerField(blank=True, null=True)),
                ('salvage_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('serial_number', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_bill_lines', to='accounting.account')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.vendorbill')),
                ('budget_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendor_bill_lines', to='accounting.budgetline')),
                ('fixed_asset', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendor_bill_line', to='accounting.fixedasset')),
                ('fund', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendor_bill_lines', to='accounting.fund')),
                ('tax_account', models.ForeignKey(blank=True, help_text='Optional recoverable-tax asset account. Leave blank when tax is part of expense/asset cost.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendor_bill_tax_lines', to='accounting.account')),
            ],
            options={
                'ordering': ('line_number', 'id'),
            },
        ),
        migrations.CreateModel(
            name='VendorAPAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('invoice', 'Invoice'), ('payment_proof', 'Payment Proof'), ('credit_note', 'Credit Note'), ('other', 'Other')], default='other', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='accounting/ap/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='accounting.vendorbill')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='accounting.vendorpayment')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_vendor_ap_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['is_active', 'legal_name'], name='accounting__is_acti_c8bce6_idx'),
        ),
        migrations.AddConstraint(
            model_name='vendorpaymentallocation',
            constraint=models.UniqueConstraint(fields=('payment', 'bill'), name='uniq_vendor_payment_bill_allocation'),
        ),
        migrations.AddConstraint(
            model_name='vendorpaymentallocation',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', Decimal('0.00'))), name='vendor_payment_allocation_positive'),
        ),
        migrations.AddIndex(
            model_name='vendorpayment',
            index=models.Index(fields=['vendor', 'payment_date'], name='accounting__vendor__8fa00d_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorpayment',
            index=models.Index(fields=['bank_account', 'payment_date'], name='accounting__bank_ac_c2fa42_idx'),
        ),
        migrations.AddConstraint(
            model_name='vendorpayment',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', Decimal('0.00'))), name='vendor_payment_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='vendorpayment',
            constraint=models.UniqueConstraint(fields=('vendor', 'reference'), name='uniq_vendor_payment_reference'),
        ),
        migrations.AddConstraint(
            model_name='vendorbillline',
            constraint=models.UniqueConstraint(fields=('bill', 'line_number'), name='uniq_vendor_bill_line_number'),
        ),
        migrations.AddConstraint(
            model_name='vendorbillline',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', Decimal('0.00'))), name='vendor_bill_line_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='vendorbillline',
            constraint=models.CheckConstraint(check=models.Q(('tax_amount__gte', Decimal('0.00'))), name='vendor_bill_line_tax_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='vendorbill',
            index=models.Index(fields=['status', 'due_date'], name='accounting__status_7d4c3d_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorbill',
            index=models.Index(fields=['vendor', 'status', 'due_date'], name='accounting__vendor__303c55_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorbill',
            index=models.Index(fields=['bill_date', 'status'], name='accounting__bill_da_e204eb_idx'),
        ),
        migrations.AddConstraint(
            model_name='vendorbill',
            constraint=models.UniqueConstraint(fields=('vendor', 'bill_number'), name='uniq_vendor_bill_number'),
        ),
        migrations.AddConstraint(
            model_name='vendorbill',
            constraint=models.CheckConstraint(check=models.Q(('due_date__gte', models.F('bill_date'))), name='vendor_bill_due_on_or_after_bill_date'),
        ),
        migrations.AddConstraint(
            model_name='vendorbill',
            constraint=models.CheckConstraint(check=models.Q(('subtotal__gte', Decimal('0.00'))), name='vendor_bill_subtotal_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='vendorbill',
            constraint=models.CheckConstraint(check=models.Q(('tax_total__gte', Decimal('0.00'))), name='vendor_bill_tax_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='vendorbill',
            constraint=models.CheckConstraint(check=models.Q(('total_amount__gte', Decimal('0.00'))), name='vendor_bill_total_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='vendorbill',
            constraint=models.CheckConstraint(check=models.Q(('amount_paid__gte', Decimal('0.00'))), name='vendor_bill_paid_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='vendorapattachment',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('bill__isnull', False), ('payment__isnull', True)), models.Q(('bill__isnull', True), ('payment__isnull', False)), _connector='OR'), name='vendor_ap_attachment_exactly_one_parent'),
        ),
    ]
