# Generated by Django 4.2.4 on 2026-09-02 04:23

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0012_vendor_vendorbill_vendorpayment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('legal_name', models.CharField(max_length=255)),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
                ('billing_email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('website', models.URLField(blank=True, default='')),
                ('address_line1', models.CharField(blank=True, default='', max_length=255)),
                ('address_line2', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=120)),
                ('province', models.CharField(blank=True, default='', max_length=120)),
                ('postal_code', models.CharField(blank=True, default='', max_length=30)),
                ('country', models.CharField(default='CA', max_length=2)),
                ('default_terms_days', models.PositiveSmallIntegerField(default=30)),
                ('default_payment_method', models.CharField(choices=[('e_transfer', 'E-Transfer'), ('eft', 'EFT / Direct Deposit'), ('cheque', 'Cheque'), ('card', 'Card'), ('wire', 'Wire Transfer'), ('other', 'Other')], default='eft', max_length=30)),
                ('tax_registration_number', models.CharField(blank=True, default='', max_length=100)),
                ('customer_reference', models.CharField(blank=True, default='', max_length=100)),
                ('internal_note', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_receivable_account', models.ForeignKey(help_text='Posting account under Accounts Receivable (1100).', on_delete=django.db.models.deletion.PROTECT, related_name='customer_default_receivable_accounts', to='accounting.account')),
                ('default_revenue_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_default_revenue_accounts', to='accounting.account')),
            ],
            options={
                'ordering': ('display_name', 'legal_name', 'code'),
            },
        ),
        migrations.CreateModel(
            name='CustomerInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('invoice_number', models.CharField(blank=True, db_index=True, default='', help_text='Leave blank to generate a TownLIT invoice number automatically.', max_length=120, unique=True)),
                ('invoice_date', models.DateField(db_index=True)),
                ('due_date', models.DateField(db_index=True)),
                ('currency', models.CharField(default='CAD', max_length=10)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('purchase_order_reference', models.CharField(blank=True, default='', max_length=120)),
                ('internal_note', models.TextField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('tax_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('amount_received', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('partial', 'Partially Paid'), ('paid', 'Paid'), ('void', 'Void')], db_index=True, default='draft', max_length=20)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customer_invoices', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='accounting.customer')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_customer_invoices', to=settings.AUTH_USER_MODEL)),
                ('posting_journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_invoice', to='accounting.journalentry')),
                ('receivable_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_invoices', to='accounting.account')),
            ],
            options={
                'ordering': ('-invoice_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='CustomerReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('receipt_number', models.CharField(db_index=True, editable=False, max_length=50, unique=True)),
                ('receipt_date', models.DateField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='CAD', max_length=10)),
                ('payment_method', models.CharField(choices=[('e_transfer', 'E-Transfer'), ('eft', 'EFT / Direct Deposit'), ('cheque', 'Cheque'), ('card', 'Card'), ('wire', 'Wire Transfer'), ('other', 'Other')], default='eft', max_length=30)),
                ('reference', models.CharField(db_index=True, max_length=255)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_receipts', to='accounting.bankaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customer_receipts', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='accounting.customer')),
                ('journal_entry', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='customer_receipt', to='accounting.journalentry')),
            ],
            options={
                'ordering': ('-receipt_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='CustomerReceiptAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_allocations', to='accounting.customerinvoice')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='accounting.customerreceipt')),
            ],
            options={
                'ordering': ('invoice__due_date', 'invoice_id'),
            },
        ),
        migrations.CreateModel(
            name='CustomerInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveSmallIntegerField()),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fund', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_invoice_lines', to='accounting.fund')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.customerinvoice')),
                ('revenue_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_invoice_revenue_lines', to='accounting.account')),
                ('tax_account', models.ForeignKey(blank=True, help_text='Sales-tax liability account. Required when tax amount is greater than zero.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_invoice_tax_lines', to='accounting.account')),
            ],
            options={
                'ordering': ('line_number', 'id'),
            },
        ),
        migrations.CreateModel(
            name='CustomerARAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('invoice', 'Invoice'), ('receipt_proof', 'Receipt Proof'), ('purchase_order', 'Purchase Order'), ('contract', 'Contract'), ('other', 'Other')], default='other', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='accounting/ar/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='accounting.customerinvoice')),
                ('receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='accounting.customerreceipt')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_customer_ar_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.AddConstraint(
            model_name='customerreceiptallocation',
            constraint=models.UniqueConstraint(fields=('receipt', 'invoice'), name='uniq_customer_receipt_invoice_allocation'),
        ),
        migrations.AddConstraint(
            model_name='customerreceiptallocation',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', Decimal('0.00'))), name='customer_receipt_allocation_positive'),
        ),
        migrations.AddIndex(
            model_name='customerreceipt',
            index=models.Index(fields=['customer', 'receipt_date'], name='accounting__custome_a2bddb_idx'),
        ),
        migrations.AddIndex(
            model_name='customerreceipt',
            index=models.Index(fields=['bank_account', 'receipt_date'], name='accounting__bank_ac_5fb60d_idx'),
        ),
        migrations.AddConstraint(
            model_name='customerreceipt',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', Decimal('0.00'))), name='customer_receipt_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='customerreceipt',
            constraint=models.UniqueConstraint(fields=('customer', 'reference'), name='uniq_customer_receipt_reference'),
        ),
        migrations.AddConstraint(
            model_name='customerinvoiceline',
            constraint=models.UniqueConstraint(fields=('invoice', 'line_number'), name='uniq_customer_invoice_line_number'),
        ),
        migrations.AddConstraint(
            model_name='customerinvoiceline',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gt', Decimal('0.00'))), name='customer_invoice_line_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='customerinvoiceline',
            constraint=models.CheckConstraint(check=models.Q(('unit_price__gte', Decimal('0.00'))), name='customer_invoice_line_unit_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='customerinvoiceline',
            constraint=models.CheckConstraint(check=models.Q(('amount__gte', Decimal('0.00'))), name='customer_invoice_line_amount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='customerinvoiceline',
            constraint=models.CheckConstraint(check=models.Q(('tax_amount__gte', Decimal('0.00'))), name='customer_invoice_line_tax_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='customerinvoice',
            index=models.Index(fields=['status', 'due_date'], name='accounting__status_803d9d_idx'),
        ),
        migrations.AddIndex(
            model_name='customerinvoice',
            index=models.Index(fields=['customer', 'status', 'due_date'], name='accounting__custome_a7682e_idx'),
        ),
        migrations.AddIndex(
            model_name='customerinvoice',
            index=models.Index(fields=['invoice_date', 'status'], name='accounting__invoice_864cb5_idx'),
        ),
        migrations.AddConstraint(
            model_name='customerinvoice',
            constraint=models.CheckConstraint(check=models.Q(('due_date__gte', models.F('invoice_date'))), name='customer_invoice_due_on_or_after_invoice_date'),
        ),
        migrations.AddConstraint(
            model_name='customerinvoice',
            constraint=models.CheckConstraint(check=models.Q(('subtotal__gte', Decimal('0.00'))), name='customer_invoice_subtotal_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='customerinvoice',
            constraint=models.CheckConstraint(check=models.Q(('tax_total__gte', Decimal('0.00'))), name='customer_invoice_tax_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='customerinvoice',
            constraint=models.CheckConstraint(check=models.Q(('total_amount__gte', Decimal('0.00'))), name='customer_invoice_total_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='customerinvoice',
            constraint=models.CheckConstraint(check=models.Q(('amount_received__gte', Decimal('0.00'))), name='customer_invoice_received_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='customerinvoice',
            constraint=models.CheckConstraint(check=models.Q(('amount_received__lte', models.F('total_amount'))), name='customer_invoice_received_not_over_total'),
        ),
        migrations.AddConstraint(
            model_name='customerarattachment',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('invoice__isnull', False), ('receipt__isnull', True)), models.Q(('invoice__isnull', True), ('receipt__isnull', False)), _connector='OR'), name='customer_ar_attachment_exactly_one_parent'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['is_active', 'legal_name'], name='accounting__is_acti_d2aa21_idx'),
        ),
    ]
