# apps/organizations/modules/church/urls.py
#
# TownLIT
#
# Created by Hossein Sakkaki on 2026-09-08.
# Last Update by Hossein Sakkaki on 2026-09-08.
#

from django.urls import path

from apps.organizations.modules.church.views import (
    ChurchAttendanceCheckInView,
    ChurchAttendanceCloseView,
    ChurchAttendanceGuestCountsView,
    ChurchAttendanceRecordCheckOutView,
    ChurchAttendanceSessionDetailView,
    ChurchAttendanceSessionsView,
    ChurchBootstrapView,
    ChurchCampusArchiveView,
    ChurchCampusDetailView,
    ChurchCampusPrimaryView,
    ChurchCampusesView,
    ChurchCongregantDetailView,
    ChurchCongregantDirectoryVisibilityView,
    ChurchCongregantSyncOfficialMembershipView,
    ChurchCongregantsView,
    ChurchExternalCongregantCreateView,
    ChurchGuestCongregantCreateView,
    ChurchHouseholdDetailView,
    ChurchHouseholdMembershipRemoveView,
    ChurchHouseholdMembersView,
    ChurchHouseholdsView,
    ChurchMemberCongregantCreateView,
    ChurchMemberDirectoryView,
    ChurchGatheringCancelView,
    ChurchGatheringCompleteView,
    ChurchGatheringDetailView,
    ChurchGatheringsView,
    ChurchGatheringSeriesDetailView,
    ChurchGatheringSeriesMaterializeView,
    ChurchGatheringSeriesView,
    ChurchLeadershipDetailView,
    ChurchLeadershipEndView,
    ChurchLeadershipView,
    ChurchMinistriesView,
    ChurchMinistryDetailView,
    ChurchPastoralCareAssignmentEndView,
    ChurchPastoralCareAssignmentsView,
    ChurchPastoralCareCaseDetailView,
    ChurchPastoralCareCasesView,
    ChurchPastoralCareCloseView,
    ChurchPastoralCareContactsView,
    ChurchPastoralCareHoldView,
    ChurchPastoralCareNotesView,
    ChurchPastoralCareReferencesView,
    ChurchPastoralCareReopenView,
    ChurchResourceDetailView,
    ChurchResourceReservationCancelView,
    ChurchResourceReservationCompleteView,
    ChurchResourceReservationsView,
    ChurchResourcesView,
    ChurchServicePlanCancelView,
    ChurchServicePlanCompleteView,
    ChurchServicePlanDetailView,
    ChurchServicePlanItemDetailView,
    ChurchServicePlanItemsView,
    ChurchServicePlanPublishView,
    ChurchServicePlanReferencesView,
    ChurchServicePlansView,
    ChurchServingAssignmentCancelView,
    ChurchServingAssignmentCheckInView,
    ChurchServingAssignmentCheckOutView,
    ChurchServingAssignmentCompleteView,
    ChurchServingAssignmentDetailView,
    ChurchServingAssignmentRespondView,
    ChurchServingAssignmentsView,
    ChurchServingTeamDetailView,
    ChurchServingTeamMembersView,
    ChurchServingTeamMembershipRemoveView,
    ChurchServingTeamsView,
    ChurchTeachingContentArchiveView,
    ChurchTeachingContentDetailView,
    ChurchTeachingContentPublishView,
    ChurchTeachingContentsView,
    ChurchTeachingReferencesView,
    ChurchTeachingSeriesArchiveView,
    ChurchTeachingSeriesDetailView,
    ChurchTeachingSeriesView,
    ChurchWorkspaceView,
)


urlpatterns = [
    path("bootstrap/", ChurchBootstrapView.as_view(), name="church-bootstrap"),
    path("workspace/", ChurchWorkspaceView.as_view(), name="church-workspace"),

    path("campuses/", ChurchCampusesView.as_view(), name="church-campuses"),
    path("campuses/<uuid:public_id>/", ChurchCampusDetailView.as_view(), name="church-campus-detail"),
    path("campuses/<uuid:public_id>/primary/", ChurchCampusPrimaryView.as_view(), name="church-campus-primary"),
    path("campuses/<uuid:public_id>/archive/", ChurchCampusArchiveView.as_view(), name="church-campus-archive"),

    path("ministries/", ChurchMinistriesView.as_view(), name="church-ministries"),
    path("ministries/<uuid:public_id>/", ChurchMinistryDetailView.as_view(), name="church-ministry-detail"),

    path("leadership/", ChurchLeadershipView.as_view(), name="church-leadership"),
    path("leadership/<uuid:public_id>/", ChurchLeadershipDetailView.as_view(), name="church-leadership-detail"),
    path("leadership/<uuid:public_id>/end/", ChurchLeadershipEndView.as_view(), name="church-leadership-end"),

    path("gathering-series/", ChurchGatheringSeriesView.as_view(), name="church-gathering-series"),
    path("gathering-series/<uuid:public_id>/", ChurchGatheringSeriesDetailView.as_view(), name="church-gathering-series-detail"),
    path("gathering-series/<uuid:public_id>/materialize/", ChurchGatheringSeriesMaterializeView.as_view(), name="church-gathering-series-materialize"),
    path("gatherings/", ChurchGatheringsView.as_view(), name="church-gatherings"),
    path("gatherings/<uuid:public_id>/", ChurchGatheringDetailView.as_view(), name="church-gathering-detail"),
    path("gatherings/<uuid:public_id>/cancel/", ChurchGatheringCancelView.as_view(), name="church-gathering-cancel"),
    path("gatherings/<uuid:public_id>/complete/", ChurchGatheringCompleteView.as_view(), name="church-gathering-complete"),

    path("attendance/sessions/", ChurchAttendanceSessionsView.as_view(), name="church-attendance-sessions"),
    path("attendance/sessions/<uuid:public_id>/", ChurchAttendanceSessionDetailView.as_view(), name="church-attendance-session-detail"),
    path("attendance/sessions/<uuid:public_id>/check-in/", ChurchAttendanceCheckInView.as_view(), name="church-attendance-check-in"),
    path("attendance/sessions/<uuid:public_id>/guest-counts/", ChurchAttendanceGuestCountsView.as_view(), name="church-attendance-guest-counts"),
    path("attendance/sessions/<uuid:public_id>/close/", ChurchAttendanceCloseView.as_view(), name="church-attendance-close"),
    path("attendance/records/<uuid:public_id>/check-out/", ChurchAttendanceRecordCheckOutView.as_view(), name="church-attendance-check-out"),

    path("serving-teams/", ChurchServingTeamsView.as_view(), name="church-serving-teams"),
    path("serving-teams/<uuid:public_id>/", ChurchServingTeamDetailView.as_view(), name="church-serving-team-detail"),
    path("serving-teams/<uuid:public_id>/members/", ChurchServingTeamMembersView.as_view(), name="church-serving-team-members"),
    path("serving-team-memberships/<uuid:public_id>/remove/", ChurchServingTeamMembershipRemoveView.as_view(), name="church-serving-team-membership-remove"),

    path("service-plans/references/", ChurchServicePlanReferencesView.as_view(), name="church-service-plan-references"),
    path("service-plans/", ChurchServicePlansView.as_view(), name="church-service-plans"),
    path("service-plans/<uuid:public_id>/", ChurchServicePlanDetailView.as_view(), name="church-service-plan-detail"),
    path("service-plans/<uuid:public_id>/items/", ChurchServicePlanItemsView.as_view(), name="church-service-plan-items"),
    path("service-plan-items/<uuid:public_id>/", ChurchServicePlanItemDetailView.as_view(), name="church-service-plan-item-detail"),
    path("service-plans/<uuid:public_id>/publish/", ChurchServicePlanPublishView.as_view(), name="church-service-plan-publish"),
    path("service-plans/<uuid:public_id>/complete/", ChurchServicePlanCompleteView.as_view(), name="church-service-plan-complete"),
    path("service-plans/<uuid:public_id>/cancel/", ChurchServicePlanCancelView.as_view(), name="church-service-plan-cancel"),

    path("serving-assignments/", ChurchServingAssignmentsView.as_view(), name="church-serving-assignments"),
    path("serving-assignments/<uuid:public_id>/", ChurchServingAssignmentDetailView.as_view(), name="church-serving-assignment-detail"),
    path("serving-assignments/<uuid:public_id>/respond/", ChurchServingAssignmentRespondView.as_view(), name="church-serving-assignment-respond"),
    path("serving-assignments/<uuid:public_id>/check-in/", ChurchServingAssignmentCheckInView.as_view(), name="church-serving-assignment-check-in"),
    path("serving-assignments/<uuid:public_id>/check-out/", ChurchServingAssignmentCheckOutView.as_view(), name="church-serving-assignment-check-out"),
    path("serving-assignments/<uuid:public_id>/cancel/", ChurchServingAssignmentCancelView.as_view(), name="church-serving-assignment-cancel"),
    path("serving-assignments/<uuid:public_id>/complete/", ChurchServingAssignmentCompleteView.as_view(), name="church-serving-assignment-complete"),

    path("congregants/", ChurchCongregantsView.as_view(), name="church-congregants"),
    path("congregants/member/", ChurchMemberCongregantCreateView.as_view(), name="church-congregant-member-create"),
    path("congregants/guest/", ChurchGuestCongregantCreateView.as_view(), name="church-congregant-guest-create"),
    path("congregants/external/", ChurchExternalCongregantCreateView.as_view(), name="church-congregant-external-create"),
    path("congregants/<uuid:public_id>/", ChurchCongregantDetailView.as_view(), name="church-congregant-detail"),
    path("congregants/<uuid:public_id>/sync-official-membership/", ChurchCongregantSyncOfficialMembershipView.as_view(), name="church-congregant-sync-official-membership"),
    path("congregants/<uuid:public_id>/directory-visibility/", ChurchCongregantDirectoryVisibilityView.as_view(), name="church-congregant-directory-visibility"),
    path("member-directory/", ChurchMemberDirectoryView.as_view(), name="church-member-directory"),

    path("households/", ChurchHouseholdsView.as_view(), name="church-households"),
    path("households/<uuid:public_id>/", ChurchHouseholdDetailView.as_view(), name="church-household-detail"),
    path("households/<uuid:public_id>/members/", ChurchHouseholdMembersView.as_view(), name="church-household-members"),
    path("household-memberships/<uuid:public_id>/remove/", ChurchHouseholdMembershipRemoveView.as_view(), name="church-household-membership-remove"),

    path("pastoral-care/references/", ChurchPastoralCareReferencesView.as_view(), name="church-pastoral-care-references"),
    path("pastoral-care/cases/", ChurchPastoralCareCasesView.as_view(), name="church-pastoral-care-cases"),
    path("pastoral-care/cases/<uuid:public_id>/", ChurchPastoralCareCaseDetailView.as_view(), name="church-pastoral-care-case-detail"),
    path("pastoral-care/cases/<uuid:public_id>/assignments/", ChurchPastoralCareAssignmentsView.as_view(), name="church-pastoral-care-assignments"),
    path("pastoral-care/assignments/<uuid:public_id>/end/", ChurchPastoralCareAssignmentEndView.as_view(), name="church-pastoral-care-assignment-end"),
    path("pastoral-care/cases/<uuid:public_id>/notes/", ChurchPastoralCareNotesView.as_view(), name="church-pastoral-care-notes"),
    path("pastoral-care/cases/<uuid:public_id>/contacts/", ChurchPastoralCareContactsView.as_view(), name="church-pastoral-care-contacts"),
    path("pastoral-care/cases/<uuid:public_id>/hold/", ChurchPastoralCareHoldView.as_view(), name="church-pastoral-care-hold"),
    path("pastoral-care/cases/<uuid:public_id>/reopen/", ChurchPastoralCareReopenView.as_view(), name="church-pastoral-care-reopen"),
    path("pastoral-care/cases/<uuid:public_id>/close/", ChurchPastoralCareCloseView.as_view(), name="church-pastoral-care-close"),

    path("teaching/references/", ChurchTeachingReferencesView.as_view(), name="church-teaching-references"),
    path("teaching/series/", ChurchTeachingSeriesView.as_view(), name="church-teaching-series"),
    path("teaching/series/<uuid:public_id>/", ChurchTeachingSeriesDetailView.as_view(), name="church-teaching-series-detail"),
    path("teaching/series/<uuid:public_id>/archive/", ChurchTeachingSeriesArchiveView.as_view(), name="church-teaching-series-archive"),
    path("teaching/content/", ChurchTeachingContentsView.as_view(), name="church-teaching-content"),
    path("teaching/content/<uuid:public_id>/", ChurchTeachingContentDetailView.as_view(), name="church-teaching-content-detail"),
    path("teaching/content/<uuid:public_id>/publish/", ChurchTeachingContentPublishView.as_view(), name="church-teaching-content-publish"),
    path("teaching/content/<uuid:public_id>/archive/", ChurchTeachingContentArchiveView.as_view(), name="church-teaching-content-archive"),

    path("resources/", ChurchResourcesView.as_view(), name="church-resources"),
    path("resources/<uuid:public_id>/", ChurchResourceDetailView.as_view(), name="church-resource-detail"),
    path("resources/<uuid:public_id>/reservations/", ChurchResourceReservationsView.as_view(), name="church-resource-reservations"),
    path("resource-reservations/<uuid:public_id>/cancel/", ChurchResourceReservationCancelView.as_view(), name="church-resource-reservation-cancel"),
    path("resource-reservations/<uuid:public_id>/complete/", ChurchResourceReservationCompleteView.as_view(), name="church-resource-reservation-complete"),
]
