# Generated by Django 4.2.4 on 2026-07-21 19:44

import apps.creative_editor.validators.document
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.common.utils
import utils.mixins.media_autoconvert
import utils.mixins.media_conversion
import uuid
import validators.mediaValidators.image_validators
import validators.security_validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreativeComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_assets', models.JSONField(blank=True, default=dict)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, default='', max_length=160)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('rendering', 'Rendering'), ('ready', 'Ready'), ('failed', 'Failed'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('authenticated', 'Authenticated'), ('public', 'Public')], db_index=True, default='private', max_length=20)),
                ('source_mode', models.CharField(choices=[('upload', 'Uploaded Image'), ('content_reference', 'Content Reference'), ('generated_background', 'Generated Background')], db_index=True, default='generated_background', max_length=32)),
                ('source_image', models.ImageField(blank=True, max_length=700, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_moment_image_size, validators.security_validators.validate_no_executable_file])),
                ('source_image_is_converted', models.BooleanField(db_index=True, default=False)),
                ('source_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('source_field_name', models.CharField(blank=True, default='', max_length=80)),
                ('canvas_width', models.PositiveIntegerField(default=1080)),
                ('canvas_height', models.PositiveIntegerField(default=1920)),
                ('format_version', models.PositiveIntegerField(default=1)),
                ('revision', models.PositiveIntegerField(db_index=True, default=1)),
                ('document', models.JSONField(blank=True, default=dict, validators=[apps.creative_editor.validators.document.validate_creative_document])),
                ('document_sha256', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('rendered_image', models.ImageField(blank=True, max_length=700, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.security_validators.validate_no_executable_file])),
                ('thumbnail', models.ImageField(blank=True, max_length=700, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.security_validators.validate_no_executable_file])),
                ('rendered_revision', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('rendered_at', models.DateTimeField(blank=True, null=True)),
                ('render_error', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Creative Composition',
                'verbose_name_plural': 'Creative Compositions',
                'ordering': ('-updated_at', '-id'),
            },
            bases=(utils.mixins.media_autoconvert.MediaAutoConvertMixin, utils.mixins.media_conversion.MediaConversionMixin, models.Model),
        ),
        migrations.CreateModel(
            name='StickerPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=140, null=True, unique=True, verbose_name='Slug')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('cover_color', models.CharField(blank=True, default='', max_length=16)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Sticker Pack',
                'verbose_name_plural': 'Sticker Packs',
                'ordering': ('sort_order', 'name', 'id'),
                'indexes': [models.Index(fields=['is_active', 'is_featured', 'sort_order'], name='sticker_pack_active_idx')],
            },
        ),
        migrations.CreateModel(
            name='StickerAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_assets', models.JSONField(blank=True, default=dict)),
                ('slug', models.SlugField(blank=True, max_length=140, null=True, unique=True, verbose_name='Slug')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('image', models.ImageField(max_length=700, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file])),
                ('is_converted', models.BooleanField(db_index=True, default=False)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('aspect_ratio', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
                ('dominant_color', models.CharField(blank=True, default='', max_length=16)),
                ('blurhash', models.CharField(blank=True, default='', max_length=180)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stickers', to='creative_editor.stickerpack')),
            ],
            options={
                'verbose_name': 'Sticker Asset',
                'verbose_name_plural': 'Sticker Assets',
                'ordering': ('sort_order', 'title', 'id'),
            },
            bases=(utils.mixins.media_autoconvert.MediaAutoConvertMixin, utils.mixins.media_conversion.MediaConversionMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CreativeRenderJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_revision', models.PositiveIntegerField(db_index=True)),
                ('document_snapshot', models.JSONField(default=dict)),
                ('document_sha256', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed'), ('canceled', 'Canceled')], db_index=True, default='queued', max_length=20)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('stage', models.CharField(blank=True, default='', max_length=40)),
                ('message', models.CharField(blank=True, default='', max_length=255)),
                ('error', models.TextField(blank=True, default='')),
                ('task_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('queue', models.CharField(default='creative_render', max_length=40)),
                ('output_path', models.TextField(blank=True, default='')),
                ('thumbnail_path', models.TextField(blank=True, default='')),
                ('attempt', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=3)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('composition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='render_jobs', to='creative_editor.creativecomposition')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CreativeFont',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=140, null=True, unique=True, verbose_name='Slug')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=120)),
                ('postscript_name', models.CharField(blank=True, default='', max_length=180)),
                ('category', models.CharField(choices=[('sans_serif', 'Sans Serif'), ('serif', 'Serif'), ('display', 'Display'), ('handwriting', 'Handwriting'), ('monospace', 'Monospace'), ('other', 'Other')], db_index=True, default='sans_serif', max_length=24)),
                ('source', models.CharField(choices=[('system', 'System'), ('bundled', 'Bundled'), ('licensed', 'Licensed'), ('other', 'Other')], db_index=True, default='system', max_length=20)),
                ('supports_ltr', models.BooleanField(default=True)),
                ('supports_rtl', models.BooleanField(default=False)),
                ('supports_bold', models.BooleanField(default=True)),
                ('supports_italic', models.BooleanField(default=False)),
                ('minimum_size', models.PositiveSmallIntegerField(default=12)),
                ('maximum_size', models.PositiveSmallIntegerField(default=160)),
                ('preview_text', models.CharField(blank=True, default='', max_length=240)),
                ('license_reference', models.CharField(blank=True, default='', max_length=220)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Creative Font',
                'verbose_name_plural': 'Creative Fonts',
                'ordering': ('sort_order', 'display_name', 'id'),
                'indexes': [models.Index(fields=['is_active', 'category', 'sort_order'], name='creative_font_active_cat_idx'), models.Index(fields=['source', 'is_active'], name='creative_font_source_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='creativefont',
            constraint=models.CheckConstraint(check=models.Q(('maximum_size__gte', models.F('minimum_size'))), name='creative_font_size_range_valid'),
        ),
        migrations.AddField(
            model_name='creativecomposition',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creative_compositions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creativecomposition',
            name='source_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creative_source_compositions', to='contenttypes.contenttype'),
        ),
        migrations.AddIndex(
            model_name='stickerasset',
            index=models.Index(fields=['pack', 'is_active', 'sort_order'], name='sticker_asset_pack_idx'),
        ),
        migrations.AddIndex(
            model_name='stickerasset',
            index=models.Index(fields=['is_featured', 'is_active'], name='sticker_asset_feature_idx'),
        ),
        migrations.AddConstraint(
            model_name='stickerasset',
            constraint=models.UniqueConstraint(fields=('pack', 'title'), name='creative_unique_sticker_title_pack'),
        ),
        migrations.AddConstraint(
            model_name='stickerasset',
            constraint=models.CheckConstraint(check=models.Q(('width__isnull', True), ('width__gt', 0), _connector='OR'), name='creative_sticker_width_valid'),
        ),
        migrations.AddConstraint(
            model_name='stickerasset',
            constraint=models.CheckConstraint(check=models.Q(('height__isnull', True), ('height__gt', 0), _connector='OR'), name='creative_sticker_height_valid'),
        ),
        migrations.AddIndex(
            model_name='creativecomposition',
            index=models.Index(fields=['owner', 'status', '-updated_at'], name='creative_comp_owner_status_idx'),
        ),
        migrations.AddIndex(
            model_name='creativecomposition',
            index=models.Index(fields=['visibility', 'status', 'is_active'], name='creative_comp_delivery_idx'),
        ),
        migrations.AddIndex(
            model_name='creativecomposition',
            index=models.Index(fields=['source_content_type', 'source_object_id'], name='creative_comp_source_idx'),
        ),
        migrations.AddIndex(
            model_name='creativecomposition',
            index=models.Index(fields=['status', 'rendered_revision', 'revision'], name='creative_comp_render_idx'),
        ),
        migrations.AddConstraint(
            model_name='creativecomposition',
            constraint=models.CheckConstraint(check=models.Q(('canvas_width__gt', 0)), name='creative_canvas_width_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='creativecomposition',
            constraint=models.CheckConstraint(check=models.Q(('canvas_height__gt', 0)), name='creative_canvas_height_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='creativecomposition',
            constraint=models.CheckConstraint(check=models.Q(('format_version__gt', 0)), name='creative_format_version_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='creativecomposition',
            constraint=models.CheckConstraint(check=models.Q(('revision__gt', 0)), name='creative_revision_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='creativecomposition',
            constraint=models.CheckConstraint(check=models.Q(('rendered_revision__isnull', True), ('rendered_revision__gt', 0), _connector='OR'), name='creative_rendered_revision_valid'),
        ),
    ]
