# Generated by Django 4.2.4 on 2026-07-22 06:51

from django.db import migrations, models
import utils.common.utils
import validators.mediaValidators.image_validators
import validators.security_validators


class Migration(migrations.Migration):

    dependencies = [
        ('creative_editor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creativecomposition',
            name='rendered_image',
            field=models.ImageField(blank=True, max_length=700, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.security_validators.validate_no_executable_file]),
        ),
        migrations.AlterField(
            model_name='creativecomposition',
            name='source_image',
            field=models.ImageField(blank=True, max_length=700, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_moment_image_size, validators.security_validators.validate_no_executable_file]),
        ),
        migrations.AlterField(
            model_name='creativecomposition',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=700, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.security_validators.validate_no_executable_file]),
        ),
        migrations.AlterField(
            model_name='stickerasset',
            name='image',
            field=models.ImageField(max_length=700, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file]),
        ),
    ]
