# Generated by Django 4.2.4 on 2026-07-28 22:19

from django.db import migrations, models
import utils.common.utils
import uuid
import validators.mediaValidators.image_validators
import validators.security_validators


class Migration(migrations.Migration):

    dependencies = [
        ('creative_editor', '0003_alter_creativecomposition_rendered_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreativeBackgroundPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=140, null=True, unique=True, verbose_name='Slug')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, default='', max_length=240)),
                ('background_type', models.CharField(choices=[('color', 'Solid Color'), ('gradient', 'Gradient')], db_index=True, max_length=20)),
                ('color', models.CharField(blank=True, default='', max_length=9)),
                ('colors', models.JSONField(blank=True, default=list)),
                ('angle', models.FloatField(default=90.0)),
                ('supported_consumers', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                'verbose_name': 'Creative Background Preset',
                'verbose_name_plural': 'Creative Background Presets',
                'ordering': ('sort_order', 'title', 'id'),
            },
        ),
        migrations.AlterModelOptions(
            name='creativerenderjob',
            options={'ordering': ('-created_at', '-id'), 'verbose_name': 'Creative Render Job', 'verbose_name_plural': 'Creative Render Jobs'},
        ),
        migrations.AlterField(
            model_name='creativecomposition',
            name='rendered_image',
            field=models.ImageField(blank=True, max_length=700, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.security_validators.validate_no_executable_file]),
        ),
        migrations.AlterField(
            model_name='creativecomposition',
            name='source_image',
            field=models.ImageField(blank=True, max_length=700, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_moment_image_size, validators.security_validators.validate_no_executable_file]),
        ),
        migrations.AlterField(
            model_name='creativecomposition',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=700, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.security_validators.validate_no_executable_file]),
        ),
        migrations.AlterField(
            model_name='stickerasset',
            name='image',
            field=models.ImageField(max_length=700, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file]),
        ),
        migrations.AddIndex(
            model_name='creativerenderjob',
            index=models.Index(fields=['composition', 'status', '-created_at'], name='creative_rjob_comp_idx'),
        ),
        migrations.AddIndex(
            model_name='creativerenderjob',
            index=models.Index(fields=['status', 'heartbeat_at'], name='creative_render_health_idx'),
        ),
        migrations.AddIndex(
            model_name='creativerenderjob',
            index=models.Index(fields=['queue', 'status'], name='creative_render_queue_idx'),
        ),
        migrations.AddConstraint(
            model_name='creativerenderjob',
            constraint=models.UniqueConstraint(fields=('composition', 'requested_revision'), name='creative_unique_render_revision'),
        ),
        migrations.AddConstraint(
            model_name='creativerenderjob',
            constraint=models.CheckConstraint(check=models.Q(('requested_revision__gt', 0)), name='creative_render_revision_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='creativerenderjob',
            constraint=models.CheckConstraint(check=models.Q(('progress__lte', 100)), name='creative_render_progress_lte_100'),
        ),
        migrations.AddConstraint(
            model_name='creativerenderjob',
            constraint=models.CheckConstraint(check=models.Q(('max_attempts__gt', 0)), name='creative_render_max_attempts_gt_zero'),
        ),
        migrations.AddIndex(
            model_name='creativebackgroundpreset',
            index=models.Index(fields=['is_active', 'is_featured', 'sort_order'], name='creative_bg_active_feature_idx'),
        ),
        migrations.AddIndex(
            model_name='creativebackgroundpreset',
            index=models.Index(fields=['background_type', 'is_active'], name='creative_bg_type_active_idx'),
        ),
    ]
