# Generated by Django 4.2.4 on 2026-08-07 17:52

from django.db import migrations, models
import utils.common.utils
import validators.mediaValidators.image_validators
import validators.security_validators


class Migration(migrations.Migration):

    dependencies = [
        ('creative_editor', '0004_creativebackgroundpreset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creativefont',
            name='asset_sha256',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='creativefont',
            name='asset_version',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='creativefont',
            name='binary_filename',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AddField(
            model_name='creativefont',
            name='copyright_notice',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='creativefont',
            name='license_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='creativefont',
            name='license_url',
            field=models.URLField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='creativecomposition',
            name='rendered_image',
            field=models.ImageField(blank=True, max_length=700, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.security_validators.validate_no_executable_file]),
        ),
        migrations.AlterField(
            model_name='creativecomposition',
            name='source_image',
            field=models.ImageField(blank=True, max_length=700, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_moment_image_size, validators.security_validators.validate_no_executable_file]),
        ),
        migrations.AlterField(
            model_name='creativecomposition',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=700, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.security_validators.validate_no_executable_file]),
        ),
        migrations.AlterField(
            model_name='creativefont',
            name='source',
            field=models.CharField(choices=[('system', 'System'), ('bundled', 'Bundled'), ('licensed', 'Licensed'), ('other', 'Other')], db_index=True, default='bundled', max_length=20),
        ),
        migrations.AlterField(
            model_name='creativefont',
            name='supports_bold',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stickerasset',
            name='image',
            field=models.ImageField(max_length=700, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file]),
        ),
    ]
