# Generated by Django 4.2.4 on 2026-08-10 20:55

from django.db import migrations, models
import utils.common.utils
import validators.mediaValidators.image_validators
import validators.security_validators


class Migration(migrations.Migration):

    dependencies = [
        ('creative_editor', '0005_creativefont_asset_sha256_creativefont_asset_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creativefont',
            name='is_user_selectable',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='creativecomposition',
            name='rendered_image',
            field=models.ImageField(blank=True, max_length=700, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.security_validators.validate_no_executable_file]),
        ),
        migrations.AlterField(
            model_name='creativecomposition',
            name='source_image',
            field=models.ImageField(blank=True, max_length=700, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_moment_image_size, validators.security_validators.validate_no_executable_file]),
        ),
        migrations.AlterField(
            model_name='creativecomposition',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=700, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.security_validators.validate_no_executable_file]),
        ),
        migrations.AlterField(
            model_name='stickerasset',
            name='image',
            field=models.ImageField(max_length=700, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file]),
        ),
        migrations.AddIndex(
            model_name='creativefont',
            index=models.Index(fields=['is_active', 'is_user_selectable', 'sort_order'], name='creative_font_picker_idx'),
        ),
    ]
