# Generated by Django 4.2.4 on 2026-08-10 23:25

from django.db import migrations, models
import django.db.models.deletion
import utils.common.utils
import utils.mixins.media_autoconvert
import utils.mixins.media_conversion
import uuid
import validators.mediaValidators.image_validators
import validators.security_validators


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('creative_editor', '0007_alter_creativecomposition_rendered_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creativecomposition',
            name='format_version',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='creativecomposition',
            name='rendered_image',
            field=models.ImageField(blank=True, max_length=700, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.security_validators.validate_no_executable_file]),
        ),
        migrations.AlterField(
            model_name='creativecomposition',
            name='source_image',
            field=models.ImageField(blank=True, max_length=700, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_moment_image_size, validators.security_validators.validate_no_executable_file]),
        ),
        migrations.AlterField(
            model_name='creativecomposition',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=700, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.security_validators.validate_no_executable_file]),
        ),
        migrations.AlterField(
            model_name='stickerasset',
            name='image',
            field=models.ImageField(max_length=700, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file]),
        ),
        migrations.CreateModel(
            name='CreativeCompositionMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_assets', models.JSONField(blank=True, default=dict)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], db_index=True, default='image', max_length=20)),
                ('source_mode', models.CharField(choices=[('upload', 'Upload'), ('content_reference', 'Content Reference')], db_index=True, default='upload', max_length=32)),
                ('source_image', models.ImageField(blank=True, max_length=700, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_moment_image_size, validators.security_validators.validate_no_executable_file])),
                ('source_image_is_converted', models.BooleanField(db_index=True, default=False)),
                ('source_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('source_field_name', models.CharField(blank=True, default='', max_length=80)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('composition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_media', to='creative_editor.creativecomposition')),
                ('source_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creative_composition_media_sources', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Creative Composition Media',
                'verbose_name_plural': 'Creative Composition Media',
                'ordering': ('created_at', 'id'),
                'indexes': [models.Index(fields=['composition', 'is_active', 'created_at'], name='creative_media_comp_active_idx'), models.Index(fields=['composition', 'media_type', 'is_active'], name='creative_media_comp_type_idx'), models.Index(fields=['source_content_type', 'source_object_id'], name='creative_media_source_idx')],
            },
            bases=(utils.mixins.media_autoconvert.MediaAutoConvertMixin, utils.mixins.media_conversion.MediaConversionMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='creativecompositionmedia',
            constraint=models.CheckConstraint(check=models.Q(('width__isnull', True), ('width__gt', 0), _connector='OR'), name='creative_media_width_valid'),
        ),
        migrations.AddConstraint(
            model_name='creativecompositionmedia',
            constraint=models.CheckConstraint(check=models.Q(('height__isnull', True), ('height__gt', 0), _connector='OR'), name='creative_media_height_valid'),
        ),
        migrations.AddConstraint(
            model_name='creativecompositionmedia',
            constraint=models.CheckConstraint(check=models.Q(('duration_ms__isnull', True), ('duration_ms__gt', 0), _connector='OR'), name='creative_media_duration_valid'),
        ),
    ]
