# apps/accounting/services/payroll/paystub_pdf_service.py

from io import BytesIO
from decimal import Decimal
from pathlib import Path

from django.conf import settings
from django.utils import timezone

from reportlab.lib import colors
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch, mm
from reportlab.pdfgen import canvas
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    Image,
)

from apps.accounting.models import PayStub


ZERO = Decimal("0.00")


class NumberedCanvas(canvas.Canvas):
    """
    Canvas with page x of y numbering.
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        """
        Save page state before final rendering.
        """

        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        """
        Add total page count to every page.
        """

        page_count = len(self._saved_page_states)

        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_number(page_count)
            super().showPage()

        super().save()

    def draw_page_number(self, page_count):
        """
        Draw page number in footer.
        """

        page_text = f"Page {self._pageNumber} of {page_count}"
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#555555"))
        self.drawRightString(7.95 * inch, 0.35 * inch, page_text)


class PayStubPDFService:
    """
    Generates a branded human-readable statement of earnings PDF.
    """

    employer_name = "TownLIT Society"
    employer_address = "Coquitlam, British Columbia, Canada"
    system_name = "TownLIT Accounting System"
    currency = "CAD"

    logo_filename = "TownLITLogo.png"

    def build_pdf(self, *, pay_stub: PayStub) -> bytes:
        """
        Return pay stub PDF bytes.
        """

        buffer = BytesIO()

        doc = SimpleDocTemplate(
            buffer,
            pagesize=LETTER,
            rightMargin=0.55 * inch,
            leftMargin=0.55 * inch,
            topMargin=0.55 * inch,
            bottomMargin=0.65 * inch,
            title=f"Pay Stub - {pay_stub.employee.display_name}",
            author=self.employer_name,
        )

        styles = self._build_styles()
        story = []

        story.extend(self._build_header(styles=styles, pay_stub=pay_stub))
        story.append(Spacer(1, 10))

        story.append(self._build_identity_table(pay_stub=pay_stub))
        story.append(Spacer(1, 12))

        story.append(Paragraph("Pay Summary", styles["SectionTitle"]))
        story.append(self._build_summary_table(pay_stub=pay_stub))
        story.append(Spacer(1, 12))

        story.append(Paragraph("Earnings", styles["SectionTitle"]))
        story.append(self._build_earnings_table(pay_stub=pay_stub))
        story.append(Spacer(1, 12))

        story.append(Paragraph("Employee Deductions", styles["SectionTitle"]))
        story.append(self._build_deductions_table(pay_stub=pay_stub))
        story.append(Spacer(1, 12))

        story.append(Paragraph("Employer Contributions", styles["SectionTitle"]))
        story.append(self._build_employer_table(pay_stub=pay_stub))
        story.append(Spacer(1, 12))

        story.append(Paragraph("Payment and Payable Balance", styles["SectionTitle"]))
        story.append(self._build_payment_table(pay_stub=pay_stub))
        story.append(Spacer(1, 14))

        story.append(
            Paragraph(
                "This statement is generated from TownLIT payroll records. "
                "It should be kept with payroll, bank payment, and CRA remittance support.",
                styles["SmallNote"],
            )
        )

        story.append(
            Paragraph(
                f"Generated by {self.system_name} at "
                f"{timezone.now().strftime('%Y-%m-%d %H:%M:%S')}",
                styles["SmallNote"],
            )
        )

        doc.build(
            story,
            onFirstPage=self._draw_page_frame,
            onLaterPages=self._draw_page_frame,
            canvasmaker=NumberedCanvas,
        )

        return buffer.getvalue()

    def _build_styles(self):
        """
        Build PDF styles.
        """

        styles = getSampleStyleSheet()

        styles.add(
            ParagraphStyle(
                name="BrandTitle",
                parent=styles["Title"],
                fontSize=18,
                leading=22,
                textColor=colors.HexColor("#0F2D3A"),
                alignment=1,
                spaceAfter=2,
            )
        )

        styles.add(
            ParagraphStyle(
                name="DocumentTitle",
                parent=styles["Heading2"],
                fontSize=13,
                leading=16,
                textColor=colors.HexColor("#0F2D3A"),
                alignment=1,
                spaceAfter=4,
            )
        )

        styles.add(
            ParagraphStyle(
                name="Subtitle",
                parent=styles["Normal"],
                fontSize=8.5,
                leading=11,
                textColor=colors.HexColor("#555555"),
                alignment=1,
            )
        )

        styles.add(
            ParagraphStyle(
                name="SectionTitle",
                parent=styles["Heading3"],
                fontSize=12,
                leading=14,
                textColor=colors.HexColor("#0F2D3A"),
                spaceAfter=5,
            )
        )

        styles.add(
            ParagraphStyle(
                name="SmallNote",
                parent=styles["Normal"],
                fontSize=8,
                leading=10,
                textColor=colors.HexColor("#555555"),
            )
        )

        return styles

    def _build_header(self, *, styles, pay_stub: PayStub):
        """
        Build branded PDF header.
        """

        elements = []

        logo_path = self._get_logo_path()

        if logo_path:
            logo = Image(logo_path, width=0.72 * inch, height=0.72 * inch)
            logo.hAlign = "CENTER"
            elements.append(logo)
            elements.append(Spacer(1, 4))

        elements.append(Paragraph(f"<b>{self.employer_name}</b>", styles["BrandTitle"]))
        elements.append(Paragraph("<b>Statement of Earnings</b>", styles["DocumentTitle"]))

        elements.append(
            Paragraph(
                f"Issued by {self.system_name} · Pay Run {pay_stub.pay_run.run_number}",
                styles["Subtitle"],
            )
        )

        return elements

    def _draw_page_frame(self, canv, doc):
        """
        Draw page border and footer branding.
        """

        canv.saveState()

        width, height = LETTER

        # Top brand line.
        canv.setStrokeColor(colors.HexColor("#0F2D3A"))
        canv.setLineWidth(0.7)
        canv.line(0.55 * inch, height - 0.42 * inch, width - 0.55 * inch, height - 0.42 * inch)

        # Footer line.
        canv.setStrokeColor(colors.HexColor("#B8C2CC"))
        canv.setLineWidth(0.5)
        canv.line(0.55 * inch, 0.52 * inch, width - 0.55 * inch, 0.52 * inch)

        # Footer left.
        canv.setFont("Helvetica", 8)
        canv.setFillColor(colors.HexColor("#555555"))
        canv.drawString(
            0.55 * inch,
            0.35 * inch,
            f"{self.employer_name} · {self.system_name} · Confidential Payroll Record",
        )

        canv.restoreState()

    def _get_logo_path(self) -> str | None:
        """
        Resolve static logo path safely.
        """

        candidates = [
            Path(settings.BASE_DIR) / "static" / "logo" / self.logo_filename,
            Path(settings.BASE_DIR) / "staticfiles" / "logo" / self.logo_filename,
            Path(settings.BASE_DIR) / "static" / "img" / self.logo_filename,
        ]

        for path in candidates:
            if path.exists():
                return str(path)

        return None

    def _build_identity_table(self, *, pay_stub: PayStub):
        """
        Build employee and pay period identity section.
        """

        pay_run = pay_stub.pay_run
        period = pay_run.pay_period
        employee = pay_stub.employee

        data = [
            ["Employer", self.employer_name],
            ["Employer Address", self.employer_address],
            ["Employee", employee.display_name],
            ["Province of Employment", employee.province_of_employment],
            ["Pay Period", f"{period.start_date} to {period.end_date}"],
            ["Pay Date", str(period.pay_date)],
            ["Pay Run", pay_run.run_number],
            ["Currency", self.currency],
        ]

        return self._label_value_table(
            data,
            label_width=2.15 * inch,
            value_width=4.95 * inch,
        )

    def _build_summary_table(self, *, pay_stub: PayStub):
        """
        Build top-level pay summary.
        """

        data = [
            ["Metric", "Amount"],
            ["Gross Pay", self._money(pay_stub.gross_salary)],
            ["Employee Deductions", self._money(pay_stub.total_employee_deductions)],
            ["Net Pay", self._money(pay_stub.net_pay)],
            ["Actual Paid", self._money(pay_stub.actual_paid)],
            ["Remaining Salary Payable", self._money(pay_stub.net_salary_payable)],
        ]

        return self._table(
            data,
            col_widths=[3.5 * inch, 2.0 * inch],
            amount_cols={1},
        )

    def _build_earnings_table(self, *, pay_stub: PayStub):
        """
        Build earnings section.
        """

        data = [
            ["Earning Type", "Amount"],
            ["Regular Salary / Wages", self._money(pay_stub.gross_salary)],
            ["Vacation Pay Earned", self._money(pay_stub.vacation_pay_earned)],
            ["Vacation Pay Paid", self._money(pay_stub.vacation_pay_paid)],
            ["Sick Pay Paid", self._money(pay_stub.sick_pay_paid)],
            ["Taxable Benefits", self._money(pay_stub.taxable_benefits)],
            ["Taxable Earnings", self._money(pay_stub.taxable_earnings)],
            ["Pensionable Earnings", self._money(pay_stub.pensionable_earnings)],
            ["Insurable Earnings", self._money(pay_stub.insurable_earnings)],
        ]

        return self._table(
            data,
            col_widths=[3.5 * inch, 2.0 * inch],
            amount_cols={1},
        )

    def _build_deductions_table(self, *, pay_stub: PayStub):
        """
        Build employee deduction section.
        """

        data = [
            ["Deduction Type", "Amount"],
            ["CPP", self._money(pay_stub.employee_cpp)],
            ["CPP2", self._money(pay_stub.employee_cpp2)],
            ["EI", self._money(pay_stub.employee_ei)],
            ["Federal Income Tax", self._money(pay_stub.federal_income_tax)],
            ["Provincial Income Tax", self._money(pay_stub.provincial_income_tax)],
            ["Other Employee Deductions", self._money(pay_stub.other_employee_deductions)],
            ["Total Employee Deductions", self._money(pay_stub.total_employee_deductions)],
        ]

        return self._table(
            data,
            col_widths=[3.5 * inch, 2.0 * inch],
            amount_cols={1},
        )

    def _build_employer_table(self, *, pay_stub: PayStub):
        """
        Build employer contribution section.
        """

        data = [
            ["Contribution Type", "Amount"],
            ["Employer CPP", self._money(pay_stub.employer_cpp)],
            ["Employer CPP2", self._money(pay_stub.employer_cpp2)],
            ["Employer EI", self._money(pay_stub.employer_ei)],
            ["Other Employer Contributions", self._money(pay_stub.other_employer_contributions)],
            ["Total Employer Contributions", self._money(pay_stub.total_employer_contributions)],
        ]

        return self._table(
            data,
            col_widths=[3.5 * inch, 2.0 * inch],
            amount_cols={1},
        )

    def _build_payment_table(self, *, pay_stub: PayStub):
        """
        Build actual payment section.
        """

        data = [
            ["Item", "Value"],
            ["Net Pay", self._money(pay_stub.net_pay)],
            ["Actual Paid", self._money(pay_stub.actual_paid)],
            ["Remaining Salary Payable", self._money(pay_stub.net_salary_payable)],
            ["Salary Paid On", str(pay_stub.salary_paid_on or "")],
            ["Payment Method", pay_stub.get_salary_payment_method_display() if pay_stub.salary_payment_method else ""],
            ["Payment Reference", pay_stub.salary_payment_reference or pay_stub.payment_note],
            ["CRA Remittance Due", self._money(pay_stub.total_remittance_due)],
        ]

        return self._table(
            data,
            col_widths=[3.5 * inch, 2.0 * inch],
            amount_cols={1},
        )

    def _label_value_table(self, data, label_width, value_width):
        """
        Build a clear label/value table.
        """

        table = Table(
            data,
            colWidths=[label_width, value_width],
        )

        table.setStyle(
            TableStyle(
                [
                    ("GRID", (0, 0), (-1, -1), 0.35, colors.HexColor("#B8C2CC")),
                    ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),

                    # Label column
                    ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#EEF3F8")),
                    ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                    ("TEXTCOLOR", (0, 0), (0, -1), colors.HexColor("#0F2D3A")),
                    ("ALIGN", (0, 0), (0, -1), "LEFT"),

                    # Value column
                    ("BACKGROUND", (1, 0), (1, -1), colors.white),
                    ("FONTNAME", (1, 0), (1, -1), "Helvetica"),
                    ("TEXTCOLOR", (1, 0), (1, -1), colors.HexColor("#111111")),
                    ("ALIGN", (1, 0), (1, -1), "LEFT"),

                    # Cell spacing
                    ("FONTSIZE", (0, 0), (-1, -1), 9),
                    ("LEADING", (0, 0), (-1, -1), 11),
                    ("TOPPADDING", (0, 0), (-1, -1), 6),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                    ("LEFTPADDING", (0, 0), (-1, -1), 8),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 8),
                ]
            )
        )

        return table
    
    def _table(self, data, col_widths, amount_cols=None, header=True):
        """
        Build styled table.
        """

        amount_cols = amount_cols or set()
        table = Table(data, colWidths=col_widths)

        commands = [
            ("GRID", (0, 0), (-1, -1), 0.35, colors.HexColor("#B8C2CC")),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("FONTSIZE", (0, 0), (-1, -1), 8.5),
            ("LEADING", (0, 0), (-1, -1), 10),
            ("TOPPADDING", (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ("LEFTPADDING", (0, 0), (-1, -1), 6),
            ("RIGHTPADDING", (0, 0), (-1, -1), 6),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F7F9FB")]),
        ]

        if header:
            commands.extend(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#D9E2F3")),
                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.HexColor("#0F2D3A")),
                    ("ALIGN", (0, 0), (-1, 0), "CENTER"),
                ]
            )

        for col in amount_cols:
            commands.append(("ALIGN", (col, 1), (col, -1), "RIGHT"))

        table.setStyle(TableStyle(commands))
        return table

    def _money(self, value) -> str:
        """
        Format money.
        """

        value = value or ZERO
        return f"{value:,.2f}"