# Generated by Django 4.2.4 on 2025-03-25 02:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SanctuaryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('post_request', 'Post Request'), ('account_request', 'Account Request'), ('organization_request', 'Organization Request')], max_length=50, verbose_name='Request Type')),
                ('reason', models.CharField(max_length=255, verbose_name='Request Reason')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='pending', max_length=50, verbose_name='Status')),
                ('request_date', models.DateTimeField(auto_now_add=True, verbose_name='Request Date')),
                ('admin_assigned_at', models.DateTimeField(blank=True, null=True, verbose_name='Admin Assigned At')),
                ('object_id', models.PositiveIntegerField()),
                ('assigned_admin', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_sanctuary_requests', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Admin')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanctuary_requests', to=settings.AUTH_USER_MODEL, verbose_name='Requester')),
            ],
        ),
        migrations.CreateModel(
            name='SanctuaryReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_status', models.CharField(choices=[('no_opinion', 'No Opinion'), ('violation_confirmed', 'Violation Confirmed'), ('violation_rejected', 'Violation Rejected')], default='no_opinion', max_length=50, verbose_name='Review Status')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('review_date', models.DateTimeField(auto_now_add=True, verbose_name='Review Date')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Assigned At')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanctuary_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Reviewer')),
                ('sanctuary_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='sanctuary.sanctuaryrequest', verbose_name='Sanctuary Request')),
            ],
        ),
        migrations.CreateModel(
            name='SanctuaryOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome_status', models.CharField(choices=[('outcome_confirmed', 'Confirmed'), ('outcome_rejected', 'Rejected'), ('outcome_pending', 'Pending')], max_length=50, verbose_name='Outcome Status')),
                ('completion_date', models.DateTimeField(auto_now_add=True, verbose_name='Completion Date')),
                ('object_id', models.PositiveIntegerField(verbose_name='Object ID')),
                ('is_appealed', models.BooleanField(default=False, verbose_name='Is Appealed')),
                ('admin_reviewed', models.BooleanField(default=False, verbose_name='Admin Reviewed')),
                ('admin_assigned_at', models.DateTimeField(blank=True, null=True, verbose_name='Admin Assigned At')),
                ('appeal_message', models.TextField(blank=True, null=True, verbose_name='Appeal Message')),
                ('appeal_deadline', models.DateTimeField(blank=True, null=True, verbose_name='Appeal Deadline')),
                ('assigned_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_sanctuary_outcome_appeals', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Content Type')),
                ('sanctuary_requests', models.ManyToManyField(related_name='outcomes', to='sanctuary.sanctuaryrequest', verbose_name='Sanctuary Requests')),
            ],
        ),
    ]
