# Generated by Django 4.2.4 on 2025-12-19 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('sanctuary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SanctuaryProtectionLabel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('object_id', models.PositiveBigIntegerField()),
                ('label_type', models.CharField(choices=[('tradition_specific_perspective', 'Tradition-Specific Perspective')], max_length=64)),
                ('applied_by', models.CharField(choices=[('council', 'Council'), ('admin', 'Admin'), ('system', 'System')], default='system', max_length=16)),
                ('note', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='sanctuaryoutcome',
            options={'ordering': ['-created_at'], 'verbose_name': 'Sanctuary Outcome', 'verbose_name_plural': 'Sanctuary Outcomes'},
        ),
        migrations.AlterModelOptions(
            name='sanctuaryrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Sanctuary Request', 'verbose_name_plural': 'Sanctuary Requests'},
        ),
        migrations.AlterModelOptions(
            name='sanctuaryreview',
            options={'verbose_name': 'Sanctuary Review', 'verbose_name_plural': 'Sanctuary Reviews'},
        ),
        migrations.RemoveField(
            model_name='sanctuaryoutcome',
            name='completion_date',
        ),
        migrations.AddField(
            model_name='sanctuaryoutcome',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sanctuaryoutcome',
            name='finalized_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Finalized At'),
        ),
        migrations.AddField(
            model_name='sanctuaryoutcome',
            name='tradition_protection_granted',
            field=models.BooleanField(default=False, verbose_name='Tradition Protection Granted'),
        ),
        migrations.AddField(
            model_name='sanctuaryoutcome',
            name='tradition_protection_note',
            field=models.TextField(blank=True, help_text='Explanation for Tradition-Specific Perspective', null=True, verbose_name='Tradition Protection Note'),
        ),
        migrations.AddField(
            model_name='sanctuaryrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sanctuaryrequest',
            name='reasons',
            field=models.JSONField(default=list, help_text='List of selected violation reasons', verbose_name='Reported Reasons'),
        ),
        migrations.AddField(
            model_name='sanctuaryrequest',
            name='report_count_snapshot',
            field=models.PositiveIntegerField(default=1, help_text='Report count when this request was created', verbose_name='Report Count Snapshot'),
        ),
        migrations.AddField(
            model_name='sanctuaryrequest',
            name='resolution_mode',
            field=models.CharField(choices=[('monitor', 'Monitor Only'), ('council', 'Council Review'), ('admin', 'Admin Review')], default='monitor', max_length=32, verbose_name='Resolution Mode'),
        ),
        migrations.AddField(
            model_name='sanctuaryrequest',
            name='tradition_label',
            field=models.CharField(blank=True, help_text='e.g. Tradition-Specific Perspective', max_length=128, null=True, verbose_name='Tradition Label'),
        ),
        migrations.AddField(
            model_name='sanctuaryrequest',
            name='tradition_protected',
            field=models.BooleanField(default=False, help_text='Marks content as protected under tradition-specific theological perspective', verbose_name='Tradition-Specific Perspective'),
        ),
        migrations.AddField(
            model_name='sanctuaryrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated'),
        ),
        migrations.AddField(
            model_name='sanctuaryreview',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sanctuaryreview',
            name='is_primary_tradition_match',
            field=models.BooleanField(default=False, help_text='True if reviewer shares tradition with reported target', verbose_name='Primary Tradition Match'),
        ),
        migrations.AddField(
            model_name='sanctuaryreview',
            name='reminded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sanctuaryreview',
            name='replaced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sanctuaryreview',
            name='reviewed_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Reviewed At'),
        ),
        migrations.AlterField(
            model_name='sanctuaryoutcome',
            name='admin_assigned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Appeal Admin Assigned At'),
        ),
        migrations.AlterField(
            model_name='sanctuaryoutcome',
            name='admin_reviewed',
            field=models.BooleanField(default=False, verbose_name='Admin Reviewed Appeal'),
        ),
        migrations.AlterField(
            model_name='sanctuaryoutcome',
            name='assigned_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sanctuary_outcome_appeals', to=settings.AUTH_USER_MODEL, verbose_name='Appeal Admin'),
        ),
        migrations.AlterField(
            model_name='sanctuaryoutcome',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='sanctuaryoutcome',
            name='object_id',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='sanctuaryoutcome',
            name='outcome_status',
            field=models.CharField(choices=[('outcome_confirmed', 'Confirmed'), ('outcome_rejected', 'Rejected'), ('outcome_pending', 'Pending')], default='outcome_pending', max_length=32, verbose_name='Outcome Status'),
        ),
        migrations.AlterField(
            model_name='sanctuaryoutcome',
            name='sanctuary_requests',
            field=models.ManyToManyField(related_name='outcomes', to='sanctuary.sanctuaryrequest', verbose_name='Related Sanctuary Requests'),
        ),
        migrations.AlterField(
            model_name='sanctuaryrequest',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Additional Description'),
        ),
        migrations.AlterField(
            model_name='sanctuaryrequest',
            name='object_id',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='sanctuaryrequest',
            name='request_type',
            field=models.CharField(choices=[('content', 'Content'), ('account', 'Account'), ('organization', 'Organization'), ('messenger_group', 'Messenger Group')], max_length=32, verbose_name='Request Type'),
        ),
        migrations.AlterField(
            model_name='sanctuaryrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='pending', max_length=32, verbose_name='Request Status'),
        ),
        migrations.AlterField(
            model_name='sanctuaryreview',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Reviewer Comment'),
        ),
        migrations.AlterField(
            model_name='sanctuaryreview',
            name='review_status',
            field=models.CharField(choices=[('no_opinion', 'No Opinion'), ('violation_confirmed', 'Violation Confirmed'), ('violation_rejected', 'Violation Rejected')], default='no_opinion', max_length=32, verbose_name='Review Status'),
        ),
        migrations.AlterUniqueTogether(
            name='sanctuaryrequest',
            unique_together={('requester', 'content_type', 'object_id')},
        ),
        migrations.AlterUniqueTogether(
            name='sanctuaryreview',
            unique_together={('sanctuary_request', 'reviewer')},
        ),
        migrations.AddIndex(
            model_name='sanctuaryoutcome',
            index=models.Index(fields=['content_type', 'object_id'], name='sanctuary_s_content_fdad40_idx'),
        ),
        migrations.AddIndex(
            model_name='sanctuaryoutcome',
            index=models.Index(fields=['is_appealed', 'admin_reviewed'], name='sanctuary_s_is_appe_19fee5_idx'),
        ),
        migrations.AddIndex(
            model_name='sanctuaryoutcome',
            index=models.Index(fields=['appeal_deadline'], name='sanctuary_s_appeal__18e510_idx'),
        ),
        migrations.AddIndex(
            model_name='sanctuaryrequest',
            index=models.Index(fields=['content_type', 'object_id'], name='sanctuary_s_content_bec2c7_idx'),
        ),
        migrations.AddIndex(
            model_name='sanctuaryrequest',
            index=models.Index(fields=['status', 'resolution_mode'], name='sanctuary_s_status_271255_idx'),
        ),
        migrations.AddIndex(
            model_name='sanctuaryrequest',
            index=models.Index(fields=['created_at'], name='sanctuary_s_created_f90b5a_idx'),
        ),
        migrations.AddField(
            model_name='sanctuaryprotectionlabel',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='sanctuaryprotectionlabel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sanctuary_labels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sanctuaryprotectionlabel',
            name='outcome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protection_labels', to='sanctuary.sanctuaryoutcome'),
        ),
        migrations.RemoveField(
            model_name='sanctuaryrequest',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='sanctuaryrequest',
            name='request_date',
        ),
        migrations.RemoveField(
            model_name='sanctuaryreview',
            name='review_date',
        ),
        migrations.AddIndex(
            model_name='sanctuaryprotectionlabel',
            index=models.Index(fields=['content_type', 'object_id'], name='sanctuary_s_content_fe09c5_idx'),
        ),
        migrations.AddIndex(
            model_name='sanctuaryprotectionlabel',
            index=models.Index(fields=['label_type', 'is_active'], name='sanctuary_s_label_t_c7ab64_idx'),
        ),
        migrations.AddIndex(
            model_name='sanctuaryprotectionlabel',
            index=models.Index(fields=['expires_at'], name='sanctuary_s_expires_470408_idx'),
        ),
        migrations.AddConstraint(
            model_name='sanctuaryprotectionlabel',
            constraint=models.UniqueConstraint(fields=('content_type', 'object_id', 'label_type', 'is_active'), name='uniq_active_label_per_target_type'),
        ),
    ]
