# Generated by Django 4.2.4 on 2025-05-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanctuary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanctuaryoutcome',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sanctuaryrequest',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sanctuaryreview',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
