# Generated by Django 4.2.4 on 2025-12-21 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sanctuary', '0002_sanctuaryprotectionlabel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SanctuaryParticipantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_participant', models.BooleanField(default=False)),
                ('participant_opted_in_at', models.DateTimeField(blank=True, null=True)),
                ('participant_opted_out_at', models.DateTimeField(blank=True, null=True)),
                ('is_eligible', models.BooleanField(default=True)),
                ('eligible_changed_at', models.DateTimeField(blank=True, null=True)),
                ('eligible_reason', models.TextField(blank=True, null=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eligible_changed_by', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sanctuary_eligibility_changes', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sanctuary_participation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sanctuary Participant Profile',
                'verbose_name_plural': 'Sanctuary Participant Profiles',
            },
        ),
        migrations.CreateModel(
            name='SanctuaryParticipantAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('opt_in', 'Opt-in'), ('opt_out', 'Opt-out'), ('eligible_true', 'Eligible True'), ('eligible_false', 'Eligible False')], max_length=32)),
                ('reason', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, help_text='Admin/system actor (nullable for user self-actions).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sanctuary_participant_audits', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='sanctuary.sanctuaryparticipantprofile')),
            ],
            options={
                'verbose_name': 'Sanctuary Participant Audit',
                'verbose_name_plural': 'Sanctuary Participant Audits',
            },
        ),
        migrations.AddIndex(
            model_name='sanctuaryparticipantprofile',
            index=models.Index(fields=['is_participant', 'is_eligible'], name='sanctuary_s_is_part_806bc7_idx'),
        ),
        migrations.AddIndex(
            model_name='sanctuaryparticipantaudit',
            index=models.Index(fields=['created_at'], name='sanctuary_s_created_d57fab_idx'),
        ),
        migrations.AddIndex(
            model_name='sanctuaryparticipantaudit',
            index=models.Index(fields=['action'], name='sanctuary_s_action_9258d2_idx'),
        ),
    ]
