# Generated by Django 4.2.4 on 2025-12-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanctuary', '0003_sanctuaryparticipantprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanctuaryreview',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Reviewed At'),
        ),
    ]
