# Generated by Django 4.2.4 on 2026-08-05 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanctuary', '0004_alter_sanctuaryreview_reviewed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanctuaryrequest',
            name='reasons',
            field=models.JSONField(default=list, help_text='List of selected Sanctuary policy concern reason codes.', verbose_name='Sanctuary Request Reasons'),
        ),
        migrations.AlterField(
            model_name='sanctuaryrequest',
            name='report_count_snapshot',
            field=models.PositiveIntegerField(default=1, help_text='Active Sanctuary request count when this request was created.', verbose_name='Request Count Snapshot'),
        ),
    ]
