# Generated by Django 4.2.4 on 2026-08-05 02:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('sanctuary', '0005_alter_sanctuaryrequest_reasons_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SanctuarySafetyHold',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('content', 'Content'), ('account', 'Account'), ('organization', 'Organization'), ('messenger_group', 'Messenger Group')], db_index=True, default='content', max_length=32)),
                ('object_id', models.PositiveBigIntegerField()),
                ('reason_codes', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('active', 'Active'), ('released', 'Released'), ('confirmed', 'Confirmed')], db_index=True, default='active', max_length=16)),
                ('previous_is_active', models.BooleanField(blank=True, null=True)),
                ('previous_is_suspended', models.BooleanField(blank=True, null=True)),
                ('did_deactivate_target', models.BooleanField(default=False, help_text='True only when this hold changed target.is_active from True to False.')),
                ('applied_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ended_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('release_note', models.TextField(blank=True, default='')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanctuary_safety_holds', to='contenttypes.contenttype')),
                ('ended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ended_sanctuary_safety_holds', to=settings.AUTH_USER_MODEL)),
                ('supporting_requests', models.ManyToManyField(blank=True, related_name='safety_holds', to='sanctuary.sanctuaryrequest')),
                ('trigger_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_safety_holds', to='sanctuary.sanctuaryrequest')),
            ],
            options={
                'verbose_name': 'Sanctuary Safety Hold',
                'verbose_name_plural': 'Sanctuary Safety Holds',
                'ordering': ['-applied_at', '-id'],
                'indexes': [models.Index(fields=['content_type', 'object_id', 'status'], name='sanctuary_s_content_f58286_idx'), models.Index(fields=['status', 'applied_at'], name='sanctuary_s_status_16c7cc_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='sanctuarysafetyhold',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('content_type', 'object_id'), name='uniq_active_sanctuary_hold_per_target'),
        ),
    ]
