# Generated by Django 4.2.4 on 2026-08-05 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanctuary', '0006_sanctuarysafetyhold_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sanctuaryrequest',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='sanctuaryrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'under_review'])), fields=('requester', 'content_type', 'object_id'), name='uniq_open_sanctuary_request_per_user_target'),
        ),
    ]
