# Generated by Django 4.2.4 on 2026-02-24 23:23

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalEntity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('entity_type', models.CharField(choices=[('CHURCH', 'Church'), ('FOUNDATION', 'Foundation'), ('GOVERNMENT', 'Government'), ('MISSION', 'Mission Agency'), ('DONOR', 'Major Donor'), ('NETWORK', 'Network')], max_length=20)),
                ('country', models.CharField(max_length=2)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('denomination', models.CharField(blank=True, max_length=150)),
                ('primary_email', models.EmailField(blank=True, max_length=254)),
                ('primary_phone', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('notes_private', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LegalEntity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(choices=[('CA', 'Canada'), ('US', 'United States')], max_length=2)),
                ('legal_type', models.CharField(choices=[('CA_CHARITY', 'Canadian Registered Charity'), ('US_501C3', 'US 501(c)(3)'), ('NONPROFIT', 'Nonprofit Organization')], max_length=20)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('tax_id', models.CharField(blank=True, max_length=100)),
                ('base_currency', models.CharField(default='CAD', max_length=3)),
                ('active', models.BooleanField(default=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TagCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=90, unique=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tags', to='advancement.tagcategory')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StrategicScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mission_alignment', models.IntegerField(default=0)),
                ('funding_capacity', models.IntegerField(default=0)),
                ('access_level', models.IntegerField(default=0)),
                ('influence_value', models.IntegerField(default=0)),
                ('effort_required', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='strategic_score', to='advancement.externalentity')),
            ],
            options={
                'verbose_name': 'Strategic Score',
                'verbose_name_plural': 'Strategic Scores',
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('opportunity_type', models.CharField(choices=[('GRANT', 'Grant'), ('PARTNERSHIP', 'Partnership'), ('SPONSORSHIP', 'Sponsorship'), ('MISSION_SUPPORT', 'Mission Support')], max_length=30)),
                ('stage', models.CharField(choices=[('PROSPECT', 'Prospect'), ('LOI', 'LOI Submitted'), ('SUBMITTED', 'Application Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined'), ('CLOSED', 'Closed')], default='PROSPECT', max_length=20)),
                ('currency', models.CharField(max_length=3)),
                ('amount_requested', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('expected_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('submission_date', models.DateField(blank=True, null=True)),
                ('decision_date', models.DateField(blank=True, null=True)),
                ('probability_score', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='advancement.externalentity')),
                ('legal_entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='advancement.legalentity')),
                ('tags', models.ManyToManyField(blank=True, related_name='opportunities', to='advancement.tag')),
            ],
            options={
                'ordering': ['-deadline', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InteractionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interaction_type', models.CharField(choices=[('EMAIL', 'Email'), ('CALL', 'Call'), ('MEETING', 'Meeting'), ('FORM_SUBMISSION', 'Form Submission'), ('EVENT', 'Event'), ('OTHER', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('WAITING', 'Waiting'), ('DONE', 'Done')], default='OPEN', max_length=10)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('summary', models.TextField()),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('next_action', models.CharField(blank=True, max_length=255)),
                ('next_action_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advancement_assigned_interactions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advancement_created_interactions', to=settings.AUTH_USER_MODEL)),
                ('external_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='advancement.externalentity')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='externalentity',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='external_entities', to='advancement.tag'),
        ),
        migrations.CreateModel(
            name='Commitment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('committed_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(max_length=3)),
                ('exchange_rate_snapshot', models.DecimalField(decimal_places=6, default=Decimal('1.0'), max_digits=12)),
                ('base_currency_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('commitment_date', models.DateField()),
                ('status', models.CharField(choices=[('PLEDGED', 'Pledged'), ('CONFIRMED', 'Confirmed'), ('CONDITIONAL', 'Conditional'), ('FULFILLED', 'Fulfilled'), ('CANCELLED', 'Cancelled')], default='PLEDGED', max_length=20)),
                ('conditions', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to='advancement.opportunity')),
            ],
            options={
                'ordering': ['-commitment_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('category', 'name'), name='uniq_tag_category_name'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['stage'], name='advancement_stage_5b18ca_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['legal_entity'], name='advancement_legal_e_96dcd3_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['currency'], name='advancement_currenc_696e2b_idx'),
        ),
        migrations.AddIndex(
            model_name='externalentity',
            index=models.Index(fields=['entity_type'], name='advancement_entity__65d9af_idx'),
        ),
        migrations.AddIndex(
            model_name='externalentity',
            index=models.Index(fields=['country'], name='advancement_country_bb90f9_idx'),
        ),
        migrations.AddIndex(
            model_name='commitment',
            index=models.Index(fields=['status'], name='advancement_status_fcdd40_idx'),
        ),
        migrations.AddIndex(
            model_name='commitment',
            index=models.Index(fields=['currency'], name='advancement_currenc_b60822_idx'),
        ),
    ]
