# Generated by Django 4.2.4 on 2026-02-27 03:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advancement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalentity',
            name='primary_contact_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='externalentity',
            name='primary_contact_title',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advancement_assigned_opportunities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commitment',
            name='base_currency_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
