# Generated by Django 4.2.4 on 2026-08-29 00:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntitlementDefinition',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=140, unique=True)),
                ('name', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True)),
                ('value_type', models.CharField(choices=[('boolean', 'Boolean'), ('integer', 'Integer'), ('decimal', 'Decimal'), ('string', 'String'), ('json', 'JSON')], default='boolean', max_length=20)),
                ('default_value', models.JSONField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Entitlement Definition',
                'verbose_name_plural': 'Entitlement Definitions',
                'ordering': ('key',),
            },
        ),
        migrations.CreateModel(
            name='EntitlementGrant',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value', models.JSONField(default=True)),
                ('source', models.CharField(choices=[('admin', 'TownLIT Admin'), ('promotion', 'Promotion'), ('system', 'System'), ('support', 'Support')], db_index=True, default='system', max_length=20)),
                ('priority', models.PositiveSmallIntegerField(db_index=True, default=100)),
                ('reason', models.CharField(blank=True, max_length=1000, null=True)),
                ('starts_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Entitlement Grant',
                'verbose_name_plural': 'Entitlement Grants',
                'ordering': ('-priority', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='PlanEntitlement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value', models.JSONField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plan Entitlement',
                'verbose_name_plural': 'Plan Entitlements',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past Due'), ('paused', 'Paused'), ('canceled', 'Canceled'), ('expired', 'Expired')], db_index=True, max_length=20)),
                ('billing_interval', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], db_index=True, max_length=20)),
                ('provider_key', models.CharField(blank=True, db_index=True, max_length=40, null=True)),
                ('provider_subscription_reference', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('trial_started_at', models.DateTimeField(blank=True, null=True)),
                ('trial_ends_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('current_period_started_at', models.DateTimeField(blank=True, null=True)),
                ('current_period_ends_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('cancel_requested_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SubscriptionAccount',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('closed', 'Closed')], db_index=True, default='active', max_length=20)),
                ('default_currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('CAD', 'Canadian Dollar'), ('GBP', 'British Pound'), ('AUD', 'Australian Dollar'), ('JPY', 'Japanese Yen'), ('CNY', 'Chinese Yuan'), ('INR', 'Indian Rupee'), ('CHF', 'Swiss Franc'), ('BRL', 'Brazilian Real'), ('MXN', 'Mexican Peso'), ('RUB', 'Russian Ruble')], default='USD', max_length=3)),
                ('billing_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'verbose_name': 'Subscription Account',
                'verbose_name_plural': 'Subscription Accounts',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SubscriptionEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=80)),
                ('source', models.CharField(choices=[('admin', 'TownLIT Admin'), ('provider', 'Payment Provider'), ('service', 'TownLIT Service'), ('system', 'System')], db_index=True, default='system', max_length=20)),
                ('dedupe_key', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Subscription Event',
                'verbose_name_plural': 'Subscription Events',
                'ordering': ('-occurred_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('audience_key', models.SlugField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('trial_key', models.SlugField(blank=True, max_length=80, null=True)),
                ('trial_duration_days', models.PositiveSmallIntegerField(default=0)),
                ('is_public', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'ordering': ('sort_order', 'name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='SubscriptionTrialUsage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('trial_key', models.SlugField(max_length=80)),
                ('started_at', models.DateTimeField(db_index=True)),
                ('ends_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trial_usages', to='subscriptions.subscriptionaccount')),
                ('subscription', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='trial_usage', to='subscriptions.subscription')),
            ],
            options={
                'verbose_name': 'Subscription Trial Usage',
                'verbose_name_plural': 'Subscription Trial Usages',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlanPrice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('CAD', 'Canadian Dollar'), ('GBP', 'British Pound'), ('AUD', 'Australian Dollar'), ('JPY', 'Japanese Yen'), ('CNY', 'Chinese Yuan'), ('INR', 'Indian Rupee'), ('CHF', 'Swiss Franc'), ('BRL', 'Brazilian Real'), ('MXN', 'Mexican Peso'), ('RUB', 'Russian Ruble')], db_index=True, default='USD', max_length=3)),
                ('billing_interval', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], db_index=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('provider_key', models.CharField(blank=True, db_index=True, max_length=40, null=True)),
                ('provider_price_reference', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('valid_from', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='subscriptions.subscriptionplan')),
            ],
            options={
                'verbose_name': 'Subscription Plan Price',
                'verbose_name_plural': 'Subscription Plan Prices',
                'ordering': ('plan_id', 'currency', 'billing_interval', '-valid_from'),
            },
        ),
        migrations.AddIndex(
            model_name='subscriptionplan',
            index=models.Index(fields=['audience_key', 'is_active', 'is_public'], name='subscriptio_audienc_f61b53_idx'),
        ),
        migrations.AddField(
            model_name='subscriptionevent',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='subscriptions.subscriptionaccount'),
        ),
        migrations.AddField(
            model_name='subscriptionevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_events_performed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscriptionevent',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='subscriptions.subscription'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='subscriptions.subscriptionaccount'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='planentitlement',
            name='entitlement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_entitlements', to='subscriptions.entitlementdefinition'),
        ),
        migrations.AddField(
            model_name='planentitlement',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_entitlements', to='subscriptions.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='entitlementgrant',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entitlement_grants', to='subscriptions.subscriptionaccount'),
        ),
        migrations.AddField(
            model_name='entitlementgrant',
            name='entitlement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grants', to='subscriptions.entitlementdefinition'),
        ),
        migrations.AddField(
            model_name='entitlementgrant',
            name='granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_entitlement_grants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entitlementgrant',
            name='source_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entitlement_grants', to='subscriptions.subscription'),
        ),
        migrations.AddIndex(
            model_name='subscriptiontrialusage',
            index=models.Index(fields=['account', 'trial_key'], name='subscriptio_account_14c3c5_idx'),
        ),
        migrations.AddConstraint(
            model_name='subscriptiontrialusage',
            constraint=models.UniqueConstraint(fields=('account', 'trial_key'), name='subscriptions_unique_trial_usage_per_account_key'),
        ),
        migrations.AddIndex(
            model_name='subscriptionplanprice',
            index=models.Index(fields=['plan', 'currency', 'billing_interval', 'is_active'], name='subscriptio_plan_id_b0e156_idx'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionplanprice',
            constraint=models.CheckConstraint(check=models.Q(('amount__gte', 0)), name='subscriptions_plan_price_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionplanprice',
            constraint=models.CheckConstraint(check=models.Q(('valid_until__isnull', True), ('valid_until__gt', models.F('valid_from')), _connector='OR'), name='subscriptions_plan_price_valid_window'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionplanprice',
            constraint=models.UniqueConstraint(fields=('plan', 'currency', 'billing_interval', 'valid_from'), name='subscriptions_unique_plan_price_version'),
        ),
        migrations.AddIndex(
            model_name='subscriptionevent',
            index=models.Index(fields=['account', '-occurred_at'], name='subscriptio_account_72f368_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionevent',
            index=models.Index(fields=['subscription', '-occurred_at'], name='subscriptio_subscri_c1e3d6_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionevent',
            index=models.Index(fields=['event_type', '-occurred_at'], name='subscriptio_event_t_a33a10_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['account', 'status'], name='subscriptio_account_03e74d_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['plan', 'status'], name='subscriptio_plan_id_f7cbce_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['provider_key', 'provider_subscription_reference'], name='subscriptio_provide_c8af43_idx'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('trialing', 'active', 'past_due', 'paused'))), fields=('account',), name='subscriptions_one_current_subscription_per_account'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(check=models.Q(('trial_started_at__isnull', True), ('trial_ends_at__isnull', True), ('trial_ends_at__gt', models.F('trial_started_at')), _connector='OR'), name='subscriptions_valid_trial_window'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(check=models.Q(('current_period_started_at__isnull', True), ('current_period_ends_at__isnull', True), ('current_period_ends_at__gt', models.F('current_period_started_at')), _connector='OR'), name='subscriptions_valid_current_period_window'),
        ),
        migrations.AddConstraint(
            model_name='planentitlement',
            constraint=models.UniqueConstraint(fields=('plan', 'entitlement'), name='subscriptions_unique_plan_entitlement'),
        ),
        migrations.AddIndex(
            model_name='entitlementgrant',
            index=models.Index(fields=['account', 'entitlement', 'is_active'], name='subscriptio_account_6dcda6_idx'),
        ),
        migrations.AddIndex(
            model_name='entitlementgrant',
            index=models.Index(fields=['account', 'priority', 'is_active'], name='subscriptio_account_d4e63f_idx'),
        ),
        migrations.AddConstraint(
            model_name='entitlementgrant',
            constraint=models.CheckConstraint(check=models.Q(('ends_at__isnull', True), ('ends_at__gt', models.F('starts_at')), _connector='OR'), name='subscriptions_entitlement_grant_valid_window'),
        ),
    ]
