# Generated by Django 4.2.4 on 2026-08-29 14:57

import apps.subscriptions.models.entitlement
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitlementdefinition',
            name='default_value',
            field=models.JSONField(default=apps.subscriptions.models.entitlement._default_false),
        ),
        migrations.AlterField(
            model_name='entitlementgrant',
            name='value',
            field=models.JSONField(default=apps.subscriptions.models.entitlement._default_true),
        ),
        migrations.AlterField(
            model_name='planentitlement',
            name='value',
            field=models.JSONField(default=apps.subscriptions.models.entitlement._default_true),
        ),
    ]
