# Generated by Django 4.2.4 on 2026-08-29 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_alter_entitlementdefinition_default_value_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscription',
            name='subscriptions_one_current_subscription_per_account',
        ),
        migrations.AddField(
            model_name='subscription',
            name='current_slot',
            field=models.PositiveSmallIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('account', 'current_slot'), name='subscriptions_one_current_subscription_per_account'),
        ),
    ]
