# Generated by Django 4.2.4 on 2026-01-28 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoTranscript',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('object_id', models.PositiveBigIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('source_language', models.CharField(blank=True, default='', max_length=10)),
                ('stt_engine', models.CharField(blank=True, default='openai', max_length=30)),
                ('stt_model', models.CharField(blank=True, default='', max_length=50)),
                ('error', models.TextField(blank=True, default='')),
                ('full_text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='TranscriptSegment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('idx', models.PositiveIntegerField(db_index=True)),
                ('start_ms', models.PositiveIntegerField()),
                ('end_ms', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='subtitles.videotranscript')),
            ],
        ),
        migrations.CreateModel(
            name='SubtitleTrack',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('target_language', models.CharField(db_index=True, max_length=10)),
                ('fmt', models.CharField(choices=[('vtt', 'Vtt'), ('srt', 'Srt')], default='vtt', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('engine', models.CharField(blank=True, default='aws+llm', max_length=30)),
                ('prompt_version', models.CharField(blank=True, default='', max_length=20)),
                ('llm_model', models.CharField(blank=True, default='', max_length=50)),
                ('is_humanized', models.BooleanField(db_index=True, default=False)),
                ('content', models.TextField(blank=True, default='')),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitle_tracks', to='subtitles.videotranscript')),
            ],
        ),
        migrations.AddConstraint(
            model_name='videotranscript',
            constraint=models.UniqueConstraint(fields=('content_type', 'object_id'), name='uniq_video_transcript_per_object'),
        ),
        migrations.AddIndex(
            model_name='transcriptsegment',
            index=models.Index(fields=['transcript', 'idx'], name='segment_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='transcriptsegment',
            constraint=models.UniqueConstraint(fields=('transcript', 'idx'), name='uniq_transcript_segment_idx'),
        ),
        migrations.AddConstraint(
            model_name='subtitletrack',
            constraint=models.UniqueConstraint(fields=('transcript', 'target_language', 'fmt'), name='uniq_subtitle_track_lang_fmt'),
        ),
    ]
