# Generated by Django 4.2.4 on 2026-01-29 04:55

from django.db import migrations, models
import utils.common.utils
import validators.mediaValidators.audio_validators
import validators.security_validators


class Migration(migrations.Migration):

    dependencies = [
        ('subtitles', '0002_videotranscript_stt_audio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videotranscript',
            name='stt_audio',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.audio_validators.validate_audio_file, validators.security_validators.validate_no_executable_file], verbose_name='STT Audio Source'),
        ),
    ]
