# Generated by Django 4.2.4 on 2026-01-29 20:27

from django.db import migrations, models
import django.db.models.deletion
import utils.common.utils
import validators.mediaValidators.audio_validators
import validators.security_validators


class Migration(migrations.Migration):

    dependencies = [
        ('subtitles', '0003_alter_videotranscript_stt_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videotranscript',
            name='stt_audio',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.audio_validators.validate_audio_file, validators.security_validators.validate_no_executable_file], verbose_name='STT Audio Source'),
        ),
        migrations.CreateModel(
            name='VoiceTrack',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('target_language', models.CharField(db_index=True, max_length=10)),
                ('provider', models.CharField(default='openai', max_length=30)),
                ('voice_id', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('audio', models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.audio_validators.validate_audio_file, validators.security_validators.validate_no_executable_file])),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subtitle_track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_tracks', to='subtitles.subtitletrack')),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_tracks', to='subtitles.videotranscript')),
            ],
        ),
        migrations.AddConstraint(
            model_name='voicetrack',
            constraint=models.UniqueConstraint(fields=('subtitle_track', 'provider', 'voice_id'), name='uniq_voice_per_subtitle_provider'),
        ),
    ]
