# Generated by Django 4.2.4 on 2026-02-03 05:34

from django.db import migrations, models
import utils.common.utils
import validators.mediaValidators.audio_validators
import validators.security_validators


class Migration(migrations.Migration):

    dependencies = [
        ('subtitles', '0004_alter_videotranscript_stt_audio_voicetrack_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicetrack',
            name='spoken_text',
            field=models.TextField(blank=True, default='', help_text='Humanized text optimized for speech (TTS)'),
        ),
        migrations.AlterField(
            model_name='videotranscript',
            name='stt_audio',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.audio_validators.validate_audio_file, validators.security_validators.validate_no_executable_file], verbose_name='STT Audio Source'),
        ),
        migrations.AlterField(
            model_name='voicetrack',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.audio_validators.validate_audio_file, validators.security_validators.validate_no_executable_file]),
        ),
    ]
