# Generated by Django 4.2.4 on 2026-06-02 23:40

from django.db import migrations, models
import utils.common.utils
import validators.mediaValidators.audio_validators
import validators.security_validators


class Migration(migrations.Migration):

    dependencies = [
        ('subtitles', '0019_alter_videotranscript_stt_audio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videotranscript',
            name='ai_processing_allowed',
            field=models.BooleanField(db_index=True, default=False, help_text='Allows expensive subtitle/translation/voice generation.'),
        ),
        migrations.AddField(
            model_name='videotranscript',
            name='content_review_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videotranscript',
            name='content_review_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='videotranscript',
            name='content_review_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_review', 'Needs review')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='videotranscript',
            name='content_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videotranscript',
            name='detected_content_type',
            field=models.CharField(choices=[('personal_testimony', 'Personal testimony'), ('worship_song', 'Worship song'), ('music', 'Music'), ('teaching', 'Teaching'), ('prayer', 'Prayer'), ('other', 'Other'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=40),
        ),
        migrations.AlterField(
            model_name='videotranscript',
            name='stt_audio',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.audio_validators.validate_audio_file, validators.security_validators.validate_no_executable_file], verbose_name='STT Audio Source'),
        ),
        migrations.AlterField(
            model_name='voicetrack',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.audio_validators.validate_audio_file, validators.security_validators.validate_no_executable_file]),
        ),
    ]
