# apps/organizations/modules/church/views/__init__.py
#
# TownLIT
#
# Created by Hossein Sakkaki on 2026-09-08.
# Last Update by Hossein Sakkaki on 2026-09-08.
#

from .attendance import (
    ChurchAttendanceCheckInView,
    ChurchAttendanceCloseView,
    ChurchAttendanceGuestCountsView,
    ChurchAttendanceRecordCheckOutView,
    ChurchAttendanceSessionDetailView,
    ChurchAttendanceSessionsView,
)
from .bootstrap import ChurchBootstrapView
from .congregation import (
    ChurchCongregantDetailView,
    ChurchCongregantDirectoryVisibilityView,
    ChurchCongregantSyncOfficialMembershipView,
    ChurchCongregantsView,
    ChurchExternalCongregantCreateView,
    ChurchGuestCongregantCreateView,
    ChurchHouseholdDetailView,
    ChurchHouseholdMembershipRemoveView,
    ChurchHouseholdMembersView,
    ChurchHouseholdsView,
    ChurchMemberCongregantCreateView,
    ChurchMemberDirectoryView,
)
from .gatherings import (
    ChurchGatheringCancelView,
    ChurchGatheringCompleteView,
    ChurchGatheringDetailView,
    ChurchGatheringsView,
    ChurchGatheringSeriesDetailView,
    ChurchGatheringSeriesMaterializeView,
    ChurchGatheringSeriesView,
)
from .operations import (
    ChurchServicePlanCancelView,
    ChurchServicePlanCompleteView,
    ChurchServicePlanDetailView,
    ChurchServicePlanItemDetailView,
    ChurchServicePlanItemsView,
    ChurchServicePlanPublishView,
    ChurchServicePlanReferencesView,
    ChurchServicePlansView,
    ChurchServingAssignmentCancelView,
    ChurchServingAssignmentCheckInView,
    ChurchServingAssignmentCheckOutView,
    ChurchServingAssignmentCompleteView,
    ChurchServingAssignmentDetailView,
    ChurchServingAssignmentRespondView,
    ChurchServingAssignmentsView,
    ChurchServingTeamDetailView,
    ChurchServingTeamMembersView,
    ChurchServingTeamMembershipRemoveView,
    ChurchServingTeamsView,
)
from .pastoral_care import (
    ChurchPastoralCareAssignmentEndView,
    ChurchPastoralCareAssignmentsView,
    ChurchPastoralCareCaseDetailView,
    ChurchPastoralCareCasesView,
    ChurchPastoralCareCloseView,
    ChurchPastoralCareContactsView,
    ChurchPastoralCareHoldView,
    ChurchPastoralCareNotesView,
    ChurchPastoralCareReferencesView,
    ChurchPastoralCareReopenView,
)
from .resources import (
    ChurchResourceDetailView,
    ChurchResourceReservationCancelView,
    ChurchResourceReservationCompleteView,
    ChurchResourceReservationsView,
    ChurchResourcesView,
)
from .workspace import (
    ChurchCampusArchiveView,
    ChurchCampusDetailView,
    ChurchCampusPrimaryView,
    ChurchCampusesView,
    ChurchLeadershipDetailView,
    ChurchLeadershipEndView,
    ChurchLeadershipView,
    ChurchMinistriesView,
    ChurchMinistryDetailView,
    ChurchWorkspaceView,
)

__all__ = [
    "ChurchAttendanceCheckInView",
    "ChurchAttendanceCloseView",
    "ChurchAttendanceGuestCountsView",
    "ChurchAttendanceRecordCheckOutView",
    "ChurchAttendanceSessionDetailView",
    "ChurchAttendanceSessionsView",
    "ChurchBootstrapView",
    "ChurchGatheringCancelView",
    "ChurchGatheringCompleteView",
    "ChurchGatheringDetailView",
    "ChurchGatheringsView",
    "ChurchGatheringSeriesDetailView",
    "ChurchGatheringSeriesMaterializeView",
    "ChurchGatheringSeriesView",
    "ChurchServicePlanCancelView",
    "ChurchServicePlanCompleteView",
    "ChurchServicePlanDetailView",
    "ChurchServicePlanItemDetailView",
    "ChurchServicePlanItemsView",
    "ChurchServicePlanPublishView",
    "ChurchServicePlanReferencesView",
    "ChurchServicePlansView",
    "ChurchServingAssignmentCancelView",
    "ChurchServingAssignmentCheckInView",
    "ChurchServingAssignmentCheckOutView",
    "ChurchServingAssignmentCompleteView",
    "ChurchServingAssignmentDetailView",
    "ChurchServingAssignmentRespondView",
    "ChurchServingAssignmentsView",
    "ChurchServingTeamDetailView",
    "ChurchServingTeamMembersView",
    "ChurchServingTeamMembershipRemoveView",
    "ChurchServingTeamsView",
    "ChurchPastoralCareAssignmentEndView",
    "ChurchPastoralCareAssignmentsView",
    "ChurchPastoralCareCaseDetailView",
    "ChurchPastoralCareCasesView",
    "ChurchPastoralCareCloseView",
    "ChurchPastoralCareContactsView",
    "ChurchPastoralCareHoldView",
    "ChurchPastoralCareNotesView",
    "ChurchPastoralCareReferencesView",
    "ChurchPastoralCareReopenView",
    "ChurchResourceDetailView",
    "ChurchResourceReservationCancelView",
    "ChurchResourceReservationCompleteView",
    "ChurchResourceReservationsView",
    "ChurchResourcesView",
    "ChurchCampusArchiveView",
    "ChurchCampusDetailView",
    "ChurchCampusPrimaryView",
    "ChurchCampusesView",
    "ChurchLeadershipDetailView",
    "ChurchLeadershipEndView",
    "ChurchLeadershipView",
    "ChurchMinistriesView",
    "ChurchMinistryDetailView",
    "ChurchCongregantDetailView",
    "ChurchCongregantDirectoryVisibilityView",
    "ChurchCongregantSyncOfficialMembershipView",
    "ChurchCongregantsView",
    "ChurchExternalCongregantCreateView",
    "ChurchGuestCongregantCreateView",
    "ChurchHouseholdDetailView",
    "ChurchHouseholdMembershipRemoveView",
    "ChurchHouseholdMembersView",
    "ChurchHouseholdsView",
    "ChurchMemberCongregantCreateView",
    "ChurchMemberDirectoryView",
    "ChurchWorkspaceView",
]

from .teaching import (
    ChurchTeachingContentArchiveView,
    ChurchTeachingContentDetailView,
    ChurchTeachingContentPublishView,
    ChurchTeachingContentsView,
    ChurchTeachingReferencesView,
    ChurchTeachingSeriesArchiveView,
    ChurchTeachingSeriesDetailView,
    ChurchTeachingSeriesView,
)

__all__ += [
    "ChurchTeachingContentArchiveView",
    "ChurchTeachingContentDetailView",
    "ChurchTeachingContentPublishView",
    "ChurchTeachingContentsView",
    "ChurchTeachingReferencesView",
    "ChurchTeachingSeriesArchiveView",
    "ChurchTeachingSeriesDetailView",
    "ChurchTeachingSeriesView",
]
