# Generated by Django 4.2.4 on 2026-01-19 21:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationCache',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('object_id', models.PositiveBigIntegerField()),
                ('field_name', models.CharField(max_length=50, verbose_name='Source Field Name')),
                ('source_language', models.CharField(max_length=5, verbose_name='Detected Source Language')),
                ('target_language', models.CharField(max_length=5, verbose_name='Target Language')),
                ('source_text_hash', models.CharField(help_text='Used for invalidation on content edit.', max_length=64, verbose_name='Hash of Source Text')),
                ('translated_text', models.TextField(verbose_name='Translated Text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation_caches', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Translation Cache',
                'verbose_name_plural': 'Translation Caches',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='translation_obj_idx'), models.Index(fields=['target_language'], name='translation_target_lang_idx'), models.Index(fields=['last_accessed_at'], name='translation_last_access_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='translationcache',
            constraint=models.UniqueConstraint(fields=('content_type', 'object_id', 'field_name', 'target_language', 'source_text_hash'), name='uniq_translation_cache_entry'),
        ),
    ]
