# Generated by Django 4.2.4 on 2026-01-21 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationcache',
            name='engine',
            field=models.CharField(db_index=True, default='aws', help_text='aws | llm | aws+llm', max_length=20),
        ),
        migrations.AddField(
            model_name='translationcache',
            name='humanized_at',
            field=models.DateTimeField(blank=True, help_text='When humanization was applied.', null=True),
        ),
        migrations.AddField(
            model_name='translationcache',
            name='is_humanized',
            field=models.BooleanField(db_index=True, default=False, help_text='True if LLM improved tone/wording.'),
        ),
        migrations.AddField(
            model_name='translationcache',
            name='llm_model',
            field=models.CharField(blank=True, default='', help_text='Which LLM model produced the final text.', max_length=50),
        ),
        migrations.AddField(
            model_name='translationcache',
            name='prompt_version',
            field=models.CharField(blank=True, default='', help_text='Prompt version for reproducibility.', max_length=20),
        ),
        migrations.AddIndex(
            model_name='translationcache',
            index=models.Index(fields=['is_humanized'], name='translation_humanized_idx'),
        ),
    ]
