# Generated by Django 4.2.4 on 2026-07-15 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0002_translationcache_engine_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationKeyGuidance',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('slug', models.CharField(choices=[('backup', 'Create recovery passphrase'), ('restore', 'Restore encryption key'), ('resolve', 'Choose encryption setup option')], db_index=True, max_length=32, unique=True)),
                ('title', models.CharField(max_length=160)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Conversation Key Guidance',
                'verbose_name_plural': 'Conversation Key Guidance',
            },
        ),
    ]
