# Generated by Django 4.2.4 on 2025-05-26 17:27

import apps.communication.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('ignore_unsubscribe', models.BooleanField(default=False, help_text='If enabled, email will be sent even to users who unsubscribed.', verbose_name='Ignore Unsubscribed Users')),
                ('custom_html', apps.communication.models.LongRichTextUploadingField(blank=True, verbose_name='Custom Email Body (Optional)')),
                ('subject', models.CharField(max_length=255)),
                ('target_group', models.CharField(choices=[('all_active', 'All Active Users'), ('believer', 'Label: Believers'), ('seeker', 'Label: Seekers'), ('prefer_not_to_say', 'Label: Prefer Not to Say'), ('seeker_and_prefer_not', 'Label: Seekers + Prefer Not to Say'), ('admins', 'TownLIT Admins'), ('deleted_members', 'Deleted Member Accounts'), ('deleted_non_members', 'Deleted Non-Member Accounts'), ('suspended', 'Suspended Accounts'), ('sanctuary_participants', 'Sanctuary-Eligible Members'), ('privacy_enabled', 'Members with Privacy Enabled'), ('unverified_identity', 'Members with Unverified Identity'), ('reengagement', 'Previously Unsubscribed Users (Re-engagement Campaign)')], default='all_active', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('scheduled', 'Scheduled')], default='draft', max_length=20)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('recipients', models.ManyToManyField(blank=True, help_text='Optional: Select specific users to send this email to. If filled, target group will be ignored.', related_name='manual_campaigns', to=settings.AUTH_USER_MODEL, verbose_name='Specific Recipients')),
            ],
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Template Name')),
                ('layout', models.CharField(choices=[('base_email', 'System Email (Security, Activation, etc.)'), ('base_site', 'Campaign/Newsletter (Invitation, Updates)')], default='base_site', help_text='Choose the layout this template will use when rendered in emails.', max_length=30, verbose_name='Layout Template')),
                ('subject_template', models.CharField(max_length=255, verbose_name='Subject')),
                ('body_template', apps.communication.models.LongRichTextUploadingField(verbose_name='HTML Body')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UnsubscribedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unsubscribed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communication.emailcampaign')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalEmailCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Campaign Title')),
                ('subject', models.CharField(max_length=255, verbose_name='Email Subject')),
                ('html_body', apps.communication.models.LongRichTextUploadingField(verbose_name='Custom Email Body (Optional)')),
                ('csv_file', models.FileField(upload_to='external_campaigns/', verbose_name='CSV File with Emails')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Is Sent')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Sent At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='communication.emailtemplate')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('family', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('nation', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('recognize', models.CharField(blank=True, max_length=100)),
                ('registre_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_unsubscribed', models.BooleanField(default=False)),
                ('became_user', models.BooleanField(default=False)),
                ('became_user_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_after_signup', models.BooleanField(default=False)),
                ('deleted_after_signup_at', models.DateTimeField(blank=True, null=True)),
                ('source_campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='communication.externalemailcampaign')),
            ],
            options={
                'verbose_name': 'External Contact',
                'verbose_name_plural': 'External Contacts',
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('opened', models.BooleanField(default=False)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked', models.BooleanField(default=False)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='communication.emailcampaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='communication.emailtemplate'),
        ),
        migrations.CreateModel(
            name='DraftCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='draft', to='communication.emailcampaign')),
            ],
        ),
    ]
