# Generated by Django 4.2.4 on 2025-05-09 18:27

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcampaign',
            name='custom_html',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Custom Email Body (Optional)'),
        ),
    ]
