# Generated by Django 4.2.4 on 2025-08-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='layout',
            field=models.CharField(choices=[('base_email', 'System Email (Security, Activation, etc.)_Base Email'), ('base_site', 'Campaign/Newsletter (Invitation, Updates)_Base Site')], default='base_site', help_text='Choose the layout this template will use when rendered in emails.', max_length=30, verbose_name='Layout Template'),
        ),
    ]
