# Generated by Django 4.2.4 on 2025-12-05 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_alter_emailtemplate_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='tag',
            field=models.CharField(blank=True, help_text='Optional tag for categorizing campaigns (e.g., Christmas 2024)', max_length=100, null=True, verbose_name='Campaign Tag'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='test_email',
            field=models.EmailField(blank=True, help_text='If provided, this email will receive a test message.', max_length=254, null=True, verbose_name='Test Email (Optional)'),
        ),
    ]
