# Generated by Django 4.2.4 on 2025-05-09 20:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communication', '0002_alter_emailcampaign_custom_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='ignore_unsubscribe',
            field=models.BooleanField(default=False, help_text='If enabled, email will be sent even to users who unsubscribed.', verbose_name='Ignore Unsubscribed Users'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='recipients',
            field=models.ManyToManyField(blank=True, help_text='Optional: Select specific users to send this email to. If filled, target group will be ignored.', related_name='manual_campaigns', to=settings.AUTH_USER_MODEL, verbose_name='Specific Recipients'),
        ),
    ]
