# Generated by Django 4.2.4 on 2025-12-19 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0003_emailcampaign_tag_emailcampaign_test_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcampaign',
            name='target_group',
            field=models.CharField(choices=[('all_active', 'All Active Users'), ('believer', 'Label: Believers'), ('seeker', 'Label: Seekers'), ('prefer_not_to_say', 'Label: Prefer Not to Say'), ('seeker_and_prefer_not', 'Label: Seekers + Prefer Not to Say'), ('admins', 'TownLIT Admins'), ('deleted_members', 'Deleted Member Accounts'), ('deleted_non_members', 'Deleted Non-Member Accounts'), ('suspended', 'Suspended Accounts'), ('sanctuary_participants', 'Sanctuary-Eligible Members'), ('privacy_enabled', 'Members with Privacy Enabled'), ('unverified_identity', 'Members with Unverified Identity'), ('reengagement', 'Previously Unsubscribed Users (Re-engagement Campaign)'), ('access_requests', 'Pending Access Requests (pre-registration users)'), ('unused_invite_access_requests', 'Access Requests with Unused Invite Codes')], default='all_active', max_length=50, verbose_name='Target Group'),
        ),
    ]
