# Generated by Django 4.2.4 on 2025-05-09 23:25

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0003_emailcampaign_ignore_unsubscribe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='body_template',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='HTML Body'),
        ),
    ]
