# Generated by Django 4.2.4 on 2026-08-20 05:35

import ckeditor_uploader.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communication', '0004_alter_emailcampaign_target_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAudience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=140, unique=True, verbose_name='Audience Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('kind', models.CharField(choices=[('dynamic', 'Dynamic Audience'), ('manual', 'Manual Audience'), ('hybrid', 'Rules + Manual Selection'), ('preset', 'TownLIT Preset')], db_index=True, default='dynamic', max_length=20, verbose_name='Audience Type')),
                ('match_type', models.CharField(choices=[('all', 'Match All Rules'), ('any', 'Match Any Rule')], default='all', max_length=10, verbose_name='Rule Matching')),
                ('preset_key', models.CharField(blank=True, choices=[('all_active', 'All Active Users'), ('believer', 'Label: Believers'), ('seeker', 'Label: Seekers'), ('prefer_not_to_say', 'Label: Prefer Not to Say'), ('seeker_and_prefer_not', 'Label: Seekers + Prefer Not to Say'), ('admins', 'TownLIT Admins'), ('deleted_members', 'Deleted Member Accounts'), ('deleted_non_members', 'Deleted Non-Member Accounts'), ('suspended', 'Suspended Accounts'), ('sanctuary_participants', 'Sanctuary-Eligible Members'), ('privacy_enabled', 'Members with Privacy Enabled'), ('unverified_identity', 'Members with Unverified Identity'), ('townlit_verified', 'TownLIT Verified Members'), ('townlit_not_verified', 'TownLIT Not Yet Verified Members'), ('reengagement', 'Previously Unsubscribed Users'), ('access_requests', 'Legacy: Pending Access Requests'), ('unused_invite_access_requests', 'Legacy: Access Requests with Unused Invite Codes')], default='', help_text='Optional built-in audience preset.', max_length=50, verbose_name='TownLIT Preset')),
                ('respect_unsubscribe', models.BooleanField(default=True, verbose_name='Respect Unsubscribe Preferences')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('estimated_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Estimated Recipients')),
                ('last_estimated_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Estimated At')),
            ],
            options={
                'verbose_name': 'Email Audience',
                'verbose_name_plural': 'Email Audiences',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmailAudienceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('field', models.CharField(choices=[('is_active', 'Account Active'), ('is_member', 'Member'), ('is_admin', 'Administrator'), ('is_suspended', 'Suspended'), ('label', 'Account Label'), ('country', 'Country'), ('city', 'City'), ('primary_language', 'Primary Language'), ('secondary_language', 'Secondary Language'), ('register_date', 'Registration Date')], max_length=40, verbose_name='Field')),
                ('operator', models.CharField(choices=[('equals', 'Equals'), ('not_equals', 'Does Not Equal'), ('in', 'Is One Of'), ('not_in', 'Is Not One Of'), ('true', 'Is True'), ('false', 'Is False'), ('contains', 'Contains'), ('before', 'Before'), ('after', 'After')], max_length=20, verbose_name='Operator')),
                ('value', models.JSONField(blank=True, null=True, verbose_name='Value')),
                ('negate', models.BooleanField(default=False, verbose_name='Negate Rule')),
                ('sort_order', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Sort Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Enabled')),
            ],
            options={
                'verbose_name': 'Email Audience Rule',
                'verbose_name_plural': 'Email Audience Rules',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EmailCampaignBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('block_type', models.CharField(choices=[('hero', 'Hero'), ('text', 'Text'), ('image', 'Image'), ('button', 'Button'), ('quote', 'Quote'), ('callout', 'Callout'), ('divider', 'Divider'), ('spacer', 'Spacer'), ('two_column', 'Two Columns'), ('social_links', 'Social Links'), ('custom_html', 'Custom HTML')], max_length=30, verbose_name='Block Type')),
                ('name', models.CharField(blank=True, max_length=120, verbose_name='Internal Block Name')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Block Content')),
                ('styles', models.JSONField(blank=True, default=dict, verbose_name='Block Styles')),
                ('sort_order', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Sort Order')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Enabled')),
            ],
            options={
                'verbose_name': 'Email Campaign Block',
                'verbose_name_plural': 'Email Campaign Blocks',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EmailCampaignDailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Date')),
                ('sent', models.PositiveIntegerField(default=0)),
                ('delivered', models.PositiveIntegerField(default=0)),
                ('failed', models.PositiveIntegerField(default=0)),
                ('bounced', models.PositiveIntegerField(default=0)),
                ('complaints', models.PositiveIntegerField(default=0)),
                ('opens', models.PositiveIntegerField(default=0)),
                ('unique_opens', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('unique_clicks', models.PositiveIntegerField(default=0)),
                ('unsubscribes', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Email Campaign Daily Metric',
                'verbose_name_plural': 'Email Campaign Daily Metrics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='EmailEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('bounced', 'Bounced'), ('complained', 'Complaint'), ('unsubscribed', 'Unsubscribed'), ('failed', 'Failed')], db_index=True, max_length=20, verbose_name='Event Type')),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Occurred At')),
                ('url', models.URLField(blank=True, max_length=2000, verbose_name='Clicked URL')),
                ('provider_event_id', models.CharField(blank=True, max_length=255, verbose_name='Provider Event ID')),
                ('dedupe_key', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Deduplication Key')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('ip_hash', models.CharField(blank=True, max_length=128, verbose_name='IP Hash')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Event Metadata')),
            ],
            options={
                'verbose_name': 'Email Event',
                'verbose_name_plural': 'Email Events',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailSubscriptionPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='Email Address')),
                ('status', models.CharField(choices=[('subscribed', 'Subscribed'), ('unsubscribed', 'Unsubscribed')], db_index=True, default='subscribed', max_length=20, verbose_name='Status')),
                ('source', models.CharField(choices=[('account', 'Account Settings'), ('email_link', 'Email Link'), ('admin', 'Administrator'), ('import', 'Imported'), ('system', 'System')], default='account', max_length=20, verbose_name='Preference Source')),
                ('subscribed_at', models.DateTimeField(blank=True, null=True, verbose_name='Subscribed At')),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True, verbose_name='Unsubscribed At')),
            ],
            options={
                'verbose_name': 'Email Subscription Preference',
                'verbose_name_plural': 'Email Subscription Preferences',
                'ordering': ['email', 'topic_id'],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplateBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('block_type', models.CharField(choices=[('hero', 'Hero'), ('text', 'Text'), ('image', 'Image'), ('button', 'Button'), ('quote', 'Quote'), ('callout', 'Callout'), ('divider', 'Divider'), ('spacer', 'Spacer'), ('two_column', 'Two Columns'), ('social_links', 'Social Links'), ('custom_html', 'Custom HTML')], max_length=30, verbose_name='Block Type')),
                ('name', models.CharField(blank=True, max_length=120, verbose_name='Internal Block Name')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Block Content')),
                ('styles', models.JSONField(blank=True, default=dict, verbose_name='Block Styles')),
                ('sort_order', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Sort Order')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Enabled')),
            ],
            options={
                'verbose_name': 'Email Template Block',
                'verbose_name_plural': 'Email Template Blocks',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EmailTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Theme Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('layout', models.CharField(choices=[('base_email', 'System Email'), ('base_site', 'Campaign / Newsletter')], default='base_site', max_length=30, verbose_name='Base Layout')),
                ('logo_url', models.URLField(blank=True, verbose_name='Logo URL')),
                ('background_color', models.CharField(default='#000000', max_length=20, verbose_name='Background Color')),
                ('surface_color', models.CharField(default='#F9F8F4', max_length=20, verbose_name='Content Background')),
                ('text_color', models.CharField(default='#2B2C30', max_length=20, verbose_name='Text Color')),
                ('heading_color', models.CharField(default='#0F52BA', max_length=20, verbose_name='Heading Color')),
                ('accent_color', models.CharField(default='#0F52BA', max_length=20, verbose_name='Accent Color')),
                ('secondary_accent_color', models.CharField(default='#F6C860', max_length=20, verbose_name='Secondary Accent')),
                ('muted_color', models.CharField(default='#7A7A7A', max_length=20, verbose_name='Muted Text Color')),
                ('button_text_color', models.CharField(default='#FFFFFF', max_length=20, verbose_name='Button Text Color')),
                ('font_family', models.CharField(default='Lato, Noto Sans, Helvetica, Segoe UI, sans-serif', max_length=255, verbose_name='Font Stack')),
                ('content_width', models.PositiveSmallIntegerField(default=600, validators=[django.core.validators.MinValueValidator(320), django.core.validators.MaxValueValidator(720)], verbose_name='Content Width')),
                ('border_radius', models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MaxValueValidator(40)], verbose_name='Border Radius')),
                ('style_config', models.JSONField(blank=True, default=dict, verbose_name='Advanced Style Configuration')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('is_default', models.BooleanField(db_index=True, default=False, verbose_name='Default Theme')),
            ],
            options={
                'verbose_name': 'Email Theme',
                'verbose_name_plural': 'Email Themes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmailTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Topic Name')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('allow_unsubscribe', models.BooleanField(default=True, verbose_name='User Can Unsubscribe')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('sort_order', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Sort Order')),
            ],
            options={
                'verbose_name': 'Email Topic',
                'verbose_name_plural': 'Email Topics',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='draftcampaign',
            options={'ordering': ['-last_edited'], 'verbose_name': 'Legacy Draft Campaign', 'verbose_name_plural': 'Legacy Draft Campaigns'},
        ),
        migrations.AlterModelOptions(
            name='emaillog',
            options={'ordering': ['-sent_at'], 'verbose_name': 'Email Delivery', 'verbose_name_plural': 'Email Deliveries'},
        ),
        migrations.AlterModelOptions(
            name='emailtemplate',
            options={'ordering': ['-updated_at', '-created_at'], 'verbose_name': 'Email Template', 'verbose_name_plural': 'Email Templates'},
        ),
        migrations.AlterModelOptions(
            name='externalemailcampaign',
            options={'ordering': ['-created_at'], 'verbose_name': 'Legacy External Email Campaign', 'verbose_name_plural': 'Legacy External Email Campaigns'},
        ),
        migrations.AlterModelOptions(
            name='scheduledemail',
            options={'ordering': ['-run_at'], 'verbose_name': 'Legacy Scheduled Email', 'verbose_name_plural': 'Legacy Scheduled Emails'},
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Approved At'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_campaigns_approved', to=settings.AUTH_USER_MODEL, verbose_name='Approved By'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='bounced_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Bounced'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='campaign_type',
            field=models.CharField(choices=[('newsletter', 'Newsletter'), ('announcement', 'Announcement'), ('community', 'Community Update'), ('event', 'Event'), ('devotional', 'Devotional / Encouragement'), ('reengagement', 'Re-engagement'), ('operational', 'Operational'), ('other', 'Other')], db_index=True, default='announcement', max_length=30, verbose_name='Campaign Type'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='canceled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Canceled At'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='click_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Clicks'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='complaint_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Complaints'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Completed At'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='content_version',
            field=models.PositiveIntegerField(default=1, verbose_name='Content Version'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='delivered_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Delivered'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='description',
            field=models.TextField(blank=True, verbose_name='Internal Description'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='failed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Failed At'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='failed_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Failed'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='from_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Sender Name Override'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='last_error',
            field=models.TextField(blank=True, verbose_name='Last Error'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='open_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Opens'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='preheader_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='Preheader Text'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='recipient_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Recipients'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='reply_to_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Reply-To Email'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='review_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Review Requested At'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='schedule_timezone',
            field=models.CharField(default='UTC', max_length=64, verbose_name='Scheduling Time Zone'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='sent_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Sent'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Sending Started At'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='track_clicks',
            field=models.BooleanField(default=True, verbose_name='Track Clicks'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='track_opens',
            field=models.BooleanField(default=True, verbose_name='Track Opens'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='unique_click_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Unique Clicks'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='unique_open_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Unique Opens'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='unsubscribe_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Unsubscribes'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_campaigns_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='utm_campaign',
            field=models.CharField(blank=True, max_length=150, verbose_name='UTM Campaign'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='utm_medium',
            field=models.CharField(blank=True, default='email', max_length=100, verbose_name='UTM Medium'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='utm_source',
            field=models.CharField(blank=True, default='townlit_email', max_length=100, verbose_name='UTM Source'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='bounced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Bounced At'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='click_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Click Count'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='complained_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Complaint At'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Delivered At'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='external_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='communication.externalcontact', verbose_name='External Contact'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='failed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Failed At'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='failure_code',
            field=models.CharField(blank=True, max_length=120, verbose_name='Failure Code'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='failure_message',
            field=models.TextField(blank=True, verbose_name='Failure Message'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='last_event_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Event At'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Delivery Metadata'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='open_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Open Count'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='provider',
            field=models.CharField(choices=[('aws_ses', 'AWS SES')], default='aws_ses', max_length=20, verbose_name='Delivery Provider'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='provider_message_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Provider Message ID'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='queued_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Queued At'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('bounced', 'Bounced'), ('complained', 'Complaint'), ('suppressed', 'Suppressed'), ('failed', 'Failed')], db_index=True, default='sent', max_length=20, verbose_name='Delivery Status'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('newsletter', 'Newsletter'), ('announcement', 'Announcement'), ('community', 'Community'), ('event', 'Event'), ('devotional', 'Devotional'), ('welcome', 'Welcome'), ('reengagement', 'Re-engagement'), ('system', 'System'), ('other', 'Other')], db_index=True, default='general', max_length=30, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='default_context',
            field=models.JSONField(blank=True, default=dict, verbose_name='Default Context'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='editor_mode',
            field=models.CharField(choices=[('rich_text', 'Rich Text'), ('blocks', 'Block Builder'), ('html', 'Custom HTML')], db_index=True, default='rich_text', max_length=20, verbose_name='Editor'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Locked templates require elevated care when editing.', verbose_name='Locked'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='is_system',
            field=models.BooleanField(db_index=True, default=False, help_text='System templates are intended for transactional emails.', verbose_name='System Template'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='preheader_template',
            field=models.CharField(blank=True, help_text='Short preview text shown by many email clients.', max_length=255, verbose_name='Preheader Text'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_templates_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='Version'),
        ),
        migrations.AddField(
            model_name='externalcontact',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='externalcontact',
            name='last_contacted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Contacted At'),
        ),
        migrations.AddField(
            model_name='externalcontact',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Metadata'),
        ),
        migrations.AddField(
            model_name='externalcontact',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Internal Notes'),
        ),
        migrations.AddField(
            model_name='externalcontact',
            name='source',
            field=models.CharField(blank=True, max_length=80, verbose_name='Contact Source'),
        ),
        migrations.AddField(
            model_name='externalcontact',
            name='tags',
            field=models.JSONField(blank=True, default=list, verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='unsubscribeduser',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Metadata'),
        ),
        migrations.AddField(
            model_name='unsubscribeduser',
            name='reason',
            field=models.CharField(blank=True, max_length=120, verbose_name='Reason'),
        ),
        migrations.AddField(
            model_name='unsubscribeduser',
            name='scope',
            field=models.CharField(choices=[('marketing', 'Marketing Emails'), ('all_optional', 'All Optional Emails')], default='marketing', max_length=20, verbose_name='Unsubscribe Scope'),
        ),
        migrations.AddField(
            model_name='unsubscribeduser',
            name='source',
            field=models.CharField(blank=True, max_length=30, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_campaigns_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='custom_html',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Custom Email Body'),
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='ignore_unsubscribe',
            field=models.BooleanField(default=False, help_text='Use only for required legal, security, safety, or operational communication.', verbose_name='Bypass Unsubscribe Protection'),
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='recipients',
            field=models.ManyToManyField(blank=True, related_name='manual_campaigns', to=settings.AUTH_USER_MODEL, verbose_name='Specific Recipients'),
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Scheduled Send Time'),
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='sent_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Sent At'),
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('review', 'Needs Review'), ('ready', 'Ready to Send'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('paused', 'Paused'), ('sent', 'Sent'), ('canceled', 'Canceled'), ('failed', 'Failed')], db_index=True, default='draft', max_length=20, verbose_name='Campaign Status'),
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='tag',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Campaign Tag'),
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='target_group',
            field=models.CharField(choices=[('all_active', 'All Active Users'), ('believer', 'Label: Believers'), ('seeker', 'Label: Seekers'), ('prefer_not_to_say', 'Label: Prefer Not to Say'), ('seeker_and_prefer_not', 'Label: Seekers + Prefer Not to Say'), ('admins', 'TownLIT Admins'), ('deleted_members', 'Deleted Member Accounts'), ('deleted_non_members', 'Deleted Non-Member Accounts'), ('suspended', 'Suspended Accounts'), ('sanctuary_participants', 'Sanctuary-Eligible Members'), ('privacy_enabled', 'Members with Privacy Enabled'), ('unverified_identity', 'Members with Unverified Identity'), ('townlit_verified', 'TownLIT Verified Members'), ('townlit_not_verified', 'TownLIT Not Yet Verified Members'), ('reengagement', 'Previously Unsubscribed Users'), ('access_requests', 'Legacy: Pending Access Requests'), ('unused_invite_access_requests', 'Legacy: Access Requests with Unused Invite Codes')], db_index=True, default='all_active', max_length=50, verbose_name='Quick Audience Preset'),
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='communication.emailtemplate', verbose_name='Email Template'),
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='test_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Test Email'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='clicked',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Link Clicked'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='clicked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='First Clicked At'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, verbose_name='Recipient Email'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='opened',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Email Opened'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='opened_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='First Opened At'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='sent_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Sent At'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_email_logs', to=settings.AUTH_USER_MODEL, verbose_name='Registered User'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='body_template',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Email Body'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_templates_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='layout',
            field=models.CharField(choices=[('base_email', 'System Email'), ('base_site', 'Campaign / Newsletter')], default='base_site', max_length=30, verbose_name='Layout Template'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='name',
            field=models.CharField(max_length=120, unique=True, verbose_name='Template Name'),
        ),
        migrations.AlterField(
            model_name='externalcontact',
            name='became_user',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Converted to User'),
        ),
        migrations.AlterField(
            model_name='externalcontact',
            name='deleted_after_signup',
            field=models.BooleanField(default=False, verbose_name='Deleted After Signup'),
        ),
        migrations.AlterField(
            model_name='externalcontact',
            name='is_unsubscribed',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Unsubscribed'),
        ),
        migrations.AlterField(
            model_name='externalcontact',
            name='source_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='communication.externalemailcampaign', verbose_name='Source Campaign'),
        ),
        migrations.AlterField(
            model_name='externalemailcampaign',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_external_email_campaigns', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='externalemailcampaign',
            name='html_body',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Custom Email Body'),
        ),
        migrations.AlterField(
            model_name='externalemailcampaign',
            name='is_sent',
            field=models.BooleanField(default=False, verbose_name='Sent'),
        ),
        migrations.AlterField(
            model_name='externalemailcampaign',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_external_campaigns', to='communication.emailtemplate', verbose_name='Email Template'),
        ),
        migrations.AlterField(
            model_name='scheduledemail',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_schedules', to='communication.emailcampaign', verbose_name='Email Campaign'),
        ),
        migrations.AlterField(
            model_name='scheduledemail',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_scheduled_emails', to=settings.AUTH_USER_MODEL, verbose_name='Scheduled By'),
        ),
        migrations.AlterField(
            model_name='scheduledemail',
            name='is_sent',
            field=models.BooleanField(default=False, verbose_name='Sent'),
        ),
        migrations.AlterField(
            model_name='unsubscribeduser',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, unique=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='unsubscribeduser',
            name='unsubscribed_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Unsubscribed At'),
        ),
        migrations.AlterField(
            model_name='unsubscribeduser',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communication_unsubscribe', to=settings.AUTH_USER_MODEL, verbose_name='Registered User'),
        ),
        migrations.AddIndex(
            model_name='emailcampaign',
            index=models.Index(fields=['status', 'scheduled_time'], name='comm_cmp_status_sched_idx'),
        ),
        migrations.AddIndex(
            model_name='emailcampaign',
            index=models.Index(fields=['campaign_type', 'status'], name='comm_cmp_type_status_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['campaign', 'status'], name='comm_log_cmp_status_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['email', 'sent_at'], name='comm_log_email_sent_idx'),
        ),
        migrations.AddIndex(
            model_name='emailtemplate',
            index=models.Index(fields=['category', 'is_active'], name='comm_tpl_cat_active_idx'),
        ),
        migrations.AddField(
            model_name='emailtheme',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_themes_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='emailtheme',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_themes_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AddField(
            model_name='emailtemplateblock',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='communication.emailtemplate', verbose_name='Email Template'),
        ),
        migrations.AddField(
            model_name='emailsubscriptionpreference',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='communication.emailtopic', verbose_name='Email Topic'),
        ),
        migrations.AddField(
            model_name='emailsubscriptionpreference',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_subscription_preferences', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='emailevent',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='communication.emaillog', verbose_name='Email Delivery'),
        ),
        migrations.AddField(
            model_name='emailcampaigndailymetric',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_metrics', to='communication.emailcampaign', verbose_name='Email Campaign'),
        ),
        migrations.AddField(
            model_name='emailcampaignblock',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='communication.emailcampaign', verbose_name='Email Campaign'),
        ),
        migrations.AddField(
            model_name='emailaudiencerule',
            name='audience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='communication.emailaudience', verbose_name='Audience'),
        ),
        migrations.AddField(
            model_name='emailaudience',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_audiences_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='emailaudience',
            name='external_contacts',
            field=models.ManyToManyField(blank=True, related_name='communication_audiences', to='communication.externalcontact', verbose_name='External Contacts'),
        ),
        migrations.AddField(
            model_name='emailaudience',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_audiences_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AddField(
            model_name='emailaudience',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='communication_audiences', to=settings.AUTH_USER_MODEL, verbose_name='Included Users'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='audience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='communication.emailaudience', verbose_name='Saved Audience'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='communication.emailtheme', verbose_name='Email Theme Override'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='communication.emailtopic', verbose_name='Subscription Topic'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='communication.emailtheme', verbose_name='Email Theme'),
        ),
        migrations.AddIndex(
            model_name='emailtemplateblock',
            index=models.Index(fields=['template', 'sort_order'], name='comm_tpl_block_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='emailsubscriptionpreference',
            constraint=models.UniqueConstraint(fields=('email', 'topic'), name='comm_email_topic_pref_unique'),
        ),
        migrations.AddIndex(
            model_name='emailevent',
            index=models.Index(fields=['delivery', 'event_type'], name='comm_evt_log_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='emailcampaigndailymetric',
            constraint=models.UniqueConstraint(fields=('campaign', 'date'), name='comm_cmp_daily_metric_unique'),
        ),
        migrations.AddIndex(
            model_name='emailcampaignblock',
            index=models.Index(fields=['campaign', 'sort_order'], name='comm_cmp_block_order_idx'),
        ),
        migrations.AddIndex(
            model_name='emailaudiencerule',
            index=models.Index(fields=['audience', 'sort_order'], name='comm_aud_rule_order_idx'),
        ),
        migrations.AddIndex(
            model_name='emailaudience',
            index=models.Index(fields=['kind', 'is_active'], name='comm_aud_kind_active_idx'),
        ),
    ]
