# Generated by Django 4.2.4 on 2025-05-10 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0005_alter_unsubscribeduser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledemail',
            name='executed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
