# Generated by Django 4.2.4 on 2026-08-20 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0005_emailaudience_emailaudiencerule_emailcampaignblock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='celery_task_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Celery Task ID'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='dispatch_attempt_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Dispatch Attempts'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='last_dispatch_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Dispatch Attempt'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='queued_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Queued At'),
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('review', 'Needs Review'), ('ready', 'Ready to Send'), ('scheduled', 'Scheduled'), ('queued', 'Queued'), ('sending', 'Sending'), ('paused', 'Paused'), ('sent', 'Sent'), ('canceled', 'Canceled'), ('failed', 'Failed')], db_index=True, default='draft', max_length=20, verbose_name='Campaign Status'),
        ),
    ]
