# Generated by Django 4.2.4 on 2025-05-12 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0006_scheduledemail_executed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcampaign',
            name='target_group',
            field=models.CharField(choices=[('all_active', 'All Active Users'), ('believer', 'Label: Believers'), ('seeker', 'Label: Seekers'), ('prefer_not_to_say', 'Label: Prefer Not to Say'), ('seeker_and_prefer_not', 'Label: Seekers + Prefer Not to Say'), ('members', 'All Members'), ('guests', 'All Guest Users'), ('admins', 'TownLIT Admins'), ('deleted_members', 'Deleted Member Accounts'), ('deleted_non_members', 'Deleted Non-Member Accounts'), ('suspended', 'Suspended Accounts'), ('sanctuary_participants', 'Sanctuary-Eligible Members'), ('privacy_enabled', 'Members with Privacy Enabled'), ('unverified_identity', 'Members with Unverified Identity')], default='all_active', max_length=50),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='communication.emailcampaign'),
        ),
    ]
