# Generated by Django 4.2.4 on 2026-08-20 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0006_emailcampaign_celery_task_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='sent_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Sent At'),
        ),
    ]
