# Generated by Django 4.2.4 on 2026-08-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0007_alter_emaillog_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='last_test_content_version',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Last Tested Content Version'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='last_test_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Last Test Email'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='last_test_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Test Sent At'),
        ),
    ]
