# Generated by Django 4.2.4 on 2025-05-12 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communication', '0007_alter_emailcampaign_target_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcampaign',
            name='target_group',
            field=models.CharField(choices=[('all_active', 'All Active Users'), ('believer', 'Label: Believers'), ('seeker', 'Label: Seekers'), ('prefer_not_to_say', 'Label: Prefer Not to Say'), ('seeker_and_prefer_not', 'Label: Seekers + Prefer Not to Say'), ('admins', 'TownLIT Admins'), ('deleted_members', 'Deleted Member Accounts'), ('deleted_non_members', 'Deleted Non-Member Accounts'), ('suspended', 'Suspended Accounts'), ('sanctuary_participants', 'Sanctuary-Eligible Members'), ('privacy_enabled', 'Members with Privacy Enabled'), ('unverified_identity', 'Members with Unverified Identity'), ('reengagement', 'Previously Unsubscribed Users (Re-engagement Campaign)')], default='all_active', max_length=50),
        ),
        migrations.CreateModel(
            name='ExternalEmailCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Campaign Title')),
                ('subject', models.CharField(max_length=255, verbose_name='Email Subject')),
                ('html_body', models.TextField(verbose_name='Email HTML Content')),
                ('csv_file', models.FileField(upload_to='external_campaigns/', verbose_name='CSV File with Emails')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Is Sent')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Sent At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
        ),
    ]
