# Generated by Django 4.2.4 on 2025-05-12 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0008_alter_emailcampaign_target_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('family', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('nation', models.CharField(blank=True, max_length=100)),
                ('recognize', models.CharField(blank=True, max_length=100)),
                ('registre_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='communication.externalemailcampaign')),
            ],
            options={
                'verbose_name': 'External Contact',
                'verbose_name_plural': 'External Contacts',
            },
        ),
    ]
