# Generated by Django 4.2.4 on 2025-05-12 19:32

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0009_externalcontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalcontact',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='externalcontact',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='externalemailcampaign',
            name='html_body',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Custom Email Body (Optional)'),
        ),
    ]
