# Generated by Django 4.2.4 on 2025-05-12 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0011_emailtemplate_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalcontact',
            name='became_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='externalcontact',
            name='deleted_after_signup',
            field=models.BooleanField(default=False),
        ),
    ]
