# Generated by Django 4.2.4 on 2025-05-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0012_externalcontact_became_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalcontact',
            name='became_user_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='externalcontact',
            name='deleted_after_signup_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
