# Generated by Django 4.2.4 on 2025-05-23 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0013_externalcontact_became_user_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='layout',
            field=models.CharField(choices=[('base_email', 'System Email (Security, Activation, etc.)'), ('base_site', 'Campaign/Newsletter (Invitation, Updates)')], default='base_site', help_text='Choose the layout this template will use when rendered in emails.', max_length=30, verbose_name='Layout Template'),
        ),
    ]
