# Generated by Django 4.2.4 on 2025-05-23 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0014_emailtemplate_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalemailcampaign',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='communication.emailtemplate'),
        ),
    ]
