# Generated by Django 4.2.4 on 2025-05-23 19:16

import apps.communication.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0015_externalemailcampaign_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcampaign',
            name='custom_html',
            field=apps.communication.models.LongRichTextUploadingField(blank=True, verbose_name='Custom Email Body (Optional)'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='body_template',
            field=apps.communication.models.LongRichTextUploadingField(verbose_name='HTML Body'),
        ),
        migrations.AlterField(
            model_name='externalemailcampaign',
            name='html_body',
            field=apps.communication.models.LongRichTextUploadingField(verbose_name='Custom Email Body (Optional)'),
        ),
    ]
