# apps/accounting/reports/exporters/csv_exporter.py

import csv
from io import StringIO
from datetime import datetime

from .branding import TOWNLIT_BRAND


class CSVReportExporter:
    """
    Export report rows as branded CSV.
    """

    def export(
        self,
        *,
        headers,
        rows,
        title="Report",
        period_label="",
        generated_by="System",
        environment_label="Production",
    ) -> bytes:
        """
        Return CSV bytes.
        """

        buffer = StringIO()
        writer = csv.writer(buffer)

        writer.writerow([TOWNLIT_BRAND["company_name"]])
        writer.writerow([title])
        writer.writerow([f"Period: {period_label or 'N/A'}"])
        writer.writerow([f"Generated At: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"])
        writer.writerow([f"Generated By: {generated_by}"])
        writer.writerow([f"Currency: {TOWNLIT_BRAND['currency']}"])
        writer.writerow([f"Environment: {environment_label}"])
        writer.writerow([])

        writer.writerow(headers)

        for row in rows:
            writer.writerow(row)

        return buffer.getvalue().encode("utf-8")