# apps/accounting/reports/exporters/pdf_exporter.py

from io import BytesIO
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    Image,
)

from .branding import TOWNLIT_BRAND, get_static_logo_path


class PDFReportExporter:
    """
    Export report rows as branded PDF table.
    """

    def export(
        self,
        *,
        title,
        headers,
        rows,
        period_label="",
        generated_by="System",
        environment_label="Production",
        logo_filename="TownLITLogo.png",
        col_widths=None,
        amount_columns=None,
    ) -> bytes:
        """
        Return branded PDF bytes.

        amount_columns:
            Set or list of zero-based column indexes that should be right-aligned.
            Only monetary / amount columns should be included here.
        """

        if amount_columns is None:
            amount_columns = set()
        else:
            amount_columns = set(amount_columns)

        output = BytesIO()
        document = SimpleDocTemplate(
            output,
            pagesize=A4,
            leftMargin=16 * mm,
            rightMargin=16 * mm,
            topMargin=16 * mm,
            bottomMargin=16 * mm,
            title=title,
            author=TOWNLIT_BRAND["company_name"],
            subject=title,
        )

        styles = getSampleStyleSheet()
        story = []

        # Logo (square, smaller)
        try:
            logo_path = get_static_logo_path(logo_filename)
            logo = Image(logo_path, width=18 * mm, height=18 * mm)
            story.append(logo)
            story.append(Spacer(1, 6))
        except Exception:
            pass

        # Main title
        story.append(Paragraph(f"<b>{TOWNLIT_BRAND['company_name']}</b>", styles["Title"]))
        story.append(Paragraph(f"<b>{title}</b>", styles["Heading2"]))
        story.append(Spacer(1, 8))

        generated_at = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        meta_lines = [
            f"Period: {period_label or 'N/A'}",
            f"Generated At: {generated_at}",
            f"Generated By: {generated_by}",
            f"Currency: {TOWNLIT_BRAND['currency']}",
            f"Environment: {environment_label}",
        ]

        for line in meta_lines:
            story.append(Paragraph(line, styles["BodyText"]))

        story.append(Spacer(1, 12))

        normalized_headers = self._normalize_headers_for_pdf(headers, styles)
        normalized_rows = self._normalize_rows_for_pdf(rows, styles, amount_columns)

        table_data = [normalized_headers] + normalized_rows

        # Default equal-width columns if no custom widths are provided
        if not col_widths:
            available_width = A4[0] - (32 * mm)
            col_count = len(headers)
            col_widths = [available_width / col_count] * col_count

        table = Table(
            table_data,
            repeatRows=1,
            colWidths=col_widths,
        )

        style_commands = [
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#D9E2F3")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.black),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("GRID", (0, 0), (-1, -1), 0.4, colors.grey),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F7F7F7")]),
            ("FONTSIZE", (0, 0), (-1, -1), 7.2),
            ("LEADING", (0, 0), (-1, -1), 9),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("ALIGN", (0, 0), (-1, 0), "CENTER"),  # headers
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ("LEFTPADDING", (0, 0), (-1, -1), 4),
            ("RIGHTPADDING", (0, 0), (-1, -1), 4),
        ]

        # Align data rows: text columns left, amount columns right
        for col_index in range(len(headers)):
            if col_index in amount_columns:
                style_commands.append(("ALIGN", (col_index, 1), (col_index, -1), "RIGHT"))
            else:
                style_commands.append(("ALIGN", (col_index, 1), (col_index, -1), "LEFT"))

        table.setStyle(TableStyle(style_commands))

        story.append(table)
        story.append(Spacer(1, 10))
        story.append(Paragraph(TOWNLIT_BRAND["report_footer_note"], styles["Italic"]))

        document.build(
            story,
            onFirstPage=self._build_footer,
            onLaterPages=self._build_footer,
        )

        return output.getvalue()

    def _normalize_headers_for_pdf(self, headers, styles):
        """
        Convert table headers to Paragraph for better wrapping.
        """

        header_style = styles["BodyText"].clone("pdf_header_style")
        header_style.fontName = "Helvetica-Bold"
        header_style.fontSize = 7.5
        header_style.leading = 9
        header_style.alignment = 1  # center

        return [
            Paragraph("" if value is None else str(value), header_style)
            for value in headers
        ]

    def _normalize_rows_for_pdf(self, rows, styles, amount_columns):
        """
        Convert row cells to Paragraph with better wrapping and alignment.
        """

        text_style = styles["BodyText"].clone("pdf_text_style")
        text_style.fontSize = 7.2
        text_style.leading = 9
        text_style.alignment = 0  # left

        amount_style = styles["BodyText"].clone("pdf_amount_style")
        amount_style.fontSize = 7.2
        amount_style.leading = 9
        amount_style.alignment = 2  # right

        normalized = []

        for row in rows:
            normalized_row = []
            for col_index, value in enumerate(row):
                text = "" if value is None else str(value)
                style = amount_style if col_index in amount_columns else text_style
                normalized_row.append(Paragraph(text, style))
            normalized.append(normalized_row)

        return normalized

    def _build_footer(self, canvas, doc):
        """
        Draw footer on every page.
        """

        canvas.saveState()
        footer_text = f"{TOWNLIT_BRAND['company_name']} | Page {doc.page}"
        canvas.setFont("Helvetica", 8)
        canvas.setFillColor(colors.grey)
        canvas.drawString(16 * mm, 10 * mm, footer_text)
        canvas.restoreState()