# apps/accounting/reports/exporters/xlsx_exporter.py

from io import BytesIO
from datetime import datetime

from openpyxl import Workbook
from openpyxl.styles import Font, Alignment, PatternFill

from .branding import TOWNLIT_BRAND


class XLSXReportExporter:
    """
    Export report rows as branded Excel workbook.
    """

    def export(
        self,
        *,
        sheet_name,
        headers,
        rows,
        title="Report",
        period_label="",
        generated_by="System",
        environment_label="Production",
    ) -> bytes:
        """
        Return XLSX bytes.
        """

        workbook = Workbook()
        worksheet = workbook.active
        worksheet.title = sheet_name[:31]

        worksheet["A1"] = TOWNLIT_BRAND["company_name"]
        worksheet["A1"].font = Font(size=16, bold=True)

        worksheet["A2"] = title
        worksheet["A2"].font = Font(size=13, bold=True)

        worksheet["A4"] = f"Period: {period_label or 'N/A'}"
        worksheet["A5"] = f"Generated At: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
        worksheet["A6"] = f"Generated By: {generated_by}"
        worksheet["A7"] = f"Currency: {TOWNLIT_BRAND['currency']}"
        worksheet["A8"] = f"Environment: {environment_label}"

        header_row = 10

        for col_index, header in enumerate(headers, start=1):
            cell = worksheet.cell(row=header_row, column=col_index, value=header)
            cell.font = Font(bold=True)
            cell.alignment = Alignment(horizontal="center")
            cell.fill = PatternFill(fill_type="solid", fgColor="D9E2F3")

        for row_index, row in enumerate(rows, start=header_row + 1):
            for col_index, value in enumerate(row, start=1):
                worksheet.cell(row=row_index, column=col_index, value=value)

        for column_cells in worksheet.columns:
            max_length = 0
            column_letter = column_cells[0].column_letter

            for cell in column_cells:
                value = "" if cell.value is None else str(cell.value)
                max_length = max(max_length, len(value))

            worksheet.column_dimensions[column_letter].width = min(max_length + 2, 40)

        output = BytesIO()
        workbook.properties.creator = TOWNLIT_BRAND["company_name"]
        workbook.properties.title = title
        workbook.properties.subject = title
        workbook.save(output)
        return output.getvalue()