# Generated by Django 4.2.4 on 2026-07-22 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyInsightDimension',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dimension', models.CharField(choices=[('gratitude', 'Gratitude'), ('peace', 'Peace'), ('hope', 'Hope'), ('faith', 'Faith'), ('connection', 'Connection'), ('purpose', 'Purpose'), ('courage', 'Courage'), ('compassion', 'Compassion'), ('self_awareness', 'Self Awareness'), ('resilience', 'Resilience'), ('rest', 'Rest'), ('growth', 'Growth')], max_length=32)),
                ('score', models.DecimalField(decimal_places=3, max_digits=7)),
                ('previous_score', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('trend', models.CharField(choices=[('up', 'Up'), ('stable', 'Stable'), ('down', 'Down'), ('insufficient', 'Insufficient Data')], default='insufficient', max_length=16)),
                ('confidence', models.DecimalField(decimal_places=5, default=0, max_digits=6)),
                ('sample_count', models.PositiveIntegerField(default=0)),
                ('explanation_key', models.CharField(blank=True, default='', max_length=100)),
                ('explanation_params', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Monthly Insight Dimension',
                'verbose_name_plural': 'Monthly Insight Dimensions',
                'ordering': ('dimension',),
            },
        ),
        migrations.CreateModel(
            name='MonthlyInsightReport',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('timezone_name', models.CharField(default='UTC', max_length=64)),
                ('status', models.CharField(choices=[('building', 'Building'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='building', max_length=16)),
                ('version', models.CharField(default='journey-monthly-insight-v1', max_length=100)),
                ('is_sufficient', models.BooleanField(db_index=True, default=False)),
                ('journey_days_count', models.PositiveIntegerField(default=0)),
                ('journey_entries_count', models.PositiveIntegerField(default=0)),
                ('reflection_sessions_count', models.PositiveIntegerField(default=0)),
                ('reflection_answers_count', models.PositiveIntegerField(default=0)),
                ('overall_score', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('previous_overall_score', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('overall_trend', models.CharField(choices=[('up', 'Up'), ('stable', 'Stable'), ('down', 'Down'), ('insufficient', 'Insufficient Data')], default='insufficient', max_length=16)),
                ('dimension_scores', models.JSONField(blank=True, default=dict)),
                ('dimension_trends', models.JSONField(blank=True, default=dict)),
                ('highlights', models.JSONField(blank=True, default=list)),
                ('growth_areas', models.JSONField(blank=True, default=list)),
                ('reflection_summary', models.JSONField(blank=True, default=dict)),
                ('journey_summary', models.JSONField(blank=True, default=dict)),
                ('source_snapshots', models.JSONField(blank=True, default=dict)),
                ('algorithm_snapshot', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Monthly Insight Report',
                'verbose_name_plural': 'Monthly Insight Reports',
                'ordering': ('-year', '-month', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ReflectionAnswer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('invalidated', 'Invalidated')], db_index=True, default='submitted', max_length=16)),
                ('selected_choice_codes', models.JSONField(default=list)),
                ('response_value', models.JSONField(blank=True, default=dict)),
                ('raw_score', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('normalized_score', models.DecimalField(decimal_places=3, default=0, max_digits=7)),
                ('dimension_scores', models.JSONField(blank=True, default=dict)),
                ('scoring_snapshot', models.JSONField(blank=True, default=dict)),
                ('submitted_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reflection Answer',
                'verbose_name_plural': 'Reflection Answers',
                'ordering': ('-submitted_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ReflectionChoice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(max_length=64)),
                ('label', models.CharField(max_length=500)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('base_score', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('dimension_weights', models.JSONField(blank=True, default=dict)),
                ('scoring_profile', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reflection Choice',
                'verbose_name_plural': 'Reflection Choices',
                'ordering': ('question_id', 'order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ReflectionQuestion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('prompt', models.TextField()),
                ('kind', models.CharField(choices=[('single_choice', 'Single Choice'), ('multiple_choice', 'Multiple Choice'), ('scale', 'Scale')], db_index=True, default='single_choice', max_length=32)),
                ('primary_dimension', models.CharField(choices=[('gratitude', 'Gratitude'), ('peace', 'Peace'), ('hope', 'Hope'), ('faith', 'Faith'), ('connection', 'Connection'), ('purpose', 'Purpose'), ('courage', 'Courage'), ('compassion', 'Compassion'), ('self_awareness', 'Self Awareness'), ('resilience', 'Resilience'), ('rest', 'Rest'), ('growth', 'Growth')], db_index=True, max_length=32)),
                ('secondary_dimensions', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('retired', 'Retired')], db_index=True, default='draft', max_length=16)),
                ('difficulty', models.PositiveSmallIntegerField(default=1)),
                ('sensitivity', models.PositiveSmallIntegerField(default=1)),
                ('selection_weight', models.DecimalField(decimal_places=4, default=1, max_digits=8)),
                ('minimum_journey_entries', models.PositiveSmallIntegerField(default=1)),
                ('minimum_active_days_in_month', models.PositiveSmallIntegerField(default=1)),
                ('allow_for_new_users', models.BooleanField(default=True)),
                ('is_brand_core', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reflection Question',
                'verbose_name_plural': 'Reflection Questions',
                'ordering': ('primary_dimension', 'code'),
            },
        ),
        migrations.CreateModel(
            name='ReflectionSession',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('source_kind', models.CharField(choices=[('journey', 'Journey'), ('moment', 'Moment'), ('testimony', 'Testimony'), ('prayer', 'Prayer'), ('system', 'System')], db_index=True, default='journey', max_length=24)),
                ('source_object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('completed', 'Completed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='open', max_length=16)),
                ('selection_version', models.CharField(default='journey-reflection-selection-v1', max_length=100)),
                ('scoring_version', models.CharField(default='journey-reflection-scoring-v1', max_length=100)),
                ('question_count', models.PositiveSmallIntegerField(default=0)),
                ('answered_count', models.PositiveSmallIntegerField(default=0)),
                ('score_total', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('dimension_scores', models.JSONField(blank=True, default=dict)),
                ('selection_context', models.JSONField(blank=True, default=dict)),
                ('opened_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reflection_sessions', to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflection_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reflection Session',
                'verbose_name_plural': 'Reflection Sessions',
                'ordering': ('-opened_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ReflectionSessionQuestion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('position', models.PositiveSmallIntegerField()),
                ('prompt_snapshot', models.TextField()),
                ('kind_snapshot', models.CharField(max_length=32)),
                ('primary_dimension_snapshot', models.CharField(max_length=32)),
                ('choice_snapshot', models.JSONField(default=list)),
                ('selection_score', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('selection_reason', models.JSONField(blank=True, default=dict)),
                ('presented_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='session_assignments', to='journey_insights.reflectionquestion')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_questions', to='journey_insights.reflectionsession')),
            ],
            options={
                'verbose_name': 'Reflection Session Question',
                'verbose_name_plural': 'Reflection Session Questions',
                'ordering': ('position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ReflectionQuestionExposure',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('exposure_cycle', models.PositiveIntegerField(db_index=True, default=1)),
                ('times_presented', models.PositiveIntegerField(default=1)),
                ('times_answered', models.PositiveIntegerField(default=0)),
                ('first_presented_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_presented_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_answered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_exposures', to='journey_insights.reflectionquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflection_question_exposures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reflection Question Exposure',
                'verbose_name_plural': 'Reflection Question Exposures',
            },
        ),
        migrations.AddIndex(
            model_name='reflectionquestion',
            index=models.Index(fields=['status', 'is_active', 'primary_dimension'], name='reflection_question_active_idx'),
        ),
        migrations.AddIndex(
            model_name='reflectionquestion',
            index=models.Index(fields=['kind', 'difficulty', 'sensitivity'], name='reflection_question_kind_idx'),
        ),
        migrations.AddConstraint(
            model_name='reflectionquestion',
            constraint=models.CheckConstraint(check=models.Q(('difficulty__gte', 1), ('difficulty__lte', 5)), name='reflection_question_difficulty_range'),
        ),
        migrations.AddConstraint(
            model_name='reflectionquestion',
            constraint=models.CheckConstraint(check=models.Q(('sensitivity__gte', 1), ('sensitivity__lte', 5)), name='reflection_question_sensitivity_range'),
        ),
        migrations.AddConstraint(
            model_name='reflectionquestion',
            constraint=models.CheckConstraint(check=models.Q(('selection_weight__gt', 0)), name='reflection_question_weight_positive'),
        ),
        migrations.AddField(
            model_name='reflectionchoice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='journey_insights.reflectionquestion'),
        ),
        migrations.AddField(
            model_name='reflectionanswer',
            name='selected_choices',
            field=models.ManyToManyField(blank=True, related_name='reflection_answers', to='journey_insights.reflectionchoice'),
        ),
        migrations.AddField(
            model_name='reflectionanswer',
            name='session_question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='journey_insights.reflectionsessionquestion'),
        ),
        migrations.AddField(
            model_name='reflectionanswer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflection_answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='monthlyinsightreport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_insight_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='monthlyinsightdimension',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimensions', to='journey_insights.monthlyinsightreport'),
        ),
        migrations.AddConstraint(
            model_name='reflectionsessionquestion',
            constraint=models.UniqueConstraint(fields=('session', 'question'), name='reflection_unique_session_question'),
        ),
        migrations.AddConstraint(
            model_name='reflectionsessionquestion',
            constraint=models.UniqueConstraint(fields=('session', 'position'), name='reflection_unique_session_position'),
        ),
        migrations.AddIndex(
            model_name='reflectionsession',
            index=models.Index(fields=['user', 'status', '-opened_at'], name='reflection_session_user_idx'),
        ),
        migrations.AddIndex(
            model_name='reflectionsession',
            index=models.Index(fields=['source_kind', 'source_content_type', 'source_object_id'], name='reflection_session_source_idx'),
        ),
        migrations.AddIndex(
            model_name='reflectionsession',
            index=models.Index(fields=['status', 'expires_at'], name='reflection_session_expiry_idx'),
        ),
        migrations.AddConstraint(
            model_name='reflectionsession',
            constraint=models.CheckConstraint(check=models.Q(('question_count__gte', 0)), name='reflection_session_question_count_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='reflectionsession',
            constraint=models.CheckConstraint(check=models.Q(('answered_count__gte', 0)), name='reflection_session_answer_count_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='reflectionquestionexposure',
            index=models.Index(fields=['user', 'exposure_cycle', 'last_presented_at'], name='refl_exp_cycle_idx'),
        ),
        migrations.AddIndex(
            model_name='reflectionquestionexposure',
            index=models.Index(fields=['user', 'question', 'times_presented'], name='refl_exp_question_idx'),
        ),
        migrations.AddConstraint(
            model_name='reflectionquestionexposure',
            constraint=models.UniqueConstraint(fields=('user', 'question'), name='refl_unique_user_question'),
        ),
        migrations.AddIndex(
            model_name='reflectionchoice',
            index=models.Index(fields=['question', 'is_active', 'order'], name='reflection_choice_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='reflectionchoice',
            constraint=models.UniqueConstraint(fields=('question', 'code'), name='reflection_unique_question_choice_code'),
        ),
        migrations.AddConstraint(
            model_name='reflectionchoice',
            constraint=models.UniqueConstraint(fields=('question', 'order'), name='reflection_unique_question_choice_order'),
        ),
        migrations.AddIndex(
            model_name='reflectionanswer',
            index=models.Index(fields=['user', '-submitted_at'], name='refl_ans_user_time_idx'),
        ),
        migrations.AddIndex(
            model_name='reflectionanswer',
            index=models.Index(fields=['status', '-submitted_at'], name='refl_ans_status_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlyinsightreport',
            index=models.Index(fields=['user', '-year', '-month'], name='mon_ins_user_hist_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlyinsightreport',
            index=models.Index(fields=['status', 'generated_at'], name='mon_ins_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='monthlyinsightreport',
            constraint=models.UniqueConstraint(fields=('user', 'year', 'month'), name='mon_ins_unique_user_period'),
        ),
        migrations.AddConstraint(
            model_name='monthlyinsightreport',
            constraint=models.CheckConstraint(check=models.Q(('month__gte', 1), ('month__lte', 12)), name='mon_ins_month_range'),
        ),
        migrations.AddConstraint(
            model_name='monthlyinsightdimension',
            constraint=models.UniqueConstraint(fields=('report', 'dimension'), name='monthly_insight_unique_report_dimension'),
        ),
    ]
