# Generated by Django 4.2.4 on 2026-07-23 00:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0081_alter_announcement_image_and_more'),
        ('journey_insights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReflectionPrompt',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('local_date', models.DateField(db_index=True)),
                ('timezone_name', models.CharField(default='UTC', max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('deferred', 'Deferred'), ('skipped', 'Skipped for today'), ('answered', 'Answered'), ('expired', 'Expired')], db_index=True, default='pending', max_length=24)),
                ('prompt_count', models.PositiveIntegerField(default=1)),
                ('deferred_count', models.PositiveIntegerField(default=0)),
                ('first_prompted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_prompted_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('deferred_at', models.DateTimeField(blank=True, null=True)),
                ('skipped_at', models.DateTimeField(blank=True, null=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_source_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_daily_reflection_prompts', to='posts.journeyentry')),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reflection_prompts', to='posts.journey')),
                ('latest_source_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='latest_daily_reflection_prompts', to='posts.journeyentry')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='daily_prompt', to='journey_insights.reflectionsession')),
                ('session_question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='daily_prompt', to='journey_insights.reflectionsessionquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reflection_prompts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Reflection Prompt',
                'verbose_name_plural': 'Daily Reflection Prompts',
                'ordering': ('-local_date', '-id'),
                'indexes': [models.Index(fields=['user', '-local_date', 'status'], name='jri_prompt_user_day_status_idx'), models.Index(fields=['status', '-last_prompted_at'], name='jri_prompt_status_time_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='dailyreflectionprompt',
            constraint=models.UniqueConstraint(fields=('user', 'local_date'), name='jri_unique_user_daily_prompt'),
        ),
    ]
