# Generated by Django 4.2.4 on 2026-07-24 23:02

import uuid

from django.db import migrations, models


def populate_session_question_public_ids(apps, schema_editor):
    ReflectionSessionQuestion = apps.get_model(
        "journey_insights",
        "ReflectionSessionQuestion",
    )

    for assignment in ReflectionSessionQuestion.objects.filter(
        public_id__isnull=True
    ).iterator():
        assignment.public_id = uuid.uuid4()
        assignment.save(update_fields=["public_id"])


class Migration(migrations.Migration):

    dependencies = [
        (
            "journey_insights",
            "0002_dailyreflectionprompt_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="reflectionsessionquestion",
            name="public_id",
            field=models.UUIDField(
                null=True,
                editable=False,
            ),
        ),
        migrations.RunPython(
            populate_session_question_public_ids,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="reflectionsessionquestion",
            name="public_id",
            field=models.UUIDField(
                default=uuid.uuid4,
                unique=True,
                editable=False,
            ),
        ),
    ]