# Generated by Django 4.2.4 on 2026-07-27 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0083_alter_announcement_image_and_more'),
        ('journey_insights', '0003_reflectionsessionquestion_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreflectionprompt',
            name='journey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_reflection_prompts', to='posts.journey'),
        ),
    ]
