# Generated by Django 4.2.4 on 2026-07-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey_insights', '0004_alter_dailyreflectionprompt_journey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreflectionprompt',
            name='first_prompted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyreflectionprompt',
            name='last_prompted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyreflectionprompt',
            name='prompt_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
