# Generated by Django 4.2.4 on 2025-05-26 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.common.utils
import validators.mediaValidators.image_validators
import validators.security_validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dialogue',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Group Name')),
                ('group_image', models.ImageField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file], verbose_name='Group Image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('is_group', models.BooleanField(default=False, verbose_name='Is Group')),
                ('rsa_required', models.BooleanField(default=False, verbose_name='Requires RSA Encryption')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Slug')),
                ('deleted_by_users', models.ManyToManyField(blank=True, related_name='deleted_dialogues', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('edited_at', models.DateTimeField(blank=True, null=True, verbose_name='Edited At')),
                ('is_edited', models.BooleanField(default=False)),
                ('is_delivered', models.BooleanField(default=False, verbose_name='Is Delivered')),
                ('content_encrypted', models.BinaryField(blank=True, null=True)),
                ('aes_key_encrypted', models.BinaryField(blank=True, null=True)),
                ('encrypted_for_device', models.CharField(blank=True, max_length=100, null=True)),
                ('is_encrypted', models.BooleanField(default=False, verbose_name='Is Encrypted')),
                ('is_encrypted_file', models.BooleanField(default=False, verbose_name='Is File Encrypted')),
                ('image', models.ImageField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, verbose_name='Image')),
                ('video', models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, verbose_name='Video')),
                ('file', models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, verbose_name='File')),
                ('audio', models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, verbose_name='Audio')),
                ('self_destruct_at', models.DateTimeField(blank=True, null=True, verbose_name='Self-destruct At')),
                ('is_system', models.BooleanField(default=False)),
                ('system_event', models.CharField(blank=True, choices=[('joined', 'Joined'), ('left', 'Left'), ('removed', 'Removed'), ('founder_transferred', 'Founder Transferred'), ('promoted_to_elder', 'Promoted to Elder'), ('demoted_to_participant', 'Demoted to Participant'), ('group_deleted', 'Group Deleted'), ('resigned_from_elder', 'Resigned from Elder Role')], max_length=50, null=True)),
                ('deleted_by_users', models.ManyToManyField(blank=True, related_name='deleted_messages', to=settings.AUTH_USER_MODEL)),
                ('dialogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='conversation.dialogue')),
                ('seen_by_users', models.ManyToManyField(blank=True, related_name='seen_messages', to=settings.AUTH_USER_MODEL, verbose_name='Seen By')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MessageEncryption',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('device_id', models.CharField(max_length=255)),
                ('encrypted_content', models.TextField()),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encryptions', to='conversation.message')),
            ],
        ),
        migrations.AddField(
            model_name='dialogue',
            name='last_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_message_dialogue', to='conversation.message'),
        ),
        migrations.AddField(
            model_name='dialogue',
            name='participants',
            field=models.ManyToManyField(related_name='dialogues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserDialogueMarker',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_sensitive', models.BooleanField(default=False)),
                ('delete_policy', models.CharField(choices=[('SOFT_DELETE', 'Soft Delete for User'), ('LEAVE_GROUP_SOFT_DELETE', 'Leave Group & Soft Delete')], default='SOFT_DELETE', max_length=50)),
                ('last_typing_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Typing At')),
                ('dialogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marked_users', to='conversation.dialogue')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marked_dialogues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'dialogue')},
            },
        ),
        migrations.CreateModel(
            name='DialogueParticipant',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('founder', 'Founder'), ('elder', 'Elder'), ('participant', 'Participant')], default='participant', max_length=20, verbose_name='Role')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Joined At')),
                ('dialogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants_roles', to='conversation.dialogue', verbose_name='Dialogue')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'unique_together': {('dialogue', 'user')},
            },
        ),
    ]
