# Generated by Django 4.2.4 on 2025-03-28 05:29

import common.validators
from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='system_event',
            field=models.CharField(blank=True, choices=[('joined', 'Joined'), ('left', 'Left'), ('removed', 'Removed'), ('founder_transferred', 'Founder Transferred'), ('promoted_to_elder', 'Promoted to Elder'), ('demoted_to_participant', 'Demoted to Participant'), ('group_deleted', 'Group Deleted'), ('resigned_from_elder', 'Resigned from Elder Role')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dialogue',
            name='group_image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.dir_upload, validators=[common.validators.validate_image_or_video_file, common.validators.validate_no_executable_file], verbose_name='Group Image'),
        ),
        migrations.AlterField(
            model_name='message',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to=utils.FileUpload.dir_upload, verbose_name='Audio'),
        ),
        migrations.AlterField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=utils.FileUpload.dir_upload, verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.dir_upload, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='message',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=utils.FileUpload.dir_upload, verbose_name='Video'),
        ),
    ]
