# Generated by Django 4.2.4 on 2025-04-07 16:54

import common.validators
from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0003_alter_dialogue_group_image_alter_message_audio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialogue',
            name='rsa_required',
            field=models.BooleanField(default=False, verbose_name='Requires RSA Encryption'),
        ),
        migrations.AddField(
            model_name='dialoguekey',
            name='rsa_used',
            field=models.BooleanField(default=False, verbose_name='RSA Used in This Chat'),
        ),
        migrations.AddField(
            model_name='message',
            name='content_plaintext',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dialogue',
            name='group_image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.dir_upload, validators=[common.validators.validate_image_or_video_file, common.validators.validate_no_executable_file], verbose_name='Group Image'),
        ),
        migrations.AlterField(
            model_name='message',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to=utils.FileUpload.dir_upload, verbose_name='Audio'),
        ),
        migrations.AlterField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=utils.FileUpload.dir_upload, verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.dir_upload, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='message',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=utils.FileUpload.dir_upload, verbose_name='Video'),
        ),
    ]
