# Generated by Django 4.2.4 on 2025-05-02 17:54

import common.validators
from django.db import migrations, models
import utils.common.utils


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0005_dialogue_slug_alter_dialogue_group_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialogue',
            name='group_image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[common.validators.validate_image_or_video_file, common.validators.validate_no_executable_file], verbose_name='Group Image'),
        ),
        migrations.AlterField(
            model_name='dialogue',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dialogueparticipant',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, verbose_name='Audio'),
        ),
        migrations.AlterField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='message',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, verbose_name='Video'),
        ),
        migrations.AlterField(
            model_name='messageencryption',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userdialoguemarker',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
