# Generated by Django 4.2.4 on 2025-08-10 05:44

from django.db import migrations, models
import utils.common.utils
import validators.mediaValidators.image_validators
import validators.security_validators


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0006_alter_dialogue_group_image_alter_message_audio_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='messageencryption',
            new_name='idx_message_device',
            old_name='conversatio_message_03ec8d_idx',
        ),
        migrations.AlterUniqueTogether(
            name='messageencryption',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='messageencryption',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dialogue',
            name='group_image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file], verbose_name='Group Image'),
        ),
        migrations.AlterField(
            model_name='message',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, verbose_name='Audio'),
        ),
        migrations.AlterField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='message',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, verbose_name='Video'),
        ),
        migrations.AddConstraint(
            model_name='messageencryption',
            constraint=models.UniqueConstraint(fields=('message', 'device_id'), name='uq_message_device'),
        ),
    ]
