# Generated by Django 4.2.4 on 2026-04-22 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.common.utils
import validators.mediaValidators.image_validators
import validators.security_validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conversation', '0060_userdialoguemarker_inbound_blocked_until_outgoing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialogue',
            name='group_image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file], verbose_name='Group Image'),
        ),
        migrations.AlterField(
            model_name='message',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, verbose_name='Audio'),
        ),
        migrations.AlterField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='message',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, verbose_name='Video'),
        ),
        migrations.CreateModel(
            name='DialoguePin',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('position', models.PositiveSmallIntegerField(verbose_name='Pin Position')),
                ('pinned_at', models.DateTimeField(auto_now_add=True, verbose_name='Pinned At')),
                ('dialogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pins', to='conversation.dialogue', verbose_name='Dialogue')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialogue_pins', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'ordering': ['position', '-pinned_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='dialoguepin',
            constraint=models.UniqueConstraint(fields=('user', 'dialogue'), name='uq_dialogue_pin_user_dialogue'),
        ),
        migrations.AddConstraint(
            model_name='dialoguepin',
            constraint=models.UniqueConstraint(fields=('user', 'position'), name='uq_dialogue_pin_user_position'),
        ),
        migrations.AddConstraint(
            model_name='dialoguepin',
            constraint=models.CheckConstraint(check=models.Q(('position__gte', 1), ('position__lte', 5)), name='ck_dialogue_pin_position_range'),
        ),
    ]
