# Generated by Django 4.2.4 on 2026-04-22 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.common.utils
import validators.mediaValidators.image_validators
import validators.security_validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conversation', '0061_alter_dialogue_group_image_alter_message_audio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialogue',
            name='group_image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file], verbose_name='Group Image'),
        ),
        migrations.AlterField(
            model_name='message',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, verbose_name='Audio'),
        ),
        migrations.AlterField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='message',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, verbose_name='Video'),
        ),
        migrations.CreateModel(
            name='MessagePin',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('position', models.PositiveSmallIntegerField(verbose_name='Pin Position')),
                ('pin_duration', models.CharField(choices=[('none', 'No Expiry'), ('1_hour', '1 Hour'), ('24_hours', '24 Hours'), ('1_week', '1 Week'), ('1_month', '1 Month'), ('3_months', '3 Months')], default='none', max_length=20, verbose_name='Pin Duration')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expires At')),
                ('reminders_enabled', models.BooleanField(default=False, verbose_name='Reminders Enabled')),
                ('reminder_interval_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Reminder Interval Minutes')),
                ('next_reminder_at', models.DateTimeField(blank=True, null=True, verbose_name='Next Reminder At')),
                ('last_reminded_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Reminded At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('dialogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_pins', to='conversation.dialogue', verbose_name='Dialogue')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pins', to='conversation.message', verbose_name='Message')),
                ('pinned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_pins_created', to=settings.AUTH_USER_MODEL, verbose_name='Pinned By')),
            ],
            options={
                'ordering': ['position', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='messagepin',
            constraint=models.UniqueConstraint(fields=('dialogue', 'message'), name='uq_message_pin_dialogue_message'),
        ),
        migrations.AddConstraint(
            model_name='messagepin',
            constraint=models.UniqueConstraint(fields=('dialogue', 'position'), name='uq_message_pin_dialogue_position'),
        ),
        migrations.AddConstraint(
            model_name='messagepin',
            constraint=models.CheckConstraint(check=models.Q(('position__gte', 1), ('position__lte', 5)), name='ck_message_pin_position_range'),
        ),
    ]
