# Generated by Django 4.2.4 on 2026-01-10 00:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaConversionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('field_name', models.CharField(max_length=64)),
                ('kind', models.CharField(choices=[('video', 'Video'), ('audio', 'Audio'), ('image', 'Image')], max_length=16)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed'), ('canceled', 'Canceled')], db_index=True, default='queued', max_length=16)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('message', models.CharField(blank=True, max_length=255, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('task_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('queue', models.CharField(blank=True, max_length=32, null=True)),
                ('source_path', models.TextField(blank=True, null=True)),
                ('output_path', models.TextField(blank=True, null=True)),
                ('attempt', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=3)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='media_conve_content_8eb2ad_idx'), models.Index(fields=['status', 'updated_at'], name='media_conve_status_531b7d_idx'), models.Index(fields=['kind', 'status'], name='media_conve_kind_1ee360_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='mediaconversionjob',
            constraint=models.UniqueConstraint(fields=('content_type', 'object_id', 'field_name'), name='uniq_media_job_per_object_field'),
        ),
    ]
