# Generated by Django 4.2.4 on 2026-01-12 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_conversion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaconversionjob',
            name='stage',
            field=models.CharField(blank=True, help_text='Current processing stage (e.g. 1080p, 720p, finalize)', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='mediaconversionjob',
            name='stage_count',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Total number of stages', null=True),
        ),
        migrations.AddField(
            model_name='mediaconversionjob',
            name='stage_index',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Index of current stage', null=True),
        ),
        migrations.AddField(
            model_name='mediaconversionjob',
            name='stage_progress',
            field=models.FloatField(blank=True, help_text='Progress within this stage (0.0 – 1.0)', null=True),
        ),
        migrations.AddField(
            model_name='mediaconversionjob',
            name='stage_started_at',
            field=models.DateTimeField(blank=True, help_text='When current stage started', null=True),
        ),
        migrations.AddField(
            model_name='mediaconversionjob',
            name='stage_weight',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Weight of this stage in overall progress (percent)', null=True),
        ),
    ]
