# Generated by Django 4.2.4 on 2026-01-12 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_conversion', '0002_mediaconversionjob_stage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaconversionjob',
            name='stage_completed_weight',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Sum of weights of completed stages before current stage', null=True),
        ),
        migrations.AddField(
            model_name='mediaconversionjob',
            name='stage_plan',
            field=models.JSONField(blank=True, help_text='Ordered stage plan: [{key,label?,weight}] used for weighted timeline', null=True),
        ),
        migrations.AddField(
            model_name='mediaconversionjob',
            name='stage_total_weight',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, help_text='Sum of weights across stage_plan (cached)', null=True),
        ),
        migrations.AlterField(
            model_name='mediaconversionjob',
            name='stage',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='mediaconversionjob',
            name='stage_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mediaconversionjob',
            name='stage_index',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mediaconversionjob',
            name='stage_progress',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mediaconversionjob',
            name='stage_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mediaconversionjob',
            name='stage_weight',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
