# Generated by Django 4.2.4 on 2026-08-12 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_conversion', '0003_mediaconversionjob_stage_completed_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaconversionjob',
            name='payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='mediaconversionjob',
            name='task_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mediaconversionjob',
            name='kind',
            field=models.CharField(choices=[('video', 'Video'), ('audio', 'Audio'), ('image', 'Image'), ('workflow', 'Workflow')], max_length=16),
        ),
    ]
