# Generated by Django 4.2.4 on 2026-08-12 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_conversion', '0004_mediaconversionjob_payload_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mediaconversionjob',
            old_name='task_name',
            new_name='workflow_handler',
        ),
    ]
