# Generated by Django 4.2.4 on 2026-08-14 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentSafetyEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('input_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video')], db_index=True, default='text', max_length=16)),
                ('input_hash', models.CharField(db_index=True, max_length=64)),
                ('context', models.CharField(choices=[('generic', 'Generic'), ('moment_caption', 'Moment Caption'), ('prayer', 'Prayer'), ('testimony', 'Testimony'), ('comment', 'Comment'), ('reply', 'Reply'), ('journey_text', 'Journey Text'), ('profile_text', 'Profile Text'), ('group_text', 'Group Text')], db_index=True, default='generic', max_length=40)),
                ('field_name', models.CharField(blank=True, default='', max_length=80)),
                ('decision', models.CharField(choices=[('allow', 'Allow'), ('review', 'Review'), ('block', 'Block')], db_index=True, max_length=16)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, max_length=16)),
                ('reason_code', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('policy_version', models.CharField(db_index=True, max_length=32)),
                ('provider', models.CharField(blank=True, default='', max_length=32)),
                ('provider_model', models.CharField(blank=True, default='', max_length=80)),
                ('provider_flagged', models.BooleanField(default=False)),
                ('adjudicated', models.BooleanField(db_index=True, default=False)),
                ('adjudication_model', models.CharField(blank=True, default='', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_safety_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Content Safety Event',
                'verbose_name_plural': 'Content Safety Events',
            },
        ),
        migrations.CreateModel(
            name='ContentSafetyAnalysisCache',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('input_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video')], db_index=True, max_length=16)),
                ('input_hash', models.CharField(db_index=True, max_length=64)),
                ('provider', models.CharField(db_index=True, default='openai', max_length=32)),
                ('provider_model', models.CharField(db_index=True, max_length=80)),
                ('provider_response_id', models.CharField(blank=True, default='', max_length=120)),
                ('flagged', models.BooleanField(db_index=True, default=False)),
                ('categories', models.JSONField(blank=True, default=dict)),
                ('category_scores', models.JSONField(blank=True, default=dict)),
                ('applied_input_types', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'verbose_name': 'Content Safety Analysis Cache',
                'verbose_name_plural': 'Content Safety Analysis Caches',
                'indexes': [models.Index(fields=['input_type', 'input_hash', 'provider', 'provider_model'], name='safety_analysis_lookup_idx'), models.Index(fields=['expires_at'], name='safety_analysis_expiry_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='contentsafetyanalysiscache',
            constraint=models.UniqueConstraint(fields=('input_type', 'input_hash', 'provider', 'provider_model'), name='uniq_content_safety_analysis'),
        ),
        migrations.AddIndex(
            model_name='contentsafetyevent',
            index=models.Index(fields=['decision', 'created_at'], name='safety_event_decision_idx'),
        ),
        migrations.AddIndex(
            model_name='contentsafetyevent',
            index=models.Index(fields=['context', 'created_at'], name='safety_event_context_idx'),
        ),
    ]
