# Generated by Django 4.2.4 on 2026-08-14 06:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('content_safety', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentSafetyAdjudicationCache',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('input_hash', models.CharField(db_index=True, max_length=64)),
                ('context', models.CharField(choices=[('generic', 'Generic'), ('moment_caption', 'Moment Caption'), ('prayer', 'Prayer'), ('testimony', 'Testimony'), ('comment', 'Comment'), ('reply', 'Reply'), ('journey_text', 'Journey Text'), ('profile_text', 'Profile Text'), ('group_text', 'Group Text')], db_index=True, max_length=40)),
                ('signal_hash', models.CharField(db_index=True, max_length=64)),
                ('policy_version', models.CharField(db_index=True, max_length=32)),
                ('model', models.CharField(db_index=True, max_length=80)),
                ('decision', models.CharField(choices=[('allow', 'Allow'), ('review', 'Review'), ('block', 'Block')], db_index=True, max_length=16)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, max_length=16)),
                ('reason_code', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'verbose_name': 'Content Safety Adjudication Cache',
                'verbose_name_plural': 'Content Safety Adjudication Caches',
                'indexes': [models.Index(fields=['input_hash', 'context', 'signal_hash', 'policy_version', 'model'], name='safety_adj_lookup_idx'), models.Index(fields=['expires_at'], name='safety_adj_expiry_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='contentsafetyadjudicationcache',
            constraint=models.UniqueConstraint(fields=('input_hash', 'context', 'signal_hash', 'policy_version', 'model'), name='uniq_safety_adjudication'),
        ),
    ]
