# Generated by Django 4.2.4 on 2026-08-14 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_safety', '0002_contentsafetyadjudicationcache_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentsafetyadjudicationcache',
            name='context',
            field=models.CharField(choices=[('generic', 'Generic'), ('moment_caption', 'Moment Caption'), ('prayer', 'Prayer'), ('testimony', 'Testimony'), ('comment', 'Comment'), ('reply', 'Reply'), ('journey_text', 'Journey Text'), ('profile_text', 'Profile Text'), ('group_text', 'Group Text'), ('group_message', 'Group Message'), ('moment_media', 'Moment Media'), ('prayer_media', 'Prayer Media'), ('testimony_media', 'Testimony Media'), ('journey_media', 'Journey Media'), ('profile_media', 'Profile Media'), ('group_message_media', 'Group Message Media')], db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='contentsafetyevent',
            name='context',
            field=models.CharField(choices=[('generic', 'Generic'), ('moment_caption', 'Moment Caption'), ('prayer', 'Prayer'), ('testimony', 'Testimony'), ('comment', 'Comment'), ('reply', 'Reply'), ('journey_text', 'Journey Text'), ('profile_text', 'Profile Text'), ('group_text', 'Group Text'), ('group_message', 'Group Message'), ('moment_media', 'Moment Media'), ('prayer_media', 'Prayer Media'), ('testimony_media', 'Testimony Media'), ('journey_media', 'Journey Media'), ('profile_media', 'Profile Media'), ('group_message_media', 'Group Message Media')], db_index=True, default='generic', max_length=40),
        ),
    ]
