# Generated by Django 4.2.4 on 2026-08-26 00:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('content_safety', '0003_alter_contentsafetyadjudicationcache_context_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentsafetyadjudicationcache',
            name='context',
            field=models.CharField(choices=[('generic', 'Generic'), ('moment_caption', 'Moment Caption'), ('prayer', 'Prayer'), ('testimony', 'Testimony'), ('comment', 'Comment'), ('reply', 'Reply'), ('journey_text', 'Journey Text'), ('profile_text', 'Profile Text'), ('group_text', 'Group Text'), ('group_message', 'Group Message'), ('moment_media', 'Moment Media'), ('prayer_media', 'Prayer Media'), ('testimony_media', 'Testimony Media'), ('journey_media', 'Journey Media'), ('profile_media', 'Profile Media'), ('group_message_media', 'Group Message Media'), ('moment_image', 'Moment Image'), ('testimony_image', 'Testimony Image'), ('journey_image', 'Journey Image'), ('group_image', 'Group Image')], db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='contentsafetyevent',
            name='context',
            field=models.CharField(choices=[('generic', 'Generic'), ('moment_caption', 'Moment Caption'), ('prayer', 'Prayer'), ('testimony', 'Testimony'), ('comment', 'Comment'), ('reply', 'Reply'), ('journey_text', 'Journey Text'), ('profile_text', 'Profile Text'), ('group_text', 'Group Text'), ('group_message', 'Group Message'), ('moment_media', 'Moment Media'), ('prayer_media', 'Prayer Media'), ('testimony_media', 'Testimony Media'), ('journey_media', 'Journey Media'), ('profile_media', 'Profile Media'), ('group_message_media', 'Group Message Media'), ('moment_image', 'Moment Image'), ('testimony_image', 'Testimony Image'), ('journey_image', 'Journey Image'), ('group_image', 'Group Image')], db_index=True, default='generic', max_length=40),
        ),
        migrations.CreateModel(
            name='ContentSafetyJob',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('object_id', models.PositiveBigIntegerField(db_index=True)),
                ('field_name', models.CharField(db_index=True, max_length=80)),
                ('input_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video')], db_index=True, default='video', max_length=16)),
                ('context', models.CharField(choices=[('generic', 'Generic'), ('moment_caption', 'Moment Caption'), ('prayer', 'Prayer'), ('testimony', 'Testimony'), ('comment', 'Comment'), ('reply', 'Reply'), ('journey_text', 'Journey Text'), ('profile_text', 'Profile Text'), ('group_text', 'Group Text'), ('group_message', 'Group Message'), ('moment_media', 'Moment Media'), ('prayer_media', 'Prayer Media'), ('testimony_media', 'Testimony Media'), ('journey_media', 'Journey Media'), ('profile_media', 'Profile Media'), ('group_message_media', 'Group Message Media'), ('moment_image', 'Moment Image'), ('testimony_image', 'Testimony Image'), ('journey_image', 'Journey Image'), ('group_image', 'Group Image')], db_index=True, max_length=40)),
                ('source_path', models.CharField(max_length=1000)),
                ('mime_type', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('done', 'Done'), ('blocked', 'Blocked'), ('review', 'Review Required'), ('failed', 'Failed'), ('canceled', 'Canceled')], db_index=True, default='queued', max_length=16)),
                ('decision', models.CharField(blank=True, choices=[('allow', 'Allow'), ('review', 'Review'), ('block', 'Block')], db_index=True, default='', max_length=16)),
                ('reason_code', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('retryable', models.BooleanField(db_index=True, default=False)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('stage', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('message', models.CharField(blank=True, default='', max_length=255)),
                ('error', models.TextField(blank=True, default='')),
                ('task_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('attempt', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('handoff_job_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_safety_jobs', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_safety_jobs', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Content Safety Job',
                'verbose_name_plural': 'Content Safety Jobs',
                'indexes': [models.Index(fields=['content_type', 'object_id', 'field_name'], name='safety_job_target_idx'), models.Index(fields=['actor', 'status'], name='safety_job_actor_status_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='contentsafetyjob',
            constraint=models.UniqueConstraint(fields=('content_type', 'object_id', 'field_name'), name='uniq_content_safety_target_field'),
        ),
    ]
