# Generated by Django 4.2.4 on 2026-08-26 01:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('content_safety', '0004_alter_contentsafetyadjudicationcache_context_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentsafetyjob',
            name='handoff_job_id',
        ),
        migrations.AddField(
            model_name='contentsafetyjob',
            name='conversion_job_id',
            field=models.PositiveBigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='contentsafetyjob',
            name='input_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='contentsafetyjob',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='contentsafetyjob',
            name='risk_level',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='contentsafetyjob',
            name='attempt',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='contentsafetyjob',
            name='input_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video')], db_index=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='contentsafetyjob',
            name='stage',
            field=models.CharField(choices=[('queued', 'Queued'), ('checking', 'Checking'), ('handoff', 'Handoff'), ('approved_waiting', 'Approved - Waiting'), ('handed_off', 'Handed Off'), ('finished', 'Finished'), ('handoff_failed', 'Handoff Failed'), ('failed', 'Failed'), ('canceled', 'Canceled')], db_index=True, default='queued', max_length=32),
        ),
        migrations.AlterField(
            model_name='contentsafetyjob',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed'), ('canceled', 'Canceled')], db_index=True, default='queued', max_length=16),
        ),
        migrations.AddIndex(
            model_name='contentsafetyjob',
            index=models.Index(fields=['status', 'updated_at'], name='safety_job_status_time_idx'),
        ),
    ]
