# Generated by Django 4.2.4 on 2026-07-20 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import utils.common.utils
import uuid
import validators.mediaValidators.audio_validators
import validators.mediaValidators.image_validators
import validators.security_validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audio_catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioPlaybackSession',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('session_id', models.UUIDField(db_index=True, unique=True)),
                ('surface', models.CharField(choices=[('audio_library', 'Audio Library'), ('search', 'Search'), ('trending', 'Trending'), ('recommended', 'Recommended'), ('recent', 'Recent'), ('favorites', 'Favorites'), ('content_creation', 'Content Creation'), ('moment', 'Moment'), ('testimony', 'Testimony'), ('profile', 'Profile'), ('deep_link', 'Deep Link'), ('other', 'Other')], db_index=True, default='other', max_length=32)),
                ('source_context', models.JSONField(blank=True, default=dict)),
                ('client_platform', models.CharField(blank=True, db_index=True, default='', max_length=24)),
                ('client_version', models.CharField(blank=True, default='', max_length=40)),
                ('device_id_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('duration_ms_snapshot', models.PositiveIntegerField(default=1)),
                ('max_position_ms', models.PositiveIntegerField(default=0)),
                ('listened_ms', models.PositiveBigIntegerField(default=0)),
                ('last_sequence', models.PositiveIntegerField(default=0)),
                ('play_counted', models.BooleanField(default=False)),
                ('qualified_play', models.BooleanField(db_index=True, default=False)),
                ('completed', models.BooleanField(db_index=True, default=False)),
                ('early_skipped', models.BooleanField(db_index=True, default=False)),
                ('used_in_content', models.BooleanField(default=False)),
                ('is_test_session', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('end_reason', models.CharField(blank=True, choices=[('completed', 'Completed'), ('paused', 'Paused'), ('switched_track', 'Switched Track'), ('dismissed', 'Dismissed'), ('backgrounded', 'Backgrounded'), ('error', 'Error'), ('used_in_content', 'Used in Content'), ('stale', 'Stale')], db_index=True, default='', max_length=24)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Audio Playback Session',
                'verbose_name_plural': 'Audio Playback Sessions',
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AudioTrackDailyListener',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AudioTrackDailyMetric',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('starts', models.PositiveBigIntegerField(default=0)),
                ('qualified_plays', models.PositiveBigIntegerField(default=0)),
                ('unique_listeners', models.PositiveBigIntegerField(default=0)),
                ('total_listened_ms', models.PositiveBigIntegerField(default=0)),
                ('completions', models.PositiveBigIntegerField(default=0)),
                ('early_skips', models.PositiveBigIntegerField(default=0)),
                ('usages', models.PositiveBigIntegerField(default=0)),
                ('unique_usage_users', models.PositiveBigIntegerField(default=0)),
                ('trending_score', models.DecimalField(db_index=True, decimal_places=6, default=0, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Audio Track Daily Metric',
                'verbose_name_plural': 'Audio Track Daily Metrics',
                'ordering': ['-date', '-trending_score', 'track_id'],
            },
        ),
        migrations.CreateModel(
            name='AudioTrackDailyUsageUser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Audio Track Daily Usage User',
                'verbose_name_plural': 'Audio Track Daily Usage Users',
            },
        ),
        migrations.CreateModel(
            name='AudioTrackMetric',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('total_starts', models.PositiveBigIntegerField(default=0)),
                ('total_qualified_plays', models.PositiveBigIntegerField(default=0)),
                ('total_unique_listeners', models.PositiveBigIntegerField(default=0)),
                ('total_listened_ms', models.PositiveBigIntegerField(default=0)),
                ('total_completions', models.PositiveBigIntegerField(default=0)),
                ('total_early_skips', models.PositiveBigIntegerField(default=0)),
                ('total_usages', models.PositiveBigIntegerField(default=0)),
                ('active_usages', models.PositiveBigIntegerField(default=0)),
                ('total_unique_usage_users', models.PositiveBigIntegerField(default=0)),
                ('trending_score', models.DecimalField(db_index=True, decimal_places=6, default=0, max_digits=20)),
                ('quality_score', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('usage_score', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('last_played_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Audio Track Metric',
                'verbose_name_plural': 'Audio Track Metrics',
                'ordering': ['-trending_score', '-total_qualified_plays', 'track_id'],
            },
        ),
        migrations.CreateModel(
            name='AudioTrackUsageUser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_used_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Audio Track Usage User',
                'verbose_name_plural': 'Audio Track Usage Users',
            },
        ),
        migrations.CreateModel(
            name='AudioUserTrackAffinity',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('total_listened_ms', models.PositiveBigIntegerField(default=0)),
                ('qualified_play_count', models.PositiveBigIntegerField(default=0)),
                ('completion_count', models.PositiveBigIntegerField(default=0)),
                ('early_skip_count', models.PositiveBigIntegerField(default=0)),
                ('usage_count', models.PositiveBigIntegerField(default=0)),
                ('affinity_score', models.DecimalField(db_index=True, decimal_places=6, default=0, max_digits=14)),
                ('first_listened_at', models.DateTimeField(blank=True, null=True)),
                ('last_listened_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Audio User Track Affinity',
                'verbose_name_plural': 'Audio User Track Affinities',
            },
        ),
        migrations.AlterModelOptions(
            name='audiocatalog',
            options={'ordering': ['sort_order', 'name', 'id'], 'verbose_name': 'Audio Catalog', 'verbose_name_plural': 'Audio Catalogs'},
        ),
        migrations.AlterModelOptions(
            name='audiocategory',
            options={'ordering': ['sort_order', 'name', 'id'], 'verbose_name': 'Audio Category', 'verbose_name_plural': 'Audio Categories'},
        ),
        migrations.AlterModelOptions(
            name='audiogenre',
            options={'ordering': ['sort_order', 'name', 'id'], 'verbose_name': 'Audio Genre', 'verbose_name_plural': 'Audio Genres'},
        ),
        migrations.AlterModelOptions(
            name='audiomood',
            options={'ordering': ['sort_order', 'name', 'id'], 'verbose_name': 'Audio Mood', 'verbose_name_plural': 'Audio Moods'},
        ),
        migrations.AlterModelOptions(
            name='audiotag',
            options={'ordering': ['sort_order', 'name', 'id'], 'verbose_name': 'Audio Tag', 'verbose_name_plural': 'Audio Tags'},
        ),
        migrations.AlterModelOptions(
            name='audiousagegrant',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Audio Usage Grant', 'verbose_name_plural': 'Audio Usage Grants'},
        ),
        migrations.AlterModelOptions(
            name='musictrack',
            options={'ordering': ('sort_order', '-published_at', 'title', 'id'), 'verbose_name': 'Music Track', 'verbose_name_plural': 'Music Tracks'},
        ),
        migrations.AddField(
            model_name='audiousagegrant',
            name='analytics_activated_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, help_text='Set after activation analytics were counted.', null=True),
        ),
        migrations.AddField(
            model_name='audiousagegrant',
            name='analytics_revoked_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, help_text='Set after active usage analytics were decremented.', null=True),
        ),
        migrations.AlterField(
            model_name='audiocatalog',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='audiocatalog',
            name='slug',
            field=models.SlugField(blank=True, max_length=140, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='audiocategory',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='audiocategory',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='audiocategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=140, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='audiogenre',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='audiogenre',
            name='slug',
            field=models.SlugField(blank=True, max_length=140, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='audiomood',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='audiomood',
            name='slug',
            field=models.SlugField(blank=True, max_length=140, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='audiotag',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='audiotag',
            name='slug',
            field=models.SlugField(blank=True, max_length=140, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='audiousagegrant',
            name='artist_snapshot',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='audiousagegrant',
            name='revoke_reason',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='musicartwork',
            name='image',
            field=models.ImageField(max_length=700, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file]),
        ),
        migrations.AlterField(
            model_name='musictrack',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='musictrack',
            name='language_code',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='musictrack',
            name='musical_key',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='musictrack',
            name='search_document',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='musictrack',
            name='slug',
            field=models.SlugField(blank=True, max_length=140, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='musictrack',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='musictrack',
            name='time_signature',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='musictrackvariant',
            name='audio_file',
            field=models.FileField(max_length=700, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.audio_validators.validate_audio_file, validators.security_validators.validate_no_executable_file]),
        ),
        migrations.AlterField(
            model_name='musictrackvariant',
            name='waveform_file',
            field=models.FileField(blank=True, max_length=700, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.security_validators.validate_no_executable_file]),
        ),
        migrations.AlterField(
            model_name='rightsevidence',
            name='evidence_file',
            field=models.FileField(max_length=700, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.security_validators.validate_no_executable_file]),
        ),
        migrations.AddIndex(
            model_name='audiousagegrant',
            index=models.Index(fields=['granted_to', 'created_at'], name='audio_catal_granted_5ac2be_idx'),
        ),
        migrations.AddIndex(
            model_name='audiousagegrant',
            index=models.Index(fields=['status', 'analytics_activated_at'], name='audio_catal_status_6d653c_idx'),
        ),
        migrations.AddField(
            model_name='audiousertrackaffinity',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_affinities', to='audio_catalog.musictrack'),
        ),
        migrations.AddField(
            model_name='audiousertrackaffinity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_track_affinities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='audiotrackusageuser',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifetime_usage_users', to='audio_catalog.musictrack'),
        ),
        migrations.AddField(
            model_name='audiotrackusageuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_lifetime_usage_rows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='audiotrackmetric',
            name='track',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_metric', to='audio_catalog.musictrack'),
        ),
        migrations.AddField(
            model_name='audiotrackdailyusageuser',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_usage_users', to='audio_catalog.musictrack'),
        ),
        migrations.AddField(
            model_name='audiotrackdailyusageuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_daily_usage_rows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='audiotrackdailymetric',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_analytics', to='audio_catalog.musictrack'),
        ),
        migrations.AddField(
            model_name='audiotrackdailylistener',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_listener_rows', to='audio_catalog.musictrack'),
        ),
        migrations.AddField(
            model_name='audiotrackdailylistener',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_daily_listener_rows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='audioplaybacksession',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playback_sessions', to='audio_catalog.musictrack'),
        ),
        migrations.AddField(
            model_name='audioplaybacksession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audio_playback_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='audioplaybacksession',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playback_sessions', to='audio_catalog.musictrackvariant'),
        ),
        migrations.AddIndex(
            model_name='audiousertrackaffinity',
            index=models.Index(fields=['user', 'affinity_score'], name='audio_catal_user_id_0918d9_idx'),
        ),
        migrations.AddIndex(
            model_name='audiousertrackaffinity',
            index=models.Index(fields=['track', 'affinity_score'], name='audio_catal_track_i_45bd9e_idx'),
        ),
        migrations.AddConstraint(
            model_name='audiousertrackaffinity',
            constraint=models.UniqueConstraint(fields=('user', 'track'), name='audio_unique_user_track_affinity'),
        ),
        migrations.AddIndex(
            model_name='audiotrackusageuser',
            index=models.Index(fields=['track', 'first_used_at'], name='audio_catal_track_i_2d9ee8_idx'),
        ),
        migrations.AddIndex(
            model_name='audiotrackusageuser',
            index=models.Index(fields=['user', 'first_used_at'], name='audio_catal_user_id_847ba9_idx'),
        ),
        migrations.AddConstraint(
            model_name='audiotrackusageuser',
            constraint=models.UniqueConstraint(fields=('track', 'user'), name='audio_unique_lifetime_track_usage_user'),
        ),
        migrations.AddIndex(
            model_name='audiotrackmetric',
            index=models.Index(fields=['trending_score', 'total_qualified_plays'], name='audio_catal_trendin_9b58fe_idx'),
        ),
        migrations.AddIndex(
            model_name='audiotrackmetric',
            index=models.Index(fields=['last_played_at'], name='audio_catal_last_pl_e1db29_idx'),
        ),
        migrations.AddIndex(
            model_name='audiotrackdailyusageuser',
            index=models.Index(fields=['date', 'track'], name='audio_catal_date_130c77_idx'),
        ),
        migrations.AddIndex(
            model_name='audiotrackdailyusageuser',
            index=models.Index(fields=['user', 'date'], name='audio_catal_user_id_8fda29_idx'),
        ),
        migrations.AddConstraint(
            model_name='audiotrackdailyusageuser',
            constraint=models.UniqueConstraint(fields=('track', 'user', 'date'), name='audio_unique_daily_track_usage_user'),
        ),
        migrations.AddIndex(
            model_name='audiotrackdailymetric',
            index=models.Index(fields=['date', 'trending_score'], name='audio_catal_date_ed52bb_idx'),
        ),
        migrations.AddIndex(
            model_name='audiotrackdailymetric',
            index=models.Index(fields=['track', 'date'], name='audio_catal_track_i_90d040_idx'),
        ),
        migrations.AddConstraint(
            model_name='audiotrackdailymetric',
            constraint=models.UniqueConstraint(fields=('track', 'date'), name='audio_unique_track_daily_metric'),
        ),
        migrations.AddIndex(
            model_name='audiotrackdailylistener',
            index=models.Index(fields=['date', 'track'], name='audio_catal_date_d76bd9_idx'),
        ),
        migrations.AddConstraint(
            model_name='audiotrackdailylistener',
            constraint=models.UniqueConstraint(fields=('track', 'user', 'date'), name='audio_unique_daily_track_listener'),
        ),
        migrations.AddIndex(
            model_name='audioplaybacksession',
            index=models.Index(fields=['track', 'started_at'], name='audio_catal_track_i_5e75f8_idx'),
        ),
        migrations.AddIndex(
            model_name='audioplaybacksession',
            index=models.Index(fields=['user', 'started_at'], name='audio_catal_user_id_e1a226_idx'),
        ),
        migrations.AddIndex(
            model_name='audioplaybacksession',
            index=models.Index(fields=['track', 'qualified_play', 'started_at'], name='audio_catal_track_i_4b1810_idx'),
        ),
        migrations.AddIndex(
            model_name='audioplaybacksession',
            index=models.Index(fields=['track', 'completed', 'started_at'], name='audio_catal_track_i_ed404a_idx'),
        ),
        migrations.AddIndex(
            model_name='audioplaybacksession',
            index=models.Index(fields=['surface', 'started_at'], name='audio_catal_surface_aa02d4_idx'),
        ),
        migrations.AddIndex(
            model_name='audioplaybacksession',
            index=models.Index(fields=['is_active', 'last_heartbeat_at'], name='audio_catal_is_acti_6fc621_idx'),
        ),
        migrations.AddIndex(
            model_name='audioplaybacksession',
            index=models.Index(fields=['is_test_session', 'started_at'], name='audio_catal_is_test_808126_idx'),
        ),
        migrations.AddConstraint(
            model_name='audioplaybacksession',
            constraint=models.CheckConstraint(check=models.Q(('duration_ms_snapshot__gt', 0)), name='audio_playback_duration_gt_zero'),
        ),
    ]
