# Generated by Django 4.2.4 on 2026-07-22 06:51

from django.db import migrations, models
import utils.common.utils
import validators.mediaValidators.audio_validators
import validators.mediaValidators.image_validators
import validators.security_validators


class Migration(migrations.Migration):

    dependencies = [
        ('audio_catalog', '0002_audioplaybacksession_audiotrackdailylistener_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audioplaybacksession',
            name='surface',
            field=models.CharField(choices=[('audio_library', 'Audio Library'), ('search', 'Search'), ('trending', 'Trending'), ('recommended', 'Recommended'), ('recent', 'Recent'), ('favorites', 'Favorites'), ('content_creation', 'Content Creation'), ('moment', 'Moment'), ('testimony', 'Testimony'), ('journey', 'Journey'), ('profile', 'Profile'), ('deep_link', 'Deep Link'), ('other', 'Other')], db_index=True, default='other', max_length=32),
        ),
        migrations.AlterField(
            model_name='musicartwork',
            name='image',
            field=models.ImageField(max_length=700, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file]),
        ),
        migrations.AlterField(
            model_name='musictrackvariant',
            name='audio_file',
            field=models.FileField(max_length=700, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.audio_validators.validate_audio_file, validators.security_validators.validate_no_executable_file]),
        ),
        migrations.AlterField(
            model_name='musictrackvariant',
            name='waveform_file',
            field=models.FileField(blank=True, max_length=700, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.security_validators.validate_no_executable_file]),
        ),
        migrations.AlterField(
            model_name='rightsevidence',
            name='evidence_file',
            field=models.FileField(max_length=700, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.security_validators.validate_no_executable_file]),
        ),
    ]
