# Generated by Django 4.2.4 on 2026-07-24 07:24

from django.db import migrations, models
import utils.common.utils
import validators.mediaValidators.audio_validators
import validators.mediaValidators.image_validators
import validators.security_validators


class Migration(migrations.Migration):

    dependencies = [
        ('audio_catalog', '0003_alter_audioplaybacksession_surface_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicartwork',
            name='image',
            field=models.ImageField(max_length=700, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file]),
        ),
        migrations.AlterField(
            model_name='musictrackvariant',
            name='audio_file',
            field=models.FileField(max_length=700, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.audio_validators.validate_audio_file, validators.security_validators.validate_no_executable_file]),
        ),
        migrations.AlterField(
            model_name='musictrackvariant',
            name='waveform_file',
            field=models.FileField(blank=True, max_length=700, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.security_validators.validate_no_executable_file]),
        ),
        migrations.AlterField(
            model_name='rightsevidence',
            name='evidence_file',
            field=models.FileField(max_length=700, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.security_validators.validate_no_executable_file]),
        ),
    ]
