# Generated by Django 4.2.4 on 2026-09-02 21:44

from django.db import migrations, models
import utils.common.utils
import validators.mediaValidators.audio_validators
import validators.mediaValidators.image_validators
import validators.security_validators


class Migration(migrations.Migration):

    dependencies = [
        ('audio_catalog', '0006_alter_musicartwork_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audiousagegrant',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.AlterModelOptions(
            name='musicartwork',
            options={'ordering': ['sort_order', '-is_primary', 'id']},
        ),
        migrations.AlterModelOptions(
            name='musictrackvariant',
            options={'ordering': ['sort_order', 'variant_type', 'id']},
        ),
        migrations.RemoveConstraint(
            model_name='audiousagegrant',
            name='audio_one_active_usage_per_content',
        ),
        migrations.RemoveConstraint(
            model_name='musicartwork',
            name='audio_one_active_primary_artwork',
        ),
        migrations.RemoveConstraint(
            model_name='musictrackvariant',
            name='audio_one_active_default_variant',
        ),
        migrations.AddField(
            model_name='audiousagegrant',
            name='active_slot',
            field=models.PositiveSmallIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='musicartwork',
            name='primary_slot',
            field=models.PositiveSmallIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='musictrackvariant',
            name='default_slot',
            field=models.PositiveSmallIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='musicartwork',
            name='image',
            field=models.ImageField(max_length=700, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file]),
        ),
        migrations.AlterField(
            model_name='musictrackvariant',
            name='audio_file',
            field=models.FileField(max_length=700, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.audio_validators.validate_audio_file, validators.security_validators.validate_no_executable_file]),
        ),
        migrations.AlterField(
            model_name='musictrackvariant',
            name='waveform_file',
            field=models.FileField(blank=True, max_length=700, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.security_validators.validate_no_executable_file]),
        ),
        migrations.AlterField(
            model_name='rightsevidence',
            name='evidence_file',
            field=models.FileField(max_length=700, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.security_validators.validate_no_executable_file]),
        ),
        migrations.AddConstraint(
            model_name='audiousagegrant',
            constraint=models.UniqueConstraint(fields=('content_type', 'object_id', 'active_slot'), name='audio_one_active_usage_per_content'),
        ),
        migrations.AddConstraint(
            model_name='musicartwork',
            constraint=models.UniqueConstraint(fields=('track', 'primary_slot'), name='audio_one_active_primary_artwork'),
        ),
        migrations.AddConstraint(
            model_name='musictrackvariant',
            constraint=models.UniqueConstraint(fields=('track', 'default_slot'), name='audio_one_active_default_variant'),
        ),
    ]
