# Generated by Django 4.2.4 on 2026-09-15 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.common.utils
import uuid
import validators.mediaValidators.audio_validators
import validators.mediaValidators.image_validators
import validators.security_validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audio_catalog', '0008_musiclyrics_musiclyricsline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicartwork',
            name='image',
            field=models.ImageField(max_length=700, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file]),
        ),
        migrations.AlterField(
            model_name='musictrackvariant',
            name='audio_file',
            field=models.FileField(max_length=700, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.audio_validators.validate_audio_file, validators.security_validators.validate_no_executable_file]),
        ),
        migrations.AlterField(
            model_name='musictrackvariant',
            name='waveform_file',
            field=models.FileField(blank=True, max_length=700, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.security_validators.validate_no_executable_file]),
        ),
        migrations.AlterField(
            model_name='rightsevidence',
            name='evidence_file',
            field=models.FileField(max_length=700, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.security_validators.validate_no_executable_file]),
        ),
        migrations.CreateModel(
            name='AudioUserTrackLibraryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_favorite', models.BooleanField(db_index=True, default=False)),
                ('favorited_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_library_entries', to='audio_catalog.musictrack')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_library_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audio User Track Library Entry',
                'verbose_name_plural': 'Audio User Track Library Entries',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['user', '-created_at'], name='audio_library_user_saved_idx'), models.Index(fields=['user', 'is_favorite', '-favorited_at'], name='audio_library_user_fav_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='audiousertracklibraryentry',
            constraint=models.UniqueConstraint(fields=('user', 'track'), name='audio_unique_user_track_library_entry'),
        ),
    ]
