# Generated by Django 4.2.4 on 2026-09-15 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.common.utils
import utils.mixins.media_autoconvert
import utils.mixins.media_conversion
import uuid
import validators.mediaValidators.image_validators
import validators.security_validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audio_catalog', '0010_alter_musicartwork_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=140, null=True, unique=True, verbose_name='Slug')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('subtitle', models.CharField(blank=True, default='', max_length=180)),
                ('description', models.TextField(blank=True, default='')),
                ('release_type', models.CharField(choices=[('single', 'Single'), ('ep', 'EP'), ('album', 'Album')], db_index=True, max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('published', 'Published'), ('suspended', 'Suspended'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('language_code', models.CharField(blank=True, default='', max_length=16)),
                ('release_date', models.DateField(blank=True, db_index=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('version', models.PositiveIntegerField(default=1)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='releases', to='audio_catalog.audiocatalog')),
            ],
            options={
                'verbose_name': 'Music Release',
                'verbose_name_plural': 'Music Releases',
                'ordering': ('-release_date', '-published_at', 'title', 'id'),
            },
        ),
        migrations.CreateModel(
            name='MusicReleaseTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disc_number', models.PositiveSmallIntegerField(default=1)),
                ('track_number', models.PositiveSmallIntegerField()),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_links', to='audio_catalog.musicrelease')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='release_links', to='audio_catalog.musictrack')),
            ],
            options={
                'verbose_name': 'Music Release Track',
                'verbose_name_plural': 'Music Release Tracks',
                'ordering': ('disc_number', 'track_number', 'id'),
            },
        ),
        migrations.CreateModel(
            name='MusicReleaseContributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('primary_artist', 'Primary Artist'), ('composer', 'Composer'), ('lyricist', 'Lyricist'), ('producer', 'Producer'), ('arranger', 'Arranger'), ('performer', 'Performer'), ('mix_engineer', 'Mix Engineer'), ('mastering_engineer', 'Mastering Engineer'), ('ai_provider', 'AI Provider'), ('creative_director', 'Creative Director'), ('other', 'Other')], db_index=True, max_length=40)),
                ('credit_text', models.CharField(blank=True, default='', max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='release_links', to='audio_catalog.audiocontributor')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributor_links', to='audio_catalog.musicrelease')),
            ],
            options={
                'verbose_name': 'Music Release Contributor',
                'verbose_name_plural': 'Music Release Contributors',
                'ordering': ('sort_order', 'role', 'id'),
            },
        ),
        migrations.CreateModel(
            name='MusicReleaseArtwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_assets', models.JSONField(blank=True, default=dict)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('primary', 'Primary'), ('thumbnail', 'Thumbnail'), ('player', 'Player'), ('background', 'Background'), ('alternate', 'Alternate')], db_index=True, default='primary', max_length=20)),
                ('label', models.CharField(blank=True, default='', max_length=120)),
                ('image', models.ImageField(max_length=700, upload_to=utils.common.utils.FileUpload('audio_catalog', 'artworks', 'releases'), validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file])),
                ('is_converted', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_primary', models.BooleanField(db_index=True, default=False)),
                ('primary_slot', models.PositiveSmallIntegerField(blank=True, editable=False, null=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('aspect_ratio', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
                ('dominant_color', models.CharField(blank=True, default='', max_length=16)),
                ('blurhash', models.CharField(blank=True, default='', max_length=180)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='audio_catalog.musicrelease')),
            ],
            options={
                'verbose_name': 'Music Release Artwork',
                'verbose_name_plural': 'Music Release Artworks',
                'ordering': ('sort_order', '-is_primary', 'id'),
            },
            bases=(utils.mixins.media_autoconvert.MediaAutoConvertMixin, utils.mixins.media_conversion.MediaConversionMixin, models.Model),
        ),
        migrations.AddField(
            model_name='musicrelease',
            name='contributors',
            field=models.ManyToManyField(related_name='releases', through='audio_catalog.MusicReleaseContributor', to='audio_catalog.audiocontributor'),
        ),
        migrations.AddField(
            model_name='musicrelease',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audio_releases_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='musicrelease',
            name='tracks',
            field=models.ManyToManyField(related_name='releases', through='audio_catalog.MusicReleaseTrack', to='audio_catalog.musictrack'),
        ),
        migrations.AddField(
            model_name='musicrelease',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audio_releases_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='musicreleasetrack',
            index=models.Index(fields=['release', 'disc_number', 'track_number'], name='audio_release_track_order_idx'),
        ),
        migrations.AddIndex(
            model_name='musicreleasetrack',
            index=models.Index(fields=['track', 'release'], name='audio_track_release_idx'),
        ),
        migrations.AddConstraint(
            model_name='musicreleasetrack',
            constraint=models.CheckConstraint(check=models.Q(('disc_number__gte', 1)), name='audio_release_disc_number_gte_one'),
        ),
        migrations.AddConstraint(
            model_name='musicreleasetrack',
            constraint=models.CheckConstraint(check=models.Q(('track_number__gte', 1)), name='audio_release_track_number_gte_one'),
        ),
        migrations.AddConstraint(
            model_name='musicreleasetrack',
            constraint=models.UniqueConstraint(fields=('release', 'track'), name='audio_unique_release_track'),
        ),
        migrations.AddConstraint(
            model_name='musicreleasetrack',
            constraint=models.UniqueConstraint(fields=('release', 'disc_number', 'track_number'), name='audio_unique_release_track_position'),
        ),
        migrations.AddIndex(
            model_name='musicreleasecontributor',
            index=models.Index(fields=['release', 'role', 'sort_order'], name='audio_release_contrib_idx'),
        ),
        migrations.AddConstraint(
            model_name='musicreleasecontributor',
            constraint=models.UniqueConstraint(fields=('release', 'contributor', 'role'), name='audio_unique_release_contributor_role'),
        ),
        migrations.AddIndex(
            model_name='musicreleaseartwork',
            index=models.Index(fields=['release', 'is_active', 'is_primary'], name='audio_release_artwork_idx'),
        ),
        migrations.AddIndex(
            model_name='musicreleaseartwork',
            index=models.Index(fields=['role', 'is_active'], name='audio_rel_artwork_role_idx'),
        ),
        migrations.AddConstraint(
            model_name='musicreleaseartwork',
            constraint=models.UniqueConstraint(fields=('release', 'primary_slot'), name='audio_one_active_primary_release_artwork'),
        ),
        migrations.AddIndex(
            model_name='musicrelease',
            index=models.Index(fields=['catalog', 'status', '-release_date'], name='audio_release_catalog_idx'),
        ),
        migrations.AddIndex(
            model_name='musicrelease',
            index=models.Index(fields=['release_type', 'status'], name='audio_release_type_idx'),
        ),
    ]
