# Generated by Django 4.2.4 on 2026-09-16 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_catalog', '0011_musicrelease_musicreleasetrack_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicrightsrecord',
            name='offline_playback_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='musictrack',
            name='allow_offline_playback',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='musictrackvariant',
            name='is_offline_eligible',
            field=models.BooleanField(default=False),
        ),
    ]
