# Generated by Django 4.2.4 on 2026-09-16 20:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('audio_catalog', '0012_musicrightsrecord_offline_playback_allowed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicLyricsWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField()),
                ('text', models.CharField(max_length=180)),
                ('start_ms', models.PositiveIntegerField()),
                ('end_ms', models.PositiveIntegerField()),
                ('confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('is_inferred', models.BooleanField(db_index=True, default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='audio_catalog.musiclyricsline')),
            ],
            options={
                'verbose_name': 'Music Lyrics Word',
                'verbose_name_plural': 'Music Lyrics Words',
                'ordering': ('sequence', 'id'),
                'indexes': [models.Index(fields=['line', 'sequence'], name='audio_lyr_word_seq_idx'), models.Index(fields=['line', 'start_ms'], name='audio_lyr_word_start_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='musiclyricsword',
            constraint=models.UniqueConstraint(fields=('line', 'sequence'), name='audio_uniq_lyrics_word_seq'),
        ),
        migrations.AddConstraint(
            model_name='musiclyricsword',
            constraint=models.CheckConstraint(check=models.Q(('end_ms__gt', models.F('start_ms'))), name='audio_lyrics_word_timing_valid'),
        ),
        migrations.AddConstraint(
            model_name='musiclyricsword',
            constraint=models.CheckConstraint(check=models.Q(('confidence__isnull', True), models.Q(('confidence__gte', 0), ('confidence__lte', 1)), _connector='OR'), name='audio_lyrics_word_conf_valid'),
        ),
    ]
