# Generated by Django 4.2.4 on 2026-08-13 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('reply_email', models.EmailField(blank=True, default='', max_length=254)),
                ('category', models.CharField(choices=[('technical', 'Technical Issue'), ('account_access', 'Account or Access'), ('feedback', 'Feedback or Suggestion'), ('store_order', 'Store or Order'), ('payment', 'Payment'), ('organization', 'Organization'), ('other', 'Other')], db_index=True, default='other', max_length=32)),
                ('area', models.CharField(choices=[('general', 'General'), ('accounts', 'Account'), ('profiles', 'Profile'), ('content', 'Content'), ('messenger', 'Messenger'), ('journey', 'Journey'), ('store', 'Store'), ('orders', 'Orders'), ('payment', 'Payment'), ('organizations', 'Organizations'), ('other', 'Other')], db_index=True, default='general', max_length=32)),
                ('source', models.CharField(choices=[('settings', 'Settings'), ('profile', 'Profile'), ('content', 'Content'), ('messenger', 'Messenger'), ('journey', 'Journey'), ('store', 'Store'), ('order', 'Order'), ('payment', 'Payment'), ('organization', 'Organization'), ('system', 'System')], db_index=True, default='settings', max_length=32)),
                ('subject', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_review', 'In Review'), ('waiting_user', 'Waiting for User'), ('resolved', 'Resolved'), ('closed', 'Closed')], db_index=True, default='open', max_length=24)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, default='normal', max_length=16)),
                ('context_type', models.CharField(blank=True, default='', help_text='Optional logical resource type such as order, product or profile.', max_length=64)),
                ('context_id', models.CharField(blank=True, default='', help_text='Optional identifier for the related resource.', max_length=128)),
                ('client_app_version', models.CharField(blank=True, default='', max_length=40)),
                ('client_platform', models.CharField(blank=True, default='', max_length=32)),
                ('ai_status', models.CharField(choices=[('not_used', 'Not Used'), ('eligible', 'Eligible'), ('processing', 'Processing'), ('drafted', 'Drafted'), ('assisted', 'AI Assisted')], db_index=True, default='not_used', max_length=24)),
                ('last_message_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_support_tickets', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Support Ticket',
                'verbose_name_plural': 'Support Tickets',
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicketMessage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sender_type', models.CharField(choices=[('user', 'User'), ('staff', 'TownLIT Support'), ('ai', 'AI Assistant'), ('system', 'System')], db_index=True, default='user', max_length=16)),
                ('body', models.TextField()),
                ('is_internal', models.BooleanField(db_index=True, default=False, help_text='Internal messages are never exposed to the requesting user.')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_ticket_messages', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='help_support.supportticket')),
            ],
            options={
                'verbose_name': 'Support Ticket Message',
                'verbose_name_plural': 'Support Ticket Messages',
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['ticket', 'is_internal', 'created_at'], name='help_suppor_ticket__05f915_idx'), models.Index(fields=['sender_type', 'created_at'], name='help_suppor_sender__1a7009_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['status', 'priority', '-created_at'], name='help_suppor_status_96a6f7_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['requester', 'status', '-last_message_at'], name='help_suppor_request_278ccf_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['category', 'area', 'status'], name='help_suppor_categor_e8e632_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['source', 'status'], name='help_suppor_source_b97a92_idx'),
        ),
    ]
