# Generated by Django 4.2.4 on 2026-08-26 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help_support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='area',
            field=models.CharField(choices=[('general', 'General'), ('accounts', 'Account'), ('profiles', 'Profile'), ('content', 'Content'), ('messenger', 'Messenger'), ('journey', 'Journey'), ('payment', 'Payment'), ('other', 'Other')], db_index=True, default='general', max_length=32),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='category',
            field=models.CharField(choices=[('technical', 'Technical Issue'), ('account_access', 'Account or Access'), ('feedback', 'Feedback or Suggestion'), ('payment', 'Payment'), ('other', 'Other')], db_index=True, default='other', max_length=32),
        ),
    ]
