# Generated by Django 4.2.4 on 2025-04-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='termsandpolicy',
            name='display_location',
            field=models.CharField(choices=[('footer', 'Footer'), ('official', 'Official Info Page'), ('both', 'Both')], default='official', max_length=20, verbose_name='Display Location'),
        ),
    ]
