# Generated by Django 4.2.4 on 2025-05-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_termsandpolicy_display_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policychangehistory',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
