# Generated by Django 4.2.4 on 2025-05-04 15:19

import common.validators
from django.db import migrations, models
import utils.common.utils


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_policychangehistory_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfeedback',
            options={'ordering': ['-created_at'], 'verbose_name': 'User Feedback', 'verbose_name_plural': 'User Feedbacks'},
        ),
        migrations.RemoveField(
            model_name='userfeedback',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='userfeedback',
            name='object_id',
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[common.validators.validate_image_or_video_file, common.validators.validate_no_executable_file], verbose_name='Document'),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved')], default='new', max_length=20, verbose_name='Status'),
        ),
    ]
