# Generated by Django 4.2.4 on 2025-05-06 00:55

import common.validators
from django.db import migrations, models
import django.db.models.deletion
import utils.common.utils


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_userfeedback_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('language', models.CharField(default='en', max_length=10, verbose_name='Language')),
                ('episode_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Episode Number')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='View Count')),
                ('video_file', models.FileField(upload_to=utils.common.utils.FileUpload.dir_upload, validators=[common.validators.validate_image_or_video_file, common.validators.validate_no_executable_file], verbose_name='Video File')),
                ('thumbnail', models.ImageField(upload_to=utils.common.utils.FileUpload.dir_upload, validators=[common.validators.validate_image_or_video_file, common.validators.validate_no_executable_file], verbose_name='Thumbnail / Poster')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('publish_date', models.DateTimeField(verbose_name='Publish Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Official Video',
                'verbose_name_plural': 'Official Videos',
                'ordering': ['-publish_date', 'episode_number'],
            },
        ),
        migrations.CreateModel(
            name='VideoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Category Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Video Category',
                'verbose_name_plural': 'Video Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VideoSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Series Title')),
                ('description', models.TextField(blank=True, verbose_name='Series Description')),
                ('language', models.CharField(default='en', max_length=10, verbose_name='Language')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Video Series',
                'verbose_name_plural': 'Video Series',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[common.validators.validate_image_or_video_file, common.validators.validate_no_executable_file], verbose_name='Document'),
        ),
        migrations.CreateModel(
            name='VideoViewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to='main.officialvideo')),
            ],
            options={
                'verbose_name': 'Video View Log',
                'verbose_name_plural': 'Video View Logs',
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.AddField(
            model_name='officialvideo',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='main.videocategory', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='officialvideo',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='main.videoseries', verbose_name='Series'),
        ),
    ]
