# Generated by Django 4.2.4 on 2025-05-14 14:50

import common.validators
from django.db import migrations, models
import utils.common.utils


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_officialvideo_thumbnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='termsandpolicy',
            name='footer_column',
            field=models.CharField(blank=True, choices=[('left', 'Left Column'), ('right', 'Right Column')], help_text='Optional. Only applies if display location is Footer or Both.', max_length=10, null=True, verbose_name='Footer Column (optional)'),
        ),
        migrations.AlterField(
            model_name='officialvideo',
            name='thumbnail',
            field=models.ImageField(upload_to=utils.common.utils.FileUpload.dir_upload, validators=[common.validators.validate_image_or_video_file, common.validators.validate_no_executable_file], verbose_name='Thumbnail / Poster'),
        ),
        migrations.AlterField(
            model_name='officialvideo',
            name='video_file',
            field=models.FileField(upload_to=utils.common.utils.FileUpload.dir_upload, validators=[common.validators.validate_no_executable_file], verbose_name='Video File'),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[common.validators.validate_image_or_video_file, common.validators.validate_no_executable_file], verbose_name='Document'),
        ),
    ]
