# Generated by Django 4.2.4 on 2025-05-16 15:13

import common.validators
from django.db import migrations, models
import utils.common.utils


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_officialvideo_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officialvideo',
            name='thumbnail',
            field=models.ImageField(upload_to=utils.common.utils.FileUpload.dir_upload, validators=[common.validators.validate_image_or_video_file, common.validators.validate_no_executable_file], verbose_name='Thumbnail / Poster'),
        ),
        migrations.AlterField(
            model_name='officialvideo',
            name='video_file',
            field=models.FileField(upload_to=utils.common.utils.FileUpload.dir_upload, validators=[common.validators.validate_no_executable_file], verbose_name='Video File'),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[common.validators.validate_image_or_video_file, common.validators.validate_no_executable_file], verbose_name='Document'),
        ),
    ]
