# Generated by Django 4.2.4 on 2025-05-16 19:44

import common.validators
from django.db import migrations, models
import utils.common.utils


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_officialvideo_thumbnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='termsandpolicy',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fa', 'Persian'), ('tr', 'Turkish'), ('es', 'Spanish'), ('zh', 'Chinese'), ('ar', 'Arabic'), ('ko', 'Korean'), ('fr', 'French'), ('de', 'German'), ('it', 'Italian'), ('pt', 'Portuguese'), ('ru', 'Russian'), ('ja', 'Japanese'), ('hi', 'Hindi'), ('bn', 'Bengali'), ('ur', 'Urdu'), ('id', 'Indonesian'), ('ta', 'Tamil'), ('ms', 'Malay'), ('vi', 'Vietnamese'), ('th', 'Thai')], default='en', max_length=10, verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='termsandpolicy',
            name='requires_acceptance',
            field=models.BooleanField(default=False, verbose_name='Requires Acceptance'),
        ),
        migrations.AddField(
            model_name='termsandpolicy',
            name='version_number',
            field=models.CharField(default='1.0', max_length=20, verbose_name='Version Number'),
        ),
        migrations.AlterField(
            model_name='officialvideo',
            name='thumbnail',
            field=models.ImageField(upload_to=utils.common.utils.FileUpload.dir_upload, validators=[common.validators.validate_image_or_video_file, common.validators.validate_no_executable_file], verbose_name='Thumbnail / Poster'),
        ),
        migrations.AlterField(
            model_name='officialvideo',
            name='video_file',
            field=models.FileField(upload_to=utils.common.utils.FileUpload.dir_upload, validators=[common.validators.validate_no_executable_file], verbose_name='Video File'),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[common.validators.validate_image_or_video_file, common.validators.validate_no_executable_file], verbose_name='Document'),
        ),
    ]
