# Generated by Django 4.2.4 on 2025-05-16 22:07

import common.validators
from django.db import migrations, models
import django.db.models.deletion
import utils.common.utils


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_termsandpolicy_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoseries',
            name='intro_video',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intro_for_series', to='main.officialvideo', verbose_name='Introductory Video'),
        ),
        migrations.AlterField(
            model_name='officialvideo',
            name='thumbnail',
            field=models.ImageField(upload_to=utils.common.utils.FileUpload.dir_upload, validators=[common.validators.validate_image_or_video_file, common.validators.validate_no_executable_file], verbose_name='Thumbnail / Poster'),
        ),
        migrations.AlterField(
            model_name='officialvideo',
            name='video_file',
            field=models.FileField(upload_to=utils.common.utils.FileUpload.dir_upload, validators=[common.validators.validate_no_executable_file], verbose_name='Video File'),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[common.validators.validate_image_or_video_file, common.validators.validate_no_executable_file], verbose_name='Document'),
        ),
    ]
