# Generated by Django 4.2.4 on 2025-12-21 17:16

from django.db import migrations, models
import utils.common.utils
import validators.mediaValidators.image_validators
import validators.mediaValidators.video_validators
import validators.security_validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_alter_officialvideo_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useragreement',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='useragreement',
            name='policy_last_updated_snapshot',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Policy Last Updated Snapshot'),
        ),
        migrations.AddField(
            model_name='useragreement',
            name='policy_version_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Policy Version Snapshot'),
        ),
        migrations.AlterField(
            model_name='officialvideo',
            name='thumbnail',
            field=models.FileField(upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file], verbose_name='Thumbnail / Poster'),
        ),
        migrations.AlterField(
            model_name='officialvideo',
            name='video',
            field=models.FileField(upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.video_validators.validate_video_file, validators.security_validators.validate_no_executable_file], verbose_name='Video File'),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='screenshot',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file], verbose_name='Document'),
        ),
        migrations.AddIndex(
            model_name='useragreement',
            index=models.Index(fields=['user', 'policy', 'is_latest_agreement'], name='main_userag_user_id_67b5d6_idx'),
        ),
        migrations.AddIndex(
            model_name='useragreement',
            index=models.Index(fields=['agreed_at'], name='main_userag_agreed__8e4297_idx'),
        ),
        migrations.AddConstraint(
            model_name='useragreement',
            constraint=models.UniqueConstraint(condition=models.Q(('is_latest_agreement', True)), fields=('user', 'policy'), name='uniq_latest_agreement_per_user_policy'),
        ),
    ]
