# Generated by Django 4.2.4 on 2025-12-25 04:51

from django.db import migrations, models
import utils.common.utils
import validators.mediaValidators.image_validators
import validators.mediaValidators.video_validators
import validators.security_validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_alter_useragreement_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='termsandpolicy',
            name='acceptance_context',
            field=models.CharField(choices=[('registration', 'Registration'), ('login', 'Login'), ('sanctuary', 'Sanctuary'), ('feature', 'Feature Access')], db_index=True, default='registration', max_length=30, verbose_name='Acceptance Context'),
        ),
        migrations.AddField(
            model_name='termsandpolicy',
            name='show_in_footer',
            field=models.BooleanField(default=False, help_text='If enabled, this policy link can appear in the frontend footer.', verbose_name='Show In Footer'),
        ),
        migrations.AlterField(
            model_name='officialvideo',
            name='thumbnail',
            field=models.FileField(upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file], verbose_name='Thumbnail / Poster'),
        ),
        migrations.AlterField(
            model_name='officialvideo',
            name='video',
            field=models.FileField(upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.video_validators.validate_video_file, validators.security_validators.validate_no_executable_file], verbose_name='Video File'),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='screenshot',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file], verbose_name='Document'),
        ),
    ]
