# Generated by Django 4.2.4 on 2025-05-26 17:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Amount')),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('canceled', 'Canceled')], default='pending', max_length=10, verbose_name='Payment Status')),
                ('is_anonymous_donor', models.BooleanField(default=False, verbose_name='Anonymous Donor')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Guest Email')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('reference_number', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Reference Number')),
                ('cancel_token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('cancel_token_created_at', models.DateTimeField(blank=True, null=True)),
                ('confirm_token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('confirm_token_created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
        migrations.CreateModel(
            name='PaymentAdvertisement',
            fields=[
                ('payment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payment.payment')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
            ],
            options={
                'verbose_name': 'Payment Advertisement',
                'verbose_name_plural': 'Payment Advertisements',
            },
            bases=('payment.payment',),
        ),
        migrations.CreateModel(
            name='PaymentDonation',
            fields=[
                ('payment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payment.payment')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Payment Donation',
                'verbose_name_plural': 'Payment Donations',
            },
            bases=('payment.payment',),
        ),
        migrations.CreateModel(
            name='PaymentShoppingCart',
            fields=[
                ('payment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payment.payment')),
            ],
            options={
                'verbose_name': 'Payment Shopping Cart',
                'verbose_name_plural': 'Payment Shopping Carts',
            },
            bases=('payment.payment',),
        ),
        migrations.CreateModel(
            name='PaymentSubscription',
            fields=[
                ('payment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payment.payment')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Payment Subscription',
                'verbose_name_plural': 'Payment Subscriptions',
            },
            bases=('payment.payment',),
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pricing_type', models.CharField(choices=[('subscription', 'Subscription'), ('advertisement', 'Advertisement')], max_length=20, verbose_name='Pricing Type')),
                ('duration', models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=20, verbose_name='Duration')),
                ('billing_cycle', models.CharField(choices=[('one_time', 'One-Time'), ('recurring_indefinite', 'Recurring Indefinitely'), ('recurring_until', 'Recurring Until Date')], max_length=20, verbose_name='Billing Cycle')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Discount (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Pricing',
                'verbose_name_plural': 'Pricings',
                'unique_together': {('pricing_type', 'duration', 'billing_cycle')},
            },
        ),
        migrations.CreateModel(
            name='PaymentInvoice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Invoice Number')),
                ('issued_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Issued Date')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Due Date')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Is Paid')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='payment.payment', verbose_name='Payment')),
            ],
            options={
                'verbose_name': 'Payment Invoice',
                'verbose_name_plural': 'Payment Invoices',
            },
        ),
    ]
