# Generated by Django 4.2.4 on 2025-04-20 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profilesOrg', '0001_initial'),
        ('accounts', '0001_initial'),
        ('orders', '0003_initial'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='profilesOrg.organization', verbose_name='Organization'),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='paymentsubscription',
            name='subscription_pricing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payment.pricing', verbose_name='Subscription Pricing'),
        ),
        migrations.AddField(
            model_name='paymentshoppingcart',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.address', verbose_name='Billing Address'),
        ),
        migrations.AddField(
            model_name='paymentshoppingcart',
            name='shopping_cart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='orders.shoppingcart', verbose_name='Shopping Cart'),
        ),
        migrations.AddField(
            model_name='paymentadvertisement',
            name='advertisement_pricing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payment.pricing', verbose_name='Advertisement Pricing'),
        ),
    ]
