# Generated by Django 4.2.4 on 2025-05-07 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_payment_is_anonymous_donor_alter_payment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Guest Email'),
        ),
    ]
