# Generated by Django 4.2.4 on 2025-05-08 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_payment_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='cancel_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='cancel_token_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
