# Generated by Django 4.2.4 on 2025-05-08 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_payment_cancel_token_payment_cancel_token_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='confirm_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='confirm_token_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
