# Generated by Django 4.2.4 on 2025-05-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_payment_stripe_payment_intent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('canceled', 'Canceled')], default='pending', max_length=10, verbose_name='Payment Status'),
        ),
    ]
