# Generated by Django 4.2.4 on 2025-12-27 17:22

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone
import utils.common.utils
import validators.mediaValidators.audio_validators
import validators.mediaValidators.image_validators
import validators.mediaValidators.pdf_validators
import validators.mediaValidators.video_validators
import validators.security_validators


class Migration(migrations.Migration):

    dependencies = [
        ('profilesOrg', '0040_alter_organization_license_document_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0037_remove_moment_content_remove_moment_moment_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moment',
            name='is_hidden',
        ),
        migrations.RemoveField(
            model_name='moment',
            name='is_restricted',
        ),
        migrations.RemoveField(
            model_name='moment',
            name='org_tags',
        ),
        migrations.RemoveField(
            model_name='moment',
            name='user_tags',
        ),
        migrations.RemoveField(
            model_name='testimony',
            name='is_hidden',
        ),
        migrations.RemoveField(
            model_name='testimony',
            name='is_restricted',
        ),
        migrations.AddField(
            model_name='moment',
            name='last_viewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moment',
            name='suspended_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when target was suspended.', null=True),
        ),
        migrations.AddField(
            model_name='moment',
            name='suspension_reason',
            field=models.CharField(blank=True, help_text='Optional reason code or short description.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moment',
            name='view_count_internal',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='moment',
            name='visibility',
            field=models.CharField(choices=[('default', 'Default (Profile-based)'), ('global', 'Global (Public)'), ('friends', 'Friends only'), ('covenant', 'LIT Covenant'), ('private', 'Only me')], db_index=True, default='default', max_length=20, verbose_name='Visibility'),
        ),
        migrations.AddField(
            model_name='testimony',
            name='suspended_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when target was suspended.', null=True),
        ),
        migrations.AddField(
            model_name='testimony',
            name='suspension_reason',
            field=models.CharField(blank=True, help_text='Optional reason code or short description.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='testimony',
            name='visibility',
            field=models.CharField(choices=[('default', 'Default (Profile-based)'), ('global', 'Global (Public)'), ('friends', 'Friends only'), ('covenant', 'LIT Covenant'), ('private', 'Only me')], db_index=True, default='default', max_length=20, verbose_name='Visibility'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file], verbose_name='Announcement Image'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.audio_validators.validate_audio_file, validators.security_validators.validate_no_executable_file], verbose_name='Audio Lesson'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file], verbose_name='Image Lesson'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.video_validators.validate_video_file, validators.security_validators.validate_no_executable_file], verbose_name='Video Lesson'),
        ),
        migrations.AlterField(
            model_name='library',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file], verbose_name='Book Image'),
        ),
        migrations.AlterField(
            model_name='library',
            name='license_document',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.pdf_validators.validate_pdf_file, validators.security_validators.validate_no_executable_file], verbose_name='License Document'),
        ),
        migrations.AlterField(
            model_name='library',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.pdf_validators.validate_pdf_file, validators.security_validators.validate_no_executable_file], verbose_name='Book File'),
        ),
        migrations.AlterField(
            model_name='mediacontent',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.pdf_validators.validate_pdf_file, validators.security_validators.validate_no_executable_file], verbose_name='Media File'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='image_or_video',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file, validators.security_validators.validate_no_executable_file], verbose_name='Mission Image/Video'),
        ),
        migrations.AlterField(
            model_name='moment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file], verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='moment',
            name='is_active',
            field=models.BooleanField(default=True, help_text='System-level activation flag (false = removed from feeds).'),
        ),
        migrations.AlterField(
            model_name='moment',
            name='is_suspended',
            field=models.BooleanField(default=False, help_text='System-level suspension due to moderation outcome.'),
        ),
        migrations.AlterField(
            model_name='moment',
            name='reports_count',
            field=models.PositiveIntegerField(default=0, help_text='Historical cumulative reports count (not active wave).'),
        ),
        migrations.AlterField(
            model_name='moment',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file], verbose_name='Thumbnail'),
        ),
        migrations.AlterField(
            model_name='moment',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.video_validators.validate_video_file, validators.security_validators.validate_no_executable_file], verbose_name='Video'),
        ),
        migrations.AlterField(
            model_name='pray',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file], verbose_name='Pray Image'),
        ),
        migrations.AlterField(
            model_name='preach',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file], verbose_name='Lesson Image'),
        ),
        migrations.AlterField(
            model_name='preach',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.video_validators.validate_video_file, validators.security_validators.validate_no_executable_file], verbose_name='Lesson Video'),
        ),
        migrations.AlterField(
            model_name='serviceevent',
            name='event_banner',
            field=models.ImageField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file], verbose_name='Event Banner'),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.audio_validators.validate_audio_file, validators.security_validators.validate_no_executable_file], verbose_name='Testimony Audio'),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='is_active',
            field=models.BooleanField(default=True, help_text='System-level activation flag (false = removed from feeds).'),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='is_suspended',
            field=models.BooleanField(default=False, help_text='System-level suspension due to moderation outcome.'),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='org_tags',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='tagged_in_testimonies', to='profilesOrg.organization'),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='reports_count',
            field=models.PositiveIntegerField(default=0, help_text='Historical cumulative reports count (not active wave).'),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file], verbose_name='Thumbnail'),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='user_tags',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='tagged_in_testimonies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.video_validators.validate_video_file, validators.security_validators.validate_no_executable_file], verbose_name='Testimony Video'),
        ),
        migrations.AlterField(
            model_name='worship',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.audio_validators.validate_audio_file, validators.security_validators.validate_no_executable_file], verbose_name='Worship Audio'),
        ),
        migrations.AlterField(
            model_name='worship',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file], verbose_name='Worship Image'),
        ),
        migrations.AlterField(
            model_name='worship',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.video_validators.validate_video_file, validators.security_validators.validate_no_executable_file], verbose_name='Worship Video'),
        ),
        migrations.AddIndex(
            model_name='moment',
            index=models.Index(fields=['visibility'], name='posts_momen_visibil_00a946_idx'),
        ),
    ]
