# Generated by Django 4.2.4 on 2026-02-23 05:04

import apps.core.availability.interfaces
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import utils.common.utils
import utils.mixins.media_autoconvert
import utils.mixins.media_conversion
import validators.mediaValidators.audio_validators
import validators.mediaValidators.image_validators
import validators.mediaValidators.pdf_validators
import validators.mediaValidators.video_validators
import validators.security_validators


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('posts', '0063_alter_announcement_image_alter_lesson_audio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prayer',
            fields=[
                ('slug', models.SlugField(blank=True, max_length=140, null=True, unique=True, verbose_name='Slug')),
                ('visibility', models.CharField(choices=[('global', 'Global (Public)'), ('friends', 'Friends only'), ('covenant', 'LIT Covenant'), ('private', 'Only me')], db_index=True, default='global', max_length=20, verbose_name='Visibility')),
                ('is_hidden', models.BooleanField(default=False, help_text='UI-level hide (not moderation).')),
                ('reports_count', models.PositiveIntegerField(default=0, help_text='Historical cumulative reports count (not active wave).')),
                ('is_suspended', models.BooleanField(default=False, help_text='System-level suspension due to moderation outcome.')),
                ('is_active', models.BooleanField(default=True, help_text='System-level activation flag (false = removed from feeds).')),
                ('suspended_at', models.DateTimeField(blank=True, help_text='Timestamp when target was suspended.', null=True)),
                ('suspension_reason', models.CharField(blank=True, help_text='Optional reason code or short description.', max_length=255, null=True)),
                ('comments_count', models.PositiveIntegerField(default=0)),
                ('recomments_count', models.PositiveIntegerField(default=0)),
                ('reactions_count', models.PositiveIntegerField(default=0)),
                ('reactions_breakdown', models.JSONField(default=dict)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('caption', models.TextField(blank=True, null=True, verbose_name='Prayer Text')),
                ('image', models.ImageField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file], verbose_name='Image')),
                ('video', models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.video_validators.validate_moment_video_file, validators.security_validators.validate_no_executable_file], verbose_name='Video')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file], verbose_name='Thumbnail')),
                ('object_id', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('answered', 'Answered'), ('not_answered', 'Not Answered')], db_index=True, default='waiting', max_length=24)),
                ('answered_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('view_count_internal', models.PositiveBigIntegerField(default=0)),
                ('last_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_converted', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Prayer',
                'verbose_name_plural': 'Prayers',
            },
            bases=(utils.mixins.media_autoconvert.MediaAutoConvertMixin, utils.mixins.media_conversion.MediaConversionMixin, apps.core.availability.interfaces.AvailabilityAware, models.Model),
        ),
        migrations.CreateModel(
            name='PrayerResponse',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('result_status', models.CharField(choices=[('answered', 'Answered'), ('not_answered', 'Not Answered')], db_index=True, max_length=24)),
                ('response_text', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file], verbose_name='Response Image')),
                ('video', models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.video_validators.validate_moment_video_file, validators.security_validators.validate_no_executable_file], verbose_name='Response Video')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file], verbose_name='Response Thumbnail')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_converted', models.BooleanField(default=False)),
                ('prayer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='posts.prayer')),
            ],
            options={
                'verbose_name': 'Prayer Response',
                'verbose_name_plural': 'Prayer Responses',
            },
            bases=(utils.mixins.media_autoconvert.MediaAutoConvertMixin, utils.mixins.media_conversion.MediaConversionMixin, apps.core.availability.interfaces.AvailabilityAware, models.Model),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file], verbose_name='Announcement Image'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.audio_validators.validate_audio_file, validators.security_validators.validate_no_executable_file], verbose_name='Audio Lesson'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file], verbose_name='Image Lesson'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.video_validators.validate_video_file, validators.security_validators.validate_no_executable_file], verbose_name='Video Lesson'),
        ),
        migrations.AlterField(
            model_name='library',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file], verbose_name='Book Image'),
        ),
        migrations.AlterField(
            model_name='library',
            name='license_document',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.pdf_validators.validate_pdf_file, validators.security_validators.validate_no_executable_file], verbose_name='License Document'),
        ),
        migrations.AlterField(
            model_name='library',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.pdf_validators.validate_pdf_file, validators.security_validators.validate_no_executable_file], verbose_name='Book File'),
        ),
        migrations.AlterField(
            model_name='mediacontent',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.pdf_validators.validate_pdf_file, validators.security_validators.validate_no_executable_file], verbose_name='Media File'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='image_or_video',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file, validators.security_validators.validate_no_executable_file], verbose_name='Mission Image/Video'),
        ),
        migrations.AlterField(
            model_name='moment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file], verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='moment',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file], verbose_name='Thumbnail'),
        ),
        migrations.AlterField(
            model_name='moment',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.video_validators.validate_moment_video_file, validators.security_validators.validate_no_executable_file], verbose_name='Video'),
        ),
        migrations.AlterField(
            model_name='preach',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file], verbose_name='Lesson Image'),
        ),
        migrations.AlterField(
            model_name='preach',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.video_validators.validate_video_file, validators.security_validators.validate_no_executable_file], verbose_name='Lesson Video'),
        ),
        migrations.AlterField(
            model_name='serviceevent',
            name='event_banner',
            field=models.ImageField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file], verbose_name='Event Banner'),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.audio_validators.validate_audio_file, validators.security_validators.validate_no_executable_file], verbose_name='Testimony Audio'),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file], verbose_name='Thumbnail'),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.video_validators.validate_testimony_video_file, validators.security_validators.validate_no_executable_file], verbose_name='Testimony Video'),
        ),
        migrations.AlterField(
            model_name='worship',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.audio_validators.validate_audio_file, validators.security_validators.validate_no_executable_file], verbose_name='Worship Audio'),
        ),
        migrations.AlterField(
            model_name='worship',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file], verbose_name='Worship Image'),
        ),
        migrations.AlterField(
            model_name='worship',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.video_validators.validate_video_file, validators.security_validators.validate_no_executable_file], verbose_name='Worship Video'),
        ),
        migrations.DeleteModel(
            name='Pray',
        ),
        migrations.AddIndex(
            model_name='prayerresponse',
            index=models.Index(fields=['created_at'], name='prayer_resp_created_idx'),
        ),
        migrations.AddIndex(
            model_name='prayerresponse',
            index=models.Index(fields=['result_status'], name='prayer_resp_result_idx'),
        ),
        migrations.AddIndex(
            model_name='prayer',
            index=models.Index(fields=['visibility', '-published_at', '-id'], name='prayer_vis_pub_id_idx'),
        ),
        migrations.AddIndex(
            model_name='prayer',
            index=models.Index(fields=['content_type', 'object_id', 'published_at'], name='prayer_owner_pub_idx'),
        ),
        migrations.AddIndex(
            model_name='prayer',
            index=models.Index(fields=['is_active', 'is_hidden', 'published_at'], name='prayer_mod_pub_idx'),
        ),
        migrations.AddIndex(
            model_name='prayer',
            index=models.Index(fields=['status', 'answered_at'], name='prayer_status_answered_idx'),
        ),
        migrations.AddIndex(
            model_name='prayer',
            index=models.Index(fields=['published_at'], name='prayer_pub_idx'),
        ),
    ]
