# Generated by Django 4.2.4 on 2026-07-22 06:51

import apps.core.availability.interfaces
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import utils.common.utils
import validators.mediaValidators.audio_validators
import validators.mediaValidators.image_validators
import validators.mediaValidators.pdf_validators
import validators.mediaValidators.video_validators
import validators.security_validators


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('creative_editor', '0002_alter_creativecomposition_rendered_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audio_catalog', '0003_alter_audioplaybacksession_surface_and_more'),
        ('posts', '0078_moment_notification_dispatched_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('slug', models.SlugField(blank=True, max_length=140, null=True, unique=True, verbose_name='Slug')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('object_id', models.PositiveIntegerField()),
                ('local_date', models.DateField(db_index=True)),
                ('timezone_name', models.CharField(default='UTC', max_length=64)),
                ('palette_mode', models.CharField(choices=[('dawn', 'Dawn'), ('evening', 'Evening')], db_index=True, max_length=16)),
                ('display_seed', models.PositiveIntegerField(default=0)),
                ('close_text', models.TextField(blank=True, default='')),
                ('close_is_private', models.BooleanField(default=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journey_chapters', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Journey',
                'verbose_name_plural': 'Journeys',
                'ordering': ('-local_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='JourneyEntry',
            fields=[
                ('media_assets', models.JSONField(blank=True, default=dict)),
                ('slug', models.SlugField(blank=True, max_length=140, null=True, unique=True, verbose_name='Slug')),
                ('visibility', models.CharField(choices=[('global', 'Global (Public)'), ('friends', 'Friends only'), ('covenant', 'LIT Covenant'), ('private', 'Only me')], db_index=True, default='global', max_length=20, verbose_name='Visibility')),
                ('is_hidden', models.BooleanField(default=False, help_text='UI-level hide (not moderation).')),
                ('reports_count', models.PositiveIntegerField(default=0, help_text='Historical cumulative reports count (not active wave).')),
                ('is_suspended', models.BooleanField(default=False, help_text='System-level suspension due to moderation outcome.')),
                ('is_active', models.BooleanField(default=True, help_text='System-level activation flag (false = removed from feeds).')),
                ('suspended_at', models.DateTimeField(blank=True, help_text='Timestamp when target was suspended.', null=True)),
                ('suspension_reason', models.CharField(blank=True, help_text='Optional reason code or short description.', max_length=255, null=True)),
                ('reactions_breakdown', models.JSONField(default=dict)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('object_id', models.PositiveIntegerField()),
                ('sequence', models.PositiveSmallIntegerField(db_index=True)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('shared_content', 'Shared Content')], db_index=True, default='image', max_length=24)),
                ('visual_source_type', models.CharField(choices=[('uploaded_image', 'Uploaded Image'), ('content_reference', 'Content Reference'), ('solid_background', 'Solid Background'), ('gradient_background', 'Gradient Background'), ('preset_background', 'Preset Background')], db_index=True, max_length=32)),
                ('composition_public_id_snapshot', models.UUIDField()),
                ('render_job_public_id_snapshot', models.UUIDField()),
                ('composition_revision', models.PositiveIntegerField()),
                ('composition_document_sha256', models.CharField(db_index=True, max_length=64)),
                ('rendered_image', models.ImageField(max_length=700, upload_to=utils.common.utils.FileUpload.dir_upload)),
                ('thumbnail', models.ImageField(max_length=700, upload_to=utils.common.utils.FileUpload.dir_upload)),
                ('music_clip_start_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('music_clip_end_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('music_volume', models.DecimalField(decimal_places=3, default=1, max_digits=4)),
                ('music_attribution_text', models.TextField(blank=True, default='')),
                ('display_duration_ms', models.PositiveIntegerField(default=15000)),
                ('retention_policy', models.CharField(choices=[('keep', 'Keep in Journey archive'), ('delete_after_expiry', 'Delete after expiry')], db_index=True, default='keep', max_length=32)),
                ('published_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('view_count_internal', models.PositiveBigIntegerField(default=0)),
                ('unique_viewers_count', models.PositiveBigIntegerField(default=0)),
                ('reactions_count', models.PositiveIntegerField(default=0)),
                ('last_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('composition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_journey_entries', to='creative_editor.creativecomposition')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journey_entries', to='contenttypes.contenttype')),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='posts.journey')),
                ('music_track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journey_entries', to='audio_catalog.musictrack')),
                ('music_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journey_entries', to='audio_catalog.musictrackvariant')),
                ('render_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_journey_entries', to='creative_editor.creativerenderjob')),
            ],
            options={
                'verbose_name': 'Journey Entry',
                'verbose_name_plural': 'Journey Entries',
                'ordering': ('sequence', 'id'),
            },
            bases=(apps.core.availability.interfaces.AvailabilityAware, models.Model),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file], verbose_name='Announcement Image'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.audio_validators.validate_audio_file, validators.security_validators.validate_no_executable_file], verbose_name='Audio Lesson'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file], verbose_name='Image Lesson'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.video_validators.validate_video_file, validators.security_validators.validate_no_executable_file], verbose_name='Video Lesson'),
        ),
        migrations.AlterField(
            model_name='library',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file], verbose_name='Book Image'),
        ),
        migrations.AlterField(
            model_name='library',
            name='license_document',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.pdf_validators.validate_pdf_file, validators.security_validators.validate_no_executable_file], verbose_name='License Document'),
        ),
        migrations.AlterField(
            model_name='library',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.pdf_validators.validate_pdf_file, validators.security_validators.validate_no_executable_file], verbose_name='Book File'),
        ),
        migrations.AlterField(
            model_name='mediacontent',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.pdf_validators.validate_pdf_file, validators.security_validators.validate_no_executable_file], verbose_name='Media File'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='image_or_video',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file, validators.security_validators.validate_no_executable_file], verbose_name='Mission Image/Video'),
        ),
        migrations.AlterField(
            model_name='moment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_moment_image_size, validators.security_validators.validate_no_executable_file], verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='moment',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file], verbose_name='Thumbnail'),
        ),
        migrations.AlterField(
            model_name='moment',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.video_validators.validate_moment_video_file, validators.security_validators.validate_no_executable_file], verbose_name='Video'),
        ),
        migrations.AlterField(
            model_name='prayer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file], verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='prayer',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file], verbose_name='Thumbnail'),
        ),
        migrations.AlterField(
            model_name='prayer',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.video_validators.validate_prayer_video_file, validators.security_validators.validate_no_executable_file], verbose_name='Video'),
        ),
        migrations.AlterField(
            model_name='prayerresponse',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file], verbose_name='Response Image'),
        ),
        migrations.AlterField(
            model_name='prayerresponse',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file], verbose_name='Response Thumbnail'),
        ),
        migrations.AlterField(
            model_name='prayerresponse',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.video_validators.validate_prayer_video_file, validators.security_validators.validate_no_executable_file], verbose_name='Response Video'),
        ),
        migrations.AlterField(
            model_name='preach',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file], verbose_name='Lesson Image'),
        ),
        migrations.AlterField(
            model_name='preach',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.video_validators.validate_video_file, validators.security_validators.validate_no_executable_file], verbose_name='Lesson Video'),
        ),
        migrations.AlterField(
            model_name='serviceevent',
            name='event_banner',
            field=models.ImageField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file], verbose_name='Event Banner'),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.audio_validators.validate_audio_file, validators.security_validators.validate_no_executable_file], verbose_name='Testimony Audio'),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='audio_artwork',
            field=models.ImageField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file], verbose_name='Audio Artwork'),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file], verbose_name='Thumbnail'),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.video_validators.validate_testimony_video_file, validators.security_validators.validate_no_executable_file], verbose_name='Testimony Video'),
        ),
        migrations.AlterField(
            model_name='worship',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.audio_validators.validate_audio_file, validators.security_validators.validate_no_executable_file], verbose_name='Worship Audio'),
        ),
        migrations.AlterField(
            model_name='worship',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file], verbose_name='Worship Image'),
        ),
        migrations.AlterField(
            model_name='worship',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.video_validators.validate_video_file, validators.security_validators.validate_no_executable_file], verbose_name='Worship Video'),
        ),
        migrations.CreateModel(
            name='JourneyEntryView',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_viewed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_viewed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('view_count', models.PositiveIntegerField(default=1)),
                ('max_progress_ms', models.PositiveIntegerField(default=0)),
                ('completed', models.BooleanField(db_index=True, default=False)),
                ('source', models.CharField(choices=[('avatar_ring', 'Avatar Ring'), ('profile_archive', 'Profile Archive'), ('journey_stream', 'Journey Stream'), ('deep_link', 'Deep Link'), ('other', 'Other')], db_index=True, default='other', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewer_records', to='posts.journeyentry')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journey_entry_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journey Entry View',
                'verbose_name_plural': 'Journey Entry Views',
                'ordering': ('-last_viewed_at', '-id'),
                'indexes': [models.Index(fields=['entry', '-last_viewed_at'], name='journey_view_entry_time_idx'), models.Index(fields=['viewer', '-last_viewed_at'], name='journey_view_user_time_idx'), models.Index(fields=['entry', 'completed'], name='journey_view_completion_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='journeyentryview',
            constraint=models.UniqueConstraint(fields=('entry', 'viewer'), name='journey_unique_entry_viewer'),
        ),
        migrations.AddIndex(
            model_name='journeyentry',
            index=models.Index(fields=['journey', 'sequence'], name='journey_entry_order_idx'),
        ),
        migrations.AddIndex(
            model_name='journeyentry',
            index=models.Index(fields=['content_type', 'object_id', '-published_at'], name='journey_entry_owner_pub_idx'),
        ),
        migrations.AddIndex(
            model_name='journeyentry',
            index=models.Index(fields=['expires_at', 'retention_policy', 'archived_at'], name='journey_entry_expiry_idx'),
        ),
        migrations.AddIndex(
            model_name='journeyentry',
            index=models.Index(fields=['visibility', 'is_active', 'is_hidden', '-published_at'], name='journey_entry_visible_idx'),
        ),
        migrations.AddConstraint(
            model_name='journeyentry',
            constraint=models.UniqueConstraint(fields=('journey', 'sequence'), name='journey_unique_entry_sequence'),
        ),
        migrations.AddConstraint(
            model_name='journeyentry',
            constraint=models.CheckConstraint(check=models.Q(('sequence__gte', 1), ('sequence__lte', 12)), name='journey_entry_sequence_range'),
        ),
        migrations.AddConstraint(
            model_name='journeyentry',
            constraint=models.CheckConstraint(check=models.Q(('display_duration_ms__gte', 15000), ('display_duration_ms__lte', 60000)), name='journey_entry_duration_range'),
        ),
        migrations.AddConstraint(
            model_name='journeyentry',
            constraint=models.CheckConstraint(check=models.Q(('expires_at__gt', models.F('published_at'))), name='journey_entry_expiry_after_publish'),
        ),
        migrations.AddIndex(
            model_name='journey',
            index=models.Index(fields=['content_type', 'object_id', '-local_date'], name='journey_owner_day_idx'),
        ),
        migrations.AddIndex(
            model_name='journey',
            index=models.Index(fields=['local_date', 'palette_mode'], name='journey_day_palette_idx'),
        ),
        migrations.AddConstraint(
            model_name='journey',
            constraint=models.UniqueConstraint(fields=('content_type', 'object_id', 'local_date'), name='journey_unique_owner_local_day'),
        ),
    ]
