# Generated by Django 4.2.4 on 2026-09-01 17:05

import apps.core.availability.interfaces
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.common.utils
import utils.mixins.media_autoconvert
import utils.mixins.media_conversion
import uuid
import validators.mediaValidators.audio_validators
import validators.mediaValidators.image_validators
import validators.mediaValidators.video_validators
import validators.security_validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0008_alter_churchauditlog_event_churchteachingseries_and_more'),
        ('posts', '0087_alter_announcement_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchTeachingContent',
            fields=[
                ('media_assets', models.JSONField(blank=True, default=dict)),
                ('slug', models.SlugField(blank=True, max_length=140, null=True, unique=True, verbose_name='Slug')),
                ('reports_count', models.PositiveIntegerField(default=0, help_text='Historical cumulative reports count (not active wave).')),
                ('is_suspended', models.BooleanField(default=False, help_text='System-level suspension due to moderation outcome.')),
                ('is_active', models.BooleanField(default=True, help_text='System-level activation flag (false = removed from feeds).')),
                ('suspended_at', models.DateTimeField(blank=True, help_text='Timestamp when target was suspended.', null=True)),
                ('suspension_reason', models.CharField(blank=True, help_text='Optional reason code or short description.', max_length=255, null=True)),
                ('comments_count', models.PositiveIntegerField(default=0)),
                ('recomments_count', models.PositiveIntegerField(default=0)),
                ('reactions_count', models.PositiveIntegerField(default=0)),
                ('reactions_breakdown', models.JSONField(blank=True, default=dict)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('teaching_type', models.CharField(choices=[('sermon', 'Sermon'), ('bible_teaching', 'Bible Teaching'), ('devotional', 'Devotional'), ('training', 'Training')], db_index=True, default='sermon', max_length=30)),
                ('content_format', models.CharField(choices=[('written', 'Written'), ('video', 'Video')], db_index=True, max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=16)),
                ('audience', models.CharField(choices=[('public', 'Public'), ('organization_members', 'Organization Members'), ('internal', 'Authorized Church Staff')], db_index=True, default='public', max_length=30)),
                ('title', models.CharField(max_length=220)),
                ('excerpt', models.CharField(blank=True, default='', max_length=1000)),
                ('body', models.TextField(blank=True, default='')),
                ('speaker_name_snapshot', models.CharField(max_length=180)),
                ('video', models.FileField(blank=True, max_length=700, null=True, upload_to=utils.common.utils.FileUpload('posts', 'videos', 'church_teaching'), validators=[validators.security_validators.validate_no_executable_file])),
                ('thumbnail', models.ImageField(blank=True, max_length=700, null=True, upload_to=utils.common.utils.FileUpload('posts', 'photos', 'church_teaching'), validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file])),
                ('is_converted', models.BooleanField(db_index=True, default=True)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='church_teaching_contents_archived', to=settings.AUTH_USER_MODEL)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_contents', to='organizations.churchcampus')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='church_teaching_contents_created', to=settings.AUTH_USER_MODEL)),
                ('ministry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_contents', to='organizations.churchministry')),
                ('occurrence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_contents', to='organizations.churchgatheringoccurrence')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='church_teaching_contents_published', to=settings.AUTH_USER_MODEL)),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contents', to='organizations.churchteachingseries')),
                ('service_plan_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_contents', to='organizations.churchserviceplanitem')),
                ('speaker_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='church_teaching_contents_spoken', to='organizations.organizationmembership')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='church_teaching_contents_updated', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_contents', to='organizations.churchworkspace')),
            ],
            options={
                'verbose_name': 'Church Teaching Content',
                'verbose_name_plural': 'Church Teaching Content',
                'ordering': ('-published_at', '-created_at', '-id'),
            },
            bases=(utils.mixins.media_autoconvert.MediaAutoConvertMixin, utils.mixins.media_conversion.MediaConversionMixin, apps.core.availability.interfaces.AvailabilityAware, models.Model),
        ),
        migrations.CreateModel(
            name='ChurchTeachingScriptureReference',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('reference_text', models.CharField(max_length=180)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('normalized', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scripture_references', to='posts.churchteachingcontent')),
            ],
            options={
                'verbose_name': 'Church Teaching Scripture Reference',
                'verbose_name_plural': 'Church Teaching Scripture References',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.RemoveField(
            model_name='conference',
            name='conference_resources',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='workshops',
        ),
        migrations.RemoveField(
            model_name='futureconference',
            name='conference_location',
        ),
        migrations.RemoveField(
            model_name='futureconference',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='futureconference',
            name='in_town_speakers',
        ),
        migrations.RemoveField(
            model_name='futureconference',
            name='sponsors',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='in_town_teachers',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='library',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='mediacontent',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='contact_persons',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='location',
        ),
        migrations.RemoveField(
            model_name='preach',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='preach',
            name='in_town_preacher',
        ),
        migrations.RemoveField(
            model_name='serviceevent',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='serviceevent',
            name='location',
        ),
        migrations.RemoveField(
            model_name='worship',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='worship',
            name='in_town_leaders',
        ),
        migrations.RemoveField(
            model_name='worship',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='worship',
            name='worship_resources',
        ),
        migrations.AlterField(
            model_name='journeyentry',
            name='rendered_image',
            field=models.ImageField(blank=True, max_length=700, null=True, upload_to=utils.common.utils.FileUpload.dir_upload),
        ),
        migrations.AlterField(
            model_name='journeyentry',
            name='rendered_video',
            field=models.FileField(blank=True, max_length=700, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.security_validators.validate_no_executable_file]),
        ),
        migrations.AlterField(
            model_name='journeyentry',
            name='thumbnail',
            field=models.ImageField(max_length=700, upload_to=utils.common.utils.FileUpload.dir_upload),
        ),
        migrations.AlterField(
            model_name='moment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_moment_image_size, validators.security_validators.validate_no_executable_file], verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='moment',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file], verbose_name='Thumbnail'),
        ),
        migrations.AlterField(
            model_name='moment',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.video_validators.validate_moment_video_file, validators.security_validators.validate_no_executable_file], verbose_name='Video'),
        ),
        migrations.AlterField(
            model_name='prayer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file], verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='prayer',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file], verbose_name='Thumbnail'),
        ),
        migrations.AlterField(
            model_name='prayer',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.video_validators.validate_prayer_video_file, validators.security_validators.validate_no_executable_file], verbose_name='Video'),
        ),
        migrations.AlterField(
            model_name='prayerresponse',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file], verbose_name='Response Image'),
        ),
        migrations.AlterField(
            model_name='prayerresponse',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file], verbose_name='Response Thumbnail'),
        ),
        migrations.AlterField(
            model_name='prayerresponse',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.video_validators.validate_prayer_video_file, validators.security_validators.validate_no_executable_file], verbose_name='Response Video'),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.audio_validators.validate_audio_file, validators.security_validators.validate_no_executable_file], verbose_name='Testimony Audio'),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='audio_artwork',
            field=models.ImageField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file], verbose_name='Audio Artwork'),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file], verbose_name='Thumbnail'),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.video_validators.validate_testimony_video_file, validators.security_validators.validate_no_executable_file], verbose_name='Testimony Video'),
        ),
        migrations.DeleteModel(
            name='Announcement',
        ),
        migrations.DeleteModel(
            name='Conference',
        ),
        migrations.DeleteModel(
            name='FutureConference',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.DeleteModel(
            name='Library',
        ),
        migrations.DeleteModel(
            name='MediaContent',
        ),
        migrations.DeleteModel(
            name='Mission',
        ),
        migrations.DeleteModel(
            name='Preach',
        ),
        migrations.DeleteModel(
            name='ServiceEvent',
        ),
        migrations.DeleteModel(
            name='Worship',
        ),
        migrations.AddIndex(
            model_name='churchteachingscripturereference',
            index=models.Index(fields=['content', 'sort_order'], name='posts_churc_content_0ca17a_idx'),
        ),
        migrations.AddConstraint(
            model_name='churchteachingscripturereference',
            constraint=models.UniqueConstraint(fields=('content', 'sort_order'), name='posts_church_teaching_unique_scripture_order'),
        ),
        migrations.AddIndex(
            model_name='churchteachingcontent',
            index=models.Index(fields=['workspace', 'status', 'created_at'], name='posts_churc_workspa_4dff52_idx'),
        ),
        migrations.AddIndex(
            model_name='churchteachingcontent',
            index=models.Index(fields=['workspace', 'audience', 'status'], name='posts_churc_workspa_66132d_idx'),
        ),
        migrations.AddIndex(
            model_name='churchteachingcontent',
            index=models.Index(fields=['series', 'status', 'published_at'], name='posts_churc_series__73b67e_idx'),
        ),
        migrations.AddIndex(
            model_name='churchteachingcontent',
            index=models.Index(fields=['occurrence', 'status'], name='posts_churc_occurre_2d0642_idx'),
        ),
        migrations.AddIndex(
            model_name='churchteachingcontent',
            index=models.Index(fields=['teaching_type', 'content_format', 'status'], name='posts_churc_teachin_1e2633_idx'),
        ),
        migrations.AddConstraint(
            model_name='churchteachingcontent',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('archived_at__isnull', True), ('published_at__isnull', True), ('status', 'draft')), models.Q(('archived_at__isnull', True), ('published_at__isnull', False), ('status', 'published')), models.Q(('archived_at__isnull', False), ('status', 'archived')), _connector='OR'), name='posts_church_teaching_status_consistent'),
        ),
    ]
