# Generated by Django 4.2.4 on 2026-09-14 17:32

from django.db import migrations, models
import utils.common.utils
import validators.mediaValidators.audio_validators
import validators.mediaValidators.image_validators
import validators.mediaValidators.video_validators
import validators.security_validators


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0088_churchteachingcontent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journeyentry',
            name='rendered_image',
            field=models.ImageField(blank=True, max_length=700, null=True, upload_to=utils.common.utils.FileUpload('posts', 'images', 'journey')),
        ),
        migrations.AlterField(
            model_name='journeyentry',
            name='rendered_video',
            field=models.FileField(blank=True, max_length=700, null=True, upload_to=utils.common.utils.FileUpload('posts', 'videos', 'journey'), validators=[validators.security_validators.validate_no_executable_file]),
        ),
        migrations.AlterField(
            model_name='journeyentry',
            name='thumbnail',
            field=models.ImageField(max_length=700, upload_to=utils.common.utils.FileUpload('posts', 'thumbnails', 'journey')),
        ),
        migrations.AlterField(
            model_name='moment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.common.utils.FileUpload('posts', 'images', 'moment'), validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_moment_image_size, validators.security_validators.validate_no_executable_file], verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='moment',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=utils.common.utils.FileUpload('posts', 'images', 'moment'), validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file], verbose_name='Thumbnail'),
        ),
        migrations.AlterField(
            model_name='moment',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload('posts', 'videos', 'moment'), validators=[validators.mediaValidators.video_validators.validate_moment_video_file, validators.security_validators.validate_no_executable_file], verbose_name='Video'),
        ),
        migrations.AlterField(
            model_name='prayer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.common.utils.FileUpload('posts', 'images', 'pray'), validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file], verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='prayer',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=utils.common.utils.FileUpload('posts', 'images', 'pray'), validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file], verbose_name='Thumbnail'),
        ),
        migrations.AlterField(
            model_name='prayer',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload('posts', 'videos', 'pray'), validators=[validators.mediaValidators.video_validators.validate_prayer_video_file, validators.security_validators.validate_no_executable_file], verbose_name='Video'),
        ),
        migrations.AlterField(
            model_name='prayerresponse',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.common.utils.FileUpload('posts', 'images', 'pray'), validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file], verbose_name='Response Image'),
        ),
        migrations.AlterField(
            model_name='prayerresponse',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=utils.common.utils.FileUpload('posts', 'images', 'pray'), validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file], verbose_name='Response Thumbnail'),
        ),
        migrations.AlterField(
            model_name='prayerresponse',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload('posts', 'videos', 'pray'), validators=[validators.mediaValidators.video_validators.validate_prayer_video_file, validators.security_validators.validate_no_executable_file], verbose_name='Response Video'),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload('posts', 'audios', 'testimony'), validators=[validators.mediaValidators.audio_validators.validate_audio_file, validators.security_validators.validate_no_executable_file], verbose_name='Testimony Audio'),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='audio_artwork',
            field=models.ImageField(blank=True, null=True, upload_to=utils.common.utils.FileUpload('posts', 'artworks', 'testimony'), validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file], verbose_name='Audio Artwork'),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=utils.common.utils.FileUpload('posts', 'photos', 'testimony'), validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file], verbose_name='Thumbnail'),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=utils.common.utils.FileUpload('posts', 'videos', 'testimony'), validators=[validators.mediaValidators.video_validators.validate_testimony_video_file, validators.security_validators.validate_no_executable_file], verbose_name='Testimony Video'),
        ),
    ]
