# Generated by Django 4.2.4 on 2026-09-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0010_stabilize_worship_evidence_upload_path'),
        ('posts', '0089_stabilize_posts_media_upload_paths'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimony',
            name='org_tags',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='tagged_in_testimonies', to='organizations.organization'),
        ),
    ]
