# Generated by Django 4.2.4 on 2026-08-29 16:08

from django.db import migrations, models
import utils.common.utils
import validators.mediaValidators.image_validators
import validators.security_validators


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='organizationconnection',
            name='organizations_unique_active_connection_per_user',
        ),
        migrations.RemoveConstraint(
            model_name='organizationmembership',
            name='organizations_unique_current_membership',
        ),
        migrations.RemoveConstraint(
            model_name='organizationmembershiprequest',
            name='organizations_unique_pending_membership_request',
        ),
        migrations.RemoveConstraint(
            model_name='organizationroleassignment',
            name='organizations_unique_active_role_assignment',
        ),
        migrations.AddField(
            model_name='organizationconnection',
            name='active_slot',
            field=models.PositiveSmallIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='current_slot',
            field=models.PositiveSmallIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='organizationmembershiprequest',
            name='pending_slot',
            field=models.PositiveSmallIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='organizationroleassignment',
            name='active_slot',
            field=models.PositiveSmallIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file]),
        ),
        migrations.AddConstraint(
            model_name='organizationconnection',
            constraint=models.UniqueConstraint(fields=('organization', 'user', 'active_slot'), name='organizations_unique_active_connection_per_user'),
        ),
        migrations.AddConstraint(
            model_name='organizationmembership',
            constraint=models.UniqueConstraint(fields=('organization', 'member', 'current_slot'), name='organizations_unique_current_membership'),
        ),
        migrations.AddConstraint(
            model_name='organizationmembershiprequest',
            constraint=models.UniqueConstraint(fields=('organization', 'member', 'pending_slot'), name='organizations_unique_pending_membership_request'),
        ),
        migrations.AddConstraint(
            model_name='organizationroleassignment',
            constraint=models.UniqueConstraint(fields=('membership', 'role', 'scope_type', 'scope_key', 'active_slot'), name='organizations_unique_active_role_assignment'),
        ),
    ]
