# Generated by Django 4.2.4 on 2026-08-30 14:44

import apps.organizations.models.verification
import apps.organizations.upload_paths
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid
import validators.mediaValidators.image_validators
import validators.security_validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0002_remove_organizationconnection_organizations_unique_active_connection_per_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationGovernanceElector',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('membership_id_snapshot', models.PositiveBigIntegerField()),
                ('role_keys_snapshot', models.JSONField(blank=True, default=list)),
                ('vote_weight', models.DecimalField(decimal_places=3, default='1.000', max_digits=8)),
                ('is_eligible', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='governance_elector_snapshots', to='organizations.organizationmembership')),
            ],
            options={
                'verbose_name': 'Organization Governance Elector',
                'verbose_name_plural': 'Organization Governance Electors',
            },
        ),
        migrations.CreateModel(
            name='OrganizationGovernanceProposal',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('action_key', models.CharField(choices=[('owner_addition', 'Add Owner'), ('owner_removal', 'Remove Owner'), ('organization_closure', 'Close Organization'), ('organization_restoration', 'Restore Organization'), ('relationship_consent', 'Relationship Consent'), ('relationship_ending', 'End Relationship')], db_index=True, max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('canceled', 'Canceled'), ('executed', 'Executed'), ('execution_failed', 'Execution Failed')], db_index=True, default='draft', max_length=30)),
                ('open_slot', models.PositiveSmallIntegerField(blank=True, editable=False, null=True)),
                ('subject_key', models.CharField(db_index=True, default='global', editable=False, max_length=120)),
                ('title', models.CharField(max_length=240)),
                ('rationale', models.TextField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('rule_snapshot', models.JSONField(blank=True, default=dict)),
                ('opened_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('closes_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('executed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('execution_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_organization_governance_proposals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organization Governance Proposal',
                'verbose_name_plural': 'Organization Governance Proposals',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrganizationGovernanceVote',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('choice', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject'), ('abstain', 'Abstain')], db_index=True, max_length=20)),
                ('cast_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cast_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organization_governance_votes', to=settings.AUTH_USER_MODEL)),
                ('elector', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='vote', to='organizations.organizationgovernanceelector')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='organizations.organizationgovernanceproposal')),
            ],
            options={
                'verbose_name': 'Organization Governance Vote',
                'verbose_name_plural': 'Organization Governance Votes',
                'ordering': ('cast_at',),
            },
        ),
        migrations.CreateModel(
            name='OrganizationRelationship',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('relationship_type', models.CharField(choices=[('parent_branch', 'Parent / Branch'), ('affiliate', 'Affiliate'), ('network_member', 'Network Membership'), ('sponsorship', 'Sponsorship')], db_index=True, max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('rejected', 'Rejected'), ('suspended', 'Suspended'), ('ended', 'Ended')], db_index=True, default='pending', max_length=20)),
                ('current_slot', models.PositiveSmallIntegerField(blank=True, editable=False, null=True)),
                ('authority_slot', models.PositiveSmallIntegerField(blank=True, editable=False, null=True)),
                ('activated_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('suspended_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('end_reason', models.CharField(blank=True, max_length=1000, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_organization_relationships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organization Relationship',
                'verbose_name_plural': 'Organization Relationships',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrganizationVerificationCase',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('path', models.CharField(choices=[('direct', 'Direct Legal Verification'), ('sponsored_branch', 'Sponsored Branch Verification')], db_index=True, default='direct', max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('needs_information', 'Needs Information'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], db_index=True, default='draft', max_length=30)),
                ('current_slot', models.PositiveSmallIntegerField(blank=True, editable=False, null=True)),
                ('legal_name', models.CharField(blank=True, max_length=240, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=120, null=True)),
                ('jurisdiction_country', models.CharField(blank=True, choices=[('AF', 'Afghanistan'), ('AL', 'Albania'), ('DZ', 'Algeria'), ('AD', 'Andorra'), ('AO', 'Angola'), ('AG', 'Antigua and Barbuda'), ('AR', 'Argentina'), ('AM', 'Armenia'), ('AU', 'Australia'), ('AT', 'Austria'), ('AZ', 'Azerbaijan'), ('BS', 'Bahamas'), ('BH', 'Bahrain'), ('BD', 'Bangladesh'), ('BB', 'Barbados'), ('BY', 'Belarus'), ('BE', 'Belgium'), ('BZ', 'Belize'), ('BJ', 'Benin'), ('BT', 'Bhutan'), ('BO', 'Bolivia'), ('BA', 'Bosnia and Herzegovina'), ('BW', 'Botswana'), ('BR', 'Brazil'), ('BN', 'Brunei'), ('BG', 'Bulgaria'), ('BF', 'Burkina Faso'), ('BI', 'Burundi'), ('CV', 'Cabo Verde'), ('KH', 'Cambodia'), ('CM', 'Cameroon'), ('CA', 'Canada'), ('CF', 'Central African Republic'), ('TD', 'Chad'), ('CL', 'Chile'), ('CN', 'China'), ('CO', 'Colombia'), ('KM', 'Comoros'), ('CG', 'Congo'), ('CR', 'Costa Rica'), ('HR', 'Croatia'), ('CU', 'Cuba'), ('CY', 'Cyprus'), ('CZ', 'Czechia'), ('DK', 'Denmark'), ('DJ', 'Djibouti'), ('DM', 'Dominica'), ('DO', 'Dominican Republic'), ('EC', 'Ecuador'), ('EG', 'Egypt'), ('SV', 'El Salvador'), ('GQ', 'Equatorial Guinea'), ('ER', 'Eritrea'), ('EE', 'Estonia'), ('SZ', 'Eswatini'), ('ET', 'Ethiopia'), ('FJ', 'Fiji'), ('FI', 'Finland'), ('FR', 'France'), ('GA', 'Gabon'), ('GM', 'Gambia'), ('GE', 'Georgia'), ('DE', 'Germany'), ('GH', 'Ghana'), ('GR', 'Greece'), ('GD', 'Grenada'), ('GT', 'Guatemala'), ('GN', 'Guinea'), ('GW', 'Guinea-Bissau'), ('GY', 'Guyana'), ('HT', 'Haiti'), ('VA', 'Holy See'), ('HN', 'Honduras'), ('HU', 'Hungary'), ('IS', 'Iceland'), ('IN', 'India'), ('ID', 'Indonesia'), ('IR', 'Iran'), ('IQ', 'Iraq'), ('IE', 'Ireland'), ('IL', 'Israel'), ('IT', 'Italy'), ('JM', 'Jamaica'), ('JP', 'Japan'), ('JO', 'Jordan'), ('KZ', 'Kazakhstan'), ('KE', 'Kenya'), ('KI', 'Kiribati'), ('KP', 'Korea (North)'), ('KR', 'Korea (South)'), ('XK', 'Kosovo'), ('KW', 'Kuwait'), ('KG', 'Kyrgyzstan'), ('LA', 'Laos'), ('LV', 'Latvia'), ('LB', 'Lebanon'), ('LS', 'Lesotho'), ('LR', 'Liberia'), ('LY', 'Libya'), ('LI', 'Liechtenstein'), ('LT', 'Lithuania'), ('LU', 'Luxembourg'), ('MG', 'Madagascar'), ('MW', 'Malawi'), ('MY', 'Malaysia'), ('MV', 'Maldives'), ('ML', 'Mali'), ('MT', 'Malta'), ('MH', 'Marshall Islands'), ('MR', 'Mauritania'), ('MU', 'Mauritius'), ('MX', 'Mexico'), ('FM', 'Micronesia'), ('MD', 'Moldova'), ('MC', 'Monaco'), ('MN', 'Mongolia'), ('ME', 'Montenegro'), ('MA', 'Morocco'), ('MZ', 'Mozambique'), ('MM', 'Myanmar'), ('NA', 'Namibia'), ('NR', 'Nauru'), ('NP', 'Nepal'), ('NL', 'Netherlands'), ('NZ', 'New Zealand'), ('NI', 'Nicaragua'), ('NE', 'Niger'), ('NG', 'Nigeria'), ('MK', 'North Macedonia'), ('NO', 'Norway'), ('OM', 'Oman'), ('PK', 'Pakistan'), ('PW', 'Palau'), ('PS', 'Palestine'), ('PA', 'Panama'), ('PG', 'Papua New Guinea'), ('PY', 'Paraguay'), ('PE', 'Peru'), ('PH', 'Philippines'), ('PL', 'Poland'), ('PT', 'Portugal'), ('QA', 'Qatar'), ('RO', 'Romania'), ('RU', 'Russia'), ('RW', 'Rwanda'), ('KN', 'Saint Kitts and Nevis'), ('LC', 'Saint Lucia'), ('VC', 'Saint Vincent and the Grenadines'), ('WS', 'Samoa'), ('SM', 'San Marino'), ('ST', 'Sao Tome and Principe'), ('SA', 'Saudi Arabia'), ('SN', 'Senegal'), ('RS', 'Serbia'), ('SC', 'Seychelles'), ('SL', 'Sierra Leone'), ('SG', 'Singapore'), ('SK', 'Slovakia'), ('SI', 'Slovenia'), ('SB', 'Solomon Islands'), ('SO', 'Somalia'), ('ZA', 'South Africa'), ('SS', 'South Sudan'), ('ES', 'Spain'), ('LK', 'Sri Lanka'), ('SD', 'Sudan'), ('SR', 'Suriname'), ('SE', 'Sweden'), ('CH', 'Switzerland'), ('SY', 'Syria'), ('TW', 'Taiwan'), ('TJ', 'Tajikistan'), ('TZ', 'Tanzania'), ('TH', 'Thailand'), ('TL', 'Timor-Leste'), ('TG', 'Togo'), ('TO', 'Tonga'), ('TT', 'Trinidad and Tobago'), ('TN', 'Tunisia'), ('TR', 'Turkey'), ('TM', 'Turkmenistan'), ('TV', 'Tuvalu'), ('UG', 'Uganda'), ('UA', 'Ukraine'), ('AE', 'United Arab Emirates'), ('GB', 'United Kingdom'), ('US', 'United States'), ('UY', 'Uruguay'), ('UZ', 'Uzbekistan'), ('VU', 'Vanuatu'), ('VE', 'Venezuela'), ('VN', 'Vietnam'), ('YE', 'Yemen'), ('ZM', 'Zambia'), ('ZW', 'Zimbabwe')], db_index=True, max_length=2, null=True)),
                ('jurisdiction_region', models.CharField(blank=True, max_length=160, null=True)),
                ('registration_authority', models.CharField(blank=True, max_length=240, null=True)),
                ('registered_address', models.TextField(blank=True, null=True)),
                ('organization_notes', models.TextField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('review_started_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('decision_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organization Verification Case',
                'verbose_name_plural': 'Organization Verification Cases',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.organizations.upload_paths.organization_logo_upload_to, validators=[validators.mediaValidators.image_validators.validate_image_file, validators.mediaValidators.image_validators.validate_image_size, validators.security_validators.validate_no_executable_file]),
        ),
        migrations.AlterField(
            model_name='organizationauditlog',
            name='action',
            field=models.CharField(choices=[('organization_created', 'Organization Created'), ('organization_updated', 'Organization Updated'), ('followed', 'Organization Followed'), ('unfollowed', 'Organization Unfollowed'), ('membership_requested', 'Membership Requested'), ('membership_invited', 'Membership Invited'), ('membership_accepted', 'Membership Accepted'), ('membership_rejected', 'Membership Rejected'), ('membership_withdrawn', 'Membership Withdrawn'), ('membership_canceled', 'Membership Invitation Canceled'), ('member_left', 'Member Left'), ('member_removed', 'Member Removed'), ('role_assigned', 'Role Assigned'), ('role_revoked', 'Role Revoked'), ('verification_case_created', 'Verification Case Created'), ('verification_submitted', 'Verification Submitted'), ('verification_needs_information', 'Verification Needs Information'), ('verification_approved', 'Verification Approved'), ('verification_rejected', 'Verification Rejected'), ('verification_withdrawn', 'Verification Withdrawn'), ('verification_revoked', 'Verification Revoked'), ('relationship_requested', 'Relationship Requested'), ('relationship_consent_approved', 'Relationship Consent Approved'), ('relationship_consent_rejected', 'Relationship Consent Rejected'), ('relationship_activated', 'Relationship Activated'), ('relationship_ended', 'Relationship Ended'), ('governance_proposal_created', 'Governance Proposal Created'), ('governance_proposal_opened', 'Governance Proposal Opened'), ('governance_vote_cast', 'Governance Vote Cast'), ('governance_decided', 'Governance Decided'), ('governance_executed', 'Governance Executed'), ('governance_execution_failed', 'Governance Execution Failed')], db_index=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='organizationauditlog',
            name='source',
            field=models.CharField(choices=[('service', 'TownLIT Service'), ('admin', 'TownLIT Admin'), ('system', 'System'), ('governance', 'Governance')], db_index=True, default='service', max_length=20),
        ),
        migrations.CreateModel(
            name='OrganizationVerificationGrant',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('grant_type', models.CharField(choices=[('direct', 'Verified Organization'), ('sponsored_branch', 'Verified Branch')], db_index=True, max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('superseded', 'Superseded'), ('revoked', 'Revoked'), ('expired', 'Expired')], db_index=True, default='active', max_length=20)),
                ('active_slot', models.PositiveSmallIntegerField(blank=True, editable=False, null=True)),
                ('granted_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('revocation_reason', models.CharField(blank=True, max_length=1000, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_organization_verifications', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_grants', to='organizations.organization')),
                ('relationship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verification_grants', to='organizations.organizationrelationship')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by_grants', to='organizations.organizationverificationgrant')),
                ('verification_case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grants', to='organizations.organizationverificationcase')),
            ],
            options={
                'verbose_name': 'Organization Verification Grant',
                'verbose_name_plural': 'Organization Verification Grants',
                'ordering': ('-granted_at',),
            },
        ),
        migrations.CreateModel(
            name='OrganizationVerificationDocument',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('document_type', models.CharField(choices=[('incorporation', 'Incorporation Document'), ('charity_registration', 'Charity Registration'), ('church_registration', 'Church Registration'), ('tax_document', 'Tax Document'), ('authorization_letter', 'Authorization Letter'), ('parent_organization_letter', 'Parent Organization Letter'), ('representative_identity', 'Authorized Representative Identity'), ('other', 'Other')], db_index=True, max_length=40)),
                ('title', models.CharField(blank=True, max_length=240, null=True)),
                ('file', models.FileField(upload_to=apps.organizations.upload_paths.organization_verification_upload_to, validators=[apps.organizations.models.verification.validate_organization_verification_file])),
                ('document_number', models.CharField(blank=True, max_length=160, null=True)),
                ('issued_at', models.DateField(blank=True, null=True)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('review_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('review_note', models.CharField(blank=True, max_length=1000, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_organization_verification_documents', to=settings.AUTH_USER_MODEL)),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_documents', to='organizations.organizationverificationdocument')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_organization_verification_documents', to=settings.AUTH_USER_MODEL)),
                ('verification_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='organizations.organizationverificationcase')),
            ],
            options={
                'verbose_name': 'Organization Verification Document',
                'verbose_name_plural': 'Organization Verification Documents',
                'ordering': ('created_at',),
            },
        ),
        migrations.AddField(
            model_name='organizationverificationcase',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_cases', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='organizationverificationcase',
            name='relationship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verification_cases', to='organizations.organizationrelationship'),
        ),
        migrations.AddField(
            model_name='organizationverificationcase',
            name='renewal_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='renewal_cases', to='organizations.organizationverificationgrant'),
        ),
        migrations.AddField(
            model_name='organizationverificationcase',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_organization_verification_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationverificationcase',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_organization_verification_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='OrganizationRelationshipConsent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revoked', 'Revoked')], db_index=True, default='pending', max_length=20)),
                ('decided_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('note', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_relationship_consent_decisions', to=settings.AUTH_USER_MODEL)),
                ('governance_proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relationship_consent_records', to='organizations.organizationgovernanceproposal')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationship_consents', to='organizations.organization')),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='organizations.organizationrelationship')),
            ],
            options={
                'verbose_name': 'Organization Relationship Consent',
                'verbose_name_plural': 'Organization Relationship Consents',
            },
        ),
        migrations.AddField(
            model_name='organizationrelationship',
            name='requested_by_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_relationships', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='organizationrelationship',
            name='source_organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='organizationrelationship',
            name='target_organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='organizations.organization'),
        ),
        migrations.CreateModel(
            name='OrganizationGovernanceVoteRevision',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('previous_choice', models.CharField(blank=True, choices=[('approve', 'Approve'), ('reject', 'Reject'), ('abstain', 'Abstain')], max_length=20, null=True)),
                ('new_choice', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject'), ('abstain', 'Abstain')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organization_governance_vote_revisions', to=settings.AUTH_USER_MODEL)),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='organizations.organizationgovernancevote')),
            ],
            options={
                'verbose_name': 'Organization Governance Vote Revision',
                'verbose_name_plural': 'Organization Governance Vote Revisions',
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='OrganizationGovernanceRule',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action_key', models.CharField(choices=[('owner_addition', 'Add Owner'), ('owner_removal', 'Remove Owner'), ('organization_closure', 'Close Organization'), ('organization_restoration', 'Restore Organization'), ('relationship_consent', 'Relationship Consent'), ('relationship_ending', 'End Relationship')], db_index=True, max_length=50)),
                ('electorate_type', models.CharField(choices=[('owners', 'Owners'), ('active_members', 'Active Members'), ('role', 'Specific Role')], default='owners', max_length=30)),
                ('quorum_percent', models.DecimalField(decimal_places=2, default='100.00', max_digits=5)),
                ('approval_percent', models.DecimalField(decimal_places=2, default='66.67', max_digits=5)),
                ('minimum_electors', models.PositiveSmallIntegerField(default=1)),
                ('voting_period_hours', models.PositiveIntegerField(default=72)),
                ('allow_abstain', models.BooleanField(default=True)),
                ('allow_vote_changes', models.BooleanField(default=False)),
                ('exclude_target_membership', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('electorate_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='governance_rules', to='organizations.organizationrole')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='governance_rules', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Organization Governance Rule',
                'verbose_name_plural': 'Organization Governance Rules',
                'ordering': ('action_key',),
            },
        ),
        migrations.AddField(
            model_name='organizationgovernanceproposal',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='governance_proposals', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='organizationgovernanceproposal',
            name='proposed_by_membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='governance_proposals_created', to='organizations.organizationmembership'),
        ),
        migrations.AddField(
            model_name='organizationgovernanceproposal',
            name='relationship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='governance_proposals', to='organizations.organizationrelationship'),
        ),
        migrations.AddField(
            model_name='organizationgovernanceproposal',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='organizations.organizationgovernancerule'),
        ),
        migrations.AddField(
            model_name='organizationgovernanceproposal',
            name='target_membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='governance_proposals_as_target', to='organizations.organizationmembership'),
        ),
        migrations.AddField(
            model_name='organizationgovernanceelector',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electors', to='organizations.organizationgovernanceproposal'),
        ),
        migrations.AddField(
            model_name='organizationgovernanceelector',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organization_governance_elector_snapshots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='OrganizationGovernanceDecision',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('result', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('no_quorum', 'No Quorum'), ('insufficient_electorate', 'Insufficient Electorate')], db_index=True, max_length=30)),
                ('eligible_count', models.PositiveIntegerField(default=0)),
                ('participating_count', models.PositiveIntegerField(default=0)),
                ('approve_count', models.PositiveIntegerField(default=0)),
                ('reject_count', models.PositiveIntegerField(default=0)),
                ('abstain_count', models.PositiveIntegerField(default=0)),
                ('eligible_weight', models.DecimalField(decimal_places=3, default='0.000', max_digits=14)),
                ('participating_weight', models.DecimalField(decimal_places=3, default='0.000', max_digits=14)),
                ('approve_weight', models.DecimalField(decimal_places=3, default='0.000', max_digits=14)),
                ('reject_weight', models.DecimalField(decimal_places=3, default='0.000', max_digits=14)),
                ('abstain_weight', models.DecimalField(decimal_places=3, default='0.000', max_digits=14)),
                ('quorum_required_weight', models.DecimalField(decimal_places=3, default='0.000', max_digits=14)),
                ('approval_required_weight', models.DecimalField(decimal_places=3, default='0.000', max_digits=14)),
                ('quorum_percent_snapshot', models.DecimalField(decimal_places=2, max_digits=5)),
                ('approval_percent_snapshot', models.DecimalField(decimal_places=2, max_digits=5)),
                ('participation_percent', models.DecimalField(decimal_places=2, default='0.00', max_digits=5)),
                ('approval_percent_actual', models.DecimalField(decimal_places=2, default='0.00', max_digits=5)),
                ('quorum_met', models.BooleanField(default=False)),
                ('approval_met', models.BooleanField(default=False)),
                ('algorithm_version', models.PositiveSmallIntegerField(default=1)),
                ('decided_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decision', to='organizations.organizationgovernanceproposal')),
            ],
            options={
                'verbose_name': 'Organization Governance Decision',
                'verbose_name_plural': 'Organization Governance Decisions',
            },
        ),
        migrations.AddField(
            model_name='organizationauditlog',
            name='governance_proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='organizations.organizationgovernanceproposal'),
        ),
        migrations.AddField(
            model_name='organizationauditlog',
            name='relationship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='organizations.organizationrelationship'),
        ),
        migrations.AddField(
            model_name='organizationauditlog',
            name='verification_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='organizations.organizationverificationcase'),
        ),
        migrations.AddIndex(
            model_name='organizationverificationgrant',
            index=models.Index(fields=['organization', 'status', 'granted_at'], name='organizatio_organiz_80df15_idx'),
        ),
        migrations.AddConstraint(
            model_name='organizationverificationgrant',
            constraint=models.UniqueConstraint(fields=('organization', 'active_slot'), name='organizations_unique_active_verification_grant'),
        ),
        migrations.AddConstraint(
            model_name='organizationverificationgrant',
            constraint=models.CheckConstraint(check=models.Q(('expires_at__isnull', True), ('expires_at__gt', models.F('granted_at')), _connector='OR'), name='organizations_verification_grant_valid_window'),
        ),
        migrations.AddIndex(
            model_name='organizationverificationdocument',
            index=models.Index(fields=['verification_case', 'is_active', 'review_status'], name='organizatio_verific_775f1d_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationverificationcase',
            index=models.Index(fields=['organization', 'status', 'created_at'], name='organizatio_organiz_458fbc_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationverificationcase',
            index=models.Index(fields=['status', 'submitted_at'], name='organizatio_status_c8a0ae_idx'),
        ),
        migrations.AddConstraint(
            model_name='organizationverificationcase',
            constraint=models.UniqueConstraint(fields=('organization', 'current_slot'), name='organizations_unique_open_verification_case'),
        ),
        migrations.AddConstraint(
            model_name='organizationrelationshipconsent',
            constraint=models.UniqueConstraint(fields=('relationship', 'organization'), name='organizations_unique_relationship_consent'),
        ),
        migrations.AddIndex(
            model_name='organizationrelationship',
            index=models.Index(fields=['source_organization', 'relationship_type', 'status'], name='organizatio_source__1037f3_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationrelationship',
            index=models.Index(fields=['target_organization', 'relationship_type', 'status'], name='organizatio_target__21cfc2_idx'),
        ),
        migrations.AddConstraint(
            model_name='organizationrelationship',
            constraint=models.CheckConstraint(check=models.Q(('source_organization', models.F('target_organization')), _negated=True), name='organizations_relationship_distinct_parties'),
        ),
        migrations.AddConstraint(
            model_name='organizationrelationship',
            constraint=models.UniqueConstraint(fields=('source_organization', 'target_organization', 'relationship_type', 'current_slot'), name='organizations_unique_current_relationship'),
        ),
        migrations.AddConstraint(
            model_name='organizationrelationship',
            constraint=models.UniqueConstraint(fields=('target_organization', 'relationship_type', 'authority_slot'), name='organizations_unique_current_authority'),
        ),
        migrations.AddConstraint(
            model_name='organizationgovernancerule',
            constraint=models.UniqueConstraint(fields=('organization', 'action_key'), name='organizations_unique_governance_rule'),
        ),
        migrations.AddConstraint(
            model_name='organizationgovernancerule',
            constraint=models.CheckConstraint(check=models.Q(('quorum_percent__gte', 0), ('quorum_percent__lte', 100)), name='organizations_governance_quorum_range'),
        ),
        migrations.AddConstraint(
            model_name='organizationgovernancerule',
            constraint=models.CheckConstraint(check=models.Q(('approval_percent__gte', 0), ('approval_percent__lte', 100)), name='organizations_governance_approval_range'),
        ),
        migrations.AddIndex(
            model_name='organizationgovernanceproposal',
            index=models.Index(fields=['organization', 'status', 'created_at'], name='organizatio_organiz_9620e4_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationgovernanceproposal',
            index=models.Index(fields=['status', 'closes_at'], name='organizatio_status_a5d283_idx'),
        ),
        migrations.AddConstraint(
            model_name='organizationgovernanceproposal',
            constraint=models.UniqueConstraint(fields=('organization', 'action_key', 'subject_key', 'open_slot'), name='organizations_unique_open_governance_action'),
        ),
        migrations.AddConstraint(
            model_name='organizationgovernanceproposal',
            constraint=models.CheckConstraint(check=models.Q(('closes_at__isnull', True), ('opened_at__isnull', True), ('closes_at__gt', models.F('opened_at')), _connector='OR'), name='organizations_governance_voting_window'),
        ),
        migrations.AddConstraint(
            model_name='organizationgovernanceelector',
            constraint=models.UniqueConstraint(fields=('proposal', 'membership'), name='organizations_unique_governance_elector_membership'),
        ),
        migrations.AddConstraint(
            model_name='organizationgovernanceelector',
            constraint=models.UniqueConstraint(fields=('proposal', 'user'), name='organizations_unique_governance_elector_user'),
        ),
        migrations.AddConstraint(
            model_name='organizationgovernanceelector',
            constraint=models.CheckConstraint(check=models.Q(('vote_weight__gt', 0)), name='organizations_governance_vote_weight_positive'),
        ),
    ]
