# Generated by Django 4.2.4 on 2026-08-30 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0003_organizationgovernanceelector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationauditlog',
            name='action',
            field=models.CharField(choices=[('organization_created', 'Organization Created'), ('organization_updated', 'Organization Updated'), ('followed', 'Organization Followed'), ('unfollowed', 'Organization Unfollowed'), ('membership_requested', 'Membership Requested'), ('membership_invited', 'Membership Invited'), ('membership_accepted', 'Membership Accepted'), ('membership_rejected', 'Membership Rejected'), ('membership_withdrawn', 'Membership Withdrawn'), ('membership_canceled', 'Membership Invitation Canceled'), ('member_left', 'Member Left'), ('member_removed', 'Member Removed'), ('role_assigned', 'Role Assigned'), ('role_revoked', 'Role Revoked'), ('module_enabled', 'Organization Module Enabled'), ('module_disabled', 'Organization Module Disabled'), ('module_suspended', 'Organization Module Suspended'), ('module_restored', 'Organization Module Restored'), ('module_updated', 'Organization Module Updated'), ('verification_case_created', 'Verification Case Created'), ('verification_submitted', 'Verification Submitted'), ('verification_needs_information', 'Verification Needs Information'), ('verification_approved', 'Verification Approved'), ('verification_rejected', 'Verification Rejected'), ('verification_withdrawn', 'Verification Withdrawn'), ('verification_revoked', 'Verification Revoked'), ('relationship_requested', 'Relationship Requested'), ('relationship_consent_approved', 'Relationship Consent Approved'), ('relationship_consent_rejected', 'Relationship Consent Rejected'), ('relationship_activated', 'Relationship Activated'), ('relationship_ended', 'Relationship Ended'), ('governance_proposal_created', 'Governance Proposal Created'), ('governance_proposal_opened', 'Governance Proposal Opened'), ('governance_vote_cast', 'Governance Vote Cast'), ('governance_decided', 'Governance Decided'), ('governance_executed', 'Governance Executed'), ('governance_execution_failed', 'Governance Execution Failed')], db_index=True, max_length=60),
        ),
        migrations.CreateModel(
            name='OrganizationModuleDefinition',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('entitlement_key', models.CharField(db_index=True, max_length=140, unique=True)),
                ('requires_verification', models.BooleanField(default=True)),
                ('requires_entitlement', models.BooleanField(default=True)),
                ('fallback_access_mode', models.CharField(choices=[('read_only', 'Read Only'), ('locked', 'Locked')], default='read_only', max_length=20)),
                ('schema_version', models.PositiveSmallIntegerField(default=1)),
                ('sort_order', models.PositiveSmallIntegerField(db_index=True, default=100)),
                ('is_public_catalog', models.BooleanField(db_index=True, default=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organization Module Definition',
                'verbose_name_plural': 'Organization Module Definitions',
                'ordering': ('sort_order', 'name', 'id'),
                'indexes': [models.Index(fields=['is_active', 'is_public_catalog', 'sort_order'], name='organizatio_is_acti_8216aa_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrganizationModuleActivation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=160, null=True)),
                ('summary', models.CharField(blank=True, max_length=1000, null=True)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('members_only', 'Members Only'), ('private', 'Private')], db_index=True, default='public', max_length=20)),
                ('status', models.CharField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled'), ('suspended', 'Suspended by TownLIT')], db_index=True, default='enabled', max_length=20)),
                ('activated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('disabled_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('suspended_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_organization_modules', to=settings.AUTH_USER_MODEL)),
                ('last_changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changed_organization_modules', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activations', to='organizations.organizationmoduledefinition')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_activations', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Organization Module Activation',
                'verbose_name_plural': 'Organization Module Activations',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='organizationauditlog',
            name='module_activation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='organizations.organizationmoduleactivation'),
        ),
        migrations.AddIndex(
            model_name='organizationmoduleactivation',
            index=models.Index(fields=['organization', 'status', 'visibility'], name='organizatio_organiz_972840_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationmoduleactivation',
            index=models.Index(fields=['module', 'status'], name='organizatio_module__6689d1_idx'),
        ),
        migrations.AddConstraint(
            model_name='organizationmoduleactivation',
            constraint=models.UniqueConstraint(fields=('organization', 'module'), name='organizations_unique_module_activation'),
        ),
        migrations.AddConstraint(
            model_name='organizationmoduleactivation',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('disabled_at__isnull', True), ('status', 'enabled'), ('suspended_at__isnull', True)), models.Q(('disabled_at__isnull', False), ('status', 'disabled'), ('suspended_at__isnull', True)), models.Q(('disabled_at__isnull', True), ('status', 'suspended'), ('suspended_at__isnull', False)), _connector='OR'), name='organizations_module_activation_state_consistent'),
        ),
    ]
