# Generated by Django 4.2.4 on 2026-08-31 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0103_alter_customuser_image_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0004_alter_organizationauditlog_action_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchCampus',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=180)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('public_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('public_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('website_url', models.URLField(blank=True, max_length=500, null=True)),
                ('timezone_override', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], db_index=True, default='active', max_length=20)),
                ('is_primary', models.BooleanField(db_index=True, default=False)),
                ('primary_slot', models.PositiveSmallIntegerField(blank=True, editable=False, null=True)),
                ('sort_order', models.PositiveSmallIntegerField(db_index=True, default=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='church_campuses', to='accounts.address')),
            ],
            options={
                'verbose_name': 'Church Campus',
                'verbose_name_plural': 'Church Campuses',
                'ordering': ('sort_order', 'name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ChurchMinistry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=180)),
                ('description', models.CharField(blank=True, max_length=1500, null=True)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('members_only', 'Members Only'), ('private', 'Private')], db_index=True, default='public', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], db_index=True, default='active', max_length=20)),
                ('is_accepting_participants', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(db_index=True, default=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ministries', to='organizations.churchcampus')),
            ],
            options={
                'verbose_name': 'Church Ministry',
                'verbose_name_plural': 'Church Ministries',
                'ordering': ('sort_order', 'name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ChurchWorkspace',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('timezone_override', models.CharField(blank=True, max_length=64, null=True)),
                ('membership_directory_enabled', models.BooleanField(default=False)),
                ('attendance_tracking_enabled', models.BooleanField(default=True)),
                ('default_gathering_duration_minutes', models.PositiveSmallIntegerField(default=90)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='church_workspace', to='organizations.organizationmoduleactivation')),
            ],
            options={
                'verbose_name': 'Church Workspace',
                'verbose_name_plural': 'Church Workspaces',
            },
        ),
        migrations.CreateModel(
            name='ChurchMinistryMembership',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('participation_role', models.CharField(choices=[('participant', 'Participant'), ('volunteer', 'Volunteer'), ('leader', 'Leader')], db_index=True, default='participant', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('ended', 'Ended')], db_index=True, default='active', max_length=20)),
                ('active_slot', models.PositiveSmallIntegerField(blank=True, editable=False, null=True)),
                ('joined_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_publicly_listed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='church_ministry_memberships', to='organizations.organizationmembership')),
                ('ministry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='organizations.churchministry')),
            ],
            options={
                'verbose_name': 'Church Ministry Membership',
                'verbose_name_plural': 'Church Ministry Memberships',
                'ordering': ('-joined_at', 'id'),
            },
        ),
        migrations.AddField(
            model_name='churchministry',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ministries', to='organizations.churchworkspace'),
        ),
        migrations.CreateModel(
            name='ChurchLeadershipAssignment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('position_type', models.CharField(choices=[('senior_pastor', 'Senior Pastor'), ('associate_pastor', 'Associate Pastor'), ('pastor', 'Pastor'), ('elder', 'Elder'), ('deacon', 'Deacon'), ('ministry_leader', 'Ministry Leader'), ('worship_leader', 'Worship Leader'), ('church_administrator', 'Church Administrator'), ('other', 'Other')], db_index=True, max_length=30)),
                ('custom_title', models.CharField(blank=True, max_length=160, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('ended', 'Ended')], db_index=True, default='active', max_length=20)),
                ('context_key', models.CharField(db_index=True, editable=False, max_length=120)),
                ('active_slot', models.PositiveSmallIntegerField(blank=True, editable=False, null=True)),
                ('publicly_listed', models.BooleanField(db_index=True, default=False)),
                ('sort_order', models.PositiveSmallIntegerField(db_index=True, default=100)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leadership_assignments', to='organizations.churchcampus')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='church_leadership_assignments', to='organizations.organizationmembership')),
                ('ministry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leadership_assignments', to='organizations.churchministry')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leadership_assignments', to='organizations.churchworkspace')),
            ],
            options={
                'verbose_name': 'Church Leadership Assignment',
                'verbose_name_plural': 'Church Leadership Assignments',
                'ordering': ('sort_order', 'position_type', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ChurchGatheringSeries',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=180)),
                ('gathering_type', models.CharField(choices=[('sunday_worship', 'Sunday Worship'), ('worship_service', 'Worship Service'), ('communion', 'Communion Service'), ('prayer_meeting', 'Prayer Meeting'), ('fellowship', 'Fellowship Gathering'), ('baptism_service', 'Baptism Service'), ('membership_meeting', 'Membership Meeting'), ('special_service', 'Special Service'), ('other', 'Other')], db_index=True, max_length=30)),
                ('description', models.CharField(blank=True, max_length=1500, null=True)),
                ('location_label', models.CharField(blank=True, max_length=250, null=True)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('members_only', 'Members Only'), ('private', 'Private')], db_index=True, default='public', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], db_index=True, default='active', max_length=20)),
                ('recurrence_frequency', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Every Two Weeks'), ('monthly', 'Monthly')], db_index=True, max_length=20)),
                ('weekday', models.PositiveSmallIntegerField()),
                ('monthly_week', models.CharField(blank=True, choices=[('first', 'First'), ('second', 'Second'), ('third', 'Third'), ('fourth', 'Fourth'), ('last', 'Last')], max_length=10, null=True)),
                ('local_start_time', models.TimeField()),
                ('duration_minutes', models.PositiveSmallIntegerField(default=90)),
                ('effective_start_date', models.DateField(db_index=True)),
                ('effective_end_date', models.DateField(blank=True, db_index=True, null=True)),
                ('auto_create_attendance', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gathering_series', to='organizations.churchcampus')),
                ('ministry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gathering_series', to='organizations.churchministry')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gathering_series', to='organizations.churchworkspace')),
            ],
            options={
                'verbose_name': 'Church Gathering Series',
                'verbose_name_plural': 'Church Gathering Series',
                'ordering': ('name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ChurchGatheringOccurrence',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=180)),
                ('gathering_type', models.CharField(choices=[('sunday_worship', 'Sunday Worship'), ('worship_service', 'Worship Service'), ('communion', 'Communion Service'), ('prayer_meeting', 'Prayer Meeting'), ('fellowship', 'Fellowship Gathering'), ('baptism_service', 'Baptism Service'), ('membership_meeting', 'Membership Meeting'), ('special_service', 'Special Service'), ('other', 'Other')], db_index=True, max_length=30)),
                ('location_label', models.CharField(blank=True, max_length=250, null=True)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('members_only', 'Members Only'), ('private', 'Private')], db_index=True, default='public', max_length=20)),
                ('starts_at', models.DateTimeField(db_index=True)),
                ('ends_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('canceled', 'Canceled'), ('completed', 'Completed')], db_index=True, default='scheduled', max_length=20)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('series', 'Recurring Series')], db_index=True, default='manual', max_length=20)),
                ('canceled_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gathering_occurrences', to='organizations.churchcampus')),
                ('canceled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canceled_church_gatherings', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_church_gatherings', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_church_gatherings', to=settings.AUTH_USER_MODEL)),
                ('ministry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gathering_occurrences', to='organizations.churchministry')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occurrences', to='organizations.churchgatheringseries')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gathering_occurrences', to='organizations.churchworkspace')),
            ],
            options={
                'verbose_name': 'Church Gathering Occurrence',
                'verbose_name_plural': 'Church Gathering Occurrences',
                'ordering': ('starts_at', 'id'),
            },
        ),
        migrations.AddField(
            model_name='churchcampus',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campuses', to='organizations.churchworkspace'),
        ),
        migrations.CreateModel(
            name='ChurchAuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event', models.CharField(choices=[('workspace_initialized', 'Workspace Initialized'), ('workspace_updated', 'Workspace Updated'), ('campus_created', 'Campus Created'), ('campus_updated', 'Campus Updated'), ('campus_primary_changed', 'Primary Campus Changed'), ('campus_archived', 'Campus Archived'), ('ministry_created', 'Ministry Created'), ('ministry_updated', 'Ministry Updated'), ('ministry_participant_added', 'Ministry Participant Added'), ('ministry_participant_removed', 'Ministry Participant Removed'), ('leadership_assigned', 'Leadership Assigned'), ('leadership_ended', 'Leadership Ended'), ('gathering_series_created', 'Gathering Series Created'), ('gathering_series_updated', 'Gathering Series Updated'), ('gathering_created', 'Gathering Created'), ('gathering_canceled', 'Gathering Canceled'), ('gathering_completed', 'Gathering Completed'), ('attendance_opened', 'Attendance Opened'), ('attendance_checked_in', 'Attendance Checked In'), ('attendance_checked_out', 'Attendance Checked Out'), ('attendance_guest_counts_updated', 'Guest Counts Updated'), ('attendance_closed', 'Attendance Closed')], db_index=True, max_length=60)),
                ('entity_type', models.CharField(db_index=True, max_length=60)),
                ('entity_public_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='church_audit_actions', to=settings.AUTH_USER_MODEL)),
                ('membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='church_audit_logs', to='organizations.organizationmembership')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='organizations.churchworkspace')),
            ],
            options={
                'verbose_name': 'Church Audit Log',
                'verbose_name_plural': 'Church Audit Logs',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ChurchAttendanceSession',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], db_index=True, default='open', max_length=20)),
                ('opened_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('unregistered_adult_count', models.PositiveIntegerField(default=0)),
                ('unregistered_child_count', models.PositiveIntegerField(default=0)),
                ('anonymous_online_count', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_church_attendance_sessions', to=settings.AUTH_USER_MODEL)),
                ('occurrence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_session', to='organizations.churchgatheringoccurrence')),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_church_attendance_sessions', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='organizations.churchworkspace')),
            ],
            options={
                'verbose_name': 'Church Attendance Session',
                'verbose_name_plural': 'Church Attendance Sessions',
                'ordering': ('-opened_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ChurchAttendanceRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('presence', models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('serving', 'Serving'), ('online', 'Online')], db_index=True, default='present', max_length=20)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('self_check_in', 'Self Check-in'), ('kiosk', 'Kiosk'), ('imported', 'Imported')], db_index=True, default='manual', max_length=20)),
                ('checked_in_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('checked_out_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='church_attendance_records', to='organizations.organizationmembership')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_church_attendance', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='organizations.churchattendancesession')),
            ],
            options={
                'verbose_name': 'Church Attendance Record',
                'verbose_name_plural': 'Church Attendance Records',
                'ordering': ('checked_in_at', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='churchworkspace',
            constraint=models.CheckConstraint(check=models.Q(('default_gathering_duration_minutes__gte', 15), ('default_gathering_duration_minutes__lte', 720)), name='organizations_church_workspace_duration_range'),
        ),
        migrations.AddIndex(
            model_name='churchministrymembership',
            index=models.Index(fields=['ministry', 'status', 'participation_role'], name='organizatio_ministr_548b80_idx'),
        ),
        migrations.AddIndex(
            model_name='churchministrymembership',
            index=models.Index(fields=['membership', 'status'], name='organizatio_members_42af3b_idx'),
        ),
        migrations.AddConstraint(
            model_name='churchministrymembership',
            constraint=models.UniqueConstraint(fields=('ministry', 'membership', 'active_slot'), name='organizations_church_unique_active_ministry_member'),
        ),
        migrations.AddConstraint(
            model_name='churchministrymembership',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('ended_at__isnull', True), ('status', 'active')), models.Q(('ended_at__isnull', False), ('status', 'ended')), _connector='OR'), name='organizations_church_ministry_member_state_consistent'),
        ),
        migrations.AddIndex(
            model_name='churchministry',
            index=models.Index(fields=['workspace', 'status', 'visibility'], name='organizatio_workspa_165920_idx'),
        ),
        migrations.AddIndex(
            model_name='churchministry',
            index=models.Index(fields=['campus', 'status'], name='organizatio_campus__98d102_idx'),
        ),
        migrations.AddConstraint(
            model_name='churchministry',
            constraint=models.UniqueConstraint(fields=('workspace', 'slug'), name='organizations_church_unique_ministry_slug'),
        ),
        migrations.AddIndex(
            model_name='churchleadershipassignment',
            index=models.Index(fields=['workspace', 'status', 'position_type'], name='organizatio_workspa_d3ec0b_idx'),
        ),
        migrations.AddIndex(
            model_name='churchleadershipassignment',
            index=models.Index(fields=['membership', 'status'], name='organizatio_members_01a6d4_idx'),
        ),
        migrations.AddIndex(
            model_name='churchleadershipassignment',
            index=models.Index(fields=['campus', 'status'], name='organizatio_campus__7b2c5e_idx'),
        ),
        migrations.AddIndex(
            model_name='churchleadershipassignment',
            index=models.Index(fields=['ministry', 'status'], name='organizatio_ministr_3377e4_idx'),
        ),
        migrations.AddConstraint(
            model_name='churchleadershipassignment',
            constraint=models.UniqueConstraint(fields=('workspace', 'membership', 'position_type', 'context_key', 'active_slot'), name='organizations_church_unique_active_leadership'),
        ),
        migrations.AddConstraint(
            model_name='churchleadershipassignment',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('ended_at__isnull', True), ('status', 'active')), models.Q(('ended_at__isnull', False), ('status', 'ended')), _connector='OR'), name='organizations_church_leadership_state_consistent'),
        ),
        migrations.AddIndex(
            model_name='churchgatheringseries',
            index=models.Index(fields=['workspace', 'status', 'gathering_type'], name='organizatio_workspa_d95c94_idx'),
        ),
        migrations.AddIndex(
            model_name='churchgatheringseries',
            index=models.Index(fields=['campus', 'status'], name='organizatio_campus__1af171_idx'),
        ),
        migrations.AddIndex(
            model_name='churchgatheringseries',
            index=models.Index(fields=['ministry', 'status'], name='organizatio_ministr_68b0a0_idx'),
        ),
        migrations.AddConstraint(
            model_name='churchgatheringseries',
            constraint=models.CheckConstraint(check=models.Q(('weekday__gte', 0), ('weekday__lte', 6)), name='organizations_church_gathering_weekday_range'),
        ),
        migrations.AddConstraint(
            model_name='churchgatheringseries',
            constraint=models.CheckConstraint(check=models.Q(('duration_minutes__gte', 15), ('duration_minutes__lte', 720)), name='organizations_church_gathering_duration_range'),
        ),
        migrations.AddConstraint(
            model_name='churchgatheringseries',
            constraint=models.CheckConstraint(check=models.Q(('effective_end_date__isnull', True), ('effective_end_date__gte', models.F('effective_start_date')), _connector='OR'), name='organizations_church_gathering_series_date_window'),
        ),
        migrations.AddIndex(
            model_name='churchgatheringoccurrence',
            index=models.Index(fields=['workspace', 'status', 'starts_at'], name='organizatio_workspa_2ccc7e_idx'),
        ),
        migrations.AddIndex(
            model_name='churchgatheringoccurrence',
            index=models.Index(fields=['campus', 'starts_at'], name='organizatio_campus__f1abe7_idx'),
        ),
        migrations.AddIndex(
            model_name='churchgatheringoccurrence',
            index=models.Index(fields=['ministry', 'starts_at'], name='organizatio_ministr_cc875e_idx'),
        ),
        migrations.AddConstraint(
            model_name='churchgatheringoccurrence',
            constraint=models.UniqueConstraint(fields=('series', 'starts_at'), name='organizations_church_unique_series_occurrence'),
        ),
        migrations.AddConstraint(
            model_name='churchgatheringoccurrence',
            constraint=models.CheckConstraint(check=models.Q(('ends_at__gt', models.F('starts_at'))), name='organizations_church_occurrence_time_window'),
        ),
        migrations.AddConstraint(
            model_name='churchgatheringoccurrence',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('canceled_at__isnull', True), ('completed_at__isnull', True), ('status', 'scheduled')), models.Q(('canceled_at__isnull', False), ('completed_at__isnull', True), ('status', 'canceled')), models.Q(('canceled_at__isnull', True), ('completed_at__isnull', False), ('status', 'completed')), _connector='OR'), name='organizations_church_occurrence_state_consistent'),
        ),
        migrations.AddIndex(
            model_name='churchcampus',
            index=models.Index(fields=['workspace', 'status', 'sort_order'], name='organizatio_workspa_b59105_idx'),
        ),
        migrations.AddConstraint(
            model_name='churchcampus',
            constraint=models.UniqueConstraint(fields=('workspace', 'slug'), name='organizations_church_unique_campus_slug'),
        ),
        migrations.AddConstraint(
            model_name='churchcampus',
            constraint=models.UniqueConstraint(fields=('workspace', 'primary_slot'), name='organizations_church_unique_primary_campus'),
        ),
        migrations.AddIndex(
            model_name='churchauditlog',
            index=models.Index(fields=['workspace', 'event', 'created_at'], name='organizatio_workspa_2c8cd8_idx'),
        ),
        migrations.AddIndex(
            model_name='churchauditlog',
            index=models.Index(fields=['workspace', 'entity_type', 'entity_public_id'], name='organizatio_workspa_f91f31_idx'),
        ),
        migrations.AddIndex(
            model_name='churchattendancesession',
            index=models.Index(fields=['workspace', 'status', 'opened_at'], name='organizatio_workspa_b0f9d2_idx'),
        ),
        migrations.AddConstraint(
            model_name='churchattendancesession',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('closed_at__isnull', True), ('status', 'open')), models.Q(('closed_at__isnull', False), ('status', 'closed')), _connector='OR'), name='organizations_church_attendance_session_state_consistent'),
        ),
        migrations.AddIndex(
            model_name='churchattendancerecord',
            index=models.Index(fields=['session', 'presence'], name='organizatio_session_f8e04d_idx'),
        ),
        migrations.AddIndex(
            model_name='churchattendancerecord',
            index=models.Index(fields=['membership', 'checked_in_at'], name='organizatio_members_8b588b_idx'),
        ),
        migrations.AddConstraint(
            model_name='churchattendancerecord',
            constraint=models.UniqueConstraint(fields=('session', 'membership'), name='organizations_church_unique_attendance_record'),
        ),
        migrations.AddConstraint(
            model_name='churchattendancerecord',
            constraint=models.CheckConstraint(check=models.Q(('checked_out_at__isnull', True), ('checked_out_at__gt', models.F('checked_in_at')), _connector='OR'), name='organizations_church_attendance_checkout_window'),
        ),
    ]
