# Generated by Django 4.2.4 on 2026-08-31 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0005_churchcampus_churchministry_churchworkspace_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchResource',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('resource_type', models.CharField(choices=[('room', 'Room'), ('equipment', 'Equipment'), ('vehicle', 'Vehicle'), ('other', 'Other')], db_index=True, max_length=20)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=180)),
                ('description', models.CharField(blank=True, max_length=1500, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], db_index=True, default='active', max_length=20)),
                ('is_reservable', models.BooleanField(db_index=True, default=True)),
                ('quantity_available', models.PositiveIntegerField(default=1)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('sort_order', models.PositiveSmallIntegerField(db_index=True, default=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='organizations.churchcampus')),
                ('ministry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='organizations.churchministry')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='organizations.churchworkspace')),
            ],
            options={
                'verbose_name': 'Church Resource',
                'verbose_name_plural': 'Church Resources',
                'ordering': ('sort_order', 'name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ChurchServicePlan',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('theme', models.CharField(blank=True, max_length=180, null=True)),
                ('internal_notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('completed', 'Completed'), ('canceled', 'Canceled')], db_index=True, default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('canceled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='church_service_plans_canceled', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='church_service_plans_completed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='church_service_plans_created', to=settings.AUTH_USER_MODEL)),
                ('occurrence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_plan', to='organizations.churchgatheringoccurrence')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='church_service_plans_published', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_plans', to='organizations.churchworkspace')),
            ],
            options={
                'verbose_name': 'Church Service Plan',
                'verbose_name_plural': 'Church Service Plans',
                'ordering': ('-created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ChurchServingTeam',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=180)),
                ('description', models.CharField(blank=True, max_length=1500, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], db_index=True, default='active', max_length=20)),
                ('sort_order', models.PositiveSmallIntegerField(db_index=True, default=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serving_teams', to='organizations.churchcampus')),
                ('ministry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serving_teams', to='organizations.churchministry')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serving_teams', to='organizations.churchworkspace')),
            ],
            options={
                'verbose_name': 'Church Serving Team',
                'verbose_name_plural': 'Church Serving Teams',
                'ordering': ('sort_order', 'name', 'id'),
            },
        ),
        migrations.AlterField(
            model_name='churchauditlog',
            name='event',
            field=models.CharField(choices=[('workspace_initialized', 'Workspace Initialized'), ('workspace_updated', 'Workspace Updated'), ('campus_created', 'Campus Created'), ('campus_updated', 'Campus Updated'), ('campus_primary_changed', 'Primary Campus Changed'), ('campus_archived', 'Campus Archived'), ('ministry_created', 'Ministry Created'), ('ministry_updated', 'Ministry Updated'), ('ministry_participant_added', 'Ministry Participant Added'), ('ministry_participant_removed', 'Ministry Participant Removed'), ('leadership_assigned', 'Leadership Assigned'), ('leadership_ended', 'Leadership Ended'), ('gathering_series_created', 'Gathering Series Created'), ('gathering_series_updated', 'Gathering Series Updated'), ('gathering_created', 'Gathering Created'), ('gathering_canceled', 'Gathering Canceled'), ('gathering_completed', 'Gathering Completed'), ('attendance_opened', 'Attendance Opened'), ('attendance_checked_in', 'Attendance Checked In'), ('attendance_checked_out', 'Attendance Checked Out'), ('attendance_guest_counts_updated', 'Guest Counts Updated'), ('attendance_closed', 'Attendance Closed'), ('serving_team_created', 'Serving Team Created'), ('serving_team_updated', 'Serving Team Updated'), ('serving_team_member_added', 'Serving Team Member Added'), ('serving_team_member_removed', 'Serving Team Member Removed'), ('service_plan_created', 'Service Plan Created'), ('service_plan_updated', 'Service Plan Updated'), ('service_plan_published', 'Service Plan Published'), ('service_plan_completed', 'Service Plan Completed'), ('service_plan_canceled', 'Service Plan Canceled'), ('service_plan_item_added', 'Service Plan Item Added'), ('service_plan_item_updated', 'Service Plan Item Updated'), ('service_plan_item_removed', 'Service Plan Item Removed'), ('serving_assignment_created', 'Serving Assignment Created'), ('serving_assignment_responded', 'Serving Assignment Responded'), ('serving_assignment_checked_in', 'Serving Assignment Checked In'), ('serving_assignment_checked_out', 'Serving Assignment Checked Out'), ('serving_assignment_canceled', 'Serving Assignment Canceled'), ('serving_assignment_completed', 'Serving Assignment Completed'), ('resource_created', 'Resource Created'), ('resource_updated', 'Resource Updated'), ('resource_reserved', 'Resource Reserved'), ('resource_reservation_canceled', 'Resource Reservation Canceled'), ('resource_reservation_completed', 'Resource Reservation Completed')], db_index=True, max_length=60),
        ),
        migrations.CreateModel(
            name='ChurchServingAssignment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('role_label', models.CharField(max_length=120)),
                ('context_key', models.CharField(db_index=True, editable=False, max_length=240)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('confirmed', 'Confirmed'), ('declined', 'Declined'), ('canceled', 'Canceled'), ('completed', 'Completed')], db_index=True, default='invited', max_length=20)),
                ('invited_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('responded_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('checked_in_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('checked_out_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=1000, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('canceled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='church_serving_assignments_canceled', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='church_serving_assignments_completed', to=settings.AUTH_USER_MODEL)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='church_serving_assignments_invited', to=settings.AUTH_USER_MODEL)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='church_serving_assignments', to='organizations.organizationmembership')),
                ('service_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serving_assignments', to='organizations.churchserviceplan')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='organizations.churchservingteam')),
            ],
            options={
                'verbose_name': 'Church Serving Assignment',
                'verbose_name_plural': 'Church Serving Assignments',
                'ordering': ('service_plan', 'team', 'role_label', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ChurchServicePlanItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('item_type', models.CharField(choices=[('opening', 'Opening'), ('worship', 'Worship'), ('prayer', 'Prayer'), ('scripture', 'Scripture'), ('sermon', 'Sermon'), ('communion', 'Communion'), ('offering', 'Offering'), ('announcement', 'Announcement'), ('ministry_feature', 'Ministry Feature'), ('response', 'Response'), ('transition', 'Transition'), ('closing', 'Closing'), ('custom', 'Custom')], db_index=True, max_length=30)),
                ('title', models.CharField(max_length=180)),
                ('notes', models.CharField(blank=True, max_length=1500, null=True)),
                ('planned_duration_seconds', models.PositiveIntegerField(default=0)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=100)),
                ('is_optional', models.BooleanField(default=False)),
                ('is_internal_only', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ministry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_plan_items', to='organizations.churchministry')),
                ('service_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='organizations.churchserviceplan')),
                ('serving_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_plan_items', to='organizations.churchservingteam')),
            ],
            options={
                'verbose_name': 'Church Service Plan Item',
                'verbose_name_plural': 'Church Service Plan Items',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ChurchResourceReservation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('starts_at', models.DateTimeField(db_index=True)),
                ('ends_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('canceled', 'Canceled'), ('completed', 'Completed')], db_index=True, default='reserved', max_length=20)),
                ('canceled_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=1000, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('canceled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='church_resource_reservations_canceled', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='church_resource_reservations_completed', to=settings.AUTH_USER_MODEL)),
                ('occurrence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_reservations', to='organizations.churchgatheringoccurrence')),
                ('reserved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='church_resource_reservations_created', to=settings.AUTH_USER_MODEL)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='organizations.churchresource')),
            ],
            options={
                'verbose_name': 'Church Resource Reservation',
                'verbose_name_plural': 'Church Resource Reservations',
                'ordering': ('starts_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ChurchServingTeamMembership',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('role_title', models.CharField(blank=True, max_length=120, null=True)),
                ('is_team_lead', models.BooleanField(db_index=True, default=False)),
                ('is_publicly_listed', models.BooleanField(db_index=True, default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('ended', 'Ended')], db_index=True, default='active', max_length=20)),
                ('active_slot', models.PositiveSmallIntegerField(blank=True, editable=False, null=True)),
                ('joined_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='church_serving_team_memberships', to='organizations.organizationmembership')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='organizations.churchservingteam')),
            ],
            options={
                'verbose_name': 'Church Serving Team Membership',
                'verbose_name_plural': 'Church Serving Team Memberships',
                'ordering': ('-is_team_lead', 'joined_at', 'id'),
                'indexes': [models.Index(fields=['team', 'status', 'is_team_lead'], name='organizatio_team_id_8523ca_idx'), models.Index(fields=['membership', 'status'], name='organizatio_members_896081_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='churchservingteammembership',
            constraint=models.UniqueConstraint(fields=('team', 'membership', 'active_slot'), name='organizations_church_unique_active_serving_team_member'),
        ),
        migrations.AddConstraint(
            model_name='churchservingteammembership',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('ended_at__isnull', True), ('status', 'active')), models.Q(('ended_at__isnull', False), ('status', 'ended')), _connector='OR'), name='organizations_church_serving_team_member_state_consistent'),
        ),
        migrations.AddIndex(
            model_name='churchservingteam',
            index=models.Index(fields=['workspace', 'status', 'sort_order'], name='organizatio_workspa_8db5e4_idx'),
        ),
        migrations.AddIndex(
            model_name='churchservingteam',
            index=models.Index(fields=['campus', 'status'], name='organizatio_campus__b81c47_idx'),
        ),
        migrations.AddIndex(
            model_name='churchservingteam',
            index=models.Index(fields=['ministry', 'status'], name='organizatio_ministr_1c3f2d_idx'),
        ),
        migrations.AddConstraint(
            model_name='churchservingteam',
            constraint=models.UniqueConstraint(fields=('workspace', 'slug'), name='organizations_church_unique_serving_team_slug'),
        ),
        migrations.AddIndex(
            model_name='churchservingassignment',
            index=models.Index(fields=['service_plan', 'status'], name='organizatio_service_97a143_idx'),
        ),
        migrations.AddIndex(
            model_name='churchservingassignment',
            index=models.Index(fields=['membership', 'status', 'invited_at'], name='organizatio_members_5cf8dc_idx'),
        ),
        migrations.AddIndex(
            model_name='churchservingassignment',
            index=models.Index(fields=['team', 'status'], name='organizatio_team_id_893b51_idx'),
        ),
        migrations.AddConstraint(
            model_name='churchservingassignment',
            constraint=models.UniqueConstraint(fields=('service_plan', 'membership', 'context_key'), name='organizations_church_unique_serving_assignment'),
        ),
        migrations.AddConstraint(
            model_name='churchservingassignment',
            constraint=models.CheckConstraint(check=models.Q(('checked_out_at__isnull', True), models.Q(('checked_in_at__isnull', False), ('checked_out_at__gt', models.F('checked_in_at'))), _connector='OR'), name='organizations_church_serving_checkout_window'),
        ),
        migrations.AddConstraint(
            model_name='churchservingassignment',
            constraint=models.CheckConstraint(check=models.Q(('checked_in_at__isnull', True), ('status__in', ['confirmed', 'completed']), _connector='OR'), name='organizations_church_serving_checkin_status_consistent'),
        ),
        migrations.AddConstraint(
            model_name='churchservingassignment',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('canceled_at__isnull', True), ('completed_at__isnull', True), ('responded_at__isnull', True), ('status', 'invited')), models.Q(('canceled_at__isnull', True), ('completed_at__isnull', True), ('responded_at__isnull', False), ('status', 'confirmed')), models.Q(('canceled_at__isnull', True), ('completed_at__isnull', True), ('responded_at__isnull', False), ('status', 'declined')), models.Q(('canceled_at__isnull', False), ('completed_at__isnull', True), ('status', 'canceled')), models.Q(('canceled_at__isnull', True), ('checked_in_at__isnull', False), ('completed_at__isnull', False), ('status', 'completed')), _connector='OR'), name='organizations_church_serving_assignment_state_consistent'),
        ),
        migrations.AddIndex(
            model_name='churchserviceplanitem',
            index=models.Index(fields=['service_plan', 'sort_order'], name='organizatio_service_40cefb_idx'),
        ),
        migrations.AddIndex(
            model_name='churchserviceplanitem',
            index=models.Index(fields=['service_plan', 'item_type'], name='organizatio_service_44ece8_idx'),
        ),
        migrations.AddConstraint(
            model_name='churchserviceplanitem',
            constraint=models.CheckConstraint(check=models.Q(('planned_duration_seconds__lte', 14400)), name='organizations_church_service_item_duration_range'),
        ),
        migrations.AddIndex(
            model_name='churchserviceplan',
            index=models.Index(fields=['workspace', 'status', 'created_at'], name='organizatio_workspa_e00062_idx'),
        ),
        migrations.AddConstraint(
            model_name='churchserviceplan',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('canceled_at__isnull', True), ('completed_at__isnull', True), ('published_at__isnull', True), ('status', 'draft')), models.Q(('canceled_at__isnull', True), ('completed_at__isnull', True), ('published_at__isnull', False), ('status', 'published')), models.Q(('canceled_at__isnull', True), ('completed_at__isnull', False), ('published_at__isnull', False), ('status', 'completed')), models.Q(('canceled_at__isnull', False), ('completed_at__isnull', True), ('status', 'canceled')), _connector='OR'), name='organizations_church_service_plan_state_consistent'),
        ),
        migrations.AddIndex(
            model_name='churchresourcereservation',
            index=models.Index(fields=['resource', 'status', 'starts_at'], name='organizatio_resourc_7130db_idx'),
        ),
        migrations.AddIndex(
            model_name='churchresourcereservation',
            index=models.Index(fields=['occurrence', 'status'], name='organizatio_occurre_95330f_idx'),
        ),
        migrations.AddConstraint(
            model_name='churchresourcereservation',
            constraint=models.UniqueConstraint(fields=('resource', 'occurrence'), name='organizations_church_unique_resource_occurrence'),
        ),
        migrations.AddConstraint(
            model_name='churchresourcereservation',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gte', 1)), name='organizations_church_resource_reservation_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='churchresourcereservation',
            constraint=models.CheckConstraint(check=models.Q(('ends_at__gt', models.F('starts_at'))), name='organizations_church_resource_reservation_time_window'),
        ),
        migrations.AddConstraint(
            model_name='churchresourcereservation',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('canceled_at__isnull', True), ('completed_at__isnull', True), ('status', 'reserved')), models.Q(('canceled_at__isnull', False), ('completed_at__isnull', True), ('status', 'canceled')), models.Q(('canceled_at__isnull', True), ('completed_at__isnull', False), ('status', 'completed')), _connector='OR'), name='organizations_church_resource_reservation_state_consistent'),
        ),
        migrations.AddIndex(
            model_name='churchresource',
            index=models.Index(fields=['workspace', 'status', 'resource_type'], name='organizatio_workspa_d81b45_idx'),
        ),
        migrations.AddIndex(
            model_name='churchresource',
            index=models.Index(fields=['campus', 'status'], name='organizatio_campus__b3e4c2_idx'),
        ),
        migrations.AddIndex(
            model_name='churchresource',
            index=models.Index(fields=['ministry', 'status'], name='organizatio_ministr_e6f501_idx'),
        ),
        migrations.AddConstraint(
            model_name='churchresource',
            constraint=models.UniqueConstraint(fields=('workspace', 'slug'), name='organizations_church_unique_resource_slug'),
        ),
        migrations.AddConstraint(
            model_name='churchresource',
            constraint=models.CheckConstraint(check=models.Q(('quantity_available__gte', 1)), name='organizations_church_resource_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='churchresource',
            constraint=models.CheckConstraint(check=models.Q(('capacity__isnull', True), ('capacity__gte', 1), _connector='OR'), name='organizations_church_resource_capacity_positive'),
        ),
    ]
