# Generated by Django 4.2.4 on 2026-08-31 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0079_alter_guestuser_register_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0006_churchresource_churchserviceplan_churchservingteam_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchCongregant',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('display_name_snapshot', models.CharField(max_length=160)),
                ('preferred_name', models.CharField(blank=True, default='', max_length=80)),
                ('status', models.CharField(choices=[('newcomer', 'Newcomer'), ('attendee', 'Attendee'), ('regular', 'Regular Attendee'), ('inactive', 'Inactive')], db_index=True, default='attendee', max_length=20)),
                ('source', models.CharField(choices=[('staff_created', 'Staff Created'), ('self_registered', 'Self Registered'), ('attendance', 'Attendance'), ('imported', 'Imported')], db_index=True, default='staff_created', max_length=24)),
                ('directory_visibility', models.CharField(choices=[('staff_only', 'Authorized Church Staff Only'), ('organization_members', 'Organization Members')], db_index=True, default='staff_only', max_length=30)),
                ('directory_consent_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('first_seen_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='congregants', to='organizations.churchcampus')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_church_congregants', to=settings.AUTH_USER_MODEL)),
                ('guest_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='church_congregant_records', to='profiles.guestuser')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='church_congregant_records', to='profiles.member')),
                ('official_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='church_congregant_records', to='organizations.organizationmembership')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_church_congregants', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='congregants', to='organizations.churchworkspace')),
            ],
            options={
                'verbose_name': 'Church Congregant',
                'verbose_name_plural': 'Church Congregants',
                'ordering': ('display_name_snapshot', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ChurchHousehold',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], db_index=True, default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='church_households', to='organizations.churchcampus')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_church_households', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='households', to='organizations.churchworkspace')),
            ],
            options={
                'verbose_name': 'Church Household',
                'verbose_name_plural': 'Church Households',
                'ordering': ('name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ChurchPastoralCareCase',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('category', models.CharField(choices=[('general', 'General Pastoral Care'), ('newcomer_follow_up', 'Newcomer Follow-up'), ('spiritual_care', 'Spiritual Care'), ('bereavement', 'Bereavement'), ('marriage_family', 'Marriage / Family'), ('illness_support', 'Illness Support'), ('crisis_support', 'Crisis Support'), ('other', 'Other')], db_index=True, default='general', max_length=32)),
                ('sensitivity', models.CharField(choices=[('standard', 'Standard'), ('restricted', 'Restricted'), ('highly_confidential', 'Highly Confidential')], db_index=True, default='standard', max_length=32)),
                ('status', models.CharField(choices=[('open', 'Open'), ('on_hold', 'On Hold'), ('closed', 'Closed')], db_index=True, default='open', max_length=20)),
                ('title', models.CharField(max_length=180)),
                ('summary_encrypted', models.TextField(blank=True, default='')),
                ('opened_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('closure_summary_encrypted', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_by_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_church_pastoral_care_cases', to='organizations.organizationmembership')),
                ('congregant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pastoral_care_cases', to='organizations.churchcongregant')),
                ('opened_by_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_church_pastoral_care_cases', to='organizations.organizationmembership')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pastoral_care_cases', to='organizations.churchworkspace')),
            ],
            options={
                'verbose_name': 'Church Pastoral Care Case',
                'verbose_name_plural': 'Church Pastoral Care Cases',
                'ordering': ('-opened_at', '-id'),
            },
        ),
        migrations.AlterField(
            model_name='churchauditlog',
            name='event',
            field=models.CharField(choices=[('workspace_initialized', 'Workspace Initialized'), ('workspace_updated', 'Workspace Updated'), ('campus_created', 'Campus Created'), ('campus_updated', 'Campus Updated'), ('campus_primary_changed', 'Primary Campus Changed'), ('campus_archived', 'Campus Archived'), ('ministry_created', 'Ministry Created'), ('ministry_updated', 'Ministry Updated'), ('ministry_participant_added', 'Ministry Participant Added'), ('ministry_participant_removed', 'Ministry Participant Removed'), ('leadership_assigned', 'Leadership Assigned'), ('leadership_ended', 'Leadership Ended'), ('gathering_series_created', 'Gathering Series Created'), ('gathering_series_updated', 'Gathering Series Updated'), ('gathering_created', 'Gathering Created'), ('gathering_canceled', 'Gathering Canceled'), ('gathering_completed', 'Gathering Completed'), ('attendance_opened', 'Attendance Opened'), ('attendance_checked_in', 'Attendance Checked In'), ('attendance_checked_out', 'Attendance Checked Out'), ('attendance_guest_counts_updated', 'Guest Counts Updated'), ('attendance_closed', 'Attendance Closed'), ('serving_team_created', 'Serving Team Created'), ('serving_team_updated', 'Serving Team Updated'), ('serving_team_member_added', 'Serving Team Member Added'), ('serving_team_member_removed', 'Serving Team Member Removed'), ('service_plan_created', 'Service Plan Created'), ('service_plan_updated', 'Service Plan Updated'), ('service_plan_published', 'Service Plan Published'), ('service_plan_completed', 'Service Plan Completed'), ('service_plan_canceled', 'Service Plan Canceled'), ('service_plan_item_added', 'Service Plan Item Added'), ('service_plan_item_updated', 'Service Plan Item Updated'), ('service_plan_item_removed', 'Service Plan Item Removed'), ('serving_assignment_created', 'Serving Assignment Created'), ('serving_assignment_responded', 'Serving Assignment Responded'), ('serving_assignment_checked_in', 'Serving Assignment Checked In'), ('serving_assignment_checked_out', 'Serving Assignment Checked Out'), ('serving_assignment_canceled', 'Serving Assignment Canceled'), ('serving_assignment_completed', 'Serving Assignment Completed'), ('resource_created', 'Resource Created'), ('resource_updated', 'Resource Updated'), ('resource_reserved', 'Resource Reserved'), ('resource_reservation_canceled', 'Resource Reservation Canceled'), ('resource_reservation_completed', 'Resource Reservation Completed'), ('congregant_registered', 'Congregant Registered'), ('congregant_updated', 'Congregant Updated'), ('congregant_directory_visibility_changed', 'Congregant Directory Visibility Changed'), ('household_created', 'Household Created'), ('household_updated', 'Household Updated'), ('household_member_added', 'Household Member Added'), ('household_member_removed', 'Household Member Removed'), ('pastoral_case_created', 'Pastoral Care Case Created'), ('pastoral_case_updated', 'Pastoral Care Case Updated'), ('pastoral_case_assigned', 'Pastoral Care Case Assigned'), ('pastoral_case_unassigned', 'Pastoral Care Case Unassigned'), ('pastoral_case_on_hold', 'Pastoral Care Case On Hold'), ('pastoral_case_reopened', 'Pastoral Care Case Reopened'), ('pastoral_case_closed', 'Pastoral Care Case Closed'), ('pastoral_note_added', 'Pastoral Care Note Added'), ('pastoral_contact_recorded', 'Pastoral Care Contact Recorded')], db_index=True, max_length=60),
        ),
        migrations.CreateModel(
            name='ChurchPastoralCareAssignment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('role', models.CharField(choices=[('primary', 'Primary Care Lead'), ('support', 'Support')], db_index=True, default='support', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('ended', 'Ended')], db_index=True, default='active', max_length=20)),
                ('active_slot', models.PositiveSmallIntegerField(blank=True, editable=False, null=True)),
                ('assigned_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='organizations.churchpastoralcarecase')),
                ('membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='church_pastoral_care_assignments', to='organizations.organizationmembership')),
            ],
            options={
                'verbose_name': 'Church Pastoral Care Assignment',
                'verbose_name_plural': 'Church Pastoral Care Assignments',
            },
        ),
        migrations.CreateModel(
            name='ChurchHouseholdMembership',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('relationship_type', models.CharField(choices=[('head', 'Household Head'), ('spouse', 'Spouse'), ('adult', 'Adult Household Member'), ('dependent', 'Dependent'), ('other', 'Other')], db_index=True, default='other', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('ended', 'Ended')], db_index=True, default='active', max_length=20)),
                ('active_slot', models.PositiveSmallIntegerField(blank=True, editable=False, null=True)),
                ('primary_slot', models.PositiveSmallIntegerField(blank=True, editable=False, null=True)),
                ('is_primary', models.BooleanField(db_index=True, default=False)),
                ('joined_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('congregant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='household_memberships', to='organizations.churchcongregant')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='organizations.churchhousehold')),
            ],
            options={
                'verbose_name': 'Church Household Membership',
                'verbose_name_plural': 'Church Household Memberships',
            },
        ),
        migrations.CreateModel(
            name='ChurchPastoralCareNote',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('note_type', models.CharField(choices=[('general', 'General'), ('prayer', 'Prayer'), ('follow_up', 'Follow-up'), ('visit', 'Visit'), ('internal', 'Internal')], db_index=True, default='general', max_length=20)),
                ('visibility', models.CharField(choices=[('case_team', 'Assigned Care Team'), ('pastoral_leaders', 'Pastoral Leaders')], db_index=True, default='case_team', max_length=24)),
                ('body_encrypted', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('amends_note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addenda', to='organizations.churchpastoralcarenote')),
                ('author_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='church_pastoral_care_notes', to='organizations.organizationmembership')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='organizations.churchpastoralcarecase')),
            ],
            options={
                'verbose_name': 'Church Pastoral Care Note',
                'verbose_name_plural': 'Church Pastoral Care Notes',
                'ordering': ('created_at', 'id'),
                'indexes': [models.Index(fields=['case', 'visibility', 'created_at'], name='organizatio_case_id_5a5632_idx'), models.Index(fields=['author_membership', 'created_at'], name='organizatio_author__41fb58_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChurchPastoralCareContact',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('contact_type', models.CharField(choices=[('in_person', 'In Person'), ('phone', 'Phone'), ('message', 'Message'), ('video', 'Video'), ('home_visit', 'Home Visit'), ('hospital_visit', 'Hospital Visit'), ('other', 'Other')], db_index=True, max_length=24)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('summary_encrypted', models.TextField(blank=True, default='')),
                ('follow_up_required', models.BooleanField(db_index=True, default=False)),
                ('follow_up_due_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='church_pastoral_care_contacts', to='organizations.organizationmembership')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='organizations.churchpastoralcarecase')),
            ],
            options={
                'verbose_name': 'Church Pastoral Care Contact',
                'verbose_name_plural': 'Church Pastoral Care Contacts',
                'ordering': ('-occurred_at', '-id'),
                'indexes': [models.Index(fields=['case', 'occurred_at', 'contact_type'], name='organizatio_case_id_851088_idx'), models.Index(fields=['follow_up_required', 'follow_up_due_at'], name='organizatio_follow__f73e65_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='churchpastoralcarecontact',
            constraint=models.CheckConstraint(check=models.Q(('follow_up_required', True), ('follow_up_due_at__isnull', True), _connector='OR'), name='organizations_church_pastoral_contact_followup_consistent'),
        ),
        migrations.AddIndex(
            model_name='churchpastoralcarecase',
            index=models.Index(fields=['workspace', 'status', 'sensitivity', 'opened_at'], name='organizatio_workspa_127eb3_idx'),
        ),
        migrations.AddIndex(
            model_name='churchpastoralcarecase',
            index=models.Index(fields=['congregant', 'status', 'opened_at'], name='organizatio_congreg_41ada8_idx'),
        ),
        migrations.AddIndex(
            model_name='churchpastoralcarecase',
            index=models.Index(fields=['workspace', 'category', 'status'], name='organizatio_workspa_a32df6_idx'),
        ),
        migrations.AddConstraint(
            model_name='churchpastoralcarecase',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('closed_at__isnull', False), ('status', 'closed')), models.Q(('closed_at__isnull', True), ('status__in', ['open', 'on_hold'])), _connector='OR'), name='organizations_church_pastoral_case_state_consistent'),
        ),
        migrations.AddIndex(
            model_name='churchpastoralcareassignment',
            index=models.Index(fields=['case', 'status', 'role'], name='organizatio_case_id_79aae0_idx'),
        ),
        migrations.AddIndex(
            model_name='churchpastoralcareassignment',
            index=models.Index(fields=['membership', 'status', 'assigned_at'], name='organizatio_members_c2e1c6_idx'),
        ),
        migrations.AddConstraint(
            model_name='churchpastoralcareassignment',
            constraint=models.UniqueConstraint(fields=('case', 'membership', 'active_slot'), name='organizations_church_unique_active_pastoral_assignment'),
        ),
        migrations.AddConstraint(
            model_name='churchpastoralcareassignment',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('ended_at__isnull', True), ('status', 'active')), models.Q(('ended_at__isnull', False), ('status', 'ended')), _connector='OR'), name='organizations_church_pastoral_assignment_state_consistent'),
        ),
        migrations.AddIndex(
            model_name='churchhouseholdmembership',
            index=models.Index(fields=['household', 'status', 'relationship_type'], name='organizatio_househo_641dea_idx'),
        ),
        migrations.AddIndex(
            model_name='churchhouseholdmembership',
            index=models.Index(fields=['congregant', 'status'], name='organizatio_congreg_6e9f69_idx'),
        ),
        migrations.AddConstraint(
            model_name='churchhouseholdmembership',
            constraint=models.UniqueConstraint(fields=('congregant', 'active_slot'), name='organizations_church_unique_active_household_membership'),
        ),
        migrations.AddConstraint(
            model_name='churchhouseholdmembership',
            constraint=models.UniqueConstraint(fields=('household', 'primary_slot'), name='organizations_church_unique_primary_household_member'),
        ),
        migrations.AddConstraint(
            model_name='churchhouseholdmembership',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('ended_at__isnull', True), ('status', 'active')), models.Q(('ended_at__isnull', False), ('status', 'ended')), _connector='OR'), name='organizations_church_household_member_state_consistent'),
        ),
        migrations.AddIndex(
            model_name='churchhousehold',
            index=models.Index(fields=['workspace', 'status', 'name'], name='organizatio_workspa_61037a_idx'),
        ),
        migrations.AddIndex(
            model_name='churchhousehold',
            index=models.Index(fields=['workspace', 'campus', 'status'], name='organizatio_workspa_1491b9_idx'),
        ),
        migrations.AddIndex(
            model_name='churchcongregant',
            index=models.Index(fields=['workspace', 'status', 'is_active'], name='organizatio_workspa_7bb97b_idx'),
        ),
        migrations.AddIndex(
            model_name='churchcongregant',
            index=models.Index(fields=['workspace', 'campus', 'status'], name='organizatio_workspa_b7a067_idx'),
        ),
        migrations.AddIndex(
            model_name='churchcongregant',
            index=models.Index(fields=['workspace', 'directory_visibility', 'is_active'], name='organizatio_workspa_b2f3c0_idx'),
        ),
        migrations.AddConstraint(
            model_name='churchcongregant',
            constraint=models.UniqueConstraint(fields=('workspace', 'member'), name='organizations_church_unique_member_congregant'),
        ),
        migrations.AddConstraint(
            model_name='churchcongregant',
            constraint=models.UniqueConstraint(fields=('workspace', 'guest_profile'), name='organizations_church_unique_guest_congregant'),
        ),
        migrations.AddConstraint(
            model_name='churchcongregant',
            constraint=models.CheckConstraint(check=models.Q(('guest_profile__isnull', False), ('member__isnull', False), _negated=True), name='organizations_church_congregant_single_account_identity'),
        ),
        migrations.AddConstraint(
            model_name='churchcongregant',
            constraint=models.CheckConstraint(check=models.Q(('display_name_snapshot', ''), _negated=True), name='organizations_church_congregant_display_name_required'),
        ),
        migrations.AddConstraint(
            model_name='churchcongregant',
            constraint=models.CheckConstraint(check=models.Q(('directory_visibility', 'staff_only'), ('directory_consent_at__isnull', False), _connector='OR'), name='organizations_church_congregant_directory_consent_required'),
        ),
    ]
