# Generated by Django 4.2.4 on 2026-09-01 14:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_churchcongregant_churchhousehold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchauditlog',
            name='event',
            field=models.CharField(choices=[('workspace_initialized', 'Workspace Initialized'), ('workspace_updated', 'Workspace Updated'), ('campus_created', 'Campus Created'), ('campus_updated', 'Campus Updated'), ('campus_primary_changed', 'Primary Campus Changed'), ('campus_archived', 'Campus Archived'), ('ministry_created', 'Ministry Created'), ('ministry_updated', 'Ministry Updated'), ('ministry_participant_added', 'Ministry Participant Added'), ('ministry_participant_removed', 'Ministry Participant Removed'), ('leadership_assigned', 'Leadership Assigned'), ('leadership_ended', 'Leadership Ended'), ('gathering_series_created', 'Gathering Series Created'), ('gathering_series_updated', 'Gathering Series Updated'), ('gathering_created', 'Gathering Created'), ('gathering_canceled', 'Gathering Canceled'), ('gathering_completed', 'Gathering Completed'), ('attendance_opened', 'Attendance Opened'), ('attendance_checked_in', 'Attendance Checked In'), ('attendance_checked_out', 'Attendance Checked Out'), ('attendance_guest_counts_updated', 'Guest Counts Updated'), ('attendance_closed', 'Attendance Closed'), ('serving_team_created', 'Serving Team Created'), ('serving_team_updated', 'Serving Team Updated'), ('serving_team_member_added', 'Serving Team Member Added'), ('serving_team_member_removed', 'Serving Team Member Removed'), ('service_plan_created', 'Service Plan Created'), ('service_plan_updated', 'Service Plan Updated'), ('service_plan_published', 'Service Plan Published'), ('service_plan_completed', 'Service Plan Completed'), ('service_plan_canceled', 'Service Plan Canceled'), ('service_plan_item_added', 'Service Plan Item Added'), ('service_plan_item_updated', 'Service Plan Item Updated'), ('service_plan_item_removed', 'Service Plan Item Removed'), ('serving_assignment_created', 'Serving Assignment Created'), ('serving_assignment_responded', 'Serving Assignment Responded'), ('serving_assignment_checked_in', 'Serving Assignment Checked In'), ('serving_assignment_checked_out', 'Serving Assignment Checked Out'), ('serving_assignment_canceled', 'Serving Assignment Canceled'), ('serving_assignment_completed', 'Serving Assignment Completed'), ('resource_created', 'Resource Created'), ('resource_updated', 'Resource Updated'), ('resource_reserved', 'Resource Reserved'), ('resource_reservation_canceled', 'Resource Reservation Canceled'), ('resource_reservation_completed', 'Resource Reservation Completed'), ('congregant_registered', 'Congregant Registered'), ('congregant_updated', 'Congregant Updated'), ('congregant_directory_visibility_changed', 'Congregant Directory Visibility Changed'), ('household_created', 'Household Created'), ('household_updated', 'Household Updated'), ('household_member_added', 'Household Member Added'), ('household_member_removed', 'Household Member Removed'), ('pastoral_case_created', 'Pastoral Care Case Created'), ('pastoral_case_updated', 'Pastoral Care Case Updated'), ('pastoral_case_assigned', 'Pastoral Care Case Assigned'), ('pastoral_case_unassigned', 'Pastoral Care Case Unassigned'), ('pastoral_case_on_hold', 'Pastoral Care Case On Hold'), ('pastoral_case_reopened', 'Pastoral Care Case Reopened'), ('pastoral_case_closed', 'Pastoral Care Case Closed'), ('pastoral_note_added', 'Pastoral Care Note Added'), ('pastoral_contact_recorded', 'Pastoral Care Contact Recorded'), ('teaching_series_created', 'Teaching Series Created'), ('teaching_series_updated', 'Teaching Series Updated'), ('teaching_series_archived', 'Teaching Series Archived'), ('teaching_content_created', 'Teaching Content Created'), ('teaching_content_updated', 'Teaching Content Updated'), ('teaching_content_published', 'Teaching Content Published'), ('teaching_content_archived', 'Teaching Content Archived'), ('teaching_content_deleted', 'Teaching Content Deleted')], db_index=True, max_length=60),
        ),
        migrations.CreateModel(
            name='ChurchTeachingSeries',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=180)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], db_index=True, default='active', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_series', to='organizations.churchcampus')),
                ('ministry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_series', to='organizations.churchministry')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_series', to='organizations.churchworkspace')),
            ],
            options={
                'verbose_name': 'Church Teaching Series',
                'verbose_name_plural': 'Church Teaching Series',
                'ordering': ('sort_order', 'name', 'id'),
                'indexes': [models.Index(fields=['workspace', 'status', 'sort_order'], name='organizatio_workspa_1c06ee_idx'), models.Index(fields=['campus', 'status'], name='organizatio_campus__6801a7_idx'), models.Index(fields=['ministry', 'status'], name='organizatio_ministr_f9f205_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='churchteachingseries',
            constraint=models.UniqueConstraint(fields=('workspace', 'slug'), name='organizations_church_unique_teaching_series_slug'),
        ),
    ]
