# Generated by Django 4.2.4 on 2026-09-02 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.common.utils
import uuid
import validators.security_validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audio_catalog', '0007_alter_audiousagegrant_options_and_more'),
        ('organizations', '0008_alter_churchauditlog_event_churchteachingseries_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationMusicLicense',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('expired', 'Expired'), ('revoked', 'Revoked')], db_index=True, default='draft', max_length=16)),
                ('title', models.CharField(max_length=180)),
                ('reference', models.CharField(blank=True, db_index=True, default='', max_length=220)),
                ('license_type', models.CharField(choices=[('owned', 'Owned'), ('assignment', 'Assigned'), ('exclusive', 'Exclusive License'), ('non_exclusive', 'Non-exclusive License'), ('public_domain', 'Public Domain'), ('provider_terms', 'Provider Terms'), ('other', 'Other')], db_index=True, default='non_exclusive', max_length=24)),
                ('license_version', models.CharField(blank=True, default='', max_length=100)),
                ('effective_from', models.DateTimeField(blank=True, null=True)),
                ('effective_until', models.DateTimeField(blank=True, null=True)),
                ('territory_mode', models.CharField(choices=[('worldwide', 'Worldwide'), ('allow_list', 'Allow List'), ('deny_list', 'Deny List')], db_index=True, default='worldwide', max_length=20)),
                ('territory_codes', models.JSONField(blank=True, default=list)),
                ('commercial_use_allowed', models.BooleanField(default=False)),
                ('ugc_use_allowed', models.BooleanField(default=False)),
                ('streaming_allowed', models.BooleanField(default=False)),
                ('synchronization_allowed', models.BooleanField(default=False)),
                ('adaptation_allowed', models.BooleanField(default=False)),
                ('clipping_allowed', models.BooleanField(default=False)),
                ('hosting_allowed', models.BooleanField(default=False)),
                ('sublicensing_to_end_users_allowed', models.BooleanField(default=False)),
                ('standalone_download_allowed', models.BooleanField(default=False)),
                ('external_export_allowed', models.BooleanField(default=False)),
                ('perpetual_existing_content_allowed', models.BooleanField(default=False)),
                ('attribution_required', models.BooleanField(default=False)),
                ('attribution_text', models.TextField(blank=True, default='')),
                ('restrictions', models.JSONField(blank=True, default=dict)),
                ('activated_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('revoke_reason', models.CharField(blank=True, default='', max_length=240)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_organization_music_licenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='WorshipWorkspace',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worship_workspace', to='organizations.organizationmoduleactivation')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationRightsParty',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('relationship', models.CharField(choices=[('self', 'Organization / Self'), ('licensor', 'Licensor'), ('representative', 'Representative'), ('partner', 'Partner'), ('other', 'Other')], db_index=True, default='other', max_length=24)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rights_party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organization_links', to='audio_catalog.rightsparty')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rights_parties', to='organizations.worshipworkspace')),
            ],
            options={
                'ordering': ('rights_party__display_name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='OrganizationMusicLicenseEvidence',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('evidence_type', models.CharField(choices=[('agreement', 'Agreement'), ('assignment', 'Assignment'), ('consent', 'Consent'), ('invoice', 'Invoice'), ('terms', 'Terms'), ('source_capture', 'Source Capture'), ('other', 'Other')], db_index=True, max_length=32)),
                ('title', models.CharField(max_length=180)),
                ('evidence_file', models.FileField(max_length=700, upload_to=utils.common.utils.FileUpload.dir_upload, validators=[validators.security_validators.validate_no_executable_file])),
                ('sha256', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_music_license_evidence', to=settings.AUTH_USER_MODEL)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_items', to='organizations.organizationmusiclicense')),
            ],
            options={
                'ordering': ('evidence_type', 'created_at', 'id'),
            },
        ),
        migrations.AddField(
            model_name='organizationmusiclicense',
            name='composition_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='licenses_as_composition_owner', to='organizations.organizationrightsparty'),
        ),
        migrations.AddField(
            model_name='organizationmusiclicense',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_organization_music_licenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationmusiclicense',
            name='licensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='licenses_as_licensor', to='organizations.organizationrightsparty'),
        ),
        migrations.AddField(
            model_name='organizationmusiclicense',
            name='master_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='licenses_as_master_owner', to='organizations.organizationrightsparty'),
        ),
        migrations.AddField(
            model_name='organizationmusiclicense',
            name='revoked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_organization_music_licenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationmusiclicense',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_licenses', to='organizations.worshipworkspace'),
        ),
        migrations.CreateModel(
            name='OrganizationMusicContribution',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('revoked', 'Revoked')], db_index=True, default='draft', max_length=16)),
                ('credit_text', models.CharField(max_length=240)),
                ('license_snapshot', models.JSONField(blank=True, default=dict)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('revoke_reason', models.CharField(blank=True, default='', max_length=240)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_organization_music_contributions', to=settings.AUTH_USER_MODEL)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contributions', to='organizations.organizationmusiclicense')),
                ('primary_artist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organization_music_contributions', to='audio_catalog.audiocontributor')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_organization_music_contributions', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_organization_music_contributions', to=settings.AUTH_USER_MODEL)),
                ('rights_record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organization_contribution', to='audio_catalog.musicrightsrecord')),
                ('track', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='organization_music_contribution', to='audio_catalog.musictrack')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_contributions', to='organizations.worshipworkspace')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='WorshipAuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event', models.CharField(choices=[('workspace_initialized', 'Workspace Initialized'), ('rights_party_linked', 'Rights Party Linked'), ('rights_party_deactivated', 'Rights Party Deactivated'), ('license_created', 'License Created'), ('license_evidence_added', 'License Evidence Added'), ('license_activated', 'License Activated'), ('license_revoked', 'License Revoked'), ('contribution_created', 'Contribution Created'), ('contribution_published', 'Contribution Published'), ('contribution_revoked', 'Contribution Revoked')], db_index=True, max_length=60)),
                ('entity_type', models.CharField(db_index=True, max_length=60)),
                ('entity_public_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worship_audit_actions', to=settings.AUTH_USER_MODEL)),
                ('membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worship_audit_logs', to='organizations.organizationmembership')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='organizations.worshipworkspace')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['workspace', 'event', 'created_at'], name='organizatio_workspa_e78c67_idx'), models.Index(fields=['workspace', 'entity_type', 'entity_public_id'], name='organizatio_workspa_86bf43_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='organizationrightsparty',
            index=models.Index(fields=['workspace', 'is_active', 'relationship'], name='organizatio_workspa_f30e80_idx'),
        ),
        migrations.AddConstraint(
            model_name='organizationrightsparty',
            constraint=models.UniqueConstraint(fields=('workspace', 'rights_party'), name='organizations_worship_unique_rights_party'),
        ),
        migrations.AddIndex(
            model_name='organizationmusiclicenseevidence',
            index=models.Index(fields=['license', 'evidence_type'], name='organizatio_license_6dcaac_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationmusiclicenseevidence',
            index=models.Index(fields=['sha256'], name='organizatio_sha256_8b6f61_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationmusiclicense',
            index=models.Index(fields=['workspace', 'status', 'effective_until'], name='organizatio_workspa_4065d2_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationmusiclicense',
            index=models.Index(fields=['status', 'effective_from', 'effective_until'], name='organizatio_status_4f70e6_idx'),
        ),
        migrations.AddConstraint(
            model_name='organizationmusiclicense',
            constraint=models.CheckConstraint(check=models.Q(('effective_until__isnull', True), ('effective_from__isnull', True), ('effective_until__gt', models.F('effective_from')), _connector='OR'), name='organizations_worship_license_range_valid'),
        ),
        migrations.AddIndex(
            model_name='organizationmusiccontribution',
            index=models.Index(fields=['workspace', 'status', 'created_at'], name='organizatio_workspa_689f70_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationmusiccontribution',
            index=models.Index(fields=['license', 'status', 'created_at'], name='organizatio_license_4752fd_idx'),
        ),
        migrations.AddConstraint(
            model_name='organizationmusiccontribution',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('published_at__isnull', True), ('revoked_at__isnull', True), ('status', 'draft')), models.Q(('published_at__isnull', False), ('revoked_at__isnull', True), ('status', 'published')), models.Q(('published_at__isnull', False), ('revoked_at__isnull', False), ('status', 'revoked')), _connector='OR'), name='organizations_worship_contribution_lifecycle'),
        ),
    ]
