# Generated by Django 4.2.4 on 2026-09-14 14:41

import apps.organizations.modules.worship.models.rights
from django.db import migrations, models
import validators.security_validators


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_organizationmusiclicense_worshipworkspace_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationmusiclicenseevidence',
            name='evidence_file',
            field=models.FileField(max_length=700, upload_to=apps.organizations.modules.worship.models.rights.organization_music_license_evidence_upload_to, validators=[validators.security_validators.validate_no_executable_file]),
        ),
    ]
