# apps/accounts/constants/default_usernames.py

"""
Default username fallback words.

Member users receive positive biblical-style words.
Guest users receive only the neutral "user" prefix.
"""

GUEST_FALLBACK_USERNAME_PREFIX = "user"

MEMBER_FALLBACK_USERNAME_WORDS = [
    "blessed",
    "faithful",
    "redeemed",
    "grateful",
    "joyful",
    "hopeful",
    "beloved",
    "forgiven",
    "renewed",
    "uplifted",
    "peaceful",
    "thankful",
    "humble",
    "gentle",
    "merciful",
    "kindhearted",
    "compassionate",
    "courageous",
    "steadfast",
    "patient",
    "truthful",
    "gracious",
    "encouraged",
    "encourager",
    "hopebringer",
    "joygiver",
    "peacemaker",
    "peacekeeper",
    "lightbearer",
    "faithwalker",
    "truthseeker",
    "wiseseeker",
    "goodsteward",
    "servantheart",
    "humbleheart",
    "trustingheart",
    "gentlespirit",
    "livinghope",
    "gracefilled",
    "gracebearer",
    "faithbuilder",
    "kingdomminded",
    "saltandlight",
    "servinghands",
    "brightlamp",
    "openheart",
    "pureheart",
    "newheart",
    "stillwater",
    "quietstrength",
    "steadylight",
    "morninghope",
    "dailygrace",
    "abidingjoy",
    "livingfaith",
    "mercywalker",
    "gracewalker",
    "hopewalker",
    "faithrunner",
    "truthwalker",
    "lovingheart",
    "joyfulheart",
    "peacefulheart",
    "thankfulheart",
    "strongtower",
    "safeharbor",
    "brightpath",
    "narrowpath",
    "kindspirit",
    "calmspirit",
    "braveheart",
    "firmfoundation",
    "goodfruit",
    "fruitful",
    "restored",
    "anchored",
    "chosen",
    "called",
    "guided",
    "guarded",
    "cherished",
    "comforted",
    "strengthened",
    "awakened",
    "refined",
    "rooted",
    "grounded",
    "abiding",
    "watchful",
    "prayerful",
    "mindful",
    "hopefulheart",
    "faithfulheart",
    "gracefulheart",
]