# apps/accounts/constants/devices.py

DEVICE_PLATFORM_WEB = "web"
DEVICE_PLATFORM_IOS = "ios"
DEVICE_PLATFORM_ANDROID = "android"

SUPPORTED_DEVICE_PLATFORMS = frozenset({
    DEVICE_PLATFORM_WEB,
    DEVICE_PLATFORM_IOS,
    DEVICE_PLATFORM_ANDROID,
})

FCM_DEVICE_PLATFORMS = frozenset({
    DEVICE_PLATFORM_WEB,
    DEVICE_PLATFORM_ANDROID,
})

MOBILE_DEVICE_PLATFORMS = frozenset({
    DEVICE_PLATFORM_IOS,
    DEVICE_PLATFORM_ANDROID,
})