# Generated by Django 4.2.4 on 2025-11-17 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotificationpreference',
            name='channels_mask',
            field=models.PositiveIntegerField(default=7),
        ),
    ]
