# Generated by Django 4.2.4 on 2025-12-05 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_usernotificationpreference_channels_mask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_comment', 'New Comment'), ('new_reply', 'New Reply'), ('new_reply_post_owner', 'Reply to Post Comment'), ('new_reaction', 'New Reaction'), ('new_reaction_bless', 'Bless Reaction'), ('new_reaction_gratitude', 'Gratitude Reaction'), ('new_reaction_amen', 'Amen Reaction'), ('new_reaction_encouragement', 'Encouragement Reaction'), ('new_reaction_empathy', 'Empathy Reaction'), ('friend_request_received', 'Friend Request Received'), ('friend_request_accepted', 'Friend Request Accepted'), ('friend_request_declined', 'Friend Request Declined'), ('friend_request_cancelled', 'Friend Request Cancelled'), ('friendship_deleted', 'Friendship Deleted'), ('fellowship_request_received', 'Fellowship Request Received'), ('fellowship_request_accepted', 'Fellowship Request Accepted'), ('fellowship_request_confirmed', 'Fellowship Relationship Confirmed'), ('fellowship_request_declined', 'Fellowship Request Declined'), ('fellowship_decline_notice', 'Fellowship Decline Notice'), ('fellowship_cancelled', 'Fellowship Cancelled'), ('new_message_direct', 'New Direct Message'), ('new_message_group', 'New Group Message'), ('new_testimony_written', 'New Written Testimony'), ('new_testimony_audio', 'New Audio Testimony'), ('new_testimony_video', 'New Video Testimony')], max_length=50),
        ),
        migrations.AlterField(
            model_name='usernotificationpreference',
            name='notification_type',
            field=models.CharField(choices=[('new_comment', 'New Comment'), ('new_reply', 'New Reply'), ('new_reply_post_owner', 'Reply to Post Comment'), ('new_reaction', 'New Reaction'), ('new_reaction_bless', 'Bless Reaction'), ('new_reaction_gratitude', 'Gratitude Reaction'), ('new_reaction_amen', 'Amen Reaction'), ('new_reaction_encouragement', 'Encouragement Reaction'), ('new_reaction_empathy', 'Empathy Reaction'), ('friend_request_received', 'Friend Request Received'), ('friend_request_accepted', 'Friend Request Accepted'), ('friend_request_declined', 'Friend Request Declined'), ('friend_request_cancelled', 'Friend Request Cancelled'), ('friendship_deleted', 'Friendship Deleted'), ('fellowship_request_received', 'Fellowship Request Received'), ('fellowship_request_accepted', 'Fellowship Request Accepted'), ('fellowship_request_confirmed', 'Fellowship Relationship Confirmed'), ('fellowship_request_declined', 'Fellowship Request Declined'), ('fellowship_decline_notice', 'Fellowship Decline Notice'), ('fellowship_cancelled', 'Fellowship Cancelled'), ('new_message_direct', 'New Direct Message'), ('new_message_group', 'New Group Message'), ('new_testimony_written', 'New Written Testimony'), ('new_testimony_audio', 'New Audio Testimony'), ('new_testimony_video', 'New Video Testimony')], max_length=50),
        ),
    ]
