# Generated by Django 4.2.4 on 2026-09-04 23:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0012_alter_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationCampaign',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('internal_name', models.CharField(help_text='Internal name shown only to TownLIT admins.', max_length=160)),
                ('category', models.CharField(choices=[('general', 'General Announcement'), ('app_update', 'App Update'), ('feature', 'New Feature'), ('maintenance', 'Maintenance'), ('security', 'Security Notice'), ('policy', 'Policy Update'), ('community', 'Community Announcement'), ('event', 'Event')], default='general', max_length=32)),
                ('title', models.CharField(help_text='Short notification title.', max_length=140)),
                ('message', models.TextField(help_text='User-facing notification message.')),
                ('audience_type', models.CharField(choices=[('all', 'All Users'), ('members', 'Members'), ('guests', 'Guests'), ('staff', 'Staff / Admins'), ('selected', 'Selected Users')], default='all', max_length=20)),
                ('platform_scope', models.CharField(choices=[('all', 'All Platforms'), ('ios', 'iOS'), ('android', 'Android'), ('web', 'Web'), ('mobile', 'iOS + Android')], default='all', max_length=20)),
                ('send_push', models.BooleanField(default=True, help_text='Send Push in addition to the in-app notification.')),
                ('send_email', models.BooleanField(default=False, help_text='Reserved for important service, security, and policy notices.')),
                ('action_type', models.CharField(choices=[('none', 'No Action'), ('internal', 'TownLIT Link'), ('external', 'External Link'), ('app_store', 'Apple App Store'), ('play_store', 'Google Play')], default='none', max_length=20)),
                ('action_label', models.CharField(blank=True, help_text='Example: Update Now, Learn More, Open TownLIT.', max_length=40)),
                ('action_url', models.CharField(blank=True, help_text='TownLIT path, universal link, App Store URL, or external URL.', max_length=500)),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='Leave empty to publish as soon as the campaign is queued.', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], db_index=True, default='draft', max_length=20)),
                ('total_recipients', models.PositiveIntegerField(default=0)),
                ('processed_count', models.PositiveIntegerField(default=0)),
                ('in_app_count', models.PositiveIntegerField(default=0)),
                ('push_sent_count', models.PositiveIntegerField(default=0)),
                ('email_queued_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notification_campaigns', to=settings.AUTH_USER_MODEL)),
                ('selected_users', models.ManyToManyField(blank=True, help_text='Used only when audience is Selected Users.', related_name='selected_notification_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='action_label',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='notification',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(blank=True, default='', max_length=140),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_comment', 'New Comment'), ('new_reply', 'New Reply'), ('new_reply_post_owner', 'Reply to Post Comment'), ('new_reaction', 'New Reaction'), ('new_reaction_like', 'Like Reaction'), ('new_reaction_bless', 'Bless Reaction'), ('new_reaction_gratitude', 'Gratitude Reaction'), ('new_reaction_amen', 'Amen Reaction'), ('new_reaction_encouragement', 'Encouragement Reaction'), ('new_reaction_empathy', 'Empathy Reaction'), ('new_reaction_faithfire', 'FaithFire Reaction'), ('new_reaction_support', 'Support Reaction'), ('friend_request_received', 'Friend Request Received'), ('friend_request_accepted', 'Friend Request Accepted'), ('friend_request_declined', 'Friend Request Declined'), ('friend_request_cancelled', 'Friend Request Cancelled'), ('friendship_deleted', 'Friendship Deleted'), ('fellowship_request_received', 'Fellowship Request Received'), ('fellowship_request_accepted', 'Fellowship Request Accepted'), ('fellowship_request_confirmed', 'Fellowship Relationship Confirmed'), ('fellowship_request_declined', 'Fellowship Request Declined'), ('fellowship_decline_notice', 'Fellowship Decline Notice'), ('fellowship_cancelled', 'Fellowship Cancelled'), ('new_message_direct', 'New Direct Message'), ('new_message_group', 'New Group Message'), ('messenger_group_created', 'Messenger Group Created'), ('messenger_message_pinned', 'Messenger Message Pinned'), ('messenger_reaction_direct', 'Messenger Direct Message Reaction'), ('messenger_reaction_group', 'Messenger Group Message Reaction'), ('new_testimony_written', 'New Written Testimony'), ('new_testimony_audio', 'New Audio Testimony'), ('new_testimony_video', 'New Video Testimony'), ('testimony_video_rejected', 'Video Testimony Not Accepted'), ('testimony_video_needs_review', 'Video Testimony Needs Review'), ('testimony_video_approved', 'Video Testimony Approved'), ('sanctuary_admin_assignment', 'Sanctuary: Admin Assignment'), ('sanctuary_member_review_request', 'Sanctuary: Council Review Request'), ('sanctuary_outcome_finalized', 'Sanctuary: Outcome Finalized'), ('sanctuary_appeal_assignment', 'Sanctuary: Appeal Assignment'), ('new_moment_image', 'New Image Moment'), ('new_moment_video', 'New Video Moment'), ('new_prayer_image', 'New Image Prayer'), ('new_prayer_video', 'New Video Prayer'), ('prayer_result_answered', 'Prayer Answered Update'), ('prayer_result_not_answered', 'Prayer Update (Not Answered)'), ('new_journey', 'New Journey'), ('townlit_announcement', 'TownLIT Announcement'), ('townlit_app_update', 'TownLIT App Update'), ('townlit_feature_update', 'TownLIT Feature Update'), ('townlit_maintenance', 'TownLIT Maintenance'), ('townlit_security_notice', 'TownLIT Security Notice'), ('townlit_policy_update', 'TownLIT Policy Update'), ('townlit_community', 'TownLIT Community Announcement'), ('townlit_event', 'TownLIT Event')], max_length=50),
        ),
        migrations.AlterField(
            model_name='usernotificationpreference',
            name='notification_type',
            field=models.CharField(choices=[('new_comment', 'New Comment'), ('new_reply', 'New Reply'), ('new_reply_post_owner', 'Reply to Post Comment'), ('new_reaction', 'New Reaction'), ('new_reaction_like', 'Like Reaction'), ('new_reaction_bless', 'Bless Reaction'), ('new_reaction_gratitude', 'Gratitude Reaction'), ('new_reaction_amen', 'Amen Reaction'), ('new_reaction_encouragement', 'Encouragement Reaction'), ('new_reaction_empathy', 'Empathy Reaction'), ('new_reaction_faithfire', 'FaithFire Reaction'), ('new_reaction_support', 'Support Reaction'), ('friend_request_received', 'Friend Request Received'), ('friend_request_accepted', 'Friend Request Accepted'), ('friend_request_declined', 'Friend Request Declined'), ('friend_request_cancelled', 'Friend Request Cancelled'), ('friendship_deleted', 'Friendship Deleted'), ('fellowship_request_received', 'Fellowship Request Received'), ('fellowship_request_accepted', 'Fellowship Request Accepted'), ('fellowship_request_confirmed', 'Fellowship Relationship Confirmed'), ('fellowship_request_declined', 'Fellowship Request Declined'), ('fellowship_decline_notice', 'Fellowship Decline Notice'), ('fellowship_cancelled', 'Fellowship Cancelled'), ('new_message_direct', 'New Direct Message'), ('new_message_group', 'New Group Message'), ('messenger_group_created', 'Messenger Group Created'), ('messenger_message_pinned', 'Messenger Message Pinned'), ('messenger_reaction_direct', 'Messenger Direct Message Reaction'), ('messenger_reaction_group', 'Messenger Group Message Reaction'), ('new_testimony_written', 'New Written Testimony'), ('new_testimony_audio', 'New Audio Testimony'), ('new_testimony_video', 'New Video Testimony'), ('testimony_video_rejected', 'Video Testimony Not Accepted'), ('testimony_video_needs_review', 'Video Testimony Needs Review'), ('testimony_video_approved', 'Video Testimony Approved'), ('sanctuary_admin_assignment', 'Sanctuary: Admin Assignment'), ('sanctuary_member_review_request', 'Sanctuary: Council Review Request'), ('sanctuary_outcome_finalized', 'Sanctuary: Outcome Finalized'), ('sanctuary_appeal_assignment', 'Sanctuary: Appeal Assignment'), ('new_moment_image', 'New Image Moment'), ('new_moment_video', 'New Video Moment'), ('new_prayer_image', 'New Image Prayer'), ('new_prayer_video', 'New Video Prayer'), ('prayer_result_answered', 'Prayer Answered Update'), ('prayer_result_not_answered', 'Prayer Update (Not Answered)'), ('new_journey', 'New Journey'), ('townlit_announcement', 'TownLIT Announcement'), ('townlit_app_update', 'TownLIT App Update'), ('townlit_feature_update', 'TownLIT Feature Update'), ('townlit_maintenance', 'TownLIT Maintenance'), ('townlit_security_notice', 'TownLIT Security Notice'), ('townlit_policy_update', 'TownLIT Policy Update'), ('townlit_community', 'TownLIT Community Announcement'), ('townlit_event', 'TownLIT Event')], max_length=50),
        ),
        migrations.AddField(
            model_name='notification',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='notifications.notificationcampaign'),
        ),
        migrations.CreateModel(
            name='NotificationCampaignDelivery',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=20)),
                ('push_sent', models.BooleanField(default=False)),
                ('email_queued', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='notifications.notificationcampaign')),
                ('notification', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_delivery', to='notifications.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_campaign_deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('campaign_id', 'id'),
                'indexes': [models.Index(fields=['campaign', 'status'], name='notif_deliv_camp_stat_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='notificationcampaigndelivery',
            constraint=models.UniqueConstraint(fields=('campaign', 'user'), name='notif_unique_campaign_delivery'),
        ),
        migrations.AddIndex(
            model_name='notificationcampaign',
            index=models.Index(fields=['status', 'scheduled_at'], name='notif_camp_sched_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationcampaign',
            index=models.Index(fields=['category', 'platform_scope'], name='notif_camp_target_idx'),
        ),
    ]
