# Generated by Django 4.2.4 on 2026-09-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0013_notificationcampaign_notification_action_label_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(fields=('campaign', 'user'), name='notif_unique_campaign_user'),
        ),
    ]
